open-telemetry/opentelemetry.io

- config.toml
- layouts/partials/home/hero.html
- layouts/partials/social-buttons.html
This PR is a follow-up to #21. It modifies the social buttons aesthetic to be more consistent with the other aesthetic elements on the site.
> Change social buttons aesthetic

- data/learn.yaml
- data/timeline.yaml
Incorporates changes from #26 but with fixed CLA
> Index housekeeping

- data/progress_source.yaml
Adding the current SIG progress for OpenTelemetry PHP
> Adding OpenTelemetry-PHP to the current progress list

- data/nav.yaml
This link presents the spec TOC in a slightly better format.
> Link directly to Specification README

- layouts/docs/list.html
- layouts/docs/single.html
Modifies the navbar to take up a single column.
> Reduce whitespace on docs pages with sidebar

- content/docs/python/tracing.md
> Adding trace getting started for python

- content/docs/golang/tracing.md
> Adding tracing guide for go

- scripts/fetchMilestones.js
Fixes #78 by adding proper error handling.
> improve error handling in milestone script

- content/docs/js/tracing.md
> fix: js tracing example

- content/docs/golang/tracing.md
Hi.
I found a part that could not follow the library update and fixed it.
Thank you.
> fix golang sample

- content/registry/exporter-python-jaeger.md
> adding jaeger python exporter to the registry

- content/registry/exporter-python-lightstep.md
> adding lightstep python exporter to the registry

- content/registry/exporter-python-zipkin.md
> adding zipkin python exporter to the registry

- content/registry/exporter-python-lightstep.md
> The isThirdParty flag should be set to true

- content/registry/exporter-js-jaeger.md
> adding jaeger JS exporter to the registry

- content/registry/exporter-js-zipkin.md
> adding zipkin JS exporter to the registry

- content/docs/js/tracing.md
> keep example up-to-date with latest release

- content/registry/exporter-go-lightstep.md
> Adding LightStep exporter for Go

- Makefile
- README.md
> Update instructions for running locally

- content/project-status.md
> Update project status with beta release and how to contribute info

- .gitignore
- .htmltest.yml
- Makefile
- assets/sass/style.sass
- layouts/partials/meta.html
- netlify.toml
This PR adds a link checker for internal links to the CI pipeline and upgrades the Hugo version.
> Add link checker for site

- content/docs/python/tracing.md
Update tracing example to work with version `0.4a0` and `master` branch
> Python tracing example

- content/docs/js/tracing.md
> tracing(js): initGlobalTracerProvider => setGlobalTracerProvider

- .htmltest.yml
> Allow empty hash

- content/registry/otel-java-auto-instrumentation.md
I'm not sure about registry type or tags, definitely let me know if there's something better to use!
> Add Java Auto-Instrumentation to the registry

- layouts/_default/baseof.html
> Remove octocat badge for now

- content/registry/exporter-js-prometheus.md
Based on https://github.com/open-telemetry/opentelemetry-js/issues/877
cc @mayurkale22 @dyladan
> Adding Prometheus JS exporter to the registry

- layouts/partials/home/beta.html
Just want to join the party 😁🎉
> Add Java Auto-Instrumentation to beta list

- layouts/index.html
- layouts/partials/home/logs.html
Fits under the beta box, though I'd prefer if this and the "Discover Integrations" box could sit side by side. @austinlparker is that possible?
> Add homepage update about logs working group

- content/registry/exporter-python-azure-monitor.md
> Add Microsoft Azure Monitor exporter in registry

- layouts/partials/home/logs.html
I'd accidentally made this the same color as the beta box; beta needs to be more prominent
> Changed color of logging box

- content/docs/collector/about.md
Demo Docker image changed from distrib to core version.
CC @flands @pjanotti
> Update demo Docker image to core

- content/registry/exporter-js-google-cloud-monitoring.md
> Adding_Google_Cloud_Monitoring_Exporter

- content/registry/instrumentation-python-aio-httpclient.md
- content/registry/instrumentation-python-dbapi.md
- content/registry/instrumentation-python-django.md
- content/registry/instrumentation-python-flask.md
- content/registry/instrumentation-python-grpc.md
- content/registry/instrumentation-python-mysql.md
- content/registry/instrumentation-python-psycopg2.md
- content/registry/instrumentation-python-pymongo.md
- content/registry/instrumentation-python-pymysql.md
- content/registry/instrumentation-python-redis.md
- content/registry/instrumentation-python-requests.md
- content/registry/instrumentation-python-sqlalchemy.md
- content/registry/instrumentation-python-wsgi.md
This adds the available Python instrumentations to the registry.
> Adding registry entries for Python instrumentation

- layouts/partials/home/hero.html
Following the lead of many other open source projects including [Node.js](https://nodejs.org/en/), [TypeScript](https://www.typescriptlang.org/), [React](https://reactjs.org/), [Angular](https://angular.io/), [Kubernetes](https://kubernetes.io/), [Helm](https://helm.sh/).
The message includes a link to the [Equal Justice Initiative](https://eji.org/), inspired by [React](https://reactjs.org/) and [Vue.js](https://vuejs.org/).
> Add support for #BlackLivesMatter

- content/registry/otel-java-instrumentation.md
See https://github.com/open-telemetry/community/pull/366
> Update Java Auto-Instrumentation SIG scope

- content/docs/collector/about.md
> Update Collector getting started

- content/docs/collector/about.md
- the previous command didn't work
- need to use raw.githubusercontent.com for pointing to the right yaml file content
> fix `kubectl apply` command

- content/registry/exporter-python-google-cloud-monitoring.md
- content/registry/exporter-python-google-cloud-trace.md
- content/registry/exporter-python-opencensus.md
- content/registry/exporter-python-otlp.md
- content/registry/exporter-python-prometheus.md
- content/registry/instrumentation-python-asgi.md
- content/registry/instrumentation-python-asyncpg.md
- content/registry/instrumentation-python-boto.md
- content/registry/instrumentation-python-botocore.md
- content/registry/instrumentation-python-celery.md
- content/registry/instrumentation-python-datadog.md
- content/registry/instrumentation-python-elasticsearch.md
- content/registry/instrumentation-python-jinja2.md
- content/registry/instrumentation-python-pymemcache.md
- content/registry/instrumentation-python-pyramid.md
- content/registry/instrumentation-python-sqlite3.md
- content/registry/instrumentation-python-starlette.md
- content/registry/instrumentation-python-system-metrics.md
- content/registry/shim-python-opentracing.md
> Add missing Python extensions

- content/registry/instrumentation-js-angular.md
To add my angular library to the registry
> docs: add angular library

- content/registry/instrumentation-go-gin.md
- content/registry/instrumentation-go-gorilla-mux.md
- content/registry/instrumentation-go-labstack.md
- content/registry/instrumentation-go-macaron.md
- content/registry/instrumentation-go-mongodb.md
Adding
* Macaron
* Labstack
* Mongodb
> Adding pre-existing go instrumentation plugins

- content/registry/exporter-python-google-cloud-monitoring.md
Fixed broken link to the Google Cloud Monitoring Python exporter
> Fixed broken link

- content/project-status.md
I think this helps clarify the intention here
> Clarify API stability

- content/registry/instrumentation-js-fastify.md
Adds [fastify-opentelemetry](https://github.com/autotelic/fastify-opentelemetry) to the registry.
> Add fastify-opentelemetry to registry.

- content/docs/collector/about.md
> Added a mention to the operator and builder to the collector docs

- content/docs/collector/about.md
> Added link to blog post on 'building custom otelcols'

- content/en/registry/exporter-java-honeycomb.md
Adds registry entry for a Honeycomb Java exporter.
> Add java exporter for Honeycomb

- content/en/registry/instrumentation-js-sequelize.md
Adds [opentelemetry-plugin-sequelize](https://github.com/aspecto-io/opentelemetry-ext-js/tree/master/packages/plugin-sequelize) to the registry.
> Added Sequelize (js) plugin to the registry

- content/en/docs/collector/about.md
- content/en/docs/collector/configuration.md
Attempt to make things clearer:
- collector-contrib is a superset of collector
- Demonstrate the same component can be defined multiple times
- Receivers/Exporter support push and pull based mechanisms
- Rename collector service to gateway
- Ensure receiver, processor and exporter sections are up to date
- Add proxy information
> Update Collector documentation

- config.toml
> Add link to CNCF DevStats in the footer

- README.md
- templates/language-docs/_index.md
- templates/language-docs/exporting_data.md
- templates/language-docs/getting_started.md
- templates/language-docs/instrumentation.md
- templates/registry-template.md
This is #282 but cleaned up because I made git and myself very unhappy.
> Add documentation templates

- content/en/docs/java/_index.md
- content/en/docs/java/automatic_instrumentation.md
- content/en/docs/java/getting_started.md
- content/en/docs/java/manual_instrumentation.md
Addresses #283 This will supersede documentation currently captured in README. Separate
PRs will address this.
TODOs in future PRs:
- Exporters
- Sampling
> Add initial Java documentation

- content/en/docs/java/_index.md
> Add link to Java Inst Snapshot

- README.md
- content/en/about/_index.md
> Add Creative Commons License

- content/en/docs/net/_index.md
- content/en/docs/net/getting-started.md
This is the index and quickstart docs for .NET, so we can get something going there.
> Initial .NET documentation

- content/en/docs/python/_index.md
Adding a placeholder that has a link to the Read the Docs site.
Part of #285
> adding placeholder for Python

- config.toml
- content/en/search.md
- layouts/registry/list.html
- layouts/registry/search.html
- src/js/base.js
- src/js/registrySearch.js
- webpack.config.js
Fixes #317 (and #321).
Note, I registered the GCSE engine under my @lightstep email, I'm not sure if there's a better way to do it. We can always change it later, though.
> Add GCSE site search

- content/en/docs/js/_index.md
Hey,
This PR fix the broken link for getting started
> Fix getting started link

- content/en/docs/go/exporting_data.md
- content/en/docs/go/getting-started.md
- content/en/docs/go/instrumentation.md
This is like #344, but I tried to extend the guide with a guide about metrics.
CC: @MrAlias
> Update the getting started guide for go

- assets/scss/main.scss
- config.toml
- hide create project issue URL
- adjust the spacing of page-meta and page-TOC
> improve document page meta section

- content/en/docs/collector/getting-started.md
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>
> Update forgotten link to the new main branch

- content/en/docs/rust/_index.md
> docs: Add Rust Index Page

- content/en/community/_index.md
- content/en/docs/concepts/components.md
- content/en/docs/concepts/data-collection.md
- content/en/docs/concepts/instrumenting.md
- content/en/docs/concepts/what-is-opentelemetry.md
Mostly minor cleanup, clarification, and slight restructuring. Added
repository information for instrumentation libraries to compliment #334
> Cleanup the component docs

- content/en/docs/collector/_index.md
- content/en/docs/collector/configuration.md
- content/en/docs/collector/getting-started.md
Better clarify how configuration works. Link to relevant information.
- Address #338
- Address #370 (at least part)
> Improve Collector documentation

- content/en/docs/collector/_index.md
- content/en/docs/erlang/_index.md
- content/en/docs/go/_index.md
- content/en/docs/java/_index.md
- content/en/docs/js/_index.md
- content/en/docs/net/_index.md
- content/en/docs/python/_index.md
- content/en/docs/rust/_index.md
Add descriptions to all sections and alphabetize list.
> Update doc nav

- layouts/shortcodes/release_notes.html
> Fix overflow on Releases page

- content/en/docs/concepts/data-collection.md
- content/en/docs/concepts/distributions.md
- content/en/docs/concepts/instrumenting.md
> Add initial distributions information

- content/en/docs/_index.md
- content/en/docs/collector/_index.md
- content/en/docs/collector/configuration.md
- content/en/docs/concepts/data-collection.md
Also add reference architecture information.
> Add Collector icons to documentation

- content/en/community/_index.md
- layouts/shortcodes/center.html
Attempt to standardize the layout. Also adds a center shortcode.
Addresses #322
Note that given integration with the docsy theme, it appears the first
two section cannot easily be modified.
> Update Community page

- content/en/docs/collector/_index.md
- content/en/docs/erlang/_index.md
- content/en/docs/go/_index.md
- content/en/docs/java/_index.md
- content/en/docs/js/_index.md
- content/en/docs/net/_index.md
- content/en/docs/python/_index.md
- content/en/docs/rust/_index.md
- Add icons when available
- Ensure consistent formatting across pages
> Update instrumentation libraries

- assets/scss/main.scss
- content/en/_index.md
> improve homepage cncf section

- content/en/community/_index.md
- content/en/integrations/_index.md
- content/en/vendors/_index.md
- layouts/shortcodes/column.html
- layouts/shortcodes/row.html
- Add row and column shortcodes
- Also ensure vendors page is consistent
> Add integrations page

- assets/scss/_nav.scss
- src/js/base.js
> improve homepage scroll logic to fix nav problem

- content/en/registry/collector-exporter-loki.md
Added the Loki exporter to the registry.
> Added the Loki collector exporter to the registry

- content/en/registry/collector-exporter-f5cloud.md
Added the F5 Cloud exporter to the registry.
> Added F5 Cloud collector exporter to the registry

- content/en/registry/collector-exporter-sumologic.md
Added Sumo Logic exporter to the registry
> Added Sumo Logic collector exporter to the registry

- content/en/registry/collector-exporter-splunk-hec.md
Added Splunk HEC exporter to the registry.
> Added Splunk HEC collector exporter to the registry

- content/en/registry/collector-exporter-datadog.md
Added Datadog exporter to the registry
> Added Datadog collector exporter to the registry

- content/en/registry/collector-exporter-dynatrace.md
Added Dynatrace exporter to the registry
> Added Dynatrace collector exporter to the registry

- content/en/registry/collector-exporter-carbon.md
Added Carbon collector exporter to the registry
> Added Carbon collector exporter to the registry

- content/en/registry/collector-exporter-honeycomb.md
Added Honeycomb collector exporter to the registry
> Added Honeycomb collector exporter to the registry

- content/en/registry/collector-exporter-jaeger-thrift.md
Added Jaeger Thrift collector exporter to the registry
> Added Jaeger Thrift collector exporter to the registry

- content/en/registry/collector-exporter-load-balancing.md
Added the load-balancing collector exporter to the registry
> Added the load-balancing collector exporter to the registry

- content/en/registry/collector-exporter-splunk-sapm.md
Added Splunk SAPM collector exporter to the registry
> Added Splunk SAPM collector exporter to the registry

- content/en/registry/collector-exporter-sentry.md
Added Sentry collector exporter to the registry
> Added Sentry collector exporter to the registry

- content/en/registry/collector-exporter-signalfx.md
Added SignalFx collector exporter to the registry
> Added SignalFx collector exporter to the registry

- content/en/registry/collector-exporter-google-cloud-operations.md
Added Google Cloud Operations collector exporter to the registry
> Added Google Cloud Operations collector exporter to the registry

- content/en/registry/collector-exporter-alibaba-cloud-log-service.md
Added Alibaba Cloud Log Service collector exporter to the registry
> Added Alibaba Cloud Log Service collector exporter to the registry

- content/en/registry/collector-exporter-aws-cloudwatch-emf.md
Added AWS CloudWatch EMF collector exporter to the registry
> Added AWS CloudWatch EMF collector exporter to the registry

- content/en/registry/collector-exporter-aws-xray.md
Added AWS X-Ray collector exporter to the registry
> Added AWS X-Ray collector exporter to the registry

- content/en/registry/collector-exporter-azure-monitor.md
Added Azure Monitor collector exporter to the registry
> Added Azure Monitor collector exporter to the registry

- content/en/registry/collector-exporter-jaeger.md
Added Jaeger collector exporter to the registry
> Added Jaeger collector exporter to the registry

- content/en/registry/collector-exporter-kafka.md
Added Kafka collector exporter to the registry
> Added Kafka collector exporter to the registry

- content/en/registry/collector-exporter-file.md
Added File collector exporter to the registry
> Added File collector exporter to the registry

- content/en/registry/collector-exporter-logging.md
Added Logging collector exporter to the registry
> Added Logging collector exporter to the registry

- content/en/registry/collector-exporter-opencensus.md
Added OpenCensus collector exporter to the registry
> Added OpenCensus collector exporter to the registry

- content/en/registry/collector-exporter-otlp-grpc.md
Added OTLP gRPC collector exporter to the registry
> Added OTLP gRPC collector exporter to the registry

- content/en/registry/collector-exporter-otlp-http.md
Added OTLP HTTP collector exporter to the registry
> Added OTLP HTTP collector exporter to the registry

- content/en/registry/collector-exporter-prometheus.md
Added Prometheus collector exporter to the registry
> Added Prometheus collector exporter to the registry

- content/en/registry/collector-exporter-prometheus-remote-write.md
Added Prometheus Remote Write collector exporter to the registry
> Added Prometheus Remote Write collector exporter to the registry

- content/en/registry/collector-exporter-zipkin.md
Added Zipkin collector exporter to the registry
> Added Zipkin collector exporter to the registry

- assets/scss/_registry.scss
- assets/scss/_variables_project.scss
- layouts/registry/list.html
Add "Processor" and "Receiver" registry types used in the exporter
> Add "Processor" and "Receiver" registry types used in the exporter

- content/en/registry/collector-receiver-fluent-forward.md
- content/en/registry/collector-receiver-host-metrics.md
- content/en/registry/collector-receiver-jaeger.md
- content/en/registry/collector-receiver-kafka.md
- content/en/registry/collector-receiver-opencensus.md
- content/en/registry/collector-receiver-otlp.md
- content/en/registry/collector-receiver-prometheus.md
- content/en/registry/collector-receiver-zipkin.md
Added core collector receivers to registry
> Added core collector receivers to registry

- assets/scss/_registry.scss
- assets/scss/_variables_project.scss
- layouts/registry/list.html
Added 'extension' type to registry, so Collector extensions can be listed.
> Added 'extension' type to registry

- content/en/registry/collector-processor-attributes.md
- content/en/registry/collector-processor-batch.md
- content/en/registry/collector-processor-filter.md
- content/en/registry/collector-processor-memory-limiter.md
- content/en/registry/collector-processor-probablisistic-sampling.md
- content/en/registry/collector-processor-resource.md
- content/en/registry/collector-processor-span.md
Added core exporter processors to the registry
> Added core collector processors to the registry

- content/en/registry/collector-processor-group-by-attributes.md
- content/en/registry/collector-processor-group-by-trace.md
- content/en/registry/collector-processor-k8s.md
- content/en/registry/collector-processor-metrics-transform.md
- content/en/registry/collector-processor-resource-detection.md
- content/en/registry/collector-processor-routing.md
- content/en/registry/collector-processor-span-metrics.md
- content/en/registry/collector-processor-tail-sampling.md
Added collector contrib processors to registry
> Added contrib collector processors to registry

- content/en/registry/collector-extension-fluentbit-subprocess.md
- content/en/registry/collector-extension-healthcheck.md
- content/en/registry/collector-extension-pprof.md
- content/en/registry/collector-extension-zpages.md
Added core collector extensions to registry
These will be enabled by #460.
> Added core collector extensions to registry

- content/en/registry/collector-extension-host-observer.md
- content/en/registry/collector-extension-http-forwarder.md
- content/en/registry/collector-extension-k8s-observer.md
Added contrib collector extensions to registry.
Will be enabled by #460.
> Added contrib collector extensions to registry

- content/en/registry/collector-receiver-aws-ecs-container-metrics.md
- content/en/registry/collector-receiver-aws-xray.md
- content/en/registry/collector-receiver-carbon.md
- content/en/registry/collector-receiver-collectd.md
- content/en/registry/collector-receiver-docker-stats.md
- content/en/registry/collector-receiver-dotnet-diagnostics.md
- content/en/registry/collector-receiver-filelog.md
- content/en/registry/collector-receiver-jmx.md
- content/en/registry/collector-receiver-k8s-cluster.md
- content/en/registry/collector-receiver-kubelet-stats.md
- content/en/registry/collector-receiver-memcached.md
- content/en/registry/collector-receiver-nginx.md
- content/en/registry/collector-receiver-prometheus-exec.md
- content/en/registry/collector-receiver-receiver-creator.md
- content/en/registry/collector-receiver-redis.md
- content/en/registry/collector-receiver-sapm.md
- content/en/registry/collector-receiver-signalfx.md
- content/en/registry/collector-receiver-simple-prometheus.md
- content/en/registry/collector-receiver-splunk-hec.md
- content/en/registry/collector-receiver-statsd.md
- content/en/registry/collector-receiver-wavefront.md
- content/en/registry/collector-receiver-windows-perf-counters.md
- content/en/registry/collector-receiver-zookeeper.md
Added contrib collector receivers to registry.
> Added contrib collector receivers to registry

- content/en/docs/concepts/what-is-opentelemetry.md
Fixed typo found in issue #465
Fixes: #465 
> Fixed typo found in issue #465

- content/en/docs/java/instrumentation_examples.md
- content/en/docs/js/instrumentation_examples.md
As per the recommendations on open-telemetry/opentelemetry-java-instrumentation#2354 Submitting the Pull request
And previous pr https://github.com/open-telemetry/opentelemetry.io/pull/425
> Instrumentation examples resources

- content/en/docs/go/getting-started.md
WithPusher has been deprecated, WithExporter should be used.
> fix(docs) WithPusher has been deprecated

- .github/CODEOWNERS
Related to https://github.com/open-telemetry/opentelemetry-cpp/pull/636.
> Add cpp doc owners

- content/en/docs/collector/getting-started.md
Doc updates for https://github.com/open-telemetry/opentelemetry-collector/pull/2822
> Add info for deb/rpm collector service

- content/en/registry/instrumentation-java-jax-ws.md
Add JAX-WS to the java instrumentation list.
> add jax-ws to instrumentation

- content/en/docs/java/automatic_instrumentation.md
See https://github.com/open-telemetry/opentelemetry-java/pull/2090/files
> Update dependency for @WithSpan annotation

- content/en/docs/erlang/getting-started.md
While working through the guide, I found a few things to correct grammatically, and also tried to clarify a few things that I think may not be obvious to new-comers.
> Improvements while going through the Elixir guide

- content/en/docs/go/getting-started.md
This PR updates the Go getting started example to the current version of `opentelemetry-go`.
These changes are the bare minimum to run the example under `v0.19.0`.
Changes:
* Global `SetMeterProvider` moved from `otel` module to new `otel/metric` module (under `global` package) [v0.17.0](https://github.com/open-telemetry/opentelemetry-go/blob/main/CHANGELOG.md#0170---2021-02-12).
* Renamed the `otel/label` package to `otel/attribute` [v0.18.0](https://github.com/open-telemetry/opentelemetry-go/blob/main/CHANGELOG.md#0180---2021-03-03).
* New list of packages/modules for `go get` command.
For comparison, this is the current example output:
```
[
{
"Name": "ex.com.one{instrumentation.name=ex.com/basic,A=1,B=2,C=3,ex.com/lemons=10}",
"Last": 1,
"Timestamp": "2021-03-29T16:35:07.752143-03:00" …
```
> Update Go getting started example to use opentelemetry-go 0.19.0

- content/en/registry/instrumentation-js-mssql.md
Added registry entry for MSSQL JS instrumentation, as per
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/353
> registry entry for mssql js instrumentation

- assets/scss/_nav.scss
- config.toml
- content/en/community/_index.md
- content/en/registry/_index.md
- content/en/releases/_index.md
- layouts/partials/navbar.html
Provides an extra feature modification in accordance with https://github.com/open-telemetry/opentelemetry.io/issues/511
> Addition of navbar icons

- content/en/docs/concepts/glossary.md
Changing "data oints" to "data points".
> Fix a typo in the "glossary.md".

- package.json
- webpack.config.js
Supercedes dependabot update #560
> Update Webpack and fix build file

- content/en/status/_index.md
Turns out the collector is not quite stable yet.
> Clarify status of tracing in the collector

- content/en/registry/instrumentation-swift-urlsession.md
- content/en/registry/otel-swift.md
Also add  and the URLSession instrumentation for swift
> Add registry entry for opentelemetry-swift

- .github/ISSUE_TEMPLATE/DOCS_UPDATE.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/ISSUE_REPORT.md
- .github/PULL_REQUEST_TEMPLATE/DOCS_UPDATE.md
Hopefully this can direct people to the appropriate place to file issues/PRs for docs...
> Add initial issue and PR templates

- content/en/_index.md
> Add Quarkus as a framework with integration for OpenTelemetry

- static/schemas/1.5.0
Please merge this after https://github.com/open-telemetry/opentelemetry-specification/pull/1801 is merged.
> Publish OpenTelemetry Schema File 1.5.0

- content/en/docs/go/getting-started.md
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
> Ensure sample code in Go getting started page works

- content/en/status/_index.md
Follow up on https://github.com/open-telemetry/opentelemetry.io/pull/650#issuecomment-890831768.
> Fix typo and link to the feature freeze definition

- package.json
Got inspiration from https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/examples/web/package.json.
> Update webpack, and add @opentelemetry/api

- Makefile
- package.json
> Add npm scripts for submodule management

- CONTRIBUTING.md
- Makefile
- netlify.toml
- package.json
- Preparatory work for #693
- No change in generated site files
> Rework build commands

- config.toml
> Link to Community Marketing Guidelines

- content/en/docs/collector/_index.md
Closes #731
Preview: https://deploy-preview-732--opentelemetry.netlify.app/docs/collector/
> Collector: GH page links into this repo

- content/en/docs/collector/configuration.md
- content/en/docs/collector/getting-started.md
- Followup to #734
- No change to generated site files, modulo HTML comments.
Preview: https://deploy-preview-736--opentelemetry.netlify.app/docs/collector/getting-started/
> Collector: remove unused HTML comment directives

- content/en/docs/java/_index.md
- Matching https://github.com/open-telemetry/opentelemetry-java/commit/fca5bbe36b2f1e378eb6b5fdb3ce6e448db44119
- Prep work for #661
Reference:
- https://github.com/open-telemetry/opentelemetry-java/pull/3606
- /cc @open-telemetry/java-approvers
> Java 1.6.0 docs

- .gitmodules
- Contributes to #744
- No change in generated site files
> Switch to cncf/docsy repo, opentelemetry.io branch

- assets/scss/_styles_project.scss
Closes #751
Preview tests:
- https://deploy-preview-754--opentelemetry.netlify.app/status/#component-lifecycle
- https://deploy-preview-754--opentelemetry.netlify.app/docs/collector/getting-started/#deployment
- https://deploy-preview-754--opentelemetry.netlify.app/integrations/#within-opentelemetry
> Snap-to-anchor CSS adjustment

- content/en/status/_index.md
Followup to #752. /cc @reyang 
Preview: https://deploy-preview-761--opentelemetry.netlify.app/status/
> Add line-terminating whitespace to Metrics > SDK

- content/en/registry/instrumentation-java-honeycomb.md
Add Honeycomb.io OpenTelemetry Java Distro to Registry
> Add Honeycomb.io Java Distro to Registry

- content/en/registry/instrumentation-dotnet-honeycomb.md
Add Honeycomb.io OpenTelemetry .NET Distro to Registry
> Add Honeycomb.io OpenTelemetry .NET Distro to Registry

- content/en/docs/concepts/data-sources.md
Resolves #711
---
Preview: https://deploy-preview-740--opentelemetry.netlify.app/
Closes #711
> Add `Baggage` Signal to "Concepts"

- .github/CODEOWNERS
> Remove redundant entries from CODEOWNERS

- content/en/docs/cpp/_index.md
cc @open-telemetry/cpp-maintainers
> Update otel-cpp doc for release status

- content/en/docs/js/_index.md
- Context: https://github.com/open-telemetry/opentelemetry.io/pull/794#discussion_r718789086
- Preview: https://deploy-preview-795--opentelemetry.netlify.app/docs/js/
> Fix JS title capitalization

- content/en/docs/erlang/instrumentation.md
- Using docs from https://github.com/open-telemetry/opentelemetry-erlang/commit/9565e4f4f198645fb40a5a5fd9c5ef5dd9f83f99
- #730
- https://github.com/open-telemetry/opentelemetry-erlang/issues/280
> Erlang doc updates

- content/en/docs/js/api/_index.md
- content/en/docs/js/api/context.md
- content/en/docs/js/api/tracing.md
Document tracing and context APIs for JS
> JS API documentation

- content/en/docs/collector/getting-started.md
the otel local config   file path is incorrect.
> fix otel local config file path.

- content/en/status/_index.md
> fix: Typo in status of metrics

- content/en/vendors/_index.md
Added Sentry Software to the list of vendors supporting OpenTelemetry
> Added Sentry Software to the list of vendors supporting OpenTelemetry

- content/en/docs/workshop/_index.md
- content/en/docs/workshop/resources.md
Closes #895
Previews:
- https://deploy-preview-901--opentelemetry.netlify.app/docs/
- https://deploy-preview-901--opentelemetry.netlify.app/docs/workshop/
> Delist workshop from sidenav

- content/en/docs/concepts/components.md
- content/en/docs/concepts/data-sources.md
- content/en/docs/concepts/glossary.md
- content/en/docs/concepts/instrumenting-library.md
- content/en/docs/concepts/instrumenting.md
- content/en/docs/erlang/getting-started.md
- content/en/docs/erlang/instrumentation.md
- content/en/docs/js/api/context.md
- content/en/docs/js/api/tracing.md
- content/en/docs/js/getting-started/_index.md
- content/en/docs/js/instrumentation.md
- content/en/status/_index.md
> Link to spec pages in website rather than repo

- content/en/docs/concepts/glossary.md
- Closes #907
- Also copyedited the **Attribute** definition
Preview: https://deploy-preview-914--opentelemetry.netlify.app/docs/concepts/glossary/#attribute
Note: I'll have to fix the page-scroll adjustment, but I'll do that via a separate PR.
> Glossary: for Label, see Attribute

- .gitignore
- .vscode/cspell.json
This setups up the CSpell checker for interactive user under VS Code. I haven't given consideration to running this as a part of CI. We've got higher priority items to deal with before that.
Closes #927
> CSpell config

- content/en/docs/concepts/glossary.md
- content/en/docs/concepts/instrumenting-library.md
- content/en/docs/contribution-guidelines.md
- content/en/docs/js/exporters.md
- content/en/docs/js/getting-started/nodejs.md
Contributes to #922
Preview for the glossary: https://deploy-preview-924--opentelemetry.netlify.app/docs/concepts/glossary/
> Link to intra-site pages using a local reference

- content/en/registry/otel-collector-instana.md
Create new registry entry for the Instana Agent as collector
> Add Instana Agent as collector to the registry

- content/en/vendors/_index.md
> Add Aspecto to vendor list

- layouts/shortcodes/latest_release.md
- Closes #905
- Contributes to #922
> Submodule update for languages

- layouts/docs/baseof.html
Mainly we're picking up the PHP Getting started page update.
Preview: https://deploy-preview-946--opentelemetry.netlify.app/docs/php/getting_started/
> Update language submodules, and a layout tweak

- content/en/vendors/_index.md
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Add Grafana Labs to list of vendors

- assets/scss/_styles_project.scss
- content/en/community/_index.md
> Style community page paragraphs without headers

- assets/js/tracing.js
- package.json
Closes outstanding dependabot requests.
In addition, the web collector endpoint has been updated to v0.40.0.
> Update OpenTelemetry Dependencies

- content/en/docs/instrumentation/js/instrumentation.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/973
> Add section to get the current span in JS instrumentation

- content/en/registry/instrumentation-dotnet-azure-sdk.md
- content/en/registry/instrumentation-java-azure-sdk.md
- content/en/registry/instrumentation-js-azure-sdk.md
- content/en/registry/instrumentation-python-azure-sdk.md
Add Azure SDK instrumentations for Track2 libraries into the registry
> Add Azure SDK instrumentations to the registry

- content/en/docs/instrumentation/js/exporters.md
The way you do it isn't really specific to collectors, so this can be generally useful.
---
Preview: https://deploy-preview-988--opentelemetry.netlify.app/docs/instrumentation/js/exporters/
> Update JS collector config --> OTLP exporter config

- content/en/docs/instrumentation/js/instrumentation.md
This is mostly a refactor. The first major section had several embedded concepts in one, so I broke them out separately so that they're more easily searchable/navigable.
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/974
> Break out code sample to be explicit about nested spans in JS instrumentation doc

- .gitmodules
- content/en/docs/instrumentation/java
- Supersedes #978
- This is a temporary measure until we settle #989
Preview: https://deploy-preview-995--opentelemetry.netlify.app/docs/instrumentation/java/
> Drop old and add new Java docs submodule

- content/en/docs/concepts/glossary.md
Pulling in the improvements made upstream
Preview: https://deploy-preview-1003--opentelemetry.netlify.app/
> Refresh go docs

- .gitmodules
- content/en/docs/instrumentation/java
- content/en/docs/instrumentation/java/_index.md
- content/en/docs/instrumentation/java/automatic_instrumentation.md
- content/en/docs/instrumentation/java/instrumentation_examples.md
- content/en/docs/instrumentation/java/manual_instrumentation.md
- Contributes to #989
- There are no changes to the generated site files
Preview: https://deploy-preview-1002--opentelemetry.netlify.app/docs/instrumentation/java
/cc @cartermp
> Bring java docs home

- content/en/registry/instrumentation-ruby-action-pack.md
- content/en/registry/instrumentation-ruby-action-view.md
- content/en/registry/instrumentation-ruby-active-job.md
- content/en/registry/instrumentation-ruby-active-record.md
- content/en/registry/instrumentation-ruby-active-support.md
- content/en/registry/instrumentation-ruby-bunny.md
- content/en/registry/instrumentation-ruby-koala.md
- content/en/registry/instrumentation-ruby-lmdb.md
- content/en/registry/instrumentation-ruby-pg.md
- content/en/registry/instrumentation-ruby-que.md
- content/en/registry/instrumentation-ruby-resque.md
- content/en/registry/instrumentation-ruby-rspec.md
- content/en/registry/instrumentation-ruby-trilogy.md
Add missing registry entries for all Ruby instrumentations
> Add entries for Ruby instrumentations

- content/en/docs/instrumentation/java/manual_instrumentation.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/996
> Undent java code samples

- content/en/docs/concepts/glossary.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/1006
One more link issue 🙃 - keeping this as a draft
> Refresh go docs again

- content/en/docs/instrumentation/js/exporters.md
within exporter-trace-otlp-http section
> fix busted import/require doc

- content/en/docs/instrumentation/js/instrumentation.md
Not contributing to any particular issue, just filling in some gaps
Preview: https://deploy-preview-1023--opentelemetry.netlify.app/docs/instrumentation/js/instrumentation/
> Add events, links, and recording exceptions to JS instrumentation doc

- content/en/docs/instrumentation/net/exporters.md
- content/en/docs/instrumentation/net/netframework.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1001
Preview: https://deploy-preview-1027--opentelemetry.netlify.app/docs/instrumentation/net/netframework/
> Add .NET Framework instrumentation config page

- content/en/docs/instrumentation/net/manual.md
- content/en/docs/instrumentation/net/shim.md
(currently a draft -- need to handle acquiring and managing a Tracer before this is ready)
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1001
Preview: https://deploy-preview-1028--opentelemetry.netlify.app/docs/instrumentation/net/shim/
> Add tracing shim article for .NET

- layouts/partials/banner.md
> Remove GC election announcement

- content/en/docs/migration/_index.md
Closes #1036
Preview: https://deploy-preview-1049--opentelemetry.netlify.app/docs/migration/
> Add a top-level docs Migration section

- content/en/docs/instrumentation/net/manual.md
- content/en/docs/instrumentation/net/shim.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/1078
> .NET copyedits to remove passive voice

- content/en/registry/instrumentation-go-nhatthm-otelsql.md
Add `nhatthm/otesql` to the registry
> Add `nhatthm/otesql`

- content/en/docs/instrumentation/net/automatic.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/1042
I also adjusted the first sentence to be in line with our conversation.
> Update .NET automatic instrumentation title

- content/en/docs/instrumentation/java/manual.md
There are several inaccuracies in the current metrics java doc. While these docs need overall restructuring, I wasn't ready to tackle that effort. In the mean time, I did want to resolve some of the misleading inaccuracies. 
/cc @open-telemetry/java-maintainers
> Update java metrics docs so they correctly reflect current state

- package.json
- Closes #1088
- There are no changes to the generated site files:
```console
$ npm run check-links  
...
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0.") | head
$
```
> Upgrade to Hugo 0.92.1

- package.json
No change to the generated site files.
> Upgrade postcss etc

- .vscode/cspell.json
- scripts/adjust-spec-pages.pl
There is no change to the generated site files.
> adjust-spec-pagespl script tweak

- content/en/_index.md
> Link the Get-started ellipsis button to the instrumentation section

- scripts/cp-spec-pages.sh
No change in the generated site files.
> cp-spec-pages.sh: use git clean rather than rm

- content/en/docs/instrumentation/python/cookbook.md
- Contributes to #1109
- Note to @cartermp @ocelotl @codeboten et all: I've chosen to rename & retitle the page, simplifying it to just **Cookbook** because there are no questions in the page :). In anycase, @cartermp will be reworking the pages soon so maybe this page will be reworked too?
Preview: https://deploy-preview-1115--opentelemetry.netlify.app/docs/instrumentation/python/cookbook/
> Add Python cookbook

- content/en/docs/instrumentation/net/getting-started.md
> Update .NET getting-started.md

- content/en/docs/migration/opentracing.md
- Main edits for this PR:
- Reworked opening paragraphs and tweaked the **Overview**
- Move **Language version support** to be under **Limits on compatibility**, since IMHO that's where it makes the most sense.
- Contributes to #1037
- I'll continue my review if / after this PR gets approved and merged
Preview: https://deploy-preview-1090--opentelemetry.netlify.app/docs/migration/opentracing/
> OT migration 02/02 edits

- content/en/blog/2022/v1.0-trio.md
- @tedsuo @austinlparker : here's an example of the kind of post I have in mind for pages that have already been published on Medium. Given the nature of such a post, I don't even think that we need to bother with setting the canonical link. If you feel otherwise, I can look into it.
- Closes #1092
Preview: https://deploy-preview-1091--opentelemetry.netlify.app/blog/2022/v1.0-trio/
> Blog entry for v1.0-trio announcement

- package.json
> Update netlify-cli to 9.6.1

- .htmltest.yml
- Contributes to #906
- No change in the generated site files
> Link check: remove ignore rules now that spec has been fixed

- content/en/blog/2022/auto-instrumentation-k8s.md
Preview: https://deploy-preview-1136--opentelemetry.netlify.app/blog/2022/auto-instrumentation-k8s
> Blog: add ref to Medium post on auto-instrumentation-k8s

- archetypes/medium.md
- content/en/blog/2021/otel-gc.md
Preview: https://deploy-preview-1140--opentelemetry.netlify.app/blog/2021/otel-gc
> Blog post for 2021 GC

- content/en/blog/2021/cpp-v1.md
- content/en/blog/2021/gc-election.md
- content/en/blog/2021/malabi.md
Preview:
- https://deploy-preview-1141--opentelemetry.netlify.app/blog/2021/cpp-v1
- https://deploy-preview-1141--opentelemetry.netlify.app/blog/2021/gc-election
- https://deploy-preview-1141--opentelemetry.netlify.app/blog/2021/malabi
> From Medium blog: C++ v1, GC-election and Malabi

- content/en/blog/2021/collector.md
- content/en/blog/2021/cpp.md
- content/en/blog/2021/python.md
- content/en/blog/2021/swift.md
- content/en/blog/2021/womens-day.md
- content/en/blog/2022/v1.0-trio.md
Preview:
- https://deploy-preview-1142--opentelemetry.netlify.app/blog/2021/collector
- https://deploy-preview-1142--opentelemetry.netlify.app/blog/2021/python
- https://deploy-preview-1142--opentelemetry.netlify.app/blog/2021/swift
- https://deploy-preview-1142--opentelemetry.netlify.app/blog/2021/womens-day
- https://deploy-preview-1142--opentelemetry.netlify.app/blog/2021/cpp -- updated link so as to be consistent with the new posts being added in this PR (I'm choosing not to add a redirect since `cpp-v1` was added ~ 20 min ago).
> Medium blog posts: last batch

- content/en/docs/collector/getting-started.md
Open Telemetry collector service name changed from `otel-collector` to `otelcol`
> Update otel collector service name

- .gitmodules
- content/en/docs/instrumentation/php
- content/en/docs/instrumentation/php/_index.md
- content/en/docs/instrumentation/php/getting-started.md
- Contributes to #1154
- No change to the generated site files except for these changes to PHP pages:
- git info
- Page-modified timestamps
- Page-meta (GitHub) links
Preview: https://deploy-preview-1156--opentelemetry.netlify.app/docs/instrumentation/php/
/cc @open-telemetry/php-approvers
> Make php pages local

- content/en/docs/instrumentation/java/_index.md
Signed-off-by: Kevin Earls <kearls@redhat.com>
> Correct link to Java examples

- content/en/docs/instrumentation/erlang/getting-started.md
- content/en/docs/instrumentation/erlang/instrumentation.md
Edit (@chalin):
Preview: https://deploy-preview-1167--opentelemetry.netlify.app/docs/instrumentation/erlang/getting-started/
> erlang/elixir getting started: add section using otlp exporter

- content/en/status.md
- Contributes to #1170
Preview: https://deploy-preview-1175--opentelemetry.netlify.app/status/
> Status page rework

- content/en/docs/instrumentation/python/_index.md
- content/en/docs/instrumentation/python/automatic.md
- content/en/docs/instrumentation/python/distro.md
- content/en/docs/instrumentation/python/getting-started.md
Just newline/whitespace changes.
> Normalize line lengths in python docs

- layouts/_default/baseof.html
There are no changes to the generated site files.
> Remove workaround from baseof.html

- content/en/blog/2022/troubleshooting-nodejs.md
- Followup to #1166
- Mostly markdown cleanup
- Moved the "original post" fragment to the bottom of the article, otherwise it shows up in post's summary in the blog-summary page
/cc @blumamir @austinlparker
> Copyedits for TroublesShooting Node.JS blog entry

- content/en/docs/instrumentation/erlang/getting-started.md
- content/en/docs/instrumentation/net/automatic.md
- content/en/docs/migration/opentracing.md
> Fix link intra-site links

- content/en/docs/instrumentation/java/automatic.md
Preview: https://deploy-preview-12010--opentelemetry.netlify.app/docs/instrumentation/java/automatic
> Java auto: use direct download link for javaagent.jar

- content/en/docs/instrumentation/net/shim.md
> Correct some problems in .NET OTel shim doc

- LICENSE
- LICENSE-CODE
- README.md
This will make the Clomonitor happy :) - https://clomonitor.io/projects/open-telemetry/open-telemetry.
> Use standard license files

- content/en/docs/instrumentation/java/_index.md
- content/en/docs/instrumentation/java/examples.md
Followup to #1203.
Preview:
- https://deploy-preview-1216--opentelemetry.netlify.app/docs/instrumentation/java/
- https://deploy-preview-1216--opentelemetry.netlify.app/docs/instrumentation/java/examples/
> Java: rework prose referring to examples

- content/en/_index.md
- content/en/docs/instrumentation/java/getting-started.md
- Closes #1195
Preview: https://deploy-preview-1224--opentelemetry.netlify.app/docs/instrumentation/java/getting-started/
/cc @svrnm
> New Java getting-started page

- content/en/docs/migration/_index.md
- content/en/docs/migration/opentracing.md
- Closes #1037
Preview: https://deploy-preview-1228--opentelemetry.netlify.app/docs/migration/opentracing
/cc @tedsuo @yurishkuro @calebmchenry @austinlparker
> Publish OpenTracing-migration page

- CONTRIBUTING.md
/cc @austinlparker @nate-double-u
> Contributing: improve setup instructions

- content/en/docs/collector/getting-started.md
> added link to collector helm charts

- content/en/docs/collector/getting-started.md
- Closes #1180
- Implements @jpkrohling's suggestion -- https://github.com/open-telemetry/opentelemetry.io/issues/1180#issuecomment-1056660328
- Also tweaks the opening paragraph
Preview: https://deploy-preview-1245--opentelemetry.netlify.app/docs/collector/getting-started/#getting-started
> [Collector] Drop docker section

- content/en/docs/instrumentation/java/automatic/annotations.md
cc @open-telemetry/java-instrumentation-approvers
In particular, does anyone have better idea for the term "future promise"?
> Document WithSpan future promise behavior

- content/en/docs/instrumentation/java/automatic/agent-config.md
Resolves https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5701 (not sure if that works cross repo?)
EDIT cc @open-telemetry/java-instrumentation-approvers
> Add controller and view span suppressing configuration doc

- content/en/docs/instrumentation/js/api/tracing.md
Noticed minor inconsistencies.
> Minor updates to the content

- content/en/docs/collector/_index.md
> Add a section for when to use a collector

- CONTRIBUTING.md
- README.md
- content/en/_index.md
- content/en/community/_index.md
- content/en/docs/_index.md
- content/en/registry/_index.md
- package.json
Initial manual tests of using [Prettier](https://prettier.io) as a means of addressing:
- #1063
> Add Prettier tool & normalize markdown of selected files

- content/en/docs/instrumentation/java/manual.md
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/1031
> Rethrow exception in java example, don't swallow it

- content/en/registry/exporter-js-instana.md
This supersedes #797. Talked to @willianpc on slack about pushing the PR again. He said to push it for him as doesn't have CLA setup.
Author: Willian Carvalho <willianc@pm.me>
Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>
> Add Instana JS exporter to registry

- content/en/docs/instrumentation/python/exporters.md
> [python] http ain't grpc

- .gitignore
> Ignore .netlify folder

- content/en/docs/instrumentation/erlang/getting-started.md
Ref: https://elixir-lang.slack.com/archives/CA4CNK38B/p1651066048556039
> [Erlang] Provide working stdout exporter config

- content/en/blog/2022/dotnet-instrumentation-first-beta.md
> Fix a hyperlink in dotnet-instrumentation-first-beta.md

- content/en/vendors.md
Edit (@chalin):
- Preview: https://deploy-preview-1337--opentelemetry.netlify.app/vendors/
> Add Lumigo to the vendors supporting OpenTelemetry

- content/en/blog/2022/metrics-announcement.md
Will merge at 9am PT today (05/18/22), unless someone says otherwise. /cc @mtwo @alolita @austinlparker
> Announce metrics RCs on production server

- content/en/docs/instrumentation/java/automatic/agent-config.md
> Update suppression keys

- content/en/_index.md
- content/en/mission-vision-and-values.md
- content/en/mission.md
> Add mission page

- .github/CODEOWNERS
> Add .NET approvers to CODEOWNERS

- content/en/status.md
- No change in page content (visually inspected side-by-side).
> Status page: format markdown

- content/en/status.md
- Reworks the page heading
- Closes #1377
- Closes #1334
Preview: https://deploy-preview-1380--opentelemetry.netlify.app/status/
/cc @tedsuo
> Status: fix heading and drop obsolete subtitle

- content/en/vendors.md
I am not very clear on what does `Distribution` field mean. I have kept it as `Yes` as product similar to ours has this as `Yes`. 
Please advise on what does it mean and if our entry should be changed
> Add SigNoz in the vendor list

- content/en/_index.md
- content/en/mission.md
> use oxford commas for mission

- content/en/docs/instrumentation/net/getting-started.md
You know what I love? YAML. It's the best. Nothing like some YAML in my life.
> Update yaml code block in .NET getting started

- content/en/registry/instrumentation-js-amqplib.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/1393
> update amqplib registry

- content/en/docs/acknowledgements/_index.md
The content in the gist was written by Alexandria Pigram as a part of work with Honeycomb. The gist was a way to "bootstrap" getting the content somewhere so we could utilize it here, but now we should do the proper acknowledgement.
> Update tracing content acknowledgement

- content/en/docs/concepts/observability-primer.md
> typo fixed

- content/en/docs/instrumentation/python/manual.md
Preview: https://deploy-preview-1403--opentelemetry.netlify.app/docs/instrumentation/python/manual/#create-span-with-decorators
> Add subsection for using a decorator in python manual tracing doc

- netlify.toml
> add blog redirect

- content/en/docs/acknowledgements/_index.md
- content/en/docs/collector/_index.md
- content/en/docs/concepts/components.md
- content/en/docs/concepts/data-collection.md
- content/en/docs/concepts/distributions.md
- content/en/docs/concepts/glossary.md
- content/en/docs/concepts/instrumenting-library.md
- content/en/docs/concepts/instrumenting.md
- content/en/docs/concepts/observability-primer.md
- content/en/docs/concepts/signals/_index.md
- content/en/docs/concepts/what-is-opentelemetry.md
- content/en/docs/instrumentation/_index.md
- content/en/docs/reference/_index.md
Minor(?) change: I thought it would be nice to have some more descriptions on the overview pages.
> Add descriptions to pages

- content/en/docs/concepts/sdk-configuration/otlp-exporter-configuration.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/1437
> Update OTLP SDK Config docs as per feedback

- content/en/registry/sdk-swift-nautilustelemetry.md
Adding a registry entry for [NautilusTelemetry](https://github.com/eBay/NautilusTelemetry)
> Add nautilus telemetry

- README.md
> Add some more useful contribution links to readme

- content/en/docs/concepts/signals/traces.md
This comes from https://github.com/open-telemetry/opentelemetry.io/pull/1445#discussion_r899486297
This mostly rewords the definition and provides a more motivating example.
> Clarify span event definition

- content/en/docs/concepts/signals/_index.md
- Closes #1446
- Other page-normalization changes affect only whitespace
Preview redirect test: 
- https://deploy-preview-1459--opentelemetry.netlify.app/docs/concepts/data-sources/
> Adds redirect for concepts/data-sources

- package.json
The only diff in the generated site files seems to be due to an upgrade in Chroma:
```console
$ npm run cd:public -- git diff -bw --ignore-blank-lines -I "Hugo 0." -- . ':(exclude)*.[^h]*' | head -100
...
```
```diff
diff --git a/docs/instrumentation/net/netframework/index.html b/docs/instrumentation/net/netframework/index.html
index c4729d74..7fe90d0a 100644
--- a/docs/instrumentation/net/netframework/index.html
+++ b/docs/instrumentation/net/netframework/index.html
@@ -1059,7 +1059,7 @@ with other OpenTelemetry initialization:</p>
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#204a87;font-weight:bold">public</span> <span style="color:#204a87;font-weight:bold">class</span> <span …
```
> Upgrade Hugo to 0.101.0

- content/en/registry/collector-processor-probablisistic-sampling.md
- content/en/registry/instrumentation-js-generic-pool.md
Fixes 2 typos in the registry.
> 2 typo fixes for registry

- content/en/docs/instrumentation/net/shim.md
Preview: https://deploy-preview-1488--opentelemetry.netlify.app/docs/instrumentation/net/shim/#aspnet-core
This was missing some code that actually enabled a trace to get kicked off in an aspnetcore context, so I resolved that and changed the code samples a bit in the process.
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/1487
> fix up content in .NET shim doc to work and be better

- content/en/blog/2022/k8s-metadata.md
@rubenvp8510 - might you want to link to your GH page? If so, this PR adds such a link. If not, we can just close this PR.
Preview: https://deploy-preview-1490--opentelemetry.netlify.app/blog/2022/k8s-metadata/
> K8s blog post: link to author page

- content/en/vendors.md
- Closes #1196
This isn't a perfect solution, but it is IMHO a step in the right direction -- enough so to warrant closing #1196. At some point we might prefer to have the table be generated from data, but we can face that later (if at all).
Preview: https://deploy-preview-1491--opentelemetry.netlify.app/vendors/
---
**Before** (note that the table doesn't fit _and_ the raw links are line-wrapped in some cases):
> <img width="724" alt="image" src="https://user-images.githubusercontent.com/4140793/176520135-8fe6accd-0386-4529-a4e4-dac6248d6949.png">
**After** (the table still doesn't fit on narrow mobile devices, but it does scroll horizontally, and is much narrower than before)
> <img width="727" alt="image" src="https://user-images.githubusercontent.com/4140793/176520207-be5b0a64-2f7f-447 …
> Vendor page, improve layout on mobile

- content/en/blog/2022/new-end-user-resources.md
- Followup to #1498
- Copyedits
- (Ran prettifier)
Preview: https://deploy-preview-1504--opentelemetry.netlify.app/blog/2022/new-end-user-resources/
/cc @sharrmander @austinlparker
> Copyedits for End User Resources blog post

- layouts/partials/banner.md
New announcement highlighting cool new resources for end users
This relates to https://github.com/open-telemetry/opentelemetry.io/issues/1449
Preview: https://deploy-preview-1503--opentelemetry.netlify.app/
> Update banner for end user discussion groups

- package.json
- Closes #1508 by superseding it
- No changes to the generated site files
> Update NPM dev dependencies

- layouts/partials/google-analytics.html
> Analytics: explicitly config GA4

- layouts/partials/google-analytics.html
- Contributes to #1515, option 2
> Analytics: configure both GA4 and UA IDs explicitly

- config.yaml
- layouts/partials/google-analytics.html
> Analytics: use a site-tag list

- content/en/docs/instrumentation/rust/_index.md
Signed-off-by: Harold Dost <h.dost@criteo.com>
> Add Links the to base API and SDK

- content/en/docs/concepts/signals/traces.md
I think this more or less resolves https://github.com/open-telemetry/opentelemetry.io/issues/1443
I wasn't very happy with the definition in place here, so hopefully this better explains it.
---
Preview: https://deploy-preview-1537--opentelemetry.netlify.app/docs/concepts/signals/traces/#span-context
> Rewrite subsection on span context

- content/en/docs/concepts/signals/traces.md
To assist OTel (and/or observability) newcomers to better understand.
> Add explanation of the trace sample

- content/en/docs/instrumentation/python/exporters.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/1586
> Update HTTP exporter section in python to specify endpoint

- content/en/docs/instrumentation/java/manual.md
This PR fixes #1582 by adding the resource and attributes creation for the SDK set up.
> Added resource and attributes creation for the SDK set up

- content/en/docs/collector/_index.md
A proposal for the collector-status section.
- Closes #1573
- Contributes to #1574
Preview: https://deploy-preview-1576--opentelemetry.netlify.app/docs/collector/#status-and-releases
/cc @open-telemetry/collector-contrib-approvers @cartermp @TylerHelmuth @austinlparker
> Add collector status

- content/en/docs/reference/specification/status.md
- content/en/status.md
- Followup to #1606
Preview: https://deploy-preview-1607--opentelemetry.netlify.app/docs/reference/specification/status
> Spec status: readjust page-meta links

- content/en/docs/concepts/signals/traces.md
@chalin this has all the feedback from https://github.com/open-telemetry/opentelemetry.io/pull/1592 incorporated
> Additions to span subsection in conceptual docs

- content/en/_index.md
This attribute fixes the problem but is not appropriate for this block.
changed to a more suitable item
all check
https://github.com/open-telemetry/opentelemetry.io/pull/1619
https://github.com/open-telemetry/opentelemetry.io/pull/1617
> Homepage: accessibility link attribute update

- content/en/docs/instrumentation/js/exporters.md
See #1567, @cartermp: what do you think?
> Move nodejs exporters for jaeger to OTLP.

- config.yaml
> Hugo config: use placeholder for GA ID

- .gitpod.yml
- Addresses #1026, maybe even closes it if @cartermp thinks that it's good enough.
> Gitpod minimal config

- content/en/blog/2022/new-end-user-resources.md
EMEA discussion group is now on the calendar :D
> add EMEA end user discussion group time

- archetypes/blog.md
Based on the previous few blog posts I suggest that we update the archetype to
* contain an example for the linked author name
* ask people to use prettier.
> Update blog archetype

- content/en/docs/concepts/sdk-configuration/otlp-exporter-configuration.md
> Document correction

- content/en/blog/2022/instrument-nginx/index.md
> Remove "draft" status from nginx blog

- package.json
- Closes #1641 by superseding it
> Upgrade netlify-cli

- content/en/docs/instrumentation/java/automatic/annotations.md
Fixing [typo](https://github.com/open-telemetry/opentelemetry.io/pull/1642#discussion_r951943831).
> Fix instrumentation annotations reference

- content/en/docs/instrumentation/js/_index.md
Didn't realise the status table has been out of date for a very long time.
> Fix outdated JS status table

- content/en/docs/instrumentation/net/netframework.md
Perhaps some errant copy-paste, but this does not work without the changes here.
> Update netframework code to compile

- content/en/blog/2022/instrument-nginx/index.md
the last image was linked incorrectly.
> Update picture URL in nginx blog

- layouts/registry/list.html
resolve https://github.com/open-telemetry/opentelemetry.io/issues/1637
> Registry: accessibility fix list

- config.yaml
Provided link to show meeting recordings in community page
> Provided link to show meeting recordings in community page

- README.md
As the title suggests I added some wording to the READM.md that should encourage people who are new to opentelemetry to raise issues if there's something unclear with the docs.
> Add some instructions for new comers to README.md

- assets/scss/_styles_project.scss
- content/en/status.md
This is the second part of the change in issue #1570
> added styling for status boxes

- content/en/registry/collector-exporter-instana.md
Related https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13395
> Add Instana Collector Exporter to registry

- content/en/docs/instrumentation/js/api/context.md
The zone.js repo has been moved to angular mono repo
> update link to zone.js

- layouts/registry/list.html
resolve https://github.com/open-telemetry/opentelemetry.io/issues/1719
> add indent to list (ui)

- layouts/registry/list.html
resolve https://github.com/open-telemetry/opentelemetry.io/issues/1737
after fix
when there is enough space it becomes as it was in a line
> fix content goes outside the container

- content/en/docs/instrumentation/erlang/testing.md
Haven't contributed to OTel before - thank you for your patience.
TODO: Erlang test example
Submission is based on a [blog post I wrote](https://temporaryhack.com/blog/opentelemetry-testing)
> Elixir testing doc

- content/en/blog/2022/gc-elections-2022.md
Blog post announcing the GC Elections 2022
Closes https://github.com/open-telemetry/community/issues/1166
> Blog post - GC elections 2022

- layouts/registry/list.html
resolve https://github.com/open-telemetry/opentelemetry.io/issues/1751
> update registry block list

- layouts/partials/banner.md
fixes #1750 
Preview: https://deploy-preview-1756--opentelemetry.netlify.app/
> announce gc elections via banner.

- content/en/docs/instrumentation/java/_index.md
- content/en/docs/instrumentation/java/automatic/annotations.md
We have the same for the collector getting started, makes it easier to update (and it's one step closer towards automation)
> java version as variable

- content/en/blog/2022/gc-elections-2022.md
Related: #1752, #1754, cc @jpkrohling , @SergeyKanzhelev 
Preview: https://deploy-preview-1757--opentelemetry.netlify.app/blog/2022/gc-elections-2022/
> update link to internal blog for gc announcement

- content/en/docs/concepts/glossary.md
#1699  Updating the APM definition.
> Update APM definition

- content/en/docs/collector/getting-started.md
> fix collector version

- content/en/blog/2022/dotnet-instrumentation-first-beta.md
Per https://github.com/open-telemetry/opentelemetry.io/issues/1689#issuecomment-1258313074
Thanks @svrnm 👍
> Do not use the confusing term "agent"

- content/en/docs/concepts/observability-primer.md
This PR resolves https://github.com/open-telemetry/opentelemetry.io/issues/1686 .
Preview: https://deploy-preview-1794--opentelemetry.netlify.app/docs/concepts/observability-primer/
> Removed span attributes image and converted to table.

- content/en/blog/2022/announcing-community-manager.md
This is a blog post to announce the new community manager role.
> Community Manager Announcement Post

- package.json
There is no significant changes in the generated site files:
```console
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0\.")
$
```
> Hugo and deps upgrade

- content/en/registry/exporter-go-instana.md
Update to the content/en/registry with the Instana Go exporter .md file.
> Added Instana Go exporter to the registry

- content/en/docs/instrumentation/js/libraries.md
> Add Typescript to "libraries" js doc

- content/en/docs/instrumentation/net/resources.md
First part of https://github.com/open-telemetry/opentelemetry.io/issues/1835
As noted in the issue, I can't actually get the docker resource detector to work for the simple console app.
> Add AddService to .NET resource doc

- content/en/blog/2022/debug-otel-with-otel/index.md
prettier introduced some more changes, but the relevant part is in line 210 onwards.
@yurishkuro does this sound good to you? TY
> Change misleading statements in blog post, fixes #1790

- data/instrumentation.yaml
Related to https://github.com/open-telemetry/opentelemetry-ruby/pull/1390
> Add status values for ruby to yaml

- content/en/blog/2022/kubecon-na.md
cc @alolita @djaglowski 
I visited all the links and reviewed the dates, but if some one could do another round of checks that would be appreciated
> Fix dates for KubeCon NA

- content/en/docs/instrumentation/cpp/exporters.md
I thought this might be yet another good addition to the CPP docs :)
> Add prometheus exporter to c++ docs

- README.md
as per our discussion on slack.
> Add a note to the README about instructional blog posts.

- content/en/blog/2022/opamp/index.md
> opamp blog typo grammar fixes

- content/en/blog/2022/announcing-opentelemetry-demo-release.md
> Add Demo GA Blog

- layouts/partials/banner.md
GC election is all done, and the GA release of the demo is far more interesting!
> Update banner to point at demo GA release

- content/en/docs/instrumentation/erlang/testing.md
Closes #1905
Thanks to @tsloughter for helping me figure this out!
> Fix broken elixir testing docs

- content/en/blog/2022/kubecon-na-project-update.md
To be published at 10:00 AM ET
> Post Kubecon project update

- config.yaml
> Update privacy policy link in footer

- content/en/registry/collector-receiver-k8sobjects.md
> Add K8s Objects collector receiver to registry

- content/en/docs/instrumentation/java/automatic/_index.md
Some more places where "instrumentation library" is the more accurate term.
> Update Automatic page for Java

- content/en/registry/instrumentation-js-cassandra.md
- content/en/registry/instrumentation-js-dataloader.md
- content/en/registry/instrumentation-js-fs.md
- content/en/registry/instrumentation-js-lru-memoizer.md
- content/en/registry/instrumentation-js-nestjs-core.md
- content/en/registry/instrumentation-js-redis-4.md
- content/en/registry/instrumentation-js-tedious.md
- content/en/registry/instrumentation-python-aio-pika.md
- content/en/registry/instrumentation-python-aiohttp-client.md
- content/en/registry/instrumentation-python-boto3sqs.md
- content/en/registry/instrumentation-python-confluent-kafka.md
- content/en/registry/instrumentation-python-falcon.md
- content/en/registry/instrumentation-python-httpx.md
- content/en/registry/instrumentation-python-kafka-python.md
- content/en/registry/instrumentation-python-logging.md
- content/en/registry/instrumentation-python-pika.md
- content/en/registry/instrumentation-python-remoulade.md
- content/en/registry/instrumentation-python-sklearn.md
- content/en/registry/instrumentation-python-urllib.md
- content/en/registry/instrumentation-python-urllib3.md
- content/en/registry/instrumentation-ruby-base.md
- content/en/registry/instrumentation-ruby-rake.md
- content/en/registry/instrumentation-ruby-rdkafka.md
Some more missing registry entries.
> Add instrumentations for python, ruby, JS to registry.

- assets/scss/_styles_project.scss
(Edit @chalin)
- Contributes to #1866
> Update <a> colors for dark and secondary sections

- content/en/registry/instrumentation-erlang-ecto.md
- content/en/registry/instrumentation-erlang-oban.md
- content/en/registry/instrumentation-erlang-phoenix.md
- content/en/registry/instrumentation-erlang-redix.md
- content/en/registry/instrumentation-erlang-tesla.md
Add erlang instrumentations to registry
> Add erlang instrumentations to registry

- README.md
- content/en/blog/2022/debug-otel-with-otel/index.md
- content/en/blog/2022/dotnet-instrumentation-first-beta.md
- content/en/blog/2022/k8s-otel-expose/index.md
- content/en/docs/collector/configuration.md
- content/en/docs/instrumentation/cpp/manual.md
- content/en/docs/instrumentation/js/instrumentation.md
- content/en/docs/instrumentation/net/automatic.md
- content/en/docs/instrumentation/swift/manual.md
- content/en/registry/collector-receiver-httpcheck.md
This PR fixes several typos found in markdown files.
> Fixing typos

- content/en/docs/instrumentation/js/api.md
- content/en/docs/instrumentation/js/api/_index.md
- content/en/docs/instrumentation/js/context.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1808
> Add JS API ref to sidebar

- content/en/docs/instrumentation/python/api.md
- content/en/docs/instrumentation/python/cookbook.md
- content/en/docs/instrumentation/python/distro.md
- content/en/docs/instrumentation/python/mypy.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1808
> Add Python API ref to sidebar

- content/en/docs/instrumentation/net/shim.md
This is #1867 but also applied to the tracing shim doc.
> Add independent and root span section to .NET shim

- content/en/blog/2022/announcing-opentelemetry-demo-release.md
> updated 2 links for more accuracy

- content/en/docs/collector/custom-auth.md
Signed-off-by: windsonsea <haifeng.yao@daocloud.io>
Tweak the long lines to keep a consistent style with other pages in this folder.
> Tweak line wrappings in custom-auth.md

- content/en/registry/exporter-dotnet-otlp.md
- content/en/registry/exporter-erlang-otlp.md
- content/en/registry/exporter-go-otlp.md
- content/en/registry/exporter-java-otlp.md
- content/en/registry/exporter-python-otlp.md
- content/en/registry/exporter-rust-otlp.md
> Improve the OTLP exporter description in all existing registry entries

- content/en/docs/_index.md
- content/en/docs/contribution-guidelines.md
- content/en/registry/collector-extension-healthcheck.md
- Tweak long lines to keep consistent style, and easily recognizing PR changes if any update later
- Other minor changes about consistency and grammar
```
content/en/docs/_index.md
content/en/docs/contribution-guidelines.md
content/en/registry/collector-extension-healthcheck.md
```
> tweak long line wrappings in 2 docs

- content/en/community/end-user/discussion-group.md
I edited the copy to make these sound more enticing, and also added upcoming dates for this month and next.
> Update monthly End User Discussion Group meetings copy and add dates

- content/en/docs/collector/_index.md
Only tweak long lines with prettier, no any content change.
```
content/en/docs/collector/_index.md
```
> Tweak line wrappings in /collector/_index.md

- content/en/docs/instrumentation/js/libraries.md
As mentioned in https://github.com/open-telemetry/opentelemetry.io/issues/1772 let's try this out
> Use tabpane for JS libraries doc

- content/en/docs/instrumentation/js/getting-started/browser.md
Should fix https://github.com/open-telemetry/opentelemetry.io/issues/1989
> Mention parcel and installation of it above code samples

- content/en/docs/collector/configuration.md
Performed two actions:
1. Run `npx prettier --w`
2. Manually check and tweak all lines
> Updated /collector/configuration.md

- .github/workflows/auto-update-collector-version.yml
- .github/workflows/scripts/check-collector-version.sh
Some more fixes, this worked on my fork, so hopefully it works here as well
> Fix collector version checker

- .github/workflows/auto-update-collector-version.yml
- .github/workflows/scripts/check-collector-version.sh
* Run collector checker only daily,
* Run only on fixed repos (fixes #2006)
* check for existing PRs
cc: @chalin
> Collector Version Checker Workflow fixes

- content/en/blog/2022/kubecon-na-project-update.md
- Tweak long lines 
- Added an `and`
No other changes.
> Tweak line wrappings in /blog/2022/kubecon-na-project-update.md

- content/en/docs/concepts/data-collection.md
- content/en/docs/concepts/signals/traces.md
- content/en/docs/concepts/what-is-opentelemetry.md
Mainly applying CNCF guidelines for "open source": https://github.com/cncf/foundation/blob/main/style-guide.md
> Text and style fixes for concept pages

- content/en/community/_index.md
- content/en/community/end-user/discussion-group.md
- content/en/community/end-user/slack-channel.md
Some minor fixes to the end user pages.
> Text and style fixes for community pages

- content/en/docs/instrumentation/swift/libraries.md
- content/en/docs/instrumentation/swift/manual.md
Typos & style fixes for swift docs.
> Fixes for Swift Doc

- content/en/blog/2022/frontend-overhaul/index.md
via @xoscar (https://github.com/open-telemetry/opentelemetry.io/pull/1877#issuecomment-1317181324)
@cartermp , @chalin please approve & merge
> Un-Draft Front-end overhaul blog post

- data/instrumentation.yaml
> updated swift instrumentation status

- content/en/registry/instrumentation-java-jmxmetrics.md
> Add JMX Metric Insight to Registry

- content/en/docs/migration/opentracing.md
```
content/en/docs/migration/opentracing.md
```
> optimize some text and layout in opentracing.md

- content/en/docs/instrumentation/python/getting-started.md
1. fields like name, http.target, http.route had wrong value '/roll' which should be '/rolldice' 
2. updated resource object structure
> fix instrumentation example json output

- content/en/blog/2022/announcing-opentelemetry-demo-release.md
Tweak some long lines in:
```
content/en/blog/2022/announcing-opentelemetry-demo-release.md
```
> tweak line wrappings in announcing-opentelemetry-demo-release.md

- content/en/community/end-user/discussion-group.md
Tweak long lines in:
```
content/en/community/end-user/discussion-group.md
```
> Tweak line wrappings in discussion-group.md

- content/en/community/_index.md
Closes https://github.com/open-telemetry/opentelemetry.io/issues/1449
> Add end-user section to community index page

- .github/workflows/scripts/check-collector-version.sh
> Fix bug in check-collector-version.sh

- content/en/docs/instrumentation/swift/libraries.md
Have a try to improve the layout of this section:
- before
- after
> Updated layout in instrumentation/swift/libraries.md

- content/en/vendors.md
Company website - https://www.kloudfuse.com/. Playground link with traces using otlp collector - https://playground.kloudfuse.io/#/apm/services
> Added kloudfuse as a vendor

- content/en/community/end-user/discussion-group.md
Added GMT to AMER and EMEA time zones as well for consistency.
> Add GMT to time zones

- content/en/docs/instrumentation/swift/manual.md
- Tweak long lines
- Remove trailing spaces
> Tweak lines in /instrumentation/swift/manual.md

- content/en/docs/concepts/instrumenting.md
As discussed a few times I am not very happy with the current state of the Instrumenting page. This is a try to make it better. 
https://deploy-preview-2063--opentelemetry.netlify.app/docs/concepts/instrumenting/
> Rework instrumenting page

- content/en/registry/collector-exporter-logicmonitor.md
- content/en/registry/collector-receiver-promtail.md
- content/en/registry/collector-receiver-purefa.md
- content/en/registry/exporter-dotnet-opentelemetryprotocolgrpc.md
- content/en/registry/instrumentation-java-annotations.md
- content/en/registry/instrumentation-java-dropwizard.md
- content/en/registry/instrumentation-java-extensionkotlin.md
- scripts/registry-scanner/index.mjs
> Registry Updates 2022.12

- content/en/docs/instrumentation/js/instrumentation.md
Hey, I added some tabbed content for the instrumentation in javascript. I hope I did everything accordingly. There are still some snippets left to do. I will try to get them done next week. :)
> add tabbed content to instrumentation in js

- content/en/registry/resource-detector-go-aws.md
- content/en/registry/resource-detector-go-gcp.md
- content/en/registry/resource-detector-js-alibabacloud.md
- content/en/registry/resource-detector-js-aws.md
- content/en/registry/resource-detector-js-container.md
- content/en/registry/resource-detector-js-gcp.md
- content/en/registry/resource-detector-js-github.md
- content/en/registry/resource-detector-js-instana.md
Add resource detectors for Go & JavaScript to the registry
> [Registry] Add resource detectors for go and js

- content/en/docs/concepts/components.md
Similar to the Instrumenting page the components page required some rework.
> Rework components concept page

- content/en/vendors.md
minor change to clarify that AppD is part of Cisco
> Add "Cisco" to vendor appdynamics

- content/en/docs/instrumentation/cpp/exporters.md
Opentelemetry-cpp: fix the exporters.md documentation.
In C++ exporters doc:
> Opentelemetry-cpp: fixed exporters.md

- content/en/docs/instrumentation/php/_index.md
- content/en/docs/instrumentation/php/automatic.md
- content/en/docs/instrumentation/php/automatic/_index.md
- content/en/docs/instrumentation/php/getting-started.md
- content/en/docs/instrumentation/php/manual.md
- data/instrumentation.yaml
- update PHP stability to beta for trace + metrics
- update existing getting-started documentation
- add manual and auto instrumentation documentation
> Update php documentation for beta release

- content/en/docs/instrumentation/php/examples.md
- content/en/registry/exporter-php-newrelic.md
- content/en/registry/exporter-php-otlp.md
- content/en/registry/exporter-php-zipkin.md
- content/en/registry/instrumentation-php-psr15.md
- content/en/registry/instrumentation-php-psr18.md
- content/en/registry/instrumentation-php-slim.md
- content/en/registry/otel-php-autoinstrumentation.md
* Add an examples links to the PHP sidebar
* Add some registry entries (instrumentation libraries, exporters) for PHP to the registry.
> [PHP] add examples link and registry entries

- content/en/docs/reference/specification/status.md
- Closes #1492
- Preview: https://deploy-preview-2107--opentelemetry.netlify.app/docs/reference/specification/status/#logging
> Spec status: add link to Logging section

- package.json
- Closes #2093
- Results in updates to syntax highlighting for various languages, including Python:
```console
$ npm run check-links
...
Start building sites … 
hugo v0.108.0-a0d64a46e36dd2f503bfd5ba1a5807b900df231d+extended darwin/amd64 BuildDate=2022-12-06T13:37:56Z VendorInfo=gohugoio
...
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0\.") | grep ^diff | grep -Ev '(.xml|_print)'
diff --git a/blog/2022/debug-otel-with-otel/index.html b/blog/2022/debug-otel-with-otel/index.html
diff --git a/blog/2022/exponential-histograms/index.html b/blog/2022/exponential-histograms/index.html
diff --git a/docs/instrumentation/java/manual/index.html b/docs/instrumentation/java/manual/index.html
diff --git a/docs/instrumentation/python/automatic/index.html …
```
> Hugo 0.108.0 upgrade

- content/en/community/end-user/discussion-group.md
This PR reflects changes we have agreed to make to the discussion group sessions:
- New APAC region sessions
- A project maintainer and/or GC member will be in attendance to help provide insight and context to user questions and feedback
- Sessions will now be recorded
Also updates with fresh dates for the next two months.
> Update with some changes coming this year

- content/en/docs/instrumentation/js/exporters.md
Added Typescript code snippet alongside javascript for exporters.
> Update exporters.md for inclusion of Typescript code snippet

- content/en/vendors.md
Added SolarWinds to **vendors.md**, the vendor support list.
> Added SolarWinds to vendor support list

- content/en/docs/concepts/semantic-conventions.md
- content/en/docs/instrumentation/js/serverless.md
- Tweak long lines
- Add a period at end if it is missing
- Add blank line before or after a heading
> Tweak long lines and add some periods

- content/en/docs/instrumentation/php/automatic.md
Installing extension via `pickle` requires updating `php.ini`
> php.ini has to be updated manually

- content/en/docs/instrumentation/php/automatic.md
More info regarding proper development environment requirements (https://github.com/open-telemetry/opentelemetry.io/issues/2184)
> info about development environment dependencies

- content/en/ecosystem/vendors.md
Logscale now has a native OTLP (http) support
> Add LogScale

- package.json
> Update package netlify-cli

- content/en/docs/k8s-operator/automatic.md
- Adds batch processor to pipelines
- Adds Logs pipeline.
> [operator] Update auto-instrumentation collector example

- content/en/docs/instrumentation/python/_index.md
- content/en/docs/instrumentation/python/automatic/_index.md
- Enable url in a line
- Tweak long lines
> Tweak line wrappings in /instrumentation/python/

- content/en/blog/2023/http-conventions-stability/index.md
(for reference, see https://github.com/open-telemetry/opentelemetry-specification/issues/3112)
> Add HTTP semantic convention stability blog post

- CONTRIBUTING.md
Per OTel Comms [meeting discussion on 2023/01/30](https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY/edit#heading=h.exeyjq2diqrm).
**Preview**: https://github.com/open-telemetry/opentelemetry.io/blob/1a84e1718ee23ab0e861fb800ef02c0a6a9b4488/CONTRIBUTING.md
> CONTRIBUTING: clarify issue creation and assignment

- layouts/partials/banner.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/2230
Could be worse?
> Banner updates for jan/feb

- content/en/registry/instrumentation-js-mongoose-instrumentation.md
> Update link for js mongoose instrumentation

- content/en/blog/2023/outreachy-2023-01.md
- content/en/blog/2023/outreachy-may-cohort.md
> Add outreachy 2023-01 cfp blog post

- content/en/blog/2023/otel-in-focus-01.md
Adjust the wrapping position and some indentations in:
```
content/en/blog/2023/otel-in-focus-01.md
```
> Fix indentations in blog: otel-in-focus

- .github/workflows/scripts/check-collector-version.sh
- Closes #2264
- Updates the file containing the `collectorVersion` param to be updated (following #2259)
- Adds support for dry runs via `--dry-run` flag
- Adds support for forcing `latest_version` by setting it in the env. that calls the script (useful for testing)
- Changes done in support of running the script from the command line, in particular under macOS
Test the script by running it locally, and it creates the necessary PR, e.g.:
- #2265
> Update check-collector-version.sh: support --dry-run and more

- content/en/docs/instrumentation/swift/manual.md
This class was removed from opentelemetry-swift
> removed references to OpenTelemetrySdk

- .github/CODEOWNERS
/cc @open-telemetry/demo-approvers
> Update CODEOWNERS: add demo docs, and sort entries

- data/registry/instrumentation-go-honeycomb.yml
- data/registry/instrumentation-js-node-honeycomb.yml
Add Honeycomb.io OpenTelemetry Go and Node.js Distros to Registry
> Add Honeycomb.io Go and Node Distros to Registry

- data/registry/instrumentation-go-kotel-franz-go.yml
Add instrumentation for franz-go to the registry.
> registry: add instrumentation for franz-go

- .prettierignore
- .vscode/cspell.json
- content/en/ecosystem/demo.md
- content/en/ecosystem/integrations.md
- content/en/ecosystem/vendors.md
- Enables format checking over **Ecosystem**
Preview: https://deploy-preview-2311--opentelemetry.netlify.app/ecosystem
> Enable Prettier check over Ecosystem

- .htmltest.yml
- content/en/docs/concepts/instrumenting-library.md
- Closes #1357
- **Preview**: https://deploy-preview-2305--opentelemetry.netlify.app/docs/concepts/instrumenting-library/#opentelemetry-api
> Concepts > Instrumenting libraries: fix link and prose

- .prettierignore
- content/en/docs/collector/_index.md
- content/en/docs/collector/configuration.md
- content/en/docs/collector/custom-auth.md
- content/en/docs/collector/custom-collector.md
- content/en/docs/collector/deployment.md
- content/en/docs/collector/distributions.md
- content/en/docs/collector/getting-started.md
- content/en/docs/collector/trace-receiver.md
- Enables format checking over **Collector**
- I was careful to use inline `prettier-ignore` directives where appropriate. A careful double check of the files and the rendered pages would be appreciated.
- Copyedits
- Adjusted some shell code-blocks
Preview: https://deploy-preview-2315--opentelemetry.netlify.app/docs/collector
> Enable Prettier check over Collector section

- content/en/docs/concepts/observability-primer.md
Duplicate of #2322 
I had to close the above PR to fix EasyCLA signing
> docs: fix grammar in observability primer

- .prettierignore
- content/en/community/_index.md
- content/en/community/end-user/_index.md
- content/en/community/end-user/discussion-group.md
- content/en/community/end-user/otel-in-practice.md
- content/en/community/end-user/slack-channel.md
- content/en/community/marketing-guidelines.md
- content/en/community/mission.md
- Enables format checking over **Community** section
- Minor copyedits
Preview: https://deploy-preview-2316--opentelemetry.netlify.app/community
> Enable Prettier check over Community + minor copyedits

- content/en/docs/instrumentation/python/cookbook.md
- content/en/docs/instrumentation/python/manual.md
> Make prettier in python folder

- content/en/docs/collector/configuration.md
receivers.yaml -> exporters.yaml
> Fix typo in docs/configuration.md

- content/en/community/end-user/interviews-feedback.md
- Runs formatter to fix the production build, which is currently failing
> Format interviews-feedback.md to fix production build

- content/en/blog/2023/submitting-your-first-conference-talk.md
- Removes the callout to the KubeCon Observability Day CFP which is now closed
- Fixes two small spelling/word choice errors
> Update "Submitting your first conference talk" blog post

- content/en/docs/k8s-operator/automatic.md
> Fix build, run formatter

- .htmltest.yml
- content/en/blog/2022/apisix/index.md
- content/en/blog/2022/otel-demo-app-nomad/index.md
- content/en/blog/2022/otel-in-practice.md
- content/en/docs/demo/docker-deployment.md
- package.json
- Contributes to #1052
/cc @reyang
> Fix external links reported by link checker (^a-j)

- .vscode/cspell.json
- scripts/content-modules/adjust-pages.pl
- Brings in https://github.com/open-telemetry/community/pull/1361
- Closes #2303
> Pull in latest roadmap from community repo

- content/en/docs/instrumentation/ruby/automatic.md
- content/en/docs/instrumentation/swift/libraries.md
Modified 2 files:
```
content/en/docs/instrumentation/ruby/automatic.md
content/en/docs/instrumentation/swift/libraries.md
```
> Run prettier and add 2 periods

- .htmltest.yml
- content/en/blog/2022/otel-demo-app-nomad/index.md
- content/en/docs/instrumentation/js/_index.md
- content/en/docs/instrumentation/js/context.md
- package.json
- Contributes to #1052
- External link checking highlighted some broken links.
- @avillela: please review the Nomad blog post updates. (Note: I ran Prettier over the file too.)
- @open-telemetry/javascript-approvers: please review the link updates to the JS pages
Previews:
- https://deploy-preview-2355--opentelemetry.netlify.app/blog/2022/otel-demo-app-nomad/
- https://deploy-preview-2355--opentelemetry.netlify.app/docs/instrumentation/js/
- https://deploy-preview-2355--opentelemetry.netlify.app/docs/instrumentation/js/context/
> Fix broken links in Nomad post and JS pages

- content/en/docs/instrumentation/js/serverless.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/2395
> Fix serverless typo

- content/en/blog/2023/additional-collector-sig.md
- static/refcache.json
- Take two of #2385, which is broken -- see https://github.com/open-telemetry/opentelemetry.io/pull/2385#issuecomment-1446875840.
**Preview**: https://deploy-preview-2410--opentelemetry.netlify.app/blog/2023/additional-collector-sig/
> Adding blog update for newly added collector sigs

- .prettierignore
- content/en/blog/2019/opentelemetry-governance-committee-explained/index.md
- content/en/blog/2021/malabi.md
- content/en/blog/2021/swift.md
- Enables format checking over 2019 and 2021 (all remaining) blog entries
Preview: https://deploy-preview-2412--opentelemetry.netlify.app/blog/page/5/
> Enable Prettier check over remaining blog sections

- content/en/docs/instrumentation/net/exporters.md
Added the two packages AspNetCore and HttpClient for dotnet add package and reduced the options to the new properties.
From what I can see this is how the package is to be used now. Hopefully, this change is useful
> Updated the Prometheus instructions

- content/en/docs/instrumentation/js/getting-started/browser.md
- content/en/docs/instrumentation/js/getting-started/nodejs.md
- content/en/docs/instrumentation/js/instrumentation.md
- content/en/docs/instrumentation/js/resources.md
- Contributes to #2419
- Command-line blocks:
- Fixes block language
- Tweaks commands for readability
**Preview**: https://deploy-preview-2420--opentelemetry.netlify.app
> Upgrade to Docsy v0.5.1

- content/en/docs/instrumentation/java/automatic/annotations.md
The code supports this but I also verified it experimentally.
> Minor clarification around otel.instrumentation.methods.include

- content/en/blog/2023/otel-in-focus-02.md
- static/refcache.json
February community update is ready
> add feb community roundup blog

- scripts/content-modules/adjust-pages.pl
- Fix in support of the Spec 1.19.0 - #2453
/cc @carlosalberto
> Adjust spec pages script: translate absolute URL into spec-section path

- archetypes/blog.md
- assets/scss/_styles_project.scss
- content/en/blog/2023/end-user-discussions-01.md
- content/en/blog/2023/end-user-discussions-02.md
- content/en/blog/2023/end-user-q-and-a-series-otel-and-graphql.md
- content/en/blog/2023/otel-in-focus-01.md
- content/en/blog/2023/otel-in-focus-02.md
- static/refcache.json
- Fixes #2459
- Updates the blog archetype to reflect new conventions
- End-user blog posts:
- Renames some "end-user" blog-post files so that we have consistent naming.
- Ensures that all have the same "with contributions from" first paragraph.
- Copyedits
**Preview**:
- https://deploy-preview-2460--opentelemetry.netlify.app/blog/2023/end-user-discussions-02/
- https://deploy-preview-2460--opentelemetry.netlify.app/blog/2023/end-user-discussions-01/
- https://deploy-preview-2460--opentelemetry.netlify.app/blog/2023/end-user-q-and-a-series-otel-and-graphql/
- https://deploy-preview-2460--opentelemetry.netlify.app/blog/2023/otel-end-user-q-and-a-series-otel-and-graphql/
- https://deploy-preview-2460--opentelemetry.netlify.app/blog/2023/otel-end-user-discussions-january-2023/ …
> Ensure blog posts "with contributions from" secondary authors list are consistently formatted

- content/en/docs/demo/docker-deployment.md
- content/en/docs/demo/kubernetes-deployment.md
- Update Docker memory requirement, add Kubernetes memory requirement
- Define the requirement at the application level, instead of the system level
Related to https://github.com/open-telemetry/opentelemetry-demo/pull/781
@puckpuck WDYT?
> Update memory requirements for the demo app

- content/en/blog/2022/debug-otel-with-otel/index.md
- content/en/blog/2022/instrument-kafka-clients/index.md
- content/en/blog/2023/http-conventions-stability.md
- content/en/docs/collector/transforming-telemetry.md
- content/en/docs/demo/services/frontend.md
- content/en/docs/demo/services/load-generator.md
- content/en/docs/instrumentation/python/automatic/example.md
> Link to local spec pages

- .vscode/cspell.json
- data/registry/collector-receiver-snmp.yml
> Copyedits of collector-receiver-snmp.yml

- .vscode/cspell.json
- content/en/docs/collector/getting-started.md
- Copyedits
- For command-line code blocks without output:
- Switches to lang `sh`
- Droppes `$` prompts
> Collector getting-started copyedits

- content/en/docs/concepts/signals/metrics.md
Resolves https://github.com/open-telemetry/opentelemetry.io/issues/2492
> Update metrics overview page

- package.json
- Closes #2494
- Might contribute to #2215, 🤞 
No changes to the generated site files other than the Hugo version:
```console
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0\.")  
$
```
> Update dev dependencies in package.json

- content/en/blog/2023/end-user-q-and-a-01.md
- content/en/blog/2023/end-user-q-and-a-02.md
- content/en/blog/2023/end-user-q-and-a-series-otel-and-graphql.md
- content/en/blog/2023/otel-in-focus-02.md
- static/refcache.json
OTel Q&A summary blog post for March
---
**Preview**:
- https://deploy-preview-2474--opentelemetry.netlify.app/blog/2023/end-user-q-and-a-02/
- https://deploy-preview-2474--opentelemetry.netlify.app/blog/2023/end-user-q-and-a-01/
- https://deploy-preview-2474--opentelemetry.netlify.app/blog/2023/end-user-q-and-a-series-otel-and-graphql/
- https://deploy-preview-2474--opentelemetry.netlify.app/blog/2023/otel-end-user-q-and-a-series-otel-and-graphql/
> OTel Q&A Summary Blog Post - March 2023

- content/en/blog/2023/end-user-discussions-03.md
- static/refcache.json
This is the summary of the end user discussions across all regions for the month of March. 
---
Preview: https://deploy-preview-2560--opentelemetry.netlify.app/blog/2023/end-user-discussions-03/
> End user discussion summary for March

- content/en/blog/2023/otel-in-focus-03.md
- static/refcache.json
lousy smarch weather.
neither rain nor sleet nor highly communicable infectious respiratory disease will keep me from my appointed rounds of writing the march community update.
---
Preview: https://deploy-preview-2562--opentelemetry.netlify.app/blog/2023/otel-in-focus-03/
> add march otel in focus blog

- content/en/docs/instrumentation/java/automatic/agent-config.md
- static/refcache.json
fixes https://github.com/open-telemetry/opentelemetry.io/issues/2561
> Add node for JDBC bind parameters in Java agent config

- content/en/docs/concepts/signals/baggage.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/2591
@chalin here's the one
> De-confuse baggage

- content/en/docs/instrumentation/java/automatic/agent-config.md
Clarifies that the span suppression does not only concern `CLIENT` spans; it is a generic behavior that applies to all spans produced by the agent.
> Clarify javaagent's span suppression behavior

- content/en/docs/collector/getting-started.md
> [collector] Use HTTPS with TLS v1.2 on curl commands

- content/en/docs/demo/services/frontend.md
- content/en/docs/demo/services/payment.md
Javascript SDKs are getting updated in the demo, which leads to some minor changes in the docs.
This needs to be merged **after** [#853](https://github.com/open-telemetry/opentelemetry-demo/pull/853) is merged from the OpenTelemetry Demo repo.
> [demo] update JS docs

- content/en/blog/2023/otel-in-focus-04.md
- static/refcache.json
I mean, the first day of the next month is pretty much like the last day of the prior month, right?
> Add OpenTelemetry in Focus post for April

- content/en/docs/instrumentation/python/getting-started.md
- static/refcache.json
This PR, #2651 and #2652 create some consistency across python, java & Node.JS documentation.
Preview:
https://deploy-preview-2653--opentelemetry.netlify.app/docs/instrumentation/python/getting-started/
> Python getting started more updates

- content/en/docs/instrumentation/php/automatic.md
- Followup to #2654
- **Preview**: https://deploy-preview-2656--opentelemetry.netlify.app/docs/instrumentation/php/automatic/#installation
Before:
> <img width="579" alt="image" src="https://user-images.githubusercontent.com/4140793/236354492-e97e6361-720f-4f3d-a569-c35b9eefa8d7.png">
After:
> <img width="569" alt="image" src="https://user-images.githubusercontent.com/4140793/236357055-8e83dadc-a696-4311-bc24-9f703fa12088.png">
> Fix tabbed code in PHP page

- .github/workflows/auto-update-versions.yml
- Follow up to #2568
- Context: https://github.com/open-telemetry/opentelemetry.io/pull/2568/files#r1186894997
> Auto-update versions: ensure PRs contain only one update

- .htmltest.yml
Buying myself some more time, since I won't be able to work on the refcache refresh script(s) for a little while longer.
> htmltest: bump up the cache expiry delay

- scripts/content-modules/adjust-pages.pl
- Prep for #2642
- No change to generated site files
> Script adjust-pages.pl cleanup

- content/en/docs/demo/feature-flags.md
Docs for feature flag added in https://github.com/open-telemetry/opentelemetry-demo/pull/824.
> Add cartServiceFailure to list of feature flags

- scripts/content-modules/adjust-pages.pl
- scripts/content-modules/cp-pages.sh
- Contributes to #2704
**Preview**:
- Visit https://deploy-preview-2705--opentelemetry.netlify.app/docs/specs/otel/overview/
- Click on "View page source", the result should not be a GH 404
> Fix GH link paths

- content/en/docs/instrumentation/php/exporters.md
- content/en/docs/instrumentation/php/manual.md
- content/en/docs/instrumentation/php/resources.md
- fixing some broken links
- note exporter delays and how to reduce them
- add custom resource detectors section
> updating php docs

- content/en/docs/instrumentation/php/automatic.md
- content/en/docs/instrumentation/php/exporters.md
- content/en/docs/instrumentation/php/getting-started.md
- content/en/docs/instrumentation/php/manual.md
> PHP spelling fixes

- content/en/docs/instrumentation/rust/_index.md
This removes some linter warnings
> Linter cleanups for rust docs

- content/en/blog/2023/exponential-histograms.md
- Followup to #2661
- Normalizes link to spec page
/cc @dyladan @cartermp
> Normalize link in exponential-histograms blog

- .github/workflows/scripts/auto-update-version.sh
> Auto-update spec: ensure that submodule is available

- .github/workflows/scripts/auto-update-version.sh
> Auto-update spec: fetch tags

- content/en/docs/collector/configuration.md
See https://github.com/open-telemetry/opentelemetry.io/issues/2725#issuecomment-1558694501
> Clarify connectors description

- content/en/docs/instrumentation/js/instrumentation.md
Same as #2755. I think the javascript one also needs to be fixed, but I am not sure if Javascript supports the same way of importing like typescript does
> Fix import

- .github/workflows/scripts/auto-update-version.sh
> auto-update-version.sh fix: don't try to attach a label

- content/en/blog/2023/lambda-release.md
- static/refcache.json
Adding a blog post from the FAAS sig
> add blog for lambda releases

- .github/CODEOWNERS
> CODEOWNERS: add specs-approvers to /docs/specs

- content/en/blog/2022/exponential-histograms/index.md
- content/en/docs/collector/deployment/agent.md
- content/en/docs/collector/deployment/gateway.md
- content/en/docs/concepts/glossary.md
- content/en/docs/concepts/sdk-configuration/general-sdk-configuration.md
- content/en/docs/instrumentation/python/exporters.md
- hugo.yaml
- #2642
- #2793
---
```console
$ npm run build
$ cd public
$ g diff -I 'docsspecsotlp-check' | grep ^diff | grep -v \.xml
diff --git a/blog/2022/exponential-histograms/index.html b/blog/2022/exponential-histograms/index.html
diff --git a/docs/concepts/glossary/index.html b/docs/concepts/glossary/index.html
diff --git a/docs/concepts/sdk-configuration/general-sdk-configuration/index.html b/docs/concepts/sdk-configuration/general-sdk-configuration/index.html
diff --git a/docs/instrumentation/python/exporters/index.html b/docs/instrumentation/python/exporters/index.html
```
> Link to OTLP spec

- package.json
> Add cspell to devDeps

- content/en/blog/2023/otel-in-focus-05.md
Great feature that shouldn't be missed :-)
> OTel in Focus 05/23: Also mention Apache Auto Instrumentation for the operator

- package.json
> Add  to textlint pkg to dev dependencies

- content/en/docs/instrumentation/swift/libraries.md
- content/en/docs/instrumentation/swift/manual.md
> Common weights for swift pages

- content/en/docs/instrumentation/python/api.md
- content/en/docs/instrumentation/python/automatic/_index.md
- content/en/docs/instrumentation/python/automatic/agent-config.md
- content/en/docs/instrumentation/python/automatic/example.md
- content/en/docs/instrumentation/python/automatic/operator.md
- content/en/docs/instrumentation/python/cookbook.md
- content/en/docs/instrumentation/python/distro.md
- content/en/docs/instrumentation/python/examples.md
- content/en/docs/instrumentation/python/exporters.md
- content/en/docs/instrumentation/python/getting-started.md
- content/en/docs/instrumentation/python/manual.md
- content/en/docs/instrumentation/python/mypy.md
> Common weights for python pages

- content/en/docs/instrumentation/cpp/api.md
- content/en/docs/instrumentation/cpp/examples.md
- content/en/docs/instrumentation/cpp/exporters.md
- content/en/docs/instrumentation/cpp/getting-started.md
- content/en/docs/instrumentation/cpp/manual.md
> Common weights for C++ pages

- assets/scss/_styles_project.scss
- content/en/docs/demo/architecture.md
- layouts/_default/_markup/render-codeblock-mermaid.html
> Upgrade Docsy to 0.7.0 pre-release

- scripts/content-modules/adjust-pages.pl
- Closes #2839
- Contributes to #2642
- Adds the OTLP version to the title and linkTitle
- **Preview**: https://deploy-preview-2845--opentelemetry.netlify.app/docs/specs
/cc @tigrannajaryan 
---
> <img width="1067" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/766f12bd-ed92-4126-9232-8a34baee5895">
> Update OTLP to 0.20.0

- .github/workflows/auto-update-versions.yml
- .github/workflows/scripts/auto-update-version.sh
- package.json
- Contributes to #2642
/cc @trask @tigrannajaryan
> Auto check and update OTLP spec and its version
