.prettierignore, layouts/shortcodes/docs/instrumentation/index-intro.md
- Followup to #2854
- Prep for #2852
=> Run prettier over docs shortcodes

content/en/docs/collector/deployment/gateway.md
Since I was building a tutorial where I wanted to point towards the load balancing capabilities, I thought I add my nginx config here as an example
+ some minor fixes & improvements.
cc @mhausenblas
=> add nginx config to gateway deployment pattern

content/en/docs/demo/services/cart.md
after upgrade to .NET OTel 1.5.0
=> [demo/cart] simplify resource configuration

content/en/docs/collector/_index.md, content/en/docs/collector/configuration.md, content/en/docs/collector/getting-started.md, content/en/docs/concepts/components.md, content/en/docs/concepts/distributions.md
- Followup to #2761 
- Closes #2848
---
**Preview**: https://deploy-preview-2870--opentelemetry.netlify.app/docs/
**Redirect test**:
- https://deploy-preview-2870--opentelemetry.netlify.app/docs/concepts/data-collection/
=> Fix data-collection page redirect

content/en/docs/what-is-opentelemetry.md
fixes https://github.com/open-telemetry/opentelemetry.io/pull/2878/files#r1232537425
=> fix link on what is opentelemetry page

content/en/docs/instrumentation/php/getting-started.md
fixing some incorrect instructions
call out the importance of setting minimum-stability while we are in beta
=> updating php getting-started

content/en/docs/instrumentation/php/automatic.md, content/en/docs/instrumentation/php/manual.md, content/en/docs/instrumentation/php/sdk.md
minor corrections and improvements to the php instrumentation docs
=> php docs tidy

content/en/_index.md
As per @yurishkuro [comment](https://github.com/open-telemetry/.github/pull/5#discussion_r1242139904), there is an order of importance in that tag line
=> Change order in tag line

content/en/docs/instrumentation/python/manual.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/2903
=> Causally, not casually

content/en/docs/collector/configuration.md, content/en/docs/instrumentation/cpp/_index.md, content/en/docs/instrumentation/erlang/_index.md, content/en/docs/instrumentation/go/_index.md, content/en/docs/instrumentation/java/_index.md, content/en/docs/instrumentation/js/_index.md, content/en/docs/instrumentation/net/_index.md, content/en/docs/instrumentation/php/_index.md, content/en/docs/instrumentation/python/_index.md, content/en/docs/instrumentation/ruby/_index.md, content/en/docs/instrumentation/rust/_index.md, content/en/docs/instrumentation/swift/_index.md, layouts/shortcodes/registry-search-form.html
=> Fix invalid HTML and warnings reported by Prettier

CONTRIBUTING.md
Preview: https://github.com/open-telemetry/opentelemetry.io/blob/883a15193f90a99f93397d5ae464e249907a2fdc/CONTRIBUTING.md
=> CONTRIBUTING page tweaks, mainly code-block lang

.gitmodules, .htmltest.yml, hugo.yaml, scripts/content-modules/adjust-pages.pl, scripts/content-modules/cp-pages.sh, static/refcache.json
- Contributes to #2795
- **Preview**: https://deploy-preview-2926--opentelemetry.netlify.app/docs/specs/opamp/
/cc @tigrannajaryan
=> Add OpAMP spec

content/en/docs/specs/status.md, scripts/content-modules/adjust-pages.pl
- Closes #2928
- **Preview**: https://deploy-preview-2929--opentelemetry.netlify.app/docs/specs
This is the new order:
> <img width="216" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/afba0808-86ba-42df-b73c-a339670c88b8">
=> Reorder specs

.htmltest.yml, static/refcache.json
- Followup to #2954
- #2429
- #2554
- Fixes 4xx links
- (Almost done updating the references: only about 180 left.)
=> Refcache refresh and 404 link fixes

content/en/blog/2023/otel-in-focus-06.md, layouts/partials/banner.md, static/refcache.json
**Preview**: https://deploy-preview-2963--opentelemetry.netlify.app/blog/2023/otel-in-focus-06/
=> add otel in focus for june

content/en/_index.md, content/en/blog/2023/otel-in-focus-06.md, content/en/community/end-user/interviews-feedback.md, content/en/community/marketing-guidelines.md, content/en/docs/collector/deployment/_index.md, content/en/docs/demo/services/recommendation.md, content/en/docs/instrumentation/js/exporters.md, content/en/docs/instrumentation/python/distro.md, content/en/ecosystem/vendors.md
Besides the ones in #2943 these are the last files which are having cspell or textlint issues.
=> cspell & textlint missing fixes

assets/js/registrySearch.js, content/en/blog/2022/instrument-apache-httpd-server/index.md, content/en/docs/instrumentation/js/getting-started/browser.md, content/en/docs/instrumentation/js/manual.md, content/en/docs/instrumentation/js/propagation.md, content/en/docs/instrumentation/js/serverless.md, gulp-src/prune.js, package.json, scripts/registry-scanner/index.mjs
=> Update Prettier to v3 and reformat pages

.warnings-skip-list.txt, scripts/content-modules/adjust-pages.pl
=> Make spec links to semconv local

gulp-src/lint-md.js
=> CI: lint-md task tweaks

static/refcache.json
in lieu of a cron job 🙂 https://github.com/open-telemetry/opentelemetry.io/issues/2554
=> refcache update

hugo.yaml
=> Fix meeting record icon

gulp-src/lint-md.js
- Followup to:
- #3032
- #3036
- Ensures that all files are checked by markdownlint, and that if issues are detected, then the overall task fails
- **Note**: this PR should have an action failure for the markdown lint checking. I'll submit the necessary .md fixes once I've confirmed that the action is failing on linting errors
=> [CI] Ensure that lint-md has right exit code

content/en/docs/kubernetes/helm/demo.md
- Followup to #3069
- Fixes issues reported by lint-md
- Applies a few minor copyedits
- **Preview**: https://deploy-preview-3071--opentelemetry.netlify.app/docs/kubernetes/helm/demo/
=> K8s Helm Demo page copyedits + build fix

.github/workflows/pr-actions.yml
This is a quick fix; we can optimize later by using "reduced-dependencies package.json" like in check-links.yml.
=> [CI] fix:refcache - ensure all packages are installed

content/en/docs/kubernetes/collector/components.md
Minor change, but a big impact
=> Change word "our" to "your"

content/en/docs/kubernetes/collector/components.md
Adds documentation for the kubeletstats receiver
=> [Kubernetes] Add kubeletstatsreceiver documentation

content/en/docs/kubernetes/operator/automatic.md, static/refcache.json
I've added some troubleshooting guidance for the OTel Operator's auto-instrumentation capability, based on my recent experiences with it.
=> Add troubleshooting guidance to OTel Operator auto-instruentation docs

data/ecosystem/adopters.yaml
@vjsamuel, is it ok to put you here as a contact? We try to have someone to reach out to in cases where we change this list or need additional infos.
Also feel free to add to the list of components (e.g. language SDKs) that eBay is using.
TY!
=> Add eBay to adopters.yaml

.github/workflows/pr-actions.yml
- Followup to #3103; I forgot that the env var required the flag name too
=> [CI] Clone submodules more deeply for `/fix:refache` -- take 2

data/ecosystem/adopters.yaml
* Replace `Node.JS` and `Javascript` with `JavaScript` consistently
* Add the missing referenceTitle to make the link to the ebay blog appear
=> Fix some issues in adopters list

content/en/blog/2023/otel-in-focus-07.md, static/refcache.json
n/t
---
**Preview**: https://deploy-preview-3129--opentelemetry.netlify.app/blog/2023/otel-in-focus-07/
=> add otel in focus july

content/en/docs/demo/features.md
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18201 has been closed.
@open-telemetry/demo-approvers please take a look if this note can be removed safely or needs to be changed.
=> Remove issue 18201 note from demo docs

content/en/docs/instrumentation/erlang/manual.md
I noticed that the Elixir example does not work while going through the guide. 
I am not sure if the changes for the Erlang example are 100% correct as I am not that experienced with plain Erlang.
=> Fix Erlang/Elixir example for linking spans

.github/workflows/pr-actions.yml
- Followup to #3158 - I should have fixed both commands at once 🤷🏼‍♂️ 
=> [CI] Set user info before calling git cmd in fix:* actions

.github/workflows/pr-actions.yml
- Stepping closer to making these work
=> [CI] GH actions: given env var proper scope

content/en/docs/demo/tests.md, static/refcache.json
Hi folks!
On this PR, I'm updating the OTel Demo testing docs to show the recent changes that we did there.
---
**Preview**: https://deploy-preview-3173--opentelemetry.netlify.app/docs/demo/tests/
=> Update test docs for OTel Demo

content/en/docs/kubernetes/helm/collector.md
Cleans up the presets section now that we have the components section to link to
=> [kubernetes] touchup presets doc

content/en/docs/concepts/signals/traces.md
Moved the hello span to the top (since it is the root span) and explicitly explained (briefly) the correlation between spans. #3105
=> Traces clarification fix 

content/en/docs/concepts/signals/traces.md
Fixes an issue that came in, this is affecting other PRs
=> fix formatting

content/en/docs/demo/services/cart.md
Needed for https://github.com/open-telemetry/opentelemetry-demo/pull/1086
=> [demo/cartservice] Add support for logs

data/ecosystem/vendors.yaml
=> chore: add contact email of greptime vendor

content/en/blog/2022/k8s-metadata/index.md
We got docs now
fixes https://github.com/open-telemetry/opentelemetry.io/issues/3169
=> Add notice in k8s metadata blog

content/en/docs/collector/configuration.md
-  We have improved the accessibility of our documentation by adding descriptive 'alt' attributes to image tags.
By providing meaningful 'alt' attributes for these images, we enhance the usability of our documentation for individuals who rely on screen readers or have other accessibility needs.
=> Enhanced Accessibility with Alt Attributes

content/en/blog/2023/otel-in-focus-08.md, static/refcache.json
OpenTelemetry in Focus blog for August. Better late than never!
=> Add OTel in Focus for August

content/en/docs/instrumentation/net/manual.md
Use `MyActivitySource` instead of `source`, the latter of which was missed as the wrong thing at some point
fixes https://github.com/open-telemetry/opentelemetry.io/issues/3247
=> Update .NET manual instrumentation root activity creation

data/registry/instrumentation-js-cerbos.yml, data/registry/instrumentation-python-cassandra.yml, static/refcache.json
Two additions to the registry.
For cerbos, see #3182 as well
=> Registry Updates September 2023

content/en/blog/2023/otel-dotnet-auto-instrumentation.md, static/refcache.json
Solves https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2945
=> Add blog post for .NET automatic instrumentation stable release

content/en/docs/instrumentation/go/manual.md
Per https://github.com/open-telemetry/opentelemetry.io/pull/3275#discussion_r1327263845
Fixes https://github.com/open-telemetry/opentelemetry-go/issues/3186
**Please double-check if there is anything missing in the Go metrics docs.
See: https://deploy-preview-3285--opentelemetry.netlify.app/docs/instrumentation/go/manual/#metrics**
=> Go: More Views examples

static/refcache.json
Because https://github.com/open-telemetry/community/pull/1655 got merged, the community submodule needs to be updated. cc @jpkrohling
=> Update community submodule to 61ab6aa

content/en/docs/instrumentation/go/manual.md
Changes based on https://github.com/open-telemetry/opentelemetry-go/pull/4504 and https://github.com/open-telemetry/opentelemetry-go/pull/4540
=> Go: Refine Initialize Metrics

content/en/_index.md
I wanted to put our integrations front and center for new users. Hopefully this will drive more users to our integrations and encourage more vendors to produce OTel integrations or add existing integrations to our website.
=> Spotlight project integrations

content/en/docs/instrumentation/go/exporters.md, static/refcache.json
1. Add a notice that Prometheus is experimental
2. List and add basic examples for the most popular exporters
3. Add a reference to the OTel Registry
4. Other minor refinements
=> Rewrite Go: Exporters

content/en/docs/instrumentation/go/manual.md
=> Editorial cleanup in Go: Manual Metrics

content/en/docs/instrumentation/go/getting-started.md
Very minor updates. Added an oxford comma that was missing and updated a sentence.
=> Minor updated to the getting-started.md

content/en/blog/2023/gc-elections.md, static/refcache.json
/cc election committee @mtwo @trask 
/cc @austinlparker please promote when this is published
=> Add 2023 election blog post

content/en/blog/2023/kubecon-na.md, static/refcache.json
Talk will cover how to deploy the OTel Collector via self-service tooling such as Kratix
=> Updates KubeCon blog post to adds Adriana's and Ana's platform engineering talk to schedule

data/ecosystem/integrations.yaml, static/refcache.json
Add Jenkins, OpenFeature flagd and flipt to the list of integrations 
cc @cartersocha
=> Add more integrations

data/registry/collector-extension-encoding.yml, data/registry/instrumentation-dotnet-aws.yml, data/registry/instrumentation-java-pekkoactor.yml, data/registry/instrumentation-java-pekkohttp.yml
Add Apache Pekko for Java, fix links in collector and dotnet
=> Registy Updates October 2023

content/en/blog/2022/apisix/index.md, content/en/blog/2022/debug-otel-with-otel/index.md, content/en/blog/2022/instrument-nginx/index.md, content/en/blog/2022/k8s-metadata/index.md, content/en/blog/2023/testing-otel-demo/index.md, content/en/docs/collector/scaling.md, content/en/docs/instrumentation/java/manual.md, content/en/docs/instrumentation/js/manual.md
Some minor fixes for some code fences
=> Some code fence fixes

content/en/docs/instrumentation/python/getting-started.md
https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1975
=> Fix flask v2 for python getting started

.prettierignore
Revert once the following is merged and integrated into this repo:
- https://github.com/open-telemetry/community/pull/1742
=> [CI] Ignore mission-vision-values.md until it is fixed

scripts/content-modules/adjust-pages.pl
- Prep for #3388
- Contributes to #2927
=> Update OpAMP to latest and stop using relref for it

.htmltest.yml, .warnings-skip-list.txt, scripts/content-modules/adjust-pages.pl, static/refcache.json
- Closes #3387 by superseding it
- Closes #3386 by superseding it
- Updates both submodules at the same time since they are mutually dependent on each other. I suspect that this will probably always be the case but we should confirm with the spec and semconv folks.
**Preview**:
- https://deploy-preview-3388--opentelemetry.netlify.app/docs/specs/
- https://deploy-preview-3388--opentelemetry.netlify.app/schemas/1.22.0/
/cc @svrnm
=> Update to spec 1.26.0 and semconv 1.22.0 at the SAME time

data/registry/collector-exporter-honeycombmarker.yml, data/registry/collector-receiver-git-trace2.yml, static/refcache.json
cc @jeffhostetler @arielvalentin adding the trace2receiver to the registry already. Very excited about this :-)
=> Registry Updates Oct 23 No. 2

content/en/docs/concepts/glossary.md
=> Drop Additional Terminology section from glossary

.prettierignore
- Reverts #3390
- Updates the community submodule
=> Update community repo and drop CI workaround

data/instrumentation.yaml
The core components of the PHP implementation have gone GA/stable.
=> update php to stable

content/en/ecosystem/vendors.md
This PR will fix the broken link raised in https://github.com/open-telemetry/opentelemetry.io/issues/3438
=> Broken link fix on ecosystem vendors page

.textlintrc.json
- Followup to https://github.com/open-telemetry/opentelemetry.io/pull/3429#discussion_r1377540914
- Drops NOOP config entry
/cc @theletterf
=> [CI] textlint config cleanup

package.json
=> [CI] Upgrade textlint-rule-terminology to bring in patch

content/en/blog/2023/integrations.md
=> Update publication date for integrations welcome blog

content/en/blog/2023/cloud-foundry.md, static/refcache.json
This is our first time contributing to the OTel blog. Excited to hear your feedback!
---
**Preview**: https://deploy-preview-3466--opentelemetry.netlify.app/blog/2023/cloud-foundry/
=> Add blog post about adopting OTel metrics in Cloud Foundry

content/en/docs/concepts/signals/traces.md
I'm very new to this whole topic and just started reading the docs, but I found an inconsistency in the JSON examples.
I am not quite sure if this is the correct structure, but this is how it is done above in the examples, and the text also reads as if the fields `trace_id` and `span_id` should be nested in `context`.
=> Fix example JSON in the docs

layouts/partials/banner.md
**Preview**: https://deploy-preview-3535--opentelemetry.netlify.app/
> <img width="391" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/76aa7795-9b18-469a-9687-88cab1afa934">
=> Update banner: drop old, highlight Contribfest

content/en/docs/instrumentation/php/manual.md
=> Add missing variable in code example

content/en/docs/kubernetes/operator/automatic.md
Depends on https://github.com/open-telemetry/opentelemetry-operator/pull/2358
=> [operator] Update go operator docs

.htmltest.yml
(I just won't have time to refresh the cache this quarter, so buying myself a bit of time until 24Q1 :)
=> [CI] Bump up the refcache expiry limit

content/en/docs/instrumentation/net/automatic/getting-started.md, content/en/docs/instrumentation/net/getting-started.md
=> (Re)add automatic getting started for .NET

data/ecosystem/integrations.yaml, static/refcache.json
Based on the fact that we had blog posts about those 2 let's also list them in the integrations (we can link with the blog posts later)
=> Add Cloud Foundary and Otterize Network Mapper to Integrations

content/en/docs/instrumentation/python/getting-started.md
Fixes https://github.com/open-telemetry/opentelemetry-python/issues/3544
=> Update getting-started.md fix trace example

hugo.yaml
- Followup to #3616
- Prep for #3615
=> Drop RSS for real

.github/workflows/pr-actions.yml
Fixes the fix:refcache action from failing.
=> fix permission issue with fix:refcache PR action

content/en/docs/concepts/semantic-conventions.md
Added link to semantic conventions for logs.
=> Update semantic-conventions.md adding link to logs

content/en/docs/concepts/glossary.md
Distribution is a concept in OTel and should be listed in the glossary.
=> Add distribution to glossary.md

content/en/docs/instrumentation/java/automatic/agent-config.md
=> Update 'runtime-metrics' to 'runtime-telemetry'

content/en/docs/instrumentation/js/exporters.md
=> Update exporters.md: fixed OTLP ports in description

data/registry/collector-exporter-alertmanager.yml, layouts/ecosystem/registry.json.json
=> Ensure that fuse.js-generated registry entries also render markdown, fixes #2491

data/ecosystem/integrations.yaml, static/refcache.json
As suggested by @svrnm in a previous PR, this one includes KafkaFlow in the integrations list.
https://github.com/open-telemetry/opentelemetry.io/pull/3625#pullrequestreview-1770020390
=> Add KafkaFlow in ecosystem/integrations

content/en/blog/2023/humans-of-otel.md, static/refcache.json
New blog post summarizing the Humans of OTel video.
=> Add new blog post for Humans of OTel recap

data/ecosystem/vendors.yaml, static/refcache.json
=> add openobserve

.github/dependabot.yml
Via https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> Add dependabot config for GitHub actions

content/en/docs/instrumentation/php/automatic.md
**Preview**: https://deploy-preview-3712--opentelemetry.netlify.app/docs/instrumentation/php/automatic/#next-steps
=> PHP: add more-examples link

content/en/docs/collector/installation.md
=> Make k8s URL in collector installer version-dependent, fixes #3749

content/en/docs/contributing/acknowledgements.md
- Contributes to #3767, sorry, I missed this during yesterday's review 
**Preview and redirect tests**:
- https://deploy-preview-3768--opentelemetry.netlify.app/docs/contributing/acknowledgements/
- https://deploy-preview-3768--opentelemetry.netlify.app/docs/acknowledgements/
- https://deploy-preview-3768--opentelemetry.netlify.app/acknowledgements/
=> Add missing alias to acknowledgements.md

package.json
This change only affects local builds.
=> [CI] Fix baseURL for development builds

content/en/blog/2019/_index.md, content/en/blog/2021/_index.md, content/en/blog/2022/_index.md, content/en/blog/2023/_index.md, content/en/blog/_index.md, hugo.yaml
- Fixes #3740
- **Preview**: 
- https://deploy-preview-3780--opentelemetry.netlify.app/blog/
- https://deploy-preview-3780--opentelemetry.netlify.app/blog/index.xml
- https://deploy-preview-3780--opentelemetry.netlify.app/blog/page/4/
=> Docsy update + Reenable RSS for blog index and navigation pages

.cspell.yml, content/en/blog/2023/logs-collection/index.md, content/en/docs/demo/feature-flags.md, content/en/docs/demo/telemetry-features/_index.md, content/en/docs/demo/telemetry-features/logging-features.md, content/en/docs/demo/telemetry-features/manual-span-attributes.md, content/en/docs/demo/telemetry-features/metric-features.md, content/en/docs/demo/telemetry-features/trace-features.md
- Fixes #3801
---
**Preview**: https://deploy-preview-3802--opentelemetry.netlify.app/docs/demo/telemetry-features
**Redirect tests** (selected):
- https://deploy-preview-3802--opentelemetry.netlify.app/docs/demo/features
- https://deploy-preview-3802--opentelemetry.netlify.app/docs/demo/demo_features
- https://deploy-preview-3802--opentelemetry.netlify.app/docs/demo/logging-features
- https://deploy-preview-3802--opentelemetry.netlify.app/docs/demo/manual-span-attributes
- https://deploy-preview-3802--opentelemetry.netlify.app/docs/demo/metric-features
- https://deploy-preview-3802--opentelemetry.netlify.app/docs/demo/trace-features
=> [Demo] Fix aliases and dictionary/word tweaks

data/ecosystem/vendors.yaml, static/refcache.json
Closes https://github.com/open-telemetry/opentelemetry.io/issues/3819
=> Remove Teletrace from vendor list

README.md
=> Fix community meeting time

content/en/docs/languages/php/sdk.md
related to https://github.com/open-telemetry/opentelemetry-php/pull/1220
=> [PHP] Documenting the option to disable all auto-instrumentations

.github/workflows/scripts/update-registry-versions.sh
Small bug breaking the second PR created by this script 🤦
=> Fix bug in registry update script

.textlintrc.yml, content/en/blog/2023/otel-in-focus-06.md
- Fixes #3131
- (This will have to be rebased after #3883 is merged)
=> [CI/textlint] Enforce "bug fix" as two words

.textlintrc.yml, content/en/blog/2022/apisix/index.md, content/en/blog/2022/frontend-overhaul/index.md, content/en/blog/2023/end-user-discussions-01.md, content/en/blog/2023/end-user-q-and-a-01.md, content/en/blog/2023/end-user-q-and-a-03.md, content/en/blog/2023/humans-of-otel.md, content/en/blog/2023/testing-otel-demo/index.md, content/en/docs/collector/_index.md, content/en/docs/concepts/distributions.md, content/en/docs/concepts/observability-primer.md, content/en/docs/concepts/signals/baggage.md, content/en/docs/what-is-opentelemetry.md, data/registry/collector-exporter-alertmanager.yml
- Followup to #3883
/cc @theletterf
=> [CI/textlint] Enforce "backend" rather than "back-end"

.htmltest.yml, content/en/blog/2023/end-user-discussions-03.md, static/refcache.json
=> [CI] Refcache refresh for entries before 2023-08-01

.cspell.yml, .textlintrc.yml, content/en/blog/2022/instrument-kafka-clients/index.md, content/en/docs/languages/java/automatic/agent-config.md, content/en/docs/languages/java/automatic/spring-boot.md, content/en/docs/languages/java/exporters.md, content/en/docs/languages/java/instrumentation.md, content/en/docs/languages/java/resources.md
=> [CI/textlint] Enforce "autoconfig*" as one word

content/en/docs/languages/java/instrumentation.md
=> Fix indent

.github/workflows/pr-actions.yml
fixes #3950 and also refactors that workflow file to make it easier to add additional commands. It also introduces an "all" command that does format, refcache and sync in one shot.
Demo PR: https://github.com/svrnm/opentelemetry.io/pull/74
=> [CI] Refactor PR actions workflow

data/instrumentation.yaml
Per https://github.com/open-telemetry/opentelemetry-go/pull/4897
@open-telemetry/go-maintainers PTAL
=> Mark Go Logs status as in development

data/ecosystem/integrations.yaml
Hello,
I made this pull request to update the `Kong API Gateway Integration` document.
As per the docs https://docs.konghq.com/hub/kong-inc/opentelemetry/. This Integration is `OSS` and using `Lua` programming script.
=> Updated the Kong API Gateway integration

.gitmodules
=> [CI] Add a reminder to .gitmodules about pushing docsy tags

.github/workflows/check-links.yml
- Supersedes and closes #3744
- Supersedes and closes #3746
- The problem is that both updates needed to occur at the same time
=> [CI] Update `actions/{up,down}load-artifact` to v4

content/en/docs/languages/_index.md
Following up on Slack Chat:
https://cloud-native.slack.com/archives/C041APFBYQP/p1707760677044609
---
**Preview**: https://deploy-preview-3995--opentelemetry.netlify.app/docs/languages/
=> Add Caution Note re Experimental SemConvs

data/registry/instrumentation-go-thegeekyasian-go-chi-otel.yml, static/refcache.json
Adding an adaption of OTEL for gochi/chi to the registry.
https://github.com/thegeekyasian/go-chi-otel
=> Add github.com/thegeekyasian/go-chi-otel to registry

content/en/docs/languages/java/automatic/spring-boot.md
I think this caused a build problem that somehow wasn't caught in PR?
=> Update spring-boot semconv link

content/en/docs/demo/telemetry-features/metric-coverage.md
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/4054
I understand that there are broader discussions on the topic, but this is just making metrics consistent with tracing.
=> AutoInstrumentation -> Instrumentation Libraries

.github/workflows/pr-actions.yml
Adds the remaining fix commands to the PR action (dict, filenames, markdown)
=> Add support for remaining fix commands to pr action

content/en/blog/2024/kubecon-eu.md
**Preview**: https://deploy-preview-4103--opentelemetry.netlify.app/blog/2024/kubecon-eu/#opentelemetry-observatory
=> [blog] KubeCon EU 2024 copyedits

hugo.yaml, static/refcache.json
- Contributes to #4017
- **Preview**: https://deploy-preview-4102--opentelemetry.netlify.app/community/
> ![image](https://github.com/open-telemetry/opentelemetry.io/assets/4140793/1c2b3ed4-f1fb-4336-82a7-d58d80b4d41c)
> <img width="619" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/628a8057-c5bc-4356-8978-76d9d555115d">
=> Add Public Analytics Dashboard to footer & Community pg

content/en/blog/2023/any-metric-receiver.md
Minor change to an old blog post, but otherwise this script does not work as expected.
=> Fix minor issue in any-metric-receiver.md

content/en/docs/demo/feature-flags.md
- Fixes #4144
/cc @austinlparker 
**Preview** and redirect links:
- https://deploy-preview-4146--opentelemetry.netlify.app/docs/demo/feature-flags
- https://deploy-preview-4146--opentelemetry.netlify.app/docs/demo/services/feature-flag
- https://deploy-preview-4146--opentelemetry.netlify.app/docs/demo/services/featureflagservice
=> [demo] Reintroduce services/featureflagservice alias

content/en/docs/demo/feature-flags.md
Add docs for https://github.com/open-telemetry/opentelemetry-demo/pull/1449
=> Add paymentServiceFailure & paymentServiceUnreachable featureflags to demo docs

content/en/docs/collector/troubleshooting.md
Fix for issue - https://github.com/open-telemetry/opentelemetry.io/issues/2072
=> Troubleshooting added to check available components in the collector

content/en/docs/languages/java/automatic/spring-boot.md
=> spring boot build info resource detector

data/ecosystem/vendors.yaml, static/refcache.json
Adds Chronosphere to the list of vendors who natively support OpenTelemetry.
=> Adds Chronosphere to vendors list

content/en/blog/2024/opentelemetry-announced-support-for-profiling.md
=> fix link in blog

content/en/docs/demo/kubernetes-deployment.md
Fixes Demo repo [issue 1467](https://github.com/open-telemetry/opentelemetry-demo/issues/1467)
=> [demo] - fix browser telemetry example

layouts/partials/banner.md, static/refcache.json
kubecon's over, on to the next
(okay there's one more day left)
=> Update banner for otel community day

data/ecosystem/integrations.yaml, static/refcache.json
Add ClickHouse to the OpenTelemetry integration list.
=> Add ClickHouse to the list of OTel Integrations

.cspell.yml, content/en/blog/2023/kubecon-na.md
Add 'Chronosphere' in order to solved the above error:
=> [feature][4208]: Add 'Chronosphere' word

content/en/docs/languages/java/automatic/spring-boot.md
=> remove unnecessary space

.github/workflows/check-text.yml
=> [CI] Ensure check-text GHA jobs use proper node version

content/en/docs/demo/scenarios/recommendation-cache/index.md
=> Replace recommendationCache for recommendationServiceCacheFailure

content/en/docs/demo/feature-flags.md
Adding documentation https://github.com/open-telemetry/opentelemetry-demo/pull/1486
=> Added loadgeneratorFloodHomepage flag description to docs

content/en/docs/demo/feature-flags.md
=> Make feature-flags.md more obvious

content/en/docs/languages/net/exporters.md
=> Dotnet exporters update 3

.github/component-label-map.yml, .github/workflows/label-prs.yml
Copied from https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/label-prs.yml (cc @pichlermarc) to enable auto-labeling of PRs additionally.
=> Add pr labeler workflow

data/ecosystem/distributions.yaml, static/refcache.json
Language Distros for .NET, Java, Node.js, and Python
=> Add Azure Monitor Distributions

static/refcache.json
needed to unblock all the prs broken by the refcache
=> remove bad refcache entry

data/registry/collector-extension-http-forwarder.yml
=> [CI] Spelling check test

data/ecosystem/integrations.yaml, static/refcache.json
added azure and masstransit to integrations this also includes changes from pr added azure and masstransit to integrations for natively instrumented libraries #4308 fixing issue Native libraries list https://github.com/open-telemetry/opentelemetry.io/issues/3896 by adding to integrations table
=> fixing issue Native libraries list #3896 by adding to integrations table

.github/workflows/pr-actions.yml
=> Add `token` to checkout and setup-node action pr-actions.yml

.gitmodules, scripts/content-modules/adjust-pages.pl
- BLOCKED: merge #4354 first, then rebase this PR. Once rebased, the script cleanup results in exactly the same generated site files
- Closes #3804
- Closes #3922
=> Drop workarounds from adjust-pages.pl + opamp version pin

.github/workflows/pr-actions.yml
Reverts open-telemetry/opentelemetry.io#4350 to fix the permission issues
=> Revert "Add `token` to checkout and setup-node action pr-actions.yml"

content/en/docs/languages/go/exporters.md
- Followup to https://github.com/open-telemetry/opentelemetry.io/pull/4357/files#r1578471690
- Make all Console exporter subsections consistent.
/cc @codeboten
=> Go exporter copyedits: make Console exporter subsections consistent

data/instrumentation.yaml
Per https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.26.0
CC @open-telemetry/go-approvers 
Side note: I plan to start working on https://github.com/open-telemetry/opentelemetry.io/issues/4373 next week.
=> Update Go logs status to alpha

content/en/docs/languages/swift/libraries.md
Part of https://github.com/open-telemetry/opentelemetry.io/issues/4319
@open-telemetry/swift-maintainers  Please have a look. Overall structure is based on other languages, though we might want to add further considerations on things like semver, stability, etc.
=> Edit instrumentation libraries pages: Swift

.gitmodules, assets/scss/_styles_project.scss, hugo.yaml
- Contributes to #4023
- Fixes #4391
- **Preview**: https://deploy-preview-4396--opentelemetry.netlify.app/docs/collector/quick-start/#prerequisites
=> Upgrade Docsy and switch to Chroma classes

layouts/_internal/google_analytics_async.html
- Followup to #4392
- Drops temporary template
=> Drop google_analytics_async.html

assets/scss/_styles_project.scss
- Prep for #4023
- ~BLOCKED, waiting on #4346~
- **Preview**: https://deploy-preview-4347--opentelemetry.netlify.app/
Before:
> <img width="934" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/40372b59-4f42-4602-ad2e-f74f18838b26">
> <img width="933" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/eb582bda-284e-4f0d-a1e4-5776754ec0fb">
After:
> <img width="933" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/5848c080-2468-4c52-8ecb-05c840acd732">
> <img width="938" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/d849157c-6017-498f-91f3-2f9628acb4d6">
On mobile:
> <img width="669" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/asset …
=> [Dark mode] Banner compatibility prep

.gitmodules, assets/scss/_styles_project.scss
=> Update docsy to 0.10.0

content/en/community/end-user/feedback-survey.md, content/en/community/end-user/otel-in-practice.md, content/en/community/end-user/slack-channel.md, layouts/partials/banner.md, static/refcache.json
Remove old survey from banner, and add newest one. Also made minor tweaks to End User pages.
=> Update banner with newest OTel End User SIG survey

content/en/docs/concepts/signals/traces.md
- enable quotation
- use lower case(adjusting to another expression)
=> replace 'hello' Span with  span

README.md
as per https://github.com/open-telemetry/opentelemetry.io/issues/4441#issuecomment-2099984725
=> Update slack description in readme

hugo.yaml
- Contributes to #4443
- No change in generated site files other than the build timestamp
=> Clean up site param in prep for multilang

.github/component-label-map.yml
See https://github.com/open-telemetry/opentelemetry.io/issues/4465#issuecomment-2109016143
=> Update component-label-map.yml to include lang:zh and registry

content/en/docs/demo/feature-flags.md
docs for https://github.com/open-telemetry/opentelemetry-demo/pull/1515
=> [demo docs] Add imageSlowLoad featureflag description

assets/scss/_styles_project.scss
- Fixes #4473
- **Preview**: https://deploy-preview-4493--opentelemetry.netlify.app/docs/languages/java/automatic/configuration/#configuring-with-environment-variables
/cc @zeitlinger
=> [Dark mode] Fix config-option element bg color

content/zh/docs/concepts/_index.md, content/zh/docs/concepts/components.md
Add two pages to zh folder
```
content/zh/docs/concepts/_index.md
content/zh/docs/concepts/components.md
```
See [preview](https://deploy-preview-4525--opentelemetry.netlify.app/zh/docs/concepts/components/)
=> [zh] Add concepts folder and its index

.cspell.yml, content/en/docs/contributing/localization.md, content/en/docs/zero-code/_index.md, scripts/i18n-check.sh, static/refcache.json
- Contributes to #4582
- Adds a Contributing page for localizations based on newly established conventions and tooling
- Related: #4612
**Preview**: https://deploy-preview-4614--opentelemetry.netlify.app/docs/contributing/localization/
=> [i18n] Add contributing guidelines for localizations

content/zh/docs/faas/_index.md
- Adds `content/zh/docs/faas/_index.md`
- **Preview**: https://deploy-preview-4617--opentelemetry.netlify.app/zh/docs/faas/
=> [zh] Add faas/_index.md

content/zh/docs/_index.md
=> Fix a link

data/instrumentation.yaml
=> instrumentation.yaml: use new status name, development

.gitmodules
- There is no change to the generated site files
- Related to #1635
- Also see #4678
=> Update Go submodule to v1.27.0

README.md
@austinlparker, @chalin, @cartermp please approve to make it official :-)
@tiffany76, @theletterf please review your lines, especially the affiliation
Looking forward to work with you 🎉  
---
Post-Merge TODO: @austinlparker will update the team membership
=> Add @tiffany76 as approver and @theletterf as maintainer

content/en/docs/contributing/style-guide.md
[en] fix commands in contributing/style-guide.md
=> [en] fix commands in contributing/style-guide.md

content/zh/docs/getting-started/_index.md
Add content/zh/docs/getting-started/_index.md
=> [zh] Add getting-started/_index.md

content/ja/_index.md
Though the content itself was updated to the latest original, `default_lang_commit` wasn't, so I just updated the metadata.
```
$ npm run check:i18n -- content/ja
> check:i18n
> scripts/check-i18n.sh content/ja
Processing paths: content/ja
DRIFTED files: 0 out of 8
```
=> [ja] nit: change default_lang_commit

hugo.yaml
Addresses https://github.com/open-telemetry/opentelemetry.io/issues/4666#issuecomment-2163321178
=> Update GCS engine id

content/en/docs/languages/go/exporters.md
First step to address this problem #4713
=> Delete link that does not belong to the exporters section

content/ja/docs/what-is-opentelemetry.md
=> [ja] fix 軽装 to 計装

content/en/docs/languages/python/instrumentation.md
=> Remove subjective statement regarding decorators

content/en/docs/languages/php/propagation.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/4798
=> [PHP] Edit propagation doc

content/zh/docs/migration/_index.md
zh: Add content/zh/docs/migration/_index.md
=> [zh] Add migration/_index.md

.cspell.yml, content/en/blog/2024/cve-2024-36129.md, content/en/blog/2024/hardening-the-collector-one.md, content/en/docs/languages/java/performance.md, content/en/docs/zero-code/java/agent/configuration.md, content/en/docs/zero-code/python/configuration.md
Followup to a couple of PRs that introduced GH-action job failures for spell-check.
=> Fix spelling issues, update page-local dictionaries

package.json
- There is no change to the generated site files other than generator version and site timestamp.
- Closes #4859
=> [infra] Hugo 0.129.0 + other pkg vers refresh

layouts/partials/redirects/localization.txt
- Fixes #4898
- https://deploy-preview-4906--opentelemetry.netlify.app/zh/docs/languages/python/api/
- https://deploy-preview-4906--opentelemetry.netlify.app/ja/docs/languages/java/registry/
=> [i18n] Process non-en redirect directives

content/zh/docs/what-is-opentelemetry.md
remove some duplicate content.
=> Remove duplicate content

content/pt/docs/concepts/_index.md
Add concepts `index` translation for Portuguese.
---
**Preview**: https://deploy-preview-4901--opentelemetry.netlify.app/pt/docs/concepts/
=> [pt] feat: add localization concepts index portugues

content/en/docs/concepts/sampling/index.md
Some small suggested changes to improve grammar/clarity of Sampling doc without changing meaning or content
=> Small grammatical changes to Sampling document

package.json
- Fixes #4955
- Upgrades to Hugo 0.131.0
- Closes #4954 by superseding it
- Closes #4953 by superseding it
=> [infra] Upgrade NPM packages and clean up entries

content/en/docs/concepts/signals/logs.md
fixes https://github.com/open-telemetry/opentelemetry.io/issues/4956
=> fix spell errors

content/en/docs/languages/go/exporters.md
s/trace/metric
fixes https://github.com/open-telemetry/opentelemetry.io/issues/4959
=> Fix golang metric exporter snafu

content/en/docs/concepts/sampling/index.md
Nothing like a little time working with customers to influence a targeted rewrite
=> Rewrite parts of sampling doc and add more examples of things

.github/workflows/check-format.yml, .github/workflows/check-i18n.yml, .github/workflows/check-links.yml, .github/workflows/check-registry.yml, .github/workflows/check-spelling.yml, .github/workflows/check-text.yml
=> [CI] Run workflows on `merge_group`

.cspell.yml, content/en/blog/2022/tail-sampling/index.md, content/en/docs/concepts/sampling/index.md
- Fixes #4956, again
- Sorts our local dict
/cc @theletterf @cartermp
=> [infra] Fix spelling errors, update and sort local dict

hugo.yaml
- Fixes #4967
- **Preview**: https://deploy-preview-4994--opentelemetry.netlify.app/docs/specs/semconv/attributes-registry/
=> Bumps sidebar section-entry limit

data/registry/application-integration-openfga.yml, static/refcache.json
cc @miparnisari
Preview: https://deploy-preview-4998--opentelemetry.netlify.app/ecosystem/integrations/
=> Add OpenFGA to registry

.github/component-label-map.yml
=> Prefer sig:javascript label to sig:js

hugo.yaml
Follow up of #4989
+CC @chalin
=> Add mount points for es pages

.cspell/pt-palavras.txt
this should remove the spelling issue we have in multiple PRs
=> [pt] fix cspell issue in context propagation

.github/component-label-map.yml, .github/component-owners.yml
cc @open-telemetry/docs-es-approvers @open-telemetry/docs-pt-approvers
=> Update workflows for pt, es approvers and labels

content/en/docs/collector/custom-collector.md, static/refcache.json
=> update links for new ocb binaries

content/ja/announcements/_index.md, content/ja/announcements/otel-localized.md, content/ja/blog/2024/_index.md, content/ja/blog/2024/docs-localized.md, content/ja/blog/_index.md
**Merge this PR after #4996 gets merged**
This pull request is the localization of #4996.
Issue: #4922 and #4863.
ref: #5035
=> [ja] Add the localization announcement in Japanese

content/es/docs/concepts/_index.md
Related the issue: https://github.com/open-telemetry/opentelemetry.io/issues/4887
=> [es] feature: concepts - spanish translation

content/es/docs/kubernetes/_index.md
Related the issue: https://github.com/open-telemetry/opentelemetry.io/issues/4887
=> [es] kubernetes - spanish translation

content/pt/docs/concepts/semantic-conventions.md
Add localization to the semantic-conventions.md.
Issue: #4922
=> [pt] Add /content/pt/docs/concepts/semantic-conventions.md

content/en/docs/languages/go/exporters.md, static/refcache.json
=> Add Go OTLP over gRPC exporter section

content/es/docs/demo/_index.md
Related the issue https://github.com/open-telemetry/opentelemetry.io/issues/4887
=> [es] feature: demo structure - spanish translation

data/registry/instrumentation-python-haystack-openinference.yml
Adds a new entry to the registry for the OpenInference Haystack instrumentation created by Arize AI
=> Create Haystack OpenInference Registry Entry

data/ecosystem/adopters.yaml, static/refcache.json
Hi there!
I've added MercadoLibre as adopter. Here is the [blog post](https://medium.com/mercadolibre-tech/building-a-large-scale-observability-ecosystem-1edf654b249e).
=> Add MercadoLibre as adopter

content/en/docs/concepts/sampling/index.md
English is not my mother tongue so there might be a better way to word this still.
Feel free to suggest a better way.
Just wanted to raise awareness.
=> Fix wording in index.md

content/pt/docs/concepts/instrumentation/zero-code.md
Add zero-co localization pt-br. 
Issue: https://github.com/open-telemetry/opentelemetry.io/issues/4922
=> [pt] add localization: content/pt/docs/concepts/instrumentation/zero-code.md

content/es/docs/getting-started/dev.md
Related the issue https://github.com/open-telemetry/opentelemetry.io/issues/5206
=> feat: [es]  opentelemetry.io/content/en/docs/getting-started/dev.md

content/en/docs/languages/_index.md
https://github.com/open-telemetry/opentelemetry.io/pull/5204 introduced 2 wrong links
=> fix issues in languages index

content/es/docs/_index.md
Related the issue https://github.com/open-telemetry/opentelemetry.io/issues/5206
=> feat: [es] Create docs/_index.md

content/es/docs/languages/_index.md
Related issue https://github.com/open-telemetry/opentelemetry.io/issues/5229
=> feat: [es] Create docs/languages/_index.md

content/en/docs/zero-code/net/configuration.md
Propagates: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3680
=> OTel .NET Auto - typo fixes propagators -> exporters

content/en/docs/languages/java/sdk.md
- Context: #4966
- Drops alias that didn't exist before -- unless I'm missing something here.
- Removes unnecessary title/linkTitle stutter
/cc @jack-berg
=> [editorial] lang/Java/SDK cleanup

content/en/docs/contributing/issues.md
=> Fix typo in Contributing / issues.md

content/es/docs/demo/_index.md
=> Improve intro text

layouts/shortcodes/es/docs/languages/instrumentation-intro.md
Relacionado a esta conversación https://github.com/open-telemetry/opentelemetry.io/pull/5297/files#r1786264266
=>  [es] Translate layouts/shortcodes/es/docs/languages/instrumentation-intro

.cspell/es-palabras.txt, content/es/docs/languages/python/instrumentation.md
=> [es] Translate docs/languages/python/instrumentation 

content/es/docs/concepts/distributions.md
adding [es] docs/concepts/distributions
=> adding [es] docs/concepts/distributions

.htmltest.yml, static/refcache.json
Commit https://github.com/open-telemetry/opentelemetry.io/commit/ec914dccc1f7f771924d356561fdfc1552d92659 had a failing CI but was still merged. Root cause was a link to openai.com that returned a 403 which requires manual intervention. This PR fixes that and makes sure that our CI is working again.
=> Fix refcache issue

content/en/docs/languages/js/instrumentation.md
=> Update JS Counters header to be consistent

content/en/docs/contributing/localization.md, static/refcache.json
This PR updates the contribution guidelines for localizations to include instructions how to start a new localization project.
=> Add guidelines for starting new localizations

data/ecosystem/adopters.yaml, static/refcache.json
Add NAV the largest branch of the Norwegian Government to the adopters list with link to public blog post.
=> Add NAV - Norwegian Government to adopters.yaml

package.json
=> [infra] Update pkgs, Hugo to 0.136.1

.htmltest.yml, content/zh/docs/contributing/style-guide.md
Fix #5267 
- Add anchors
- Wrap long lines
=> [zh] Add anchors and tweak lines in style-guide.md

.gitmodules, package.json
- Updates to Docsy 0.11.0, for RTL support
- Unblocks #4990
- Updates to Hugo 0.136.2 patch release
=> Update docsy to 0.11.0 and Hugo to patch 0.136.2

data/registry/tools-java-druid-extension-otlp.yaml, static/refcache.json
Adding a registry entry for a little extension for Apache Druid that allows it to ingest OTLP data.
=> Adding utility for Apache Druid ingestion of OTLP

README.md
It's time to update my affiliation on the Approvers list.
=> Update tiffany76's affiliation

content/en/announcements/2024-community-awards.md, content/en/blog/2024/community-awards.md, static/refcache.json
Adds a blogpost to announce community awards
=> Add blogpost announcing Community Awards

data/ecosystem/vendors.yaml, static/refcache.json
This pr updates the URL of GreptimeDB in vendor list.
=> Update GreptimeDB URL in vendor list

package.json
=> Update Node LTS + Hugo patch and other pkg vers

.gitmodules
- Fixes #5500
- **Preview**: https://deploy-preview-5507--opentelemetry.netlify.app/fr/docs/what-is-opentelemetry/#et-ensuite-
> <img width="300" alt="image" src="https://github.com/user-attachments/assets/1568f7c3-ef31-4099-b751-4751dc278330">
/cc @open-telemetry/docs-fr-approvers
=> [infra] Update docsy for fr

.cspell/en-words.txt, data/registry-schema.json, gulp-src/validate-registry.js
=> make language an enum in registry schema

content/pt/docs/languages/_index.md
=> Remove redirect from content/pt/docs/languages/_index.md

.github/workflows/build-dev.yml, package.json, scripts/check-markdown-wrapper.sh
- Another followup to #5561
- Skips `fix:i18n` when doing `test-and-fix` in the build-dev workflow
=> [CI] build-dev: skip fix:i18n

.github/workflows/build-dev.yml
=> [CI] build-dev: set GET=no

data/registry/application-integration-go-traefik-hub-api-management.yml, static/refcache.json
- Contributes to #5601
/cc @svrnm
=> Registry: add missing URL for Traefik

content/en/docs/collector/installation.md
fixes: https://github.com/open-telemetry/opentelemetry.io/issues/5244
=> fixed installation command

data/registry/otel-odddotnet.yml, data/registry/tools-odddotnet-client-dotnet.yml, static/refcache.json
I'm requesting to add OddDotNet and the CSharp client to the registry.
A previous PR was opened under an org account, which has been causing difficulties. I'm am abandoning that PR and re-opening under my personal account to allow edits by maintainers.
The old PR was https://github.com/open-telemetry/opentelemetry.io/pull/5576.
=> Added OddDotNet registry files (Attempt 2)

content/en/docs/zero-code/java/spring-boot-starter/out-of-the-box-instrumentation.md
Fix https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/12531
=> Add Logback MDC to the starter

package.json
No change to the generated site files other than the Hugo version.
=> Update to Hugo 0.139.0

.github/workflows/pr-actions.yml
=> [CI] Ensure that all `/fix` commands trigger a script

hugo.yaml
follow up to https://github.com/open-telemetry/opentelemetry.io/pull/5548
=> Enable new page feedback template in hugo

.github/workflows/pr-actions.yml
=> CI] Install packages before running fix:text 

data/ecosystem/vendors.yaml, static/refcache.json
add rizhiyi lunaxee product by yottabyte in vendor list
=> add rizhiyi lunaxee product by yottabyte in vendor list

package.json
- Fixes #5673
- **Preview**: https://deploy-preview-5675--opentelemetry.netlify.app/search/?q=signal
> <img width="731" alt="image" src="https://github.com/user-attachments/assets/2ace384f-c487-4898-84f0-4a56f82fcff3">
=> [CI] Patch search results page so search results will display

content/en/docs/concepts/signals/metrics.md, content/en/docs/languages/go/instrumentation.md
Part Of #5669 
Add the missing Async Gauge description
=> [en] add gauge assync definition

content/en/community/end-user/slack-channel.md, content/pt/docs/concepts/signals/metrics.md
Part Of #5669 
Add missing Gauge Async definition in the Portuguese docs
=> [pt] add missing async gauge definition to pt

content/en/docs/zero-code/java/_index.md, scripts/auto-update/all-versions.sh, scripts/auto-update/version-in-file.sh
- Proposed as an alternative to #5758. Sorry @zeitlinger, I just can't figure out atm why your PR isn't working.
- Updates some repo versions, as they updates are now picked up by this script.
=> [CI] Ensure auto update processes all files

.gitmodules, content/en/docs/languages/java/api.md
=> Fix java context usage example

content/en/blog/2024/year-in-review.md, static/refcache.json
As discussed on Monday during the SIG call here is a draft for a year in review blog post for SIG Comms
=> Blog post: 2024 in review

content/en/docs/demo/services/recommendation.md
Fix link to the GitHub repository that is broken.
=> Fix link to demo-service source folder

content/en/docs/collector/architecture.md
=> [Collector's architecture] Nit: adjusted description of the provided pipeline example

content/en/docs/zero-code/java/spring-boot-starter/annotations.md, content/en/docs/zero-code/java/spring-boot-starter/getting-started.md, content/en/docs/zero-code/java/spring-boot-starter/other-spring-autoconfig.md, content/en/docs/zero-code/java/spring-boot-starter/sdk-configuration.md
This PR fixes Gradle build script names in docs.
=> Fix Gradle build script names in docs

content/en/blog/2024/year-in-review.md, static/refcache.json
- Adds a link to the cross-posted article on the CNCF blog, published on 2024-12-20
/cc @svrnm @tiffany76
=> Update 2024 year-in-review - link to cross-post

content/en/docs/concepts/signals/traces.md
Adds a reference link to the docs so the reader can easily know where to go to learn more about Span Links.
Closes #5879.
=> Add link to learn more about Span Links

content/ja/docs/demo/development.md
translated demo/development page.
=> [ja] translate demo/development page into ja

content/es/docs/contributing/prerequisites.md
Translate in spanis page: docs/contributing/prerequisites/
Related issue https://github.com/open-telemetry/opentelemetry.io/issues/5205
=> feat: [es] create docs/contributing/prerequisites

.github/workflows/survey-on-merged-pr.yml
This workflow still doesn't work. This time I try to fix id by adding permissions to the job. I restructured it as well because I want to have it similar to the PR actions workflow.
=> Fix survey-on-merged-pr.yml

README.md
@open-telemetry/docs-maintainers please approve to make it official:-)
@tiffany76 thanks for all the great work you are doing for this community, we are very lucky to have you and excited to have you joining the maintainers group 🎉
=> Move @tiffany76 to maintainers 🎉

content/en/docs/demo/services/ad.md
Updating ad service source link.
=> Update ad.md to fix ad service source link

scripts/content-modules/adjust-pages.pl
- Fixes #5935
- **Previews**:
- https://deploy-preview-5943--opentelemetry.netlify.app/docs/specs/otel/protocol/file-exporter/
- https://deploy-preview-5943--opentelemetry.netlify.app/docs/specs/otel/trace/api/#spankind
OTel-spec fixes:
- https://github.com/open-telemetry/opentelemetry-specification/pull/4366
- https://github.com/open-telemetry/opentelemetry-specification/pull/4367
=> [CI] adjust-pages.pl: handle corner case of intra-spec links

.htmltest.yml, static/refcache.json
=> [CI] Resolve and drop all github.com IgnoreURL rules for non-OTel orgs

content/en/docs/demo/services/accounting.md, content/en/docs/demo/services/checkout.md, content/en/docs/demo/services/currency.md, content/en/docs/demo/services/email.md, content/en/docs/demo/services/payment.md, content/en/docs/demo/services/product-catalog.md, content/en/docs/demo/services/quote.md, content/en/docs/demo/services/shipping.md, static/refcache.json
updating services md file to remove service suffix from source link url
=> updating services md file to remove service suffix from source link url

content/en/docs/kubernetes/helm/demo.md
=> Adding Missing cmd to add helm repo

content/fr/_index.md, content/ja/blog/2024/_index.md, content/ja/blog/_index.md, content/pt/blog/2024/_index.md, content/pt/blog/_index.md, content/zh/blog/2024/_index.md, content/zh/blog/_index.md
- Followup to #6002
- Updates `default_lang_commit ` to proper value
=> [i18n] Update commit hash for blog index pages

.cspell/en-words.txt, content/en/blog/2023/exponential-histograms.md
=> Use direct link rather than relref in blog post

.github/workflows/reusable-workflow-notification.yml
I tested it this time!
https://github.com/open-telemetry/semantic-conventions/issues/1790
=> Another semconv workflow fix

.github/workflows/survey-on-merged-pr.yml, archetypes/blog.md, content/en/blog/2022/instrument-nginx/index.md, content/en/blog/2022/v1.0-trio.md, content/en/blog/2024/go-contrib-removal.md, content/en/docs/collector/custom-collector.md, content/en/docs/kubernetes/collector/components.md, content/en/docs/languages/net/shim.md, data/ecosystem/adopters.yaml
Per https://github.com/open-telemetry/opentelemetry.io/pull/6009#issuecomment-2605506429
=> [chore] Spelling it isn't... ...pratyush

content/en/blog/2022/announcing-opentelemetry-demo-release/index.md, content/en/docs/collector/building/connector/index.md
Per https://github.com/open-telemetry/opentelemetry.io/pull/6009#issuecomment-2605506429
=> [chore] Spelling: walkthroughs + workaround

content/en/docs/concepts/signals/_index.md
=> Fix Signals alias paths

.github/workflows/survey-on-merged-pr.yml
One more fix... hope this time it works ;-)
=> Replace issue.number with pr.number i survey-on-merged-pr.yml

package.json, scripts/content-modules/normalize-titles.pl
- Followup to #6084
- In support of:
- https://github.com/open-telemetry/semantic-conventions/issues/1821
- https://github.com/open-telemetry/semantic-conventions/issues/1820
- Improves support of `auto_gen` front-matter directive
- No impact on the generated site files, only support script changes.
=> [CI] More title normalization tweaks

content/en/docs/languages/java/api.md
Fix `metric guidelines` link under [Java API docs](https://opentelemetry.io/docs/languages/java/api/#meter) so it would stop points to `http://localhost:1313/docs/specs/semconv/general/metrics/#general-guidelines`.
=> Java metric guidelines link

.htmltest.yml
=> [infra] Report localhost:1313 links

.github/workflows/check-links.yml
- Followup to #6140
- Fixes #6127 for real this time I hope :)
/cc @svrnm @trask
=> [CI] check-links: update code to push refcache etc

content/pt/blog/2024/docs-localized.md
Updates the `default_lang_commit` and the `date` tags for the following files:
- content/pt/blog/2024/docs-localized.md
=> [pt] Update localized content on content/pt/blog/2024/docs-localized.md

.github/workflows/check-links.yml
- Followup to #6140
- Mainly reverts #6127
=> [CI] Drop push from check-links for now

.cspell.yml, data/registry/application-integration-cpp-mysql enterprise server.yml, static/refcache.json
- Updates / refreshes the refcache
- Oldest link is now 2024-08-09 10:46
- Updates cSpell config to ignore the refcache
=> [chore] Refcache refresh, link & config update

content/pt/docs/concepts/glossary.md
Updates the localized content (Portuguese) for the following files:
- content/pt/docs/concepts/glossary.md
=> [pt] Update localized content on content/pt/docs/concepts/glossary.md

content/pt/docs/languages/go/instrumentation.md
Updates the default commit for localized content (Portuguese) for the following files:
- content/pt/docs/languages/go/instrumentation.md
=> [pt] Update localized content on content/pt/docs/languages/go/instrumentation.md

content/pt/docs/concepts/signals/_index.md
Updates the default commit for localized content (Portuguese) for the following files:
- content/pt/docs/concepts/signals/_index.md
=> [pt] Update localized content on content/pt/docs/concepts/signals/_index.md

content/en/docs/contributing/pull-requests.md
Mermaid does not show proper graphs due to missing parsed period.
Fixes #6249
=> fix: Unsupported markdown: list due to missing parsed period in contributing/pull-requests page

content/ja/docs/demo/feature-flags.md
translated demo/feature-flags page.
=> [ja] translate demo/feature-flags into ja

content/ja/docs/contributing/_index.md
update contributing page in ja because it is outdated.
issue: https://github.com/open-telemetry/opentelemetry.io/issues/6172
=> [ja] update contributing/_index ja page

scripts/auto-update/version-in-file.sh
- Followup to #6272
- Fixes #6271, for real 🤞 😄
=> [CI] Auto-version update fix: match on PR num

package.json, static/refcache.json
- Closes #6266
- Updates refcache after running fragment validity checker
=> [chore] Update NPM packages and refcache hash status

content/en/announcements/training.md
- Contributes to #3463
- Announces certification and course
**Preview**: https://deploy-preview-6322--opentelemetry.netlify.app/
> <img width="501" alt="image" src="https://github.com/user-attachments/assets/050cfd10-2b53-4620-929b-7945daf74c40" />
=> Announce certificate and course

content/pt/ecosystem/demo.md
Tracked on #6241
- content/pt/ecosystem/demo.md
=> [pt] Localize content/pt/ecosystem/demo.md

content/pt/ecosystem/integrations.md
Tracked on #6245
- content/pt/ecosystem/integrations.md
=> [pt] Localize content/pt/ecosystem/integrations.md

data/ecosystem/distributions.yaml
=> Fix typos in `distributions.yaml`

content/en/docs/concepts/glossary.md
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/6069
=> Clarify event and log glossary defs

content/ja/announcements/_index.md
I updated content/ja/announcements/_index page.
It was needed to update `default_lang_commit` because it had been updated in https://github.com/open-telemetry/opentelemetry.io/pull/6339.
ref: #6172.
=> [ja] update content/ja/announcements/_index default_lang_commit

content/ja/docs/concepts/signals/logs.md
I updated content/ja/docs/concepts/logs page.
ref: https://github.com/open-telemetry/opentelemetry.io/issues/6172.
=> [ja] update content/ja/docs/concepts/signals/logs page

content/ja/docs/collector/quick-start.md
I updated content/ja/docs/collector/quick-start page.
ref: #6172.
=> [ja] update content/ja/docs/collector/quick-start

content/ja/docs/concepts/signals/baggage.md
I updated content/ja/docs/concepts/signals/baggage page.
ref: https://github.com/open-telemetry/opentelemetry.io/issues/6172.
=> [ja] update content/ja/docs/concepts/signals/baggage page

content/ja/docs/demo/_index.md
I updated content/ja/docs/demo/_index page.
ref: #6172.
=> [ja] update content/ja/docs/demo/_index

content/ja/docs/collector/installation.md
I updated content/ja/docs/collector/installation page.
ref: #6172.
=> [ja] update content/ja/docs/collector/installation

content/en/docs/collector/building/receiver.md
Fixes single word typo on line 353
=> Fix small typo in receiver.md

content/en/blog/2025/ottl-contexts-just-got-easier.md
- Followup to #6290
- Removes unnecessary Prettier directives
=> OTTL blog: prettier-directives  tidy up

content/en/docs/collector/transforming-telemetry.md
Updates the transformprocessor example to use the new simpler basic configuration style.
=> Update transformprocessor example

content/pt/docs/languages/python/_index.md
Fixing anchor reference for cutting-edge-packages
=> [pt] Fix anchor reference in python/_index.md

content/en/docs/zero-code/java/agent/annotations.md
=> Specify correct annotation for span attributes

content/ja/docs/demo/development.md
I updated content/ja/docs/demo/development page
=> [ja] update content/ja/docs/demo/development.md

content/ja/docs/demo/_index.md
I updated content/ja/docs/demo/_index.md page
=> [ja] update content/ja/docs/demo/_index.md

content/ja/docs/collector/_index.md
updated content/ja/docs/collector/_index.md page
=> [ja] update content/ja/docs/collector/_index.md page

content/ja/docs/collector/distributions.md
Translate collector/distributions page into ja
=> [ja] translate collector/distributions page

README.md
Since I am no longer working for Cisco I set my affiliation to "Independent" for now.
=> Update my affiliation in the README file

content/ja/docs/concepts/glossary.md
ref: https://github.com/open-telemetry/opentelemetry.io/issues/6490
---
preview: https://deploy-preview-6426--opentelemetry.netlify.app/ja/docs/concepts/glossary/
=> [ja] fix drift of content/ja/docs/concepts/glossary page

content/ja/docs/contributing/pr-checks.md
I translated contributing/pr-checks into ja.
preivew https://deploy-preview-6529--opentelemetry.netlify.app/ja/docs/contributing/pr-checks/.
I remain some of headers (like `MARKDOWN linter`, `SPELLING check` and so on) English because their name are names of github actions steps.
=> [ja] translated contributing/pr-checks into ja

content/ja/docs/contributing/development.md
original https://opentelemetry.io/docs/contributing/development/
I translated contributing/development into ja.
preivew https://deploy-preview-6536--opentelemetry.netlify.app/ja/docs/contributing/development/
=> [ja] translated contributing/development into ja 

content/ja/docs/contributing/acknowledgements.md
I translated contributing/acknowledgements into ja
original https://opentelemetry.io/docs/contributing/acknowledgements/
preview https://deploy-preview-6539--opentelemetry.netlify.app/ja/docs/contributing/acknowledgements/
=> [ja] translated contributing/acknowledgements into ja

content/en/blog/2025/kubecon-eu.md
- Followup to #6542 
- Consolidate paragraphs
- Copyedits
**Preview**: https://deploy-preview-6552--opentelemetry.netlify.app/blog/2025/kubecon-eu/#opentelemetry-observatory
/cc @austinlparker @danielgblanco @tiffany76
=> Kubecon post edits of Observatory section

data/ecosystem/vendors.yaml
SigNoz is no longer under the MIT license since 2022:
https://github.com/SigNoz/signoz/commit/00389271cf6c9910c5c51e35e0340900f4341a53
=> Update SigNoz data

content/en/blog/2025/otel-cicd-sig/index.md
Updating the cicd slack channel in the blog post
=> Update cicd slack channel in blog post

content/en/docs/zero-code/java/agent/annotations.md
Documents how to set a custom span name when using `@WithSpan` annotation.
=> Document java explicit span name with @WithSpan annotation

README.md
To be merged from April 7 onward, which is my starting date as a Principal Technical Writer at Elastic. :-]
=> Update my affiliation in README

content/en/docs/demo/services/shipping.md, static/refcache.json
Related to issue : https://github.com/open-telemetry/opentelemetry.io/issues/6650
=> Update the docs links to the ContextGuard Struct

data/ecosystem/vendors.yaml, static/refcache.json
- Updating product name
- Updating link to updated direct URL, instead of being redirected
=> update Last9 details

content/en/docs/languages/dotnet/instrumentation.md
activity.RecordException() does not exist
=> [.NET] Use AddException instead of RecordException

README.md
Related to issue : https://github.com/open-telemetry/opentelemetry.io/issues/6661
Adding a link in the README to the Dev Setup page.
=> Update README with link to Dev Setup page

content/en/docs/collector/internal-telemetry.md, static/refcache.json
since feature gate flipped in v0.123.0
=> note change to internal telemetry prometheus endpoint configuration

data/registry/collector-exporter-azureblob.yml, static/refcache.json
As an owner of collector component https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azureblobexporter, I want to add https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azureblobexporter to the registry.
=> [registry] Add collector exporter azureblob

content/en/blog/2023/ecs-otel-semconv-convergence.md
Related to issue https://github.com/open-telemetry/opentelemetry.io/issues/6650
Update an old link of the ECS schema to the new one.
=> Update link of ECS schema

content/en/docs/concepts/distributions.md
=> add missing word to title

content/en/docs/platforms/kubernetes/operator/troubleshooting/target-allocator.md, static/refcache.json
Related to issue : https://github.com/open-telemetry/opentelemetry.io/issues/6650
Fixing 2 404 links in the docs referencing a file that is now deleted.
=> Update links of serviceMonitorSelector in target allocator

content/en/blog/2023/otel-arrow/index.md
Related to issue : https://github.com/open-telemetry/opentelemetry.io/issues/6650
=> Update link of otel arrow blog

content/en/docs/languages/python/exporters.md, content/pt/docs/languages/python/exporters.md
Full context for this PR can be found in this issue, which outlines the problem & rationale.
https://github.com/open-telemetry/opentelemetry.io/issues/6549
=> fixes #6549 incorrect use of resource constructor

content/en/docs/platforms/kubernetes/operator/troubleshooting/target-allocator.md, static/refcache.json
Related to issue https://github.com/open-telemetry/opentelemetry.io/issues/6650
=> Update links in kubernetes target allocator docs

content/en/blog/2025/opentelemetry-logging-and-you.md, static/refcache.json
Adding a blog about logs and what we call logs and events. cc @tedsuo @lmolkova @trask @breedx-splk @pellared 
---
**Preview:** https://deploy-preview-6711--opentelemetry.netlify.app/blog/2025/opentelemetry-logging-and-you/
=> Add Log Blog

content/zh/docs/concepts/signals/traces.md
Add zh localize doc of /docs/concepts/signals/traces.md
=> [zh] Localize content/zh/docs/concepts/signals/traces.md

content/zh/docs/concepts/signals/metrics.md
Add zh localize doc of /docs/concepts/signals/metrics.md
=> [zh] Localize content/zh/docs/concepts/signals/metrics.md

content/en/docs/languages/java/instrumentation.md
Fixes #6102 
by removing outdated TODO
=> Remove out of dated TODO in Java docs

layouts/partials/include.html, layouts/shortcodes/docs/languages/exporters/intro.md, layouts/shortcodes/docs/languages/index-intro.md, layouts/shortcodes/include.html
- Contributes to #6748
- Rework based on suggestions in https://github.com/gohugoio/hugo/issues/13668#issuecomment-2841001268
No change to generated site files other than build timestamp:
```console
$ (cd public && git diff) | grep ^diff 
```
=> [infra] include feature refactoring

content/en/docs/zero-code/js/_index.md
=> Remove old info warning from nodejs zero code docs

content/en/docs/contributing/development.md, static/refcache.json
- Followup to #6738
- **Preview**: https://deploy-preview-6791--opentelemetry.netlify.app/docs/contributing/development/
/cc @avillela
=> Contributing > Dev setup rework

content/en/docs/platforms/kubernetes/operator/_index.md, static/refcache.json
This is a follow up from a docs issue that a user recommended in [slack](https://cloud-native.slack.com/archives/C033BJ8BASU/p1745852559760149?thread_ts=1745849409.341669&cid=C033BJ8BASU), thank you for reviewing :bow:
---
**Preview**: https://deploy-preview-6780--opentelemetry.netlify.app/docs/platforms/kubernetes/operator/#getting-started
=> include a note about the collector image for the operator

i18n/en.toml
- Final change to close #6658
- Updates link to where users should leave feedback
- Copyedits
=> Ask AI: update feedback link

content/en/docs/collector/building/authenticator-extension.md, content/en/docs/collector/building/receiver.md, static/refcache.json
- Fixes an invalid link to the `ConfigValidator` interface.
=> Fix link in collector/building/receiver.md

content/en/docs/collector/management.md, static/refcache.json
Updates the OpAMP references on the Collector Management page to reflect more recent progress. Fixes https://github.com/open-telemetry/opentelemetry.io/issues/6795.
=> [collector/management] Update Collector Management OpAMP references

content/en/docs/collector/resiliency.md
Add new documentation page under the Collector docs outlining the resiliency strategies and the data-loss scenarios.
Fix https://github.com/open-telemetry/opentelemetry.io/issues/5933
=> feat: add collector resiliency doc

content/en/docs/security/handling-sensitive-data.md, static/refcache.json
I thought and talked about providing a page like this one for a few times already, finally I pushed through. It's a starting point, as there is so much more that can be said about this topic, and there have been previous OTEPs on that topic as well that were dropped due to other topics being more pressing right now, so the main purpose of this page for now is telling people to be cautious!
=> add page on sensitive data handling

content/en/docs/contributing/localization.md, static/refcache.json
**Preview**: https://deploy-preview-6889--opentelemetry.netlify.app/docs/contributing/localization/#new-localizations
=> [i18n] New locale config: add maintainer instructions, and other copyedits

.github/component-owners.yml
contributes to https://github.com/open-telemetry/opentelemetry.io/issues/6765
=> Add component ownership for Bengali Approvers

content/en/announcements/kubecon-china.md, static/refcache.json
This PR creates the banner announcement for KubeCon China 2025.
Contributes to #6929.
Preview: https://deploy-preview-6936--opentelemetry.netlify.app/
=> Create banner for KubeCon China

content/en/announcements/kubecon-japan.md, static/refcache.json
This PR creates the banner announcement for KubeCon Japan 2025. 
Contributes to #6611. 
Preview: https://deploy-preview-6935--opentelemetry.netlify.app/
=> Create banner for KubeCon Japan

i18n/en.toml
- Fixes #6911
- I still think that we could add a banner at some point
- cc @austinlparker 
> <img width="555" alt="image" src="https://github.com/user-attachments/assets/162feab8-6484-4000-bc2e-36d464a1084a" />
=> Add "Ask AI" to the search placeholder text

.github/workflows/update-semconv-integration-branch.yml
Attempt to address @chalin's https://github.com/open-telemetry/opentelemetry.io/pull/6928#issuecomment-2898948956
=> Clarify semconv automation

.github/workflows/update-spec-integration-branch.yml
Follow-up on @chalin's request: https://cloud-native.slack.com/archives/C02UN96HZH6/p1747156127378089
=> Add spec automation similar to semconv

content/ja/docs/contributing/announcements.md
I translated content/ja/docs/contributing/announcements into ja.
The original file was updated `markdown` to `Markdown`.
However, Japanese translated file has been already written as `Markdown`.
Then, I updated `default_language_commit` only.
```bash
> npm run check:i18n -- -d content/ja/docs/contributing/announcements.md
> check:i18n
> scripts/check-i18n.sh -d content/ja/docs/contributing/announcements.md
Processing paths: content/ja/docs/contributing/announcements.md
diff --git a/content/en/docs/contributing/announcements.md b/content/en/docs/contributing/announcements.md
index 808ee7f9..d1f1c1a4 100644
--- a/content/en/docs/contributing/announcements.md
+++ b/content/en/docs/contributing/announcements.md
@@ -15,7 +15,7 @@ fall back to English banners, etc.
-To add a new announcement, …
```
=> [ja] docs(i18n): fix drift of content/ja/docs/contributing/announcements.md

.github/workflows/update-semconv-integration-branch.yml
I think this is the issue here: https://github.com/open-telemetry/opentelemetry.io/actions/runs/15190161284/job/42720612269
=> Fix semconv automation

.github/workflows/update-semconv-integration-branch.yml
the submodule wasn't getting updated anymore, so rolling back and just tacking fix:refcache on to the end of the (previously working) workflow
=> Fix semconv automation issue

.github/workflows/update-spec-integration-branch.yml
(same as was recently done for semconv automation)
=> Add fix:refcache to spec automation

content/en/docs/languages/js/exporters.md, static/refcache.json
=> docs: update broken link

data/ecosystem/vendors.yaml, pr-fix.patch, static/refcache.json
base14 Scout is an observability and reliability system that uses OpenTelemetry agents for collecting observability signals.
=> Update vendors.yaml - Added base14 Scout

data/registry/application-integration-go-argo-workflows.yml, static/refcache.json
Add Argo Workflows to the list of  integrations as it has native OTEL metrics.
=> feat: Add Argo Workflows to integrations

content/ja/docs/what-is-opentelemetry.md
Original English File.
- https://opentelemetry.io/docs/what-is-opentelemetry/
Preview
- https://deploy-preview-7017--opentelemetry.netlify.app/ja/docs/what-is-opentelemetry/
=> [ja] docs(i18n): fix drift of content/ja/docs/what-is-opentelemetry.md

content/ja/docs/getting-started/dev.md
Original English File.
- https://opentelemetry.io/docs/getting-started/dev/
Preview.
- https://deploy-preview-7019--opentelemetry.netlify.app/ja/docs/getting-started/dev/
=> [ja] docs(i18n): fix drift of content/ja/docs/getting-started/dev.md

content/ja/docs/demo/_index.md
Original English Page.
- https://opentelemetry.io/docs/demo/
Updated
- https://deploy-preview-7016--opentelemetry.netlify.app/ja/docs/demo/
=> [ja] docs(i18n): fix drift of content/ja/docs/demo/_index.md

content/en/docs/languages/php/resources.md
=> Fixes #7026

content/ja/blog/2025/kubecon-japan.md
Original English file.
- https://opentelemetry.io/ja/blog/2025/kubecon-japan/
Preview.
- https://deploy-preview-7024--opentelemetry.netlify.app/ja/blog/2025/kubecon-japan/
=> [ja] docs(i18n): fix drift of content/ja/blog/2025/kubecon-japan.md

content/ja/announcements/kubecon-japan.md
Original English File
- https://opentelemetry.io//ja/announcements/kubecon-japan/
Japanese File
- https://deploy-preview-7023--opentelemetry.netlify.app/ja/announcements/kubecon-japan/
=> [ja] docs(i18n): fix drift of content/ja/announcements/kubecon-japan.md

content/en/announcements/open-observability-summit-na.md
- Followup to #7046
- Fix venue for Open Observability Summit NA & OTel day
=> Fix Venue for OTel day & OO summit

content/ja/_includes/otel-does-not-validate-3rd-pty-distros.md, content/ja/docs/collector/distributions.md
Purpose.
- Follow up to https://github.com/open-telemetry/opentelemetry.io/pull/6918, https://github.com/open-telemetry/opentelemetry.io/pull/7041
Preview
- https://deploy-preview-7052--opentelemetry.netlify.app/ja/docs/collector/distributions/
=> [ja] docs(i18n): fix drift of content/ja/docs/collector/distributions.md

.github/workflows/update-semconv-integration-branch.yml, .github/workflows/update-spec-integration-branch.yml
I looked at the workflow and I _think_ it was supposed to do what @chalin is asking for in https://github.com/open-telemetry/opentelemetry.io/pull/6952#issuecomment-2963227719, but there was just a bug 🤞
=> Fix semconv and spec PR workflows

.github/workflows/update-semconv-integration-branch.yml, .github/workflows/update-spec-integration-branch.yml
See https://github.com/open-telemetry/opentelemetry.io/pull/7098#issuecomment-2968156636
=> Update adjust-pages.pl also during spec and semconv automation

content/ja/docs/collector/_index.md
A original English page preview.
- https://deploy-preview-7083--opentelemetry.netlify.app/docs/collector/
A Japanese page preview.
- https://deploy-preview-7083--opentelemetry.netlify.app/ja/docs/collector/
=> [ja] docs(i18n): fix drift of content/ja/docs/collector/_index.md

content/ja/docs/demo/architecture.md, content/ja/docs/demo/docker-deployment.md
A original English page preview.
- https://deploy-preview-7084--opentelemetry.netlify.app/docs/demo/architecture/
- https://deploy-preview-7084--opentelemetry.netlify.app/docs/demo/docker-deployment/
A Japanese page preview.
- https://deploy-preview-7084--opentelemetry.netlify.app/ja/docs/demo/architecture/
- https://deploy-preview-7084--opentelemetry.netlify.app/ja/docs/demo/docker-deployment/
=> [ja] docs(i18n): fix drift of content/ja/docs/demo/*.md files

.github/workflows/update-semconv-integration-branch.yml, .github/workflows/update-spec-integration-branch.yml
=> Adjust pages

content/en/announcements/kubecon-india.md, content/en/announcements/slack-workspace-changes.md
- Contributes to #7135
- Adds banner and links to the blog
> <img width="820" alt="image" src="https://github.com/user-attachments/assets/377a8340-2668-48dc-8f2f-5fd1622dc770" />
=> Slack-changes banner

content/ja/docs/concepts/instrumentation-scope/index.md
Original English page.
- https://deploy-preview-7142--opentelemetry.netlify.app/docs/concepts/instrumentation-scope/
Preview
- https://deploy-preview-7142--opentelemetry.netlify.app/ja/docs/concepts/instrumentation-scope/
=> [ja] docs(i18n): fix drift of content/ja/docs/concepts/instrumentation-scope/index.md

content/zh/docs/contributing/announcements.md, content/zh/docs/contributing/localization.md, content/zh/docs/contributing/prerequisites.md
```
added: content/zh/docs/contributing/announcements.md
added: content/zh/docs/contributing/prerequisites.md
modified:   content/zh/docs/contributing/localization.md
```
=> [zh] Add announcements and prerequisites and modify localization

data/ecosystem/vendors.yaml, static/refcache.json
Documentation, github, and contact information for Coroot added to vendors.yaml
=> Add Coroot to vendors.yaml

content/zh/docs/contributing/development.md
```
content/zh/docs/contributing/development.md
```
=> [zh] Add contributing/development.md

content/zh/docs/contributing/blog.md
Add zh text to this page:
```
content/zh/docs/contributing/blog.md
```
=> [zh] Add contributing/blog.md

content/zh/docs/contributing/sig-practices.md
```
content/zh/docs/contributing/sig-practices.md
```
=> [zh] Add contributing/sig-practices.md

content/zh/docs/demo/architecture.md
```
content/zh/docs/demo/architecture.md
```
See [preview](https://deploy-preview-7187--opentelemetry.netlify.app/zh/docs/demo/architecture/)
=> [zh] Add demo/architecture.md

content/en/docs/languages/sdk-configuration/general.md
=> Add missing backtick

content/en/docs/collector/building/receiver.md
Adjusted the indentation of the code example
=> [docs][collector] Adjust code indentation for receive example

content/en/docs/languages/go/getting-started.md
see: https://github.com/open-telemetry/opentelemetry-go/blob/02f7b75793b85aa926d2193beb55ef6b987e8e28/go.mod#L3
=> chore: update minimum Go version requirement

content/zh/docs/_index.md
Update zh text in:
```
content/zh/docs/_index.md
```
=> [zh] sync _index.md

content/zh/docs/demo/docker-deployment.md
```
content/zh/docs/demo/docker-deployment.md
```
=> [zh] Add demo/docker-deployment.md

content/zh/docs/concepts/glossary.md
```
content/zh/docs/concepts/glossary.md
```
=> [zh] Add concepts/glossary.md

content/pt/docs/languages/java/_index.md, content/pt/docs/languages/java/getting-started.md
Closes https://github.com/open-telemetry/opentelemetry.io/issues/5825
=> [pt] Add Java language documentation and getting started guide

content/zh/docs/demo/kubernetes-deployment.md
Add zh text:
```
content/zh/docs/demo/kubernetes-deployment.md
```
=> [zh] Add demo/kubernetes-deployment.md

.github/workflows/auto-update-registry.yml
fixes https://github.com/open-telemetry/opentelemetry.io/issues/7283
=> fix permissions for auto-update-registry

.github/workflows/build-dev.yml
=> fix build dev workflow 2

content/zh/docs/concepts/distributions.md
Add
`content/zh/docs/concepts/distributions.md`
=> [zh] Add concepts/distributions.md

content/zh/community/_index.md, content/zh/community/end-user/_index.md, content/zh/community/members.md
```
content/zh/community/_index.md
content/zh/community/end-user/_index.md
content/zh/community/members.md
```
=> [zh] Add community/ pages

content/zh/docs/concepts/signals/_index.md, content/zh/docs/concepts/signals/baggage.md, content/zh/docs/concepts/signals/traces.md
```
added content/zh/docs/concepts/signals/baggage.md
modified  content/zh/docs/concepts/signals/_index.md
modified  content/zh/docs/concepts/signals/traces.md
```
=> [zh] Add signals/baggage.md and update two pages

.github/workflows/auto-update-versions.yml
Intermediate fix to make the auto update script work, later we need to revisit this and other workflows to work with the otelbot
=> fix auto update versions workflow

content/zh/docs/platforms/_index.md, content/zh/docs/platforms/faas/_index.md, content/zh/docs/platforms/kubernetes/_index.md, content/zh/docs/platforms/kubernetes/collector/_index.md, content/zh/docs/platforms/kubernetes/helm/_index.md, content/zh/docs/platforms/kubernetes/operator/_index.md
Add zh text to `_index.md` files in:
```
content/zh/docs/platforms/
```
=> [zh] Add platforms/ pages

content/en/docs/collector/building/connector/index.md
This PR updates the OpenTelemetry Collector connector building tutorial to fix compatibility issues with recent SDK changes and significantly improves the testing section with a more practical approach.
**Fix SDK Compatibility Issues:**
- Update `connector.CreateSettings` to `connector.Settings` (deprecated)
- Add proper `component.NewType()` usage for type creation
**Add Testing Section:**
- Add step-by-step testing guide with realistic examples
- Provide expected test outputs and collector log examples
=> docs(collector): fix connector tutorial for latest OpenTelemetry Collector

content/zh/docs/collector/_index.md, content/zh/docs/collector/distributions.md
```
content/zh/docs/collector/_index.md
content/zh/docs/collector/distributions.md
```
=> [zh] Add docs/collector/

content/zh/docs/specs/_index.md, content/zh/docs/specs/status.md
```
content/zh/docs/specs/_index.md
content/zh/docs/specs/status.md
```
=> [zh] Add specs/ pages

content/zh/announcements/_index.md, content/zh/announcements/kubecon-asia.md, content/zh/announcements/kubecon-china.md, content/zh/announcements/kubecon-india.md, content/zh/announcements/kubecon-japan.md, content/zh/announcements/open-observability-summit-na.md
```
content/zh/announcements/
```
=> [zh] Add announcements/ pages

content/zh/docs/migration/opentracing.md
```
content/zh/docs/migration/opentracing.md
```
=> [zh] Add migration/opentracing.md

content/ja/docs/languages/go/exporters.md, content/ja/docs/languages/go/instrumentation.md, content/ja/docs/languages/go/libraries.md, content/ja/docs/languages/go/resources.md, content/ja/docs/languages/go/sampling.md
Original
https://deploy-preview-7153--opentelemetry.netlify.app/docs/languages/go/
Preview
https://deploy-preview-7153--opentelemetry.netlify.app/docs/languages/go/
=> [ja] docs(i18n): translate content/ja/docs/languages/go/*.md

content/fr/docs/zero-code/_index.md
Following https://github.com/open-telemetry/opentelemetry.io/pull/7351
=> [fr] Translation of Zero Code index page

content/fr/docs/zero-code/go.md
Following https://github.com/open-telemetry/opentelemetry.io/pull/7351
=> [fr] Translation of Zero Code Go docs

README.md
=> Add vitorvasc as Approver to Comms README

content/zh/docs/zero-code/_index.md, content/zh/docs/zero-code/php.md
```
content/zh/docs/zero-code/_index.md
content/zh/docs/zero-code/php.md
```
=> [zh] Add zero-code/_index.md and php.md

content/zh/docs/collector/installation.md
```
content/zh/docs/collector/installation.md
```
=> [zh] Add collector/installation.md

content/zh/docs/collector/resiliency.md
```
content/zh/docs/collector/resiliency.md
```
=> [zh] Add collector/resiliency.md

.cspell/fr-mots.txt, content/fr/docs/zero-code/python/_index.md, content/fr/docs/zero-code/python/configuration.md, content/fr/docs/zero-code/python/example.md, content/fr/docs/zero-code/python/logs-example.md, content/fr/docs/zero-code/python/operator.md, content/fr/docs/zero-code/python/troubleshooting.md, static/refcache.json
Following https://github.com/open-telemetry/opentelemetry.io/pull/7351
=> [fr] Translation of Zero Code Python docs

content/zh/docs/collector/quick-start.md
```
content/zh/docs/collector/quick-start.md
```
=> [zh] Add collector/quick-start.md

content/zh/docs/languages/java/getting-started.md
Add content/zh/docs/languages/java/getting-started.md
=> [zh]  Add content/zh/docs/languages/java/getting-started.md

content/ja/docs/contributing/development.md, content/ja/docs/contributing/issues.md, content/ja/docs/contributing/prerequisites.md, content/ja/docs/contributing/pull-requests.md
Original files.
- https://deploy-preview-7408--opentelemetry.netlify.app/docs/contributing/development/
- https://deploy-preview-7408--opentelemetry.netlify.app/docs/contributing/issues/
- https://deploy-preview-7408--opentelemetry.netlify.app/docs/contributing/prerequisites/
- https://deploy-preview-7408--opentelemetry.netlify.app/docs/contributing/pr-checks/
Preview
- https://deploy-preview-7408--opentelemetry.netlify.app/ja/docs/contributing/development/
- https://deploy-preview-7408--opentelemetry.netlify.app/ja/docs/contributing/issues/
- https://deploy-preview-7408--opentelemetry.netlify.app/ja/docs/contributing/prerequisites/
- https://deploy-preview-7408--opentelemetry.netlify.app/ja/docs/contributing/pr-checks/
=> [ja] docs(i18n): fix drift of content/ja/docs/contributing/*.md files

content/ja/docs/languages/go/getting-started.md, content/ja/docs/languages/go/instrumentation.md
Original file
- https://deploy-preview-7410--opentelemetry.netlify.app/docs/languages/go/getting-started/
- https://deploy-preview-7410--opentelemetry.netlify.app/docs/languages/go/instrumentation/
Preview
- https://deploy-preview-7410--opentelemetry.netlify.app/ja/docs/languages/go/getting-started/
- https://deploy-preview-7410--opentelemetry.netlify.app/ja/docs/languages/go/instrumentation/
=> [ja] docs(i18n): fix drift of content/ja/docs/languages/go/*.md files

content/pt/docs/contributing/localization.md
Adiciona o arquivo localization.md em português, conforme a issue #6855.
Closes #6855
=> [pt] Localize content/pt/docs/contributing/localization.md

content/es/ecosystem/_index.md
Translated page ecosystem/_index.md, related the issue: https://github.com/open-telemetry/opentelemetry.io/issues/7488
=> feat: [es] New translation - ecosystem folder

content/en/blog/2025/otip-alibaba.md
Updating date to match blog post publishing date
=> Update date of OTiP Alibaba blogpost

content/pt/community/_index.md, content/pt/community/events.md, content/pt/community/marketing-guidelines.md, content/pt/community/members.md
Tracked on #7475
- content/pt/community/_index.md
- content/pt/community/events.md
- content/pt/community/marketing-guidelines.md
- content/pt/community/members.md
=> [pt] Localize pages under /content/en/community

content/es/status.md
Add the status.md spanish page translation
=> add: status spanish translation

content/en/docs/platforms/kubernetes/collector/components.md, content/en/docs/platforms/kubernetes/getting-started.md, content/en/docs/platforms/kubernetes/operator/_index.md, content/en/docs/platforms/kubernetes/operator/automatic.md
- Contributes to #4876
- Unblocks #7477
=> [i18n] Update files under /docs/platforms/kubernetes to use absolute path

content/es/docs/platforms/kubernetes/_index.md
Related the issue: https://github.com/open-telemetry/opentelemetry.io/issues/7571
[update page. ](https://opentelemetry.io/docs/platforms/kubernetes/)
=> update: docs/platform/kubernetes/_index

content/es/status.md, content/es/training/index.md
[Translate training page to spanish](https://opentelemetry.io/training/)
=> add: training page to spanish

content/ja/docs/collector/troubleshooting.md
original:
* https://opentelemetry.io/docs/collector/troubleshooting/
translation:
* https://deploy-preview-7363--opentelemetry.netlify.app/ja/docs/collector/troubleshooting/
=> [ja]Translate content/ja/docs/collector/troubleshooting.md

content/ja/docs/demo/architecture.md
Closes #7562.
original
- https://deploy-preview-7610--opentelemetry.netlify.app/ja/docs/demo/architecture/
preview
- https://deploy-preview-7610--opentelemetry.netlify.app/docs/demo/architecture/
=> [ja] docs(i18n): fix drift of content/ja/docs/demo/architecture.md

content/es/_index.md
Tracked on #7521 
Updates the drifted content for `content/es/_index.md`
<details>
<summary>Diff</summary>
```diff
❯ npm run check:i18n -- -d content/es/_index.md
> check:i18n
> scripts/check-i18n.sh -d content/es/_index.md
Processing paths: content/es/_index.md
diff --git a/content/en/_index.md b/content/en/_index.md
index 56153ec9..5527388f 100644
--- a/content/en/_index.md
+++ b/content/en/_index.md
@@ -5,7 +5,9 @@ description: >-
observability
outputs:
- HTML
-  - REDIRECTS # Include this `content/en` ONLY
+  # Include the following for `content/en` ONLY
+  - REDIRECTS
+  - RSS
developer_note:
The blocks/cover shortcode (used below) will use as a background image any
image file containing "background" in its name.
@@ -28,7 +30,6 @@ show_banner: true
- [Learn …
```
=> [es] Update drifted content for page content/es/_index.md

content/zh/docs/languages/java/api.md
Add content/zh/docs/languages/java/api.md
=> [zh] Add content/zh/docs/languages/java/api.md

content/en/docs/languages/js/_index.md
fix DefinitelyType to DefinitelyTyped
=> fix: typographical error about DefinitelyTyped

content/es/docs/contributing/acknowledgements.md
Related issue: https://github.com/open-telemetry/opentelemetry.io/issues/5205
=> feat [es] Create docs/contributing/acknowledgements.md

content/es/docs/contributing/blog.md
Related issue: https://github.com/open-telemetry/opentelemetry.io/issues/5205
=> feat [es] Correct docs/contributing/blog.md

content/es/docs/contributing/sig-practices.md
Related issue: https://github.com/open-telemetry/opentelemetry.io/issues/5205
=> feat [es] Correct docs/contributing/sig-practices.md

data/ecosystem/vendors.yaml, static/refcache.json
=> Add `s2.dev` to vendors 

content/ja/docs/languages/go/getting-started.md, content/pt/docs/languages/go/getting-started.md, content/zh/docs/languages/go/getting-started.md
This is the https://github.com/open-telemetry/opentelemetry.io/pull/7694 counterpart for non-english pages.
=> Update go getting-started examples in non-english

content/zh/docs/languages/java/sdk.md
Add content/zh/docs/languages/java/sdk.md
=> [zh] Add content/zh/docs/languages/java/sdk.md

data/ecosystem/vendors.yaml, static/refcache.json
This is a pull request to add Mackerel, Japan's OpenTelemetry-compatible observability platform, to the Vendors section.
=> Add Mackerel to vendors.yaml

content/zh/docs/collector/deployment/_index.md, content/zh/docs/collector/deployment/agent.md
```
content/zh/docs/collector/deployment/_index.md
content/zh/docs/collector/deployment/agent.md
```
=> [zh] Add collector/deployment/_index.md and agent.md

content/zh/docs/collector/building/_index.md, content/zh/docs/collector/building/authenticator-extension.md
```
content/zh/docs/collector/building/_index.md
content/zh/docs/collector/building/authenticator-extension.md
```
=> [zh] Add collector/building/_index and authenticator-extension

content/es/docs/concepts/context-propagation.md
Updating pages related to https://github.com/open-telemetry/opentelemetry.io/issues/7521
=> [es] fix drift on content/es/docs/concepts/context-propagation.md

content/ja/docs/zero-code/obi/setup/kubernetes.md
https://opentelemetry.io/docs/zero-code/obi/setup/kubernetes/
https://github.com/open-telemetry/opentelemetry.io/blob/19ca575e83b5d058ed02dea12c7c6770b477aa71/content/en/docs/zero-code/obi/setup/kubernetes.md
https://deploy-preview-7725--opentelemetry.netlify.app/ja/docs/zero-code/obi/setup/kubernetes/
=> [ja]Translate content/en/docs/zero-code/obi/setup/kubernetes.md

content/ja/docs/zero-code/obi/setup/standalone.md
https://opentelemetry.io/docs/zero-code/obi/setup/standalone/
https://github.com/open-telemetry/opentelemetry.io/blob/c6df1ca98613ce886d3ea5ecb7ea50d02a31f18a/content/en/docs/zero-code/obi/setup/standalone.md
https://deploy-preview-7726--opentelemetry.netlify.app/ja/docs/zero-code/obi/setup/standalone/
=> [ja]Translate content/en/docs/zero-code/setup/standalone.md

content/ja/docs/languages/ruby/sampling.md
https://opentelemetry.io/docs/languages/ruby/sampling/
https://github.com/open-telemetry/opentelemetry.io/blob/6a865f53d8e40c17f42772fb8fb100d62a61fb7e/content/en/docs/languages/ruby/sampling.md
https://deploy-preview-7714--opentelemetry.netlify.app/ja/docs/languages/ruby/sampling/
=> [ja]Translate content/en/docs/languages/ruby/sampling.md

content/zh/docs/collector/management.md
```
content/zh/docs/collector/management.md
```
=> [zh] Add collector/management.md

content/zh/docs/languages/java/configuration.md
Add content/zh/docs/languages/java/configuration.md
=>  [zh] Add content/zh/docs/languages/java/configuration.md

content/en/blog/2025/contribute-to-otel.md, static/refcache.json
Add a blog post about contributing to OTel, providing guidance on where to start and what to expect.
=> feat(blog): How to contribute to OpenTelemetry

content/es/docs/concepts/signals/metrics.md
Related issue: https://github.com/open-telemetry/opentelemetry.io/issues/5206
=> [es] feature: concepts/signals/metrics - spanish translation

content/en/docs/languages/sdk-configuration/declarative-configuration.md, content/en/docs/zero-code/java/agent/declarative-configuration.md, content/en/docs/zero-code/java/agent/disable.md, content/en/docs/zero-code/java/agent/getting-started.md, static/refcache.json
Part of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/14085
Depends on #7776 (for the link target)
=> Java Declarative config: intro

data/ecosystem/adopters.yaml
This pull request adds a new adopter entry to the data/ecosystem/adopters.yaml file, expanding the list of organizations using the project.
Ecosystem updates:
Added PagBank as a new adopter, including their website, components used (Collector, Operator, Java, JavaScript, PHP, Python, .NET, Go) and a contact info.
=> feat: add PagBank as an adopter

.github/ISSUE_TEMPLATE/BLOG_POST.yml
This PR adds a form that allows people to request the publication of a blog post in a more structured manner
=> add issue template for blog posts

.github/workflows/check-links.yml, .github/workflows/scripts/check-refcache.sh, content/en/docs/contributing/pr-checks.md
- Contributes to #7865
- Tests use of download-artifact merge-multiple before we split link checking across locales
- Updates relevant section of contrib docs
=> [CI] Check-links workflow use download-artifact merge-multiple

content/ja/docs/security/_index.md
original.
- https://deploy-preview-7892--opentelemetry.netlify.app/docs/security/
preview.
- https://deploy-preview-7892--opentelemetry.netlify.app/ja/docs/security/
=> [ja] fix: a drift file of content/ja/docs/security/_index.md

.github/scripts/check-links-shard.sh, .github/workflows/check-links.yml
- Fixes #7942
- Contributes to #7865
=> [CI] Don't ignore shard link-check errors

content/ro/docs/what-is-opentelemetry.md
- Fixes #7940
- Context:
- For the link failures see, e.g., https://github.com/open-telemetry/opentelemetry.io/pull/7944#issuecomment-3353354491
=> [ro] Fix link-check failures

content/en/announcements/kubecon-na.md
=> Add banner for KubeCon NA 2025

static/refcache.json
Refreshes the refcache, the result of running:
- `npm run fix:refcache:refresh`
- `npm run check:links`
=> Refcache refresh

data/registry/tools-otel-upgrade-helper.yml, static/refcache.json
Invited to add to the registry in https://github.com/wbollock/otel_upgrade_helper/issues/6
cc: @svrnm
=> feat: add otel_upgrade_helper to registry

content/ro/docs/getting-started/_index.md
Related to https://github.com/open-telemetry/opentelemetry.io/issues/7927
=> [ro] feature /content/docs/getting-started/_index.md

content/en/docs/contributing/pr-checks.md, scripts/double-check-refcache-4XX.mjs
- Fixes the script name in the workflow
- Also updates the script name in the contrib docs
=> [CI] Update contrib does, and fix script name

.github/workflows/refcache-refresh.yml, scripts/get-url-status.mjs
- Explicitly sets an env var with the path to Chrome
- Uses the set env var in the appropriate helper script
=> [CI] refcache-refresh: fix chrome path

.github/workflows/refcache-refresh.yml, scripts/double-check-refcache-4XX.mjs, scripts/get-url-status.mjs
- Adds support for a verbose option to help us better debug refcache-refresh workflow runs
=> [CI] Refcache refresh: add verbose option

scripts/get-url-status.mjs
- Fixes call to npm CLI to be only when status is 403
=> [CI] Refcache refresh: fixes to npmjs logic
