config.toml

Maybe there is a better place to refer to, then please adjust.
For now some generic place for the link to not be broken anymore.

fix broken link to github project

---

data/timeline.yaml

Fix a typo in timeline section

---

assets/sass/home.sass
config.toml
layouts/index.html
layouts/partials/home/observability.html
layouts/partials/home/timeline.html

Not sure if this is desired or the right way to go about it, but I think it might be nice to give a breakdown of the different domains of observability. If this content is better left for a later date or a separate doc, I'm cool with that.

Add observability section to main page

---

data/learn.yaml

Noticed that the CNCF blog link was a dead link. Found the correct link.
Does not exist: https://blog.cncf.io
Corrected URL: https://www.cncf.io/newsroom/blog/

Correcting CNCF blog url from dead link.

---

config.toml
data/faq.yaml

This PR provides a link to the OT spec in the FAQ on the landing page.

Add spec link to front page

---

content/about.md

Fix broken link of release-calendar in about page.

Fix broken link of release-calendar in about page

---

content/project-status.md
data/progress_source.yaml
layouts/shortcodes/release_notes.html
scripts/fetchMilestones.js

Fixes #58 
This pulls in the latest release (pre release or normal release) from GitHub for each repo and adds a description + link to the release to the project status page.

add a release notes tracker

---

content/docs/csharp/tracing.md

add c# quickstart

---

data/progress_source.yaml
scripts/fetchMilestones.js

This fixes a bug in the milestone/release pull script to make it more resilient to unexpected URLs in the source data.

Improve milestone/release tracker resiliency

---

layouts/partials/ghbadge.html

The Hugo script for the GitHub badge was returning an empty page
when on the root of the site, which then got concatenated into
a URL that didn't exist on GitHub. This commit checks to see if
that page portion is empty, and if so sets the URL for the badge
to the OpenTelemetry organization page

fix the ref for the GitHub badge while on the root page

---

README.md

The standard version of Hugo can't run the site locally:
> error: failed to transform resource: TOCSS: failed to transform "sass/style.sass" (text/x-sass): this feature is not available in your current Hugo version Serving the full site
Signed-off-by: Daniel González Lopes <danielgonzalezlopes@gmail.com>

Add extended version of Hugo

---

content/project-status.md

It's always inaccurate and the release trackers below are better

Remove SIG progress tracker

---

content/docs/collector/configuration.md

The previous links returned a GitHub 404. This fixes the links to point to the files on the master branch. Not sure if that is what you want, but thought I'd make this pull request to help out.

Fix broken links

---

content/registry/collector-exporter-elastic.md

The Elastic APM exporter for OpenTelemetry Collector was just merged (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/240). I'd like to add it to the registry to hope folks find it.

Add Elastic APM exporter to registry

---

content/registry/plugin-go-gin.md

Gin support is now part of the opentelemetry-go-contrib repo: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/15

add Gin plugin for Golang

---

content/registry/plugin-go-gorilla-mux.md

Gorilla Mux support is now part of the opentelemetry-go-contrib repo: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/19

add Gorilla Mux plugin for Golang

---

content/docs/collector/configuration.md

As a response to an [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/557#issue-567228160) in the opentelemetry/collector repository, I am adding this piece of documentation into the collector/configuration section. This documentation will expose to the users about the capability of the configuration file handling environment variables.

Add documentation about using environment variables in config files

---

content/registry/exporter-go-google-cloud-monitoring.md
content/registry/exporter-go-google-cloud-trace.md

Add 2 exporters to OTel registry
* Google Cloud Trace exporter for Go
* Google Cloud Monitoring exporter for Go

Add Google Cloud Trace and Google Cloud Monitoring exporter for Go

---

content/registry/instrumentation-go-go-restful.md

New instrumentation plugin for generating server-side traces with go-restful http framework.

Add emicklei/go-restful instrumentation for Go

---

content/registry/instrumentation-go-gin.md
content/registry/instrumentation-go-gorilla-mux.md
content/registry/instrumentation-go-labstack.md
content/registry/instrumentation-go-macaron.md
content/registry/instrumentation-go-mongodb.md

Refer to Go as Go, not Golang. 
Keep title shorter so it fits better in the opentelemetry.io registry display

Standardizing name/formatting for go instrumentation plugins

---

content/docs/collector/configuration.md

Fixing spelling error found on the Collector configuration page: https://opentelemetry.io/docs/collector/configuration/

Fixing spelling error

---

content/project-status.md

Fixed broken specification milestones link on the https://opentelemetry.io/project-status/

Fixed specification milestones link

---

content/get-involved.md
content/registry/collector-exporter-elastic.md

* https://github.com/open-telemetry/opentelemetry.io/pull/183 added a new `language` attribute to the registry cards. This PR updates the documentation in `get-involved.md` to include this new attribute.
* Elastic exporter: Renames the exporter, links to documentation, and adds a `language`. Similar changes have been proposed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/483.

Update Elastic exporter and get-involved.md

---

content/registry/instrumentation-go-gocql.md

Addresses: [#91](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/91)
This PR adds the [gocql integration](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/github.com/gocql/gocql) to the opentelemetry registry.

chore: add gocql to opentelemetry registry

---

content/registry/instrumentation-go-sarama.md

Split from https://github.com/open-telemetry/opentelemetry-go-contrib/issues/87.
Add the Golang [instrumentation](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/github.com/Shopify/sarama) for Kafka to the opentelemetry registry.

Add Golang instrumentation for Kafka

---

content/docs/collector/about.md

I noticed this while trying it out. `go build examples/main.go` creates a binary called `main` in the folder the command is executed.

Fix the example script for local environment

---

content/registry/instrumentation-go-gomemcache.md
content/registry/instrumentation-go-grpc.md
content/registry/instrumentation-go-net-http.md
content/registry/instrumentation-go-runtime.md

The memcache instrumentation is new.
The others were relocated from the opentelemetry-go repo to the opentelemetry-go-contrib repo.

Adding new and relocated instrumentation plugins for Go contrib repo

---

content/registry/instrumentation-go-beego.md

This PR adds the `github.com/astaxie/beego` instrumentation to the opentelemetry.io registry

fix: add beego instrumentation to registry

---

layouts/partials/home/beta.html

It seems we've missed this during OTel .NET beta, trying to fix it now.

Add .NET to the beta list

---

content/docs/collector/configuration.md

Using url causes error, the exporters README suggests
that both now use endpoint

Zipkin and Jaeger exporters now use endpoint

---

content/registry/collector-exporter-elastic.md

I made some changes to the Elastic exporter registry card in https://github.com/open-telemetry/opentelemetry.io/pull/224. I had assumed that markdown links would render in the [body content](https://opentelemetry.io/registry/collector-exporter-elastic/), but it turns out that they do not. This PR removes the link. Sorry for the mistake!

docs: Remove link from Elastic exporter

---

content/registry/exporter-ruby-datadog.md

Adds [dd-opentelemetry-exporter-ruby](https://github.com/DataDog/dd-opentelemetry-exporter-ruby) to the registry.
closes: https://github.com/DataDog/dd-opentelemetry-exporter-ruby/issues/7

Add Datadog Ruby Exporter to registry

---

content/registry/exporter-js-datadog.md

Adds [dd-opentelemetry-exporter-js](https://github.com/DataDog/dd-opentelemetry-exporter-js) to the registry.
followup from the conversation and work here: https://github.com/open-telemetry/opentelemetry-js/pull/1316

Add Datadog JS Exporter to registry

---

content/registry/exporter-dotnet-honeycomb.md

Adds a .NET Honeycomb exporter created by community member @martinjt.
The exporter currently uses an older version of the .NET OTel SDK but is planned to be updated.

Add .NET Honeycomb exporter

---

content/registry/exporter-js-honeycomb.md

Adds a NodeJS Honeycomb exporter.
The exporter currently uses an older version of the OTel SDK but is planned to be updated.

Add nodejs Honeycomb exporter

---

content/registry/collector-builder.md
content/registry/instrumentation-python-opentracing-shim.md

This PR adds the OpenTelemetry Collector builder to the registry. 
It also fixes a minor issue, where the "instrumentation" option in the filter was duplicate due to a capitalization inconsistency.
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Added OpenTelemetry Collector builder to the registry

---

content/project-status.md

I saw that the current state was wrong on the website. In the section above it is properly set:
> OpenTelemetry implementations are currently in **beta** status. This page tracks the overall release milestones as we move towards full releases for each language SIG. You can find more details about the milestones at [this link](https://github.com/open-telemetry/opentelemetry-specification/milestones).

Current state alpha -> beta

---

content/en/registry/exporter-dotnet-honeycomb.md

Honeycomb has now adopted the community project. This changes updates the github repo, authors and OpenTelemtry version.

Update honeycomb .NET exporter

---

content/en/docs/collector/about.md

jaeger-opentelemetry-collector has been archived, and the link to jaeger within the archived repo is broken anyway.

Update link to Jaeger

---

content/en/_index.md

Main page at https://opentelemetry.io/ displays broken links to frameworks such as Spring or ASP.NET Core.

Fix broken URLs to compatible frameworks

---

content/en/docs/collector/about.md

The paths to `main.go` and `otel-config.yaml` have changed. This PR fixes the paths in the documentation.

Fix example paths

---

README.md
content/en/docs/collector/_index.md
content/en/docs/collector/about.md
content/en/docs/concepts/_index.md
content/en/docs/concepts/glossary.md
content/en/docs/concepts/overview.md
content/en/docs/contribution-guidelines.md
content/en/docs/workshop/_index.md

In an attempt to make it easier for people to understand what data
sources OpenTelemetry supports as well as the various components, I
added a concepts section (addresses #154). In addition, created a glossary within this
new section (addresses #193). The idea was to provide basic information
and link to authoritative resources as much as possible.
CREDIT: The information included pulls from the prior work of other
including:
- OpenTelemetry READMEs
- OpenCensus documentation
- Kubernetes documentation structure

Add concepts section

---

content/en/registry/instrumentation-python-aio-httpclient.md
content/en/registry/instrumentation-python-asgi.md
content/en/registry/instrumentation-python-asyncpg.md
content/en/registry/instrumentation-python-boto.md
content/en/registry/instrumentation-python-botocore.md
content/en/registry/instrumentation-python-celery.md
content/en/registry/instrumentation-python-dbapi.md
content/en/registry/instrumentation-python-django.md
content/en/registry/instrumentation-python-elasticsearch.md
content/en/registry/instrumentation-python-flask.md
content/en/registry/instrumentation-python-grpc.md
content/en/registry/instrumentation-python-jinja2.md
content/en/registry/instrumentation-python-mysql.md
content/en/registry/instrumentation-python-psycopg2.md
content/en/registry/instrumentation-python-pymemcache.md
content/en/registry/instrumentation-python-pymongo.md
content/en/registry/instrumentation-python-pymysql.md
content/en/registry/instrumentation-python-pyramid.md
content/en/registry/instrumentation-python-redis.md
content/en/registry/instrumentation-python-requests.md
content/en/registry/instrumentation-python-sqlalchemy.md
content/en/registry/instrumentation-python-sqlite3.md
content/en/registry/instrumentation-python-starlette.md
content/en/registry/instrumentation-python-system-metrics.md
content/en/registry/instrumentation-python-wsgi.md

Python instrumentation packages have been moved from core repo to contrib repo.

Fix dead links

---

content/en/docs/collector/_index.md
content/en/docs/go/_index.md
content/en/docs/java/_index.md
content/en/docs/net/_index.md
content/en/docs/python/_index.md
content/en/docs/workshop/_index.md

Each language entry has weight 10 so that they are sorted in
alphabetical order. Concepts is weight 1 so it comes first and
other entries to come after each language, like collector and
workshops get a multiple of 10 weight.
Before this change `.Net` was the first entry on the docs page sidebar, now it is `Concepts`.

make concepts come first in the docs page sidebar

---

content/en/registry/exporter-python-newrelic.md

Adds [newrelic/opentelemetry-exporter-python](https://github.com/newrelic/opentelemetry-exporter-python) to registry.

Add New Relic Python exporter to registry

---

content/en/_index.md

This would allow the link to redirect to the language which the user prefers.

Remove en-us from aspnetcore link

---

content/en/registry/sdk-extension-python-aws.md

Adds a reference to the python package which allows OpenTelemetry Python users to configure the generation of traces to be compatible for the AWS X-Ray service.

Add AWS SDK Extension package to registry

---

CONTRIBUTING.md
content/en/registry/otel-java-instrumentation-newrelic.md

Adds the highlighted New Relic Java Agent Distro project to registry
Which redirects to this project: https://github.com/newrelic/newrelic-opentelemetry-integration-java

Add New Relic Java Agent Distro to registry. Fix typo.

---

assets/scss/main.scss

1. found the problem.
reproduce this problem by the following URL:
- https://opentelemetry.io/about/#what-is-an-observability-framework
- https://opentelemetry.io/community/#opentelemetryio
2. found CSS code has handled this problem, btw not working.
3. fount the `h2` parent `section` used `display: flex`, make old logic not working.
4. use CSS `scroll-margin-top: {header-heigh}` to fix it :)

use css `scroll-margin-top` to offsetting an html anchor to adjust for fixed header 

---

layouts/registry/list.html
src/js/registrySearch.js

for example, a freshman needs to search a JAVA AWS OTel SDK, maybe follow this step:
1. select language to `java`.
2. input search query: `aws` 
3. bomb. return a list with `aws`, not include `java` (because we don't persistent selected language/component)
add two hide input, when form submit. will take language/component value.
when language/component value changed, update input value and urlParams

registry page: persistent value from filter language/component filter

---

content/en/vendors/_index.md

Update the vendors supporting OpenTelemetry page to include New Relic.
You can learn more about our OpenTelemetry offering [here](https://newrelic.com/solutions/opentelemetry).

Update vendors to include New Relic

---

content/en/vendors/_index.md

Honeycomb now supports OTLP ingest directly, so adding to the vendor list.

[vendors] Add honeycomb to vendors

---

content/en/vendors/_index.md

F5 has been investing in OpenTelemetry. We have created the F5 Cloud exporter which utilizes OTLP (found in the the Otel Collector Contrib repository), contributing community projects such as the Loki Exporter, and participating in multiple SIGs. We plan to increase our contributions and further evangelize OpenTelemetry via articles, presentations, and other mediums.

Added F5 to vendor page

---

content/en/vendors/_index.md

Just fixing the position of F5 which was added in #368. Sorry for missing the "Vendors are listed alphabetically".

Fixed F5 position to be listed alphabetically

---

content/en/registry/instrumentation-js-aws-sdk.md
content/en/registry/instrumentation-js-kafkajs.md
content/en/registry/instrumentation-js-sequelize.md
content/en/registry/instrumentation-js-typeorm.md

The following MD files have been updated:
js-kafkajs, js-aws-sdk, js-sequelize, js-typeorm
Also, removed otVersion as I saw it is not visible anywhere and that other instrumentations don't seem to do it anymore.

Update broken links in 4 instrumentations MD files

---

CONTRIBUTING.md
Makefile

Clean up targets and add a test target

Refactor Makefile

---

content/en/registry/instrumentation-js-aws-sdk.md
content/en/registry/instrumentation-js-kafkajs.md
content/en/registry/instrumentation-js-mongoose-instrumentation.md
content/en/registry/instrumentation-js-sequelize.md
content/en/registry/instrumentation-js-typeorm.md

In our (Aspecto) extensions [repo](https://github.com/aspecto-io/opentelemetry-ext-js) we updated our plugins to the new [instrumentation API](https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-instrumentation).  
As part of this change, the term "plugin" changes, this PR is updating the term where needed.  
We also created a new mongoose instrumentation, that contains bug fixes to the original plugin, as well follows the semantic conventions (as opposed to the previous plugin) and uses the new API, so that's added in this PR as well.

registry update plugins to instrumentation

---

assets/scss/main.scss

resolved #384 
1. all a/link use the same color
2. remove hover color change, used underline
before
now

improve link css 

---

content/en/vendors/_index.md

Sumo Logic now accepts OTLP/HTTP traces and I believe the status for Native OTLP support can be now updated

Update Sumo Logic OTLP support status

---

content/en/registry/collector-exporter-aws-prometheus-remote-write.md

Added AWS Prometheus Remote Write collector exporter to the registry

Added AWS Prometheus Remote Write collector exporter to the registry

---

CONTRIBUTING.md

OS X users unfamiliar with Hugo may waste a little time on the file descriptor issue: I've added a pointer here to save them some time.

Improve docs around running the site locally.

---

content/en/docs/collector/configuration.md

I was pretty confused trying to navigate the documentation, especially when there was so much code snippets that looked alike, until I realized the links here were broken (didn't take me anywhere): 
Currently:
1. The links in the ToC to these sections are broken (unclickable)
2. The permalink for these sections is actually: `https://opentelemetry.io/docs/collector/configuration/#a-namereceiversaimg-width35-srchttpsrawgithubcomopen-telemetryopentelemetryiomainiconography32x32receiverssvgimg-receivers`
I figured moving the icon down was the easiest way to fix them.

Move icon below heading to fix links and toc

---

content/en/docs/java/automatic_instrumentation.md

Fix syntax for %X{trace_id} / %X{span_id} + add trace_flags to match https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/logger-mdc-instrumentation.md#logger-mdc-auto-instrumentation

Fix syntax for trace_id/span_id injection example

---

content/en/docs/js/getting_started/browser.md

- changed `plugin` to `instrumentation`
- modernized API (basically simplified https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/examples/)
- some typos
- simplified console output reference

improv: modernize browser example

---

content/en/registry/instrumentation-js-sequelize.md

instrumentation-js-sequelize.md incorrectly links to mongoose repo

Fix sequelize repo link

---

content/en/docs/concepts/data-sources.md

Seems that the #metric anchor in the URL is an outdated one and the new one should be #metric-signal

Fix URL anchor to #metric-signal

---

content/en/docs/net/_index.md
content/en/docs/python/_index.md

The above PR resolves #520 and updates the status of tracing for .NET and Python

Updated release trace versions for .NET 

---

content/en/docs/concepts/data-sources.md

Seems that the #log anchor in the URL is an outdated one and the new one should be #log-signal

Fix URL anchor to #log-signal

---

content/en/docs/concepts/data-sources.md

Seems that the #distributed-tracing anchor in the URL is an outdated one and the new one should be #trace-signal

Fix URL anchor to #trace-signal

---

CONTRIBUTING.md
content/en/docs/contribution-guidelines.md

An attempt to resolve #544. I aimed for over-explaining.
Note that I use sentence-level line breaks instead of hard wraps at column 80. I didn't see anything specifying which to use, but I can add hard wraps if we're striving for consistency there. (Admittedly, I prefer sentence-level or [semantic line breaks](https://sembr.org/) over hard wraps for markdown files.)

Update CONTRIBUTING.md and Contribution Guidelines to clarify docs mirroring

---

content/en/docs/concepts/glossary.md

The Metrics SDK Terminology link points to a non-existent page (sdk.md). This proposed change would link to the Metrics specification list for now, which shows that the Metrics SDK is not available yet. As soon as the SDK page is available and the metrics specification list gets updated, this link will still get people to the right place, and it could be updated later to link directly to the metrics SDK page once it exists.

Fix broken Metrics SDK terminology link

---

config.toml

Resolves https://github.com/open-telemetry/opentelemetry.io/issues/110 by providing easier access to the icon library on the website.

Added iconography and cncf branding page

---

content/en/releases/_index.md
content/en/status/_index.md

As part of our application for CNCF incubation, we need to have a high level status report available on our website. I've updated the status information on the Releases page to cover the necessary items, and renamed the the Releases page to "Status" for clarity.

Added high level project status report

---

content/en/vendors/_index.md

Dynatrace lately [announced](https://www.dynatrace.com/news/blog/the-dynatrace-open-aiops-platform-now-provides-enterprise-grade-observability-for-ingested-opentelemetry-traces/) support for native OTLP ingest.

Add capability for Dynatrace

---

content/en/docs/collector/getting-started.md

Linux mentioned in Windows section

fixing typo in getting-started doc

---

content/en/vendors/_index.md

The Dynatrace OneAgent serves as distro by picking up OpenTelemetry traces without the need for explicit configuration.

Update vendors page

---

static/schemas/1.4.0

As described in https://github.com/open-telemetry/opentelemetry.io/issues/577
this adds the first schema file. This should publish the file at
https://opentelemetry.io/schemas/1.4.0
Merge this PR after specification 1.4.0 is released.
We will automate the addition of future schemas later.

Publish OpenTelemetry Schema File 1.4.0

---

content/en/docs/collector/configuration.md
content/en/docs/collector/custom-auth.md
content/en/registry/collector-extension-auth-bearertokenauthextension.md
content/en/registry/collector-extension-auth-oauth2clientcredentials.md
content/en/registry/collector-extension-auth-oidc.md

Please, do not merge until https://github.com/open-telemetry/opentelemetry-collector/pull/3369 is merged.
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Add documentation about auth for the collector

---

content/en/docs/collector/configuration.md

Since https://github.com/open-telemetry/opentelemetry-collector/pull/2311, 'swap' is known as 'paging'.

Fix name of scraper in hostmetrics config

---

content/en/vendors/_index.md

Honeycomb now has OTel distributions. Changing docs link to the "Getting data in" page in the Honeycomb docs site which has links for various languages.

Update vendors - Honeycomb now has Distributions

---

content/en/registry/instrumentation-python-system-metrics.md

System metrics were moved to a separate branch in https://github.com/open-telemetry/opentelemetry-python-contrib/pull/312, this PR just updates the URL to point to that branch.
Skimmed through the discussions in the PR and related issues, change seems to have been made because the system metrics instrumentation is experimental and will be added back to the main branch once it is ready for release, so should the references to system metrics be removed entirely instead?

Update repo url for python system metrics

---

content/en/registry/tools-browser-extension-autoinjection.md

A browser extension to inject OpenTelemetry into websites was recently added to the opentelemetry-contrib-js repo, would be great to have it also in the registry. (see https://github.com/open-telemetry/opentelemetry-js-contrib/pull/498)

Add registry entry for OTel Browser Extension Autoinjection

---

content/en/docs/go/getting-started.md

While stepping through the getting started guide I ran into an issue. After a bit of poking around it appears the API recently changed.
See https://github.com/open-telemetry/opentelemetry.io/issues/616

Updated for global.SetMeterProvider() API change

---

content/en/docs/collector/configuration.md

The extension name for  OAuth2 authenticator  is `oauth2client`. Corrected it from `oauth2clientcredentials`.
Reference: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oauth2clientauthextension

Corrrected the OAuth2 Extension name in the collector docs.

---

content/en/registry/instrumentation-js-winston.md

Noticed a small typo in one of the registry entries.

Fix a small typo in the description of Winston package (JS) in the registry

---

content/en/status/_index.md

Update the metrics API spec status once https://github.com/open-telemetry/opentelemetry-specification/pull/1833 is merged.

Update metrics spec status

---

content/en/docs/go/getting-started.md

The function definition of RecordBatch is as below.
```
// RecordBatch atomically records a batch of measurements.
func (m Meter) RecordBatch(ctx context.Context, ls []attribute.KeyValue, ms ...Measurement) {
if m.impl == nil {
return
}
m.impl.RecordBatch(ctx, ls, ms...)
}
```
This first parameter is missing in the caller.

Update docs: meter.RecordBatch is missing a parameter

---

layouts/partials/head-css.html
layouts/partials/scripts.html

A simple override of a couple of Docsy partials (replacing `.Site.IsServer` by `ne (getenv "HUGO_ENV") "production"`), so that it is easier to locally build a non-production version of the site, which in turn makes it easier to `git diff` the generated site files. Being able to diff generated site files provides a means to validate refactors and sanity-check most infrastructure updates.

Generate production CSS and JS in production environments only

---

.gitignore
Makefile

When testing locally, if you have `htmltest` in your path, that command will be used. Otherwise, a copy will be fetched.
Closes #546

Support use of local link checker

---

netlify.toml

Closes #636 (note that I need the features of more recent versions of Hugo to implement other changes to the site).
In comparing normalized versions of the generated site files (ignoring modified dates/times and other similar meta data), the only non-whitespace differences are in the following files:
- `/docs/collector/configuration/index.html`
- `/docs/erlang/getting-started/index.html`
- `/docs/erlang/instrumentation/index.html`
- `/docs/js/instrumentation/index.html`
The changes to these files are due to differences in code-highlighter inlined styles. For example, https://opentelemetry.io/docs/erlang/getting-started/#opentelemetry, changes from
> <img src=https://user-images.githubusercontent.com/4140793/129446123-a30a9e13-553a-4fcb-8fe9-2e1d5d526a1e.png width=400>
to
> <img …

Upgrade to Hugo 0.87.0

---

package.json

Closes #678
As noted in the docsy docs (https://www.docsy.dev/docs/getting-started/#install-postcss), we also need to add `postcss` as a dependency when upgrading to `postcss-cli` v8.

Upgrade to postcss-cli, add postcss package too

---

layouts/partials/page-meta-links.html

Contributes to #542
/cc @carlosalberto @mtwo @shelbyspees
As mentioned in the file, this is a Docsy file override. Here is the diff:
```console
$ diff {themes/docsy/,}layouts/partials/page-meta-links.html
0a1
> {{/* otel-docsy file override */ -}}
16a18
> {{ $gh_repo_path = replace $gh_repo_path ($.Param "path_base_for_github_subdir") "" -}}
```

Support GH links to canonical src in lang repo

---

static/schemas/1.6.0
static/schemas/1.6.1

Also retire the broken 1.6.0 schema.

Publish OpenTelemetry Schema File 1.6.1

---

.gitmodules
config.toml
static/schemas/1.4.0
static/schemas/1.5.0
static/schemas/1.6.1

- Closes #709
- I've checked that this **generates the same site files**, plus `schemas/1.6.0`, because that schema hasn't been deleted yet from `opentelemetry-specification` -- pending the merge of this PR, https://github.com/open-telemetry/opentelemetry-specification/pull/1910.
Preview checks:
- https://deploy-preview-715--opentelemetry.netlify.app/schemas/1.4.0
- https://deploy-preview-715--opentelemetry.netlify.app/schemas/1.5.0
- https://deploy-preview-715--opentelemetry.netlify.app/schemas/1.6.1
/cc @carlosalberto @tigrannajaryan

Serve OTel schemas from opentelemetry-specification submodule

---

content/en/registry/collector-exporter-file.md
content/en/registry/collector-exporter-jaeger.md
content/en/registry/collector-exporter-kafka.md
content/en/registry/collector-exporter-opencensus.md
content/en/registry/collector-exporter-prometheus-remote-write.md
content/en/registry/collector-exporter-prometheus.md
content/en/registry/collector-exporter-zipkin.md
content/en/registry/collector-extension-auth-bearertokenauthextension.md
content/en/registry/collector-extension-auth-oauth2clientcredentials.md
content/en/registry/collector-extension-auth-oidc.md
content/en/registry/collector-extension-fluentbit-subprocess.md
content/en/registry/collector-extension-healthcheck.md
content/en/registry/collector-extension-pprof.md
content/en/registry/collector-processor-attributes.md
content/en/registry/collector-processor-filter.md
content/en/registry/collector-processor-probablisistic-sampling.md
content/en/registry/collector-processor-resource.md
content/en/registry/collector-processor-span.md
content/en/registry/collector-receiver-fluent-forward.md
content/en/registry/collector-receiver-jaeger.md
content/en/registry/collector-receiver-kafka.md
content/en/registry/collector-receiver-opencensus.md
content/en/registry/collector-receiver-prometheus.md
content/en/registry/collector-receiver-zipkin.md
content/en/registry/exporter-go-kafka.md
content/en/registry/exporter-go-prometheus.md

Resolve docs: broken links in registry #717

Fix repo links for registry components moved from core to contrib

---

content/en/docs/concepts/glossary.md

That page clearly existed once, and doesn't now.
I replaced the ones I could find, and removed the link for "resource" since I can't find a good definition of that in the docs anymore.
Addresses #627

Fix or remove broken links to concepts/overview

---

content/en/docs/js/_index.md

- Closes #720
- Effectively reverts the `cascade` added by https://github.com/open-telemetry/opentelemetry-js/pull/2421
Preview: https://deploy-preview-733--opentelemetry.netlify.app/docs/js/

JS: make GH page links refer to this repo

---

.htmltest.yml
Makefile
package.json

- Support checking internal _and_ external links
- Don't fetch a copy of the link checker if we previously did and the copy is still available.
Note: we'll want to wait until the next release of htmltest (> 0.14.0) before checking external links. So we're waiting on https://github.com/wjdp/htmltest/discussions/174.

CI: link checking improvements & ext link checking

---

content/en/docs/collector/configuration.md
content/en/docs/collector/custom-auth.md

- I reapplied #605, resolved conflicts. The files in this PR are what is left. (I.e., notice that the registry files were not affected by #649).
- Closes #673
- Preview:
- https://deploy-preview-734--opentelemetry.netlify.app/docs/collector/configuration/#authentication
- https://deploy-preview-734--opentelemetry.netlify.app/docs/collector/custom-auth/
/cc @jpkrohling

Recovered collector authentication docs

---

assets/scss/_styles_project.scss
config.toml
content/en/_index.md
layouts/_default/baseof.html
layouts/partials/announcement.html
layouts/partials/banner.html
layouts/partials/banner.md

- Closes #757 
- This moves the banner to be under the topnav, which IMHO makes it much more visibile.
- I still have to strip out the code mods from `src/js/base.js`, but I'll do that in a followup PR.
Preview: https://deploy-preview-758--opentelemetry.netlify.app/
---
Mobile:
Desktop:

Fix banner on mobile

---

assets/scss/_styles_project.scss
src/js/base.js

- Followup to #758, and so also contributes to #757
- This PR effectively undoes the changes introduced by:
- #377
- #413
- The "Bootstrap Fixed Header" code in `base.js` has been reverted to match Docsy
With the CSS changes in this PR, the homepage top nav has the same appearance and behaves the same as for any other site pages:
> ![image](https://user-images.githubusercontent.com/4140793/134333671-495e9447-4117-4015-9d4a-56c9406ed9ad.png)

Homepage top nav: always use std bg color

---

layouts/registry/list.html

- Closes #726 
- Prep work for #744
- No change to generated site files in production mode, except that `registrySearch.js` will now be minified
Preview: https://deploy-preview-774--opentelemetry.netlify.app/registry/

fingerprinted registrySearch.js in production mode only

---

content/en/vendors/_index.md

New Relic now supports native OTLP.
cc: @alanwest @nrcventura

Update New Relic native OTLP status

---

content/en/docs/concepts/data-sources.md

- Only use code font for API element names, otherwise use bold on first use of a term.
- Add "for more info" to new Baggage section
- Followup to #740

Concepts > Data sources: copyedits

---

CONTRIBUTING.md
netlify.toml
package.json

I'm having some strange site-generation issues with the current version of Hugo. The latest version seems to be fine.
This PR switches to using the very convenient [hugo-extended](https://www.npmjs.com/package/hugo-extended) NPM package to fetch the proper version of Hugo. This makes is easier for contributors -- who will no longer need to separately install Hugo.

Upgrade to Hugo 0.88.1 via NPM

---

content/en/docs/erlang/_index.md
content/en/docs/erlang/getting-started.md
content/en/docs/erlang/instrumentation.md

Closes #802
Preview:
- https://deploy-preview-803--opentelemetry.netlify.app/docs/erlang/getting-started/
- https://deploy-preview-803--opentelemetry.netlify.app/docs/erlang/instrumentation/
---
This fixes the table of contents for each of these pages. For example, for the *Getting started** page, it now looks like this:
> <img src="https://user-images.githubusercontent.com/4140793/135680542-dc487c7c-9972-4e79-a17b-c73ad9f6593b.png" width=200>
This is what the TOC looked like before:
> <img src="https://user-images.githubusercontent.com/4140793/135680621-0cebad58-e035-47fd-9aba-7af9ede94420.png" width=200>

Erlang: fix heading levels

---

content/en/docs/collector/getting-started.md

- The [current collector MSI package(0.38.0)](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.38.0/otel-contrib-collector-0.38.0-amd64.msi) will automatically start the service

[docs] update Collector Windows Packaging

---

.gitignore
assets/scss/_styles_project.scss
package.json

Hugo 0.89.x has updates to Goldmark and Chroma, which cleans up issues like https://github.com/gohugoio/hugo/issues/8532.
This upgrade introduces only two generated-site-file diffs (aside from the Hugo version update):
```console
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0.8" -- . ':(exclude)*.xml') | grep -e ^diff
diff --git a/docs/js/instrumentation/index.html b/docs/js/instrumentation/index.html
diff --git a/index.html b/index.html
```
Here's the diff:
```diff
diff --git a/docs/js/instrumentation/index.html b/docs/js/instrumentation/index.html
index 7c13015c..51082441 100644
--- a/docs/js/instrumentation/index.html
+++ b/docs/js/instrumentation/index.html
@@ -642,7 +642,7 @@ If you do not register a global tracer provider, instrumentation which calls the
<span …
```

Upgrade packages including hugo-extended

---

.htmltest.yml
layouts/registry/list.html

- Drop unnecessary and invalid `href="#"` attributes
- Trim unnecessary trailing whitespace
- Entry links now use `target="_blank"`
- No change in the registry's functionality 
Preview: https://deploy-preview-893--opentelemetry.netlify.app/registry/

Registry: fix links + cleanup

---

content/en/docs/contribution-guidelines.md

- Contributes to
- #895
- #770
- Delists the [Contribution page](https://opentelemetry.io/docs/contribution-guidelines/) from the sidenav as part of the sidenav cleanup (pre-IA rework)
- The Contribution page remains accessible, as it was before, from the [community page](https://opentelemetry.io/community/)
Previews:
- https://deploy-preview-894--opentelemetry.netlify.app/docs/
- https://deploy-preview-894--opentelemetry.netlify.app/docs/contribution-guidelines/
Note that the Contribution page itself needs rework, but that will be handled separately.

Only show link to contrib page from Community

---

content/en/registry/exporter-cpp-etw.md
content/en/registry/exporter-cpp-fluentd.md
content/en/registry/exporter-cpp-jaeger.md
content/en/registry/exporter-cpp-otlp.md
content/en/registry/exporter-cpp-zipkin.md
content/en/registry/instrumentation-cpp-httpd.md
content/en/registry/instrumentation-cpp-nginx.md

Preview: https://deploy-preview-892--opentelemetry.netlify.app/registry/?s=&component=all&language=cpp#

Add exporters & instrumentation for otel-cpp to registry.

---

content/en/docs/collector/configuration.md

As per the issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5377, the example configuration is out dated as `insecure` is now under the `tls` node.

update the otlp exporter configuration

---

content/en/status/_index.md
layouts/shortcodes/release_notes.html

- As illustrated in #545, release details are misformatted (they're shown in code-font). While it is possible to process the release details as markdown, I don't think that it is worth it (and it doesn't look good) because to access the details, all the reader has to do is click on the release tag link.
- Closes #545 by dropping the release details. Instead we just list the components and link to their latest releases
Preview: https://deploy-preview-902--opentelemetry.netlify.app/status/#latest-releases
Before:
> ![image](https://user-images.githubusercontent.com/4140793/141288765-834c754f-dadb-44ec-b1d6-02085c70562f.png)
After:
> <img width="400" alt="LR" src="https://user-images.githubusercontent.com/4140793/141289187-7cff0643-b3bf-47cb-9d04-aa4cf501e580.png">

Status page: drop release details

---

content/en/registry/instrumentation-js-aws-sdk.md

Updated node `aws-sdk` instrumentation repo URL to OTEL contrib.
Related PR: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/678

chore: update node aws-sdk repo url

---

scripts/adjust-spec-pages.pl

This PR fixes:
- The 3 links to semantic conventions in https://deploy-preview-909--opentelemetry.netlify.app/docs/reference/specification/overview/#semantic-conventions
- In https://deploy-preview-909--opentelemetry.netlify.app/docs/reference/specification/vendors/, we now link to the local spec

adjust-spec-pages.pl: fix sem. conv. rule

---

content/en/docs/collector/getting-started.md

It looks like the Collector releases have been moved to the opentelemetry-collector-releases repo - this just updates the URL's to point to the new scheme.

Update Collector download URL's

---

content/en/docs/collector/_index.md
content/en/docs/cpp/_index.md
content/en/docs/erlang/_index.md
content/en/docs/js/_index.md
content/en/docs/net/_index.md
content/en/docs/rust/_index.md
content/en/docs/swift/_index.md
layouts/shortcodes/latest_release.md

Contributes to #905
Preview:
- https://deploy-preview-930--opentelemetry.netlify.app/docs/cpp
- https://deploy-preview-930--opentelemetry.netlify.app/docs/erlang
- https://deploy-preview-930--opentelemetry.netlify.app/docs/js
- https://deploy-preview-930--opentelemetry.netlify.app/docs/net
- https://deploy-preview-930--opentelemetry.netlify.app/docs/rust
- https://deploy-preview-930--opentelemetry.netlify.app/docs/swift

Link to latest release for all SIGs (non-submodule)

---

CONTRIBUTING.md
README.md

- Updated dev setup instructions. Also link to Gitpod.
- Replace "mirroring" section by current info.
Preview:
- https://github.com/chalin/opentelemetry.io/blob/chalin-dev-doc-updates-2021-11-17/CONTRIBUTING.md
- https://github.com/chalin/opentelemetry.io/blob/chalin-dev-doc-updates-2021-11-17/README.md

Contributing: setup instruction update, and more

---

content/en/vendors/_index.md

Adding Datadog to the entry list https://opentelemetry.io/vendors/
The exporter being already available in the repository https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter.
Checked the file renders okay and ran the test according to the Contributing Guidelines:
```
✔✔✔ passed in 379.079277ms
tested 485 documents
```

Adding Datadog as an opentelemetry provider in the documentation

---

package.json

No change in generated site files:
```console
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0.8")
$
```

Hugo 0.89.4 upgrade

---

.vscode/cspell.json
content/en/status/_index.md

- Closes #764
- Contributes to #948
- Other than the added link to the Metrics spec page, this PR introduces no other change -- in particular, statuses are **not** updated. That will be addressed separately.
https://deploy-preview-951--opentelemetry.netlify.app/status

Status page markdown rework

---

content/en/docs/collector/getting-started.md

fixes https://github.com/open-telemetry/opentelemetry.io/issues/741 (perhaps Collector releases can change back to including MSI packaging and/or archive with `.zip` but I think it's better to just be accurate for now)and gets an up to date version number.
Preview: https://deploy-preview-954--opentelemetry.netlify.app/docs/collector/getting-started/#linux-packaging

Update linux and windows packaging in collector get started page

---

content/en/docs/collector/getting-started.md

`otelcol` is not longer available as a Make target in the collector repo: https://github.com/open-telemetry/opentelemetry-collector/issues/3928

Replace obsolete Make target for building collector

---

content/en/docs/concepts/glossary.md

The Client-Side SIG is working on updates to the spec to distinguish client-side telemetry. We would like to add the term `Client-side` to the glossary, so that it is clear what it refers to and how it is distinguished from services.

Add Client-side apps to glossary

---

content/en/status/_index.md
layouts/shortcodes/spec_status.html

- Contributes to #952
- Closes #916
- Closes #874
- Note that #873 remains open because I don't know where to read the status from in the spec.
**Preview**: https://deploy-preview-959--opentelemetry.netlify.app/status
---
Here's the diff of the generated HTML (without the label links to the spec pages):
```diff
diff --git a/status/index.html b/status/index.html
index 2423f5d6..2d3db555 100644
--- a/status/index.html
+++ b/status/index.html
@@ -180,7 +180,7 @@ All instrumentation shares the same semantic conventions, to ensure that they pr
<p>Checking the current status for each client in the README of its <a href="https://github.com/open-telemetry">github repo</a> is recommended. Client support for specific features can be found in the <a …
```

Status page: use shortcode to automatically get statuses from spec

---

content/en/status/_index.md

According to @tigrannajaryan, https://github.com/open-telemetry/opentelemetry-specification/pull/2151#discussion_r755590307:
> We should be able to assume that "Traces" includes `collector/trace` as well ... since they alway are changes in a lockstep.
This PR adds a note to that effect, and removes the **Collector** entires.
Closes #873
Closes #952
Preview: https://deploy-preview-969--opentelemetry.netlify.app/status

Drop Collector status since it's the same as Protocol status

---

content/en/docs/instrumentation/js/exporters.md

fixes https://github.com/open-telemetry/opentelemetry.io/issues/703
I suppose this doesn't tell you how to send metrics data to a collector, so I'm happy to figure that out and do it too if it's needed, but since metrics are still in development I wonder if it's better to just hold off until they stabilize in the SDK.

Provide JS instructions to send traces to a collector

---

content/en/registry/instrumentation-ruby-aws-sdk.md

Because https://github.com/open-telemetry/opentelemetry-ruby/pull/1014 was merged, we can update our registry!

Add entry for Ruby AWS SDK Instrumentation

---

package.json

Closes #982
```console 
$ npm i -D --save-exact hugo-extended@latest
```
No significant changes to the generated site files other than updates to `js/tracing.js`:
```console
$ npm run check-links
...
> hugo --cleanDestinationDir -e dev -DFE
Start building sites … 
hugo v0.91.0-D1DC0E9A+extended darwin/amd64 BuildDate=2021-12-17T09:50:20Z VendorInfo=gohugoio
WARN 2021/12/17 10:14:32 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
...
========================================================================
✔✔✔ passed in 499.064305ms
tested 491 documents
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0.") | grep ^diff
diff --git a/js/tracing.js …
```

Upgrade to Hugo 0.91.0

---

content/en/docs/collector/_index.md
content/en/docs/collector/custom-auth.md
content/en/docs/collector/distributions.md
content/en/docs/concepts/distributions.md
content/en/registry/collector-builder.md

The tool now lives the in the collector repository.
Related: #965

Update the references to the Collector Builder.

---

content/en/docs/instrumentation/js/exporters.md
content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/js/instrumentation.md

Closes https://github.com/open-telemetry/opentelemetry.io/issues/980 now that Java manual TOCs are also gone

Remove manual TOCs in JS docs

---

assets/scss/_styles_project.scss

Also, taking advantage of a recent update, we now hide breadcrumbs that have only a single crumb (i.e., /docs).

Upgrade docsy to match upstream HEAD

---

content/en/docs/instrumentation/net/getting-started.md

This one's a total rewrite, but does re-use some concepts from the first one.
The existing doc has code that won't compile, and in general, is a bit heavy for getting started.
Instead, what I focused on was copy-pastable, modern .NET 6 (LTS release) samples. Concepts like acquiring a tracer (activitysource), starting a span (activity), wiring up an exporter, etc. can be covered in subsequent articles.
This would be considered a part of #1001
**Preview**: https://deploy-preview-1000--opentelemetry.netlify.app/docs/instrumentation/net/getting-started/

Rework the .NET quickstart with working samples

---

content/en/docs/instrumentation/net/getting-started.md
content/en/docs/instrumentation/net/manual.md

Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1001 (but really contributes to the implicit ".NET has no docs" issue).
Also contributes to:
https://github.com/open-telemetry/opentelemetry.io/issues/974
https://github.com/open-telemetry/opentelemetry.io/issues/973

Add manual instrumentation doc for .NET

---

content/en/docs/instrumentation/net/automatic.md
content/en/docs/instrumentation/net/getting-started.md

Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1001 and https://github.com/open-telemetry/opentelemetry.io/issues/972
Deploy preview: https://deploy-preview-1015--opentelemetry.netlify.app/

Add instrumentation libraries article for .NET

---

content/en/docs/instrumentation/net/exporters.md

Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1001
This closely follows the JS doc, which is fairly comprehensive.
Preview: https://deploy-preview-1022--opentelemetry.netlify.app/docs/instrumentation/net/exporters/

Add Exporters doc for .NET

---

package.json

Ran:
```console
$ npm i -D --save-exact hugo-extended@latest
```
The only significant diff is the Hugo version and changes to `tracing.js`, which seems ok:
```console
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0.") | grep ^diff    
diff --git a/js/tracing.js b/js/tracing.js
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0.") | head      
diff --git a/js/tracing.js b/js/tracing.js
index ac44c908..cc769388 100644
--- a/js/tracing.js
+++ b/js/tracing.js
@@ -132,11 +132,11 @@
// node_modules/@opentelemetry/api/build/esm/internal/global-utils.js
function registerGlobal(type, instance, diag3, allowOverride) {
-    var _a5;
+    var _a3;
```
Closes #1044

Update to Hugo 0.92.0

---

README.md
archetypes/blog.md

- README preview: https://github.com/chalin/opentelemetry.io/blob/chalin-blog-archetype-2022-01-20/README.md
Note that I'll revisit the Registry instructions in another PR, possibly creating a [Hugo archetype file] for that too.
[Hugo archetype file]: https://gohugo.io/content-management/archetypes

Blog archetype and "Add blog" instructions

---

content/en/registry/instrumentation-go-splunkbuntdb.md
content/en/registry/instrumentation-go-splunkchi.md
content/en/registry/instrumentation-go-splunkclient-go.md
content/en/registry/instrumentation-go-splunkdns.md
content/en/registry/instrumentation-go-splunkelastic.md
content/en/registry/instrumentation-go-splunkgorm.md
content/en/registry/instrumentation-go-splunkgraphql.md
content/en/registry/instrumentation-go-splunkhttp.md
content/en/registry/instrumentation-go-splunkhttprouter.md
content/en/registry/instrumentation-go-splunkkafka.md
content/en/registry/instrumentation-go-splunkleveldb.md
content/en/registry/instrumentation-go-splunkmysql.md
content/en/registry/instrumentation-go-splunkpgx.md
content/en/registry/instrumentation-go-splunkpq.md
content/en/registry/instrumentation-go-splunkredigo.md
content/en/registry/instrumentation-go-splunksql.md
content/en/registry/instrumentation-go-splunksqlx.md

Add listing for the following OTel Go instrumentation libraries:
- splunkbuntdb
- splunkchi
- splunkclient-go
- splunkdns
- splunkelastic
- splunkgorm
- splunkgraphql
- splunkhttp
- splunkhttprouter
- splunkkafka
- splunkleveldb
- splunkmysql
- splunkpgx
- splunkpq
- splunkredigo
- splunksql
- splunksqlx

Add Splunk OTel Go instrumentation in registry

---

.github/CODEOWNERS
README.md

- Contributes to #845, followup to #1062
- README preview: https://github.com/chalin/opentelemetry.io/blob/chalin-blog-approvers-2022-01-20/README.md

Add blog-approvers to README and CODEOWNERS

---

content/en/docs/instrumentation/java/_index.md

Reflects latest java [release](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.10.1).

Update java docs to point to 1.10.1 release

---

content/en/docs/concepts/instrumenting-library.md
content/en/docs/instrumentation/java/automatic.md
content/en/docs/instrumentation/java/examples.md
content/en/docs/instrumentation/java/manual.md
layouts/index.redirects

I think that when we merged in the Java docs (#1002), we forgot to adjust these (non-alias) redirects: https://github.com/open-telemetry/opentelemetry.io/blob/09822ce98ca88fc8b24b9254c9e4811a0ba7b95b/layouts/index.redirects#L8-L10
This PR:
- Fixes the redirects
- Contributes to #997
Preview:
- https://deploy-preview-1068--opentelemetry.netlify.app/docs/instrumentation/java/
- https://deploy-preview-1068--opentelemetry.netlify.app/docs/java/automatic_instrumentation
- https://deploy-preview-1068--opentelemetry.netlify.app/docs/instrumentation/java/automatic_instrumentation
- https://deploy-preview-1068--opentelemetry.netlify.app/docs/java/getting_started
- https://deploy-preview-1068--opentelemetry.netlify.app/docs/java/manual_instrumentation
- …

Java docs: fix redirects and rename files to use site convention

---

content/en/docs/instrumentation/net/automatic.md
content/en/docs/instrumentation/net/getting-started.md
content/en/docs/instrumentation/net/manual.md
content/en/docs/instrumentation/net/netframework.md
content/en/docs/instrumentation/net/shim.md

.NET docs are now more or less complete, but need to be cross-linked across one another. This _can_ help with SEO (at least my understanding circa 2019 this is true, that's a moving target I guess), and in general promotes a coherency I'd expect from technical docs.
Example preview: https://deploy-preview-1041--opentelemetry.netlify.app/docs/instrumentation/net/getting-started/#next-steps

Cross-link across .NET docs

---

content/en/docs/instrumentation/java/manual.md

This brings the Java docs up to par with JS docs in terms of documenting important concepts.

Add setting span status and recording exceptions for Java

---

content/en/docs/instrumentation/js/instrumentation.md

This was a bad example - we should not pre-set a span status.

Update span status code doc for JS

---

content/en/docs/instrumentation/js/getting-started/browser.md

Parcel will not bundle with esm-style imports unless it's script tag has the module type.

Update javascript web getting started example.

---

content/en/docs/migration/opentracing.md

First draft of OT migration guide. I still need to add a couple bits:
* further notes on compatibility edge cases
* links to language-specific OpenTelemetry Shim docs
But please review and let me know if this is generally a readable and actionable migration guide.
Contributes to #1037
Preview: https://deploy-preview-1083--opentelemetry.netlify.app/docs/migration/opentracing/

OpenTracing migration overview

---

content/en/docs/migration/opentracing.md

- This PR contains only markdown cleanup.
- There are no changes to the generated site files (other than the last-modified details of the page):
```console
$ npm run check-links
...
$ (cd public && git diff -b -w --ignore-blank-lines -I "dateModified|modified_time|<lastmod>|Last modified" -- . ':(exclude)*.xml')
$
```
Preview: https://deploy-preview-1089--opentelemetry.netlify.app/docs/migration/opentracing/

OT migration: markdown cleanup

---

content/en/docs/concepts/components.md

Fix typo: `simplier` -> `simpler`

Fix minor typo on Concepts > Components page

---

content/en/docs/instrumentation/python
content/en/docs/instrumentation/python/_index.md
content/en/docs/instrumentation/python/getting-started.md

- Contributes to #1109
- The pages are copied from the Python repo's `website_docs` folder (https://github.com/open-telemetry/opentelemetry-python/tree/main/website_docs).
- There are no changes in the generated site files, except for timestamps and the Git commit hash for the pages:
```console
$ (cd public && git diff -b -w --ignore-blank-lines -I "dateModified|modified_time" -- . ':(exclude)*.xml')
```
```diff
diff --git a/docs/instrumentation/python/getting-started/index.html b/docs/instrumentation/python/getting-started/index.html
index 1040be91..611e3063 100644
--- a/docs/instrumentation/python/getting-started/index.html
+++ b/docs/instrumentation/python/getting-started/index.html
@@ -1042,6 +1042,9 @@ with tracer.start_as_current_span(&quot;foo&quot;):
</code></pre>
+       <div …
```

Make Python doc pages local

---

content/en/docs/instrumentation/python/_index.md
content/en/docs/instrumentation/python/getting-started.md

- Followup to #1111 
- Remove page meta link field overrides
- Update **Getting Started** from a freshly generated version created with `content-modules/opentelemetry-python/scripts/generate_website_docs.sh` (https://github.com/open-telemetry/opentelemetry-python/blob/main/scripts/generate_website_docs.sh)
Preview: https://deploy-preview-1112--opentelemetry.netlify.app/docs/instrumentation/python/

Python page refresh and cleanup

---

content/en/docs/instrumentation/python/getting-started.md
layouts/shortcodes/code_block_from.md

- Contributes to #1109
- @open-telemetry/python-approvers: this PR adds a shortcode which can read code from a file, just like the RTD's `literalinclude` directive. **Is this something that you'd like**?
- Here's the diff in the page HTML, before and after this PR:
```diff
diff --git a/docs/instrumentation/python/getting-started/index.html b/docs/instrumentation/python/getting-started/index.html
index 8f9782e8..9772bf8b 100644
--- a/docs/instrumentation/python/getting-started/index.html
+++ b/docs/instrumentation/python/getting-started/index.html
@@ -782,7 +782,7 @@ represents an action within your application that you want to instrument, such a
or a database call. Once instrumented, you can extract helpful information such as
how long the action took. You can also add arbitrary …
```

Python Getting Started: read code from source files

---

content/en/docs/instrumentation/python/_index.md

- Contributes to #1109
- Moves various sections of [opentelemetry-python/docs/index.rst](https://github.com/open-telemetry/opentelemetry-python/blob/main/docs/index.rst) into the Python instrumentation landing page.
- The corresponding Python repo PR to remove the sections/pages is:
- https://github.com/open-telemetry/opentelemetry-python/pull/2453
Preview: https://deploy-preview-1116--opentelemetry.netlify.app/docs/instrumentation/python/
/cc @open-telemetry/python-approvers

Python: add installation instructions, refine status info, and more

---

scripts/adjust-spec-pages.pl

Contributes to #906
Site diff yields:
```console
$ (cd public && git diff -- . ':(exclude)*.xml') 
```
```diff
diff --git a/docs/reference/specification/overview/index.html b/docs/reference/specification/overview/index.html
index 480f62a6..6592fb21 100644
--- a/docs/reference/specification/overview/index.html
+++ b/docs/reference/specification/overview/index.html
@@ -19,8 +19,7 @@
<link rel="icon" type="image/png" href="/favicons/android-192x192.png" sizes="192x192">
<title>Overview | OpenTelemetry</title>
-<meta name="description" content="
-This document provides an overview of the OpenTelemetry project and defines important fundamental terms.
+<meta name="description" content="This document provides an overview of the OpenTelemetry project and defines important fundamental terms. …
```

adjust-spec-pages: match closing TOC tags exactly

---

content/en/blog/2022/v1.0-trio.md
content/en/blog/2022/welcome.md

- [Blog v1.0-trio: use new canonical_url convention](https://github.com/open-telemetry/opentelemetry.io/commit/13d51c95eb540a65e72b386eb7faba70cadbde68)
- [Make Welcome post the older than all old Medium posts](https://github.com/open-telemetry/opentelemetry.io/commit/75a42dfd87bae97295da76b637d41135db815647)
Preview: https://deploy-preview-1137--opentelemetry.netlify.app/blog/2022/

Blog: use new canonical_url convention and change date of Welcome post

---

archetypes/blog.md
archetypes/medium.md

- Also tweaks the default blog archetype
To use the Medium archetype run, e.g.:
```console
$ hugo new --kind medium content/en/blog/2021/otel-gc.md
```

Add blog archetype for old medium posts

---

layouts/shortcodes/code_block_from.md

- From #1120, incorporating @mic-max's changes. Thanks!
- Adding support for:
- `to` argument
- `show-file` boolean argument
- language-specific comment marker
- No change to generated site files.
Still keeping this as simple as possible, making incremental improvements as needed until I can port a more complete solution (from another project).

code_block_from: add support for C# and "to" argument

---

layouts/shortcodes/code_block_from.md

After rebasing and making use of the shortcode I realised that this should not be surrounded by quotations to be the actual Hugo templating boolean type. I assume that was the intention. 
If the intention was to make this a string for more flexibility of values, please close 👍

Change type of `show-file` to boolean

---

.gitignore
config.yaml
scripts/adjust-spec-pages.pl
scripts/cp-spec-pages.sh

- Contributes to #906
- Rather than place generated files under `contents`, we now use a mount point. This is much cleaner, since we never mix generated and version-controlled files in the same directories.
- In the process, I discovered that one link was wrong in `/docs/reference/specification/library-guidelines/` (see the diff below). This PR fixes the link. Other than that, there is no change to the generated site files:
```console
$ (cd public && git diff -- . ':(exclude)*.xml')            
```
```diff
diff --git a/docs/reference/specification/library-guidelines/index.html b/docs/reference/specification/library-guidelines/index.html
index 3f0f4801..d967e28f 100644
--- a/docs/reference/specification/library-guidelines/index.html
+++ …
```

Specification: rework of how the spec is generated, and link fix

---

content/en/docs/instrumentation/cpp/_index.md

Minor thing, the c++ logo is missing at https://opentelemetry.io/docs/instrumentation/cpp/

add c++ logo to instrumentation page

---

content/en/docs/concepts/distributions.md

While doing some research for creating a distribution of OpenTelemetry I was looking for guidelines for using logo, name and other collaterals. I expected to find something on the page about [Distributions](https://opentelemetry.io/docs/concepts/distributions/), so after finding them [here](https://github.com/open-telemetry/community/blob/main/marketing-guidelines.md), I thought it would be good to have them where I was looking for them.
Preview: https://deploy-preview-1150--opentelemetry.netlify.app/docs/concepts/distributions/#what-you-should-know-about-distributions

Add a note to 'Distributions' page to follow marketing and trademark guidelines

---

content/en/vendors/_index.md

- Contributes to #1170
- Contributes to #1172
- Note the change in title: the page now uses the title in the front matter:
- New title: Vendor support
- Old title: Vendors Supporting OpenTelemetry
Preview: https://deploy-preview-1171--opentelemetry.netlify.app/vendors/

Vendor page: use blocks shortcode and markdown instead of HTML

---

content/en/registry/_index.md

- Contributes to #1170
Preview: https://deploy-preview-1174--opentelemetry.netlify.app/registry/

Registry page: use blocks shortcode and markdown not HTML

---

content/en/integrations.md

- Contributes to #1170
- Contributes to #1172
- Note the change in title: the page now uses the title in the front matter/
Preview: https://deploy-preview-1176--opentelemetry.netlify.app/integrations/

Integrations page: use blocks shortcode and markdown instead of (invalid) HTML

---

netlify.toml

Fixes #976 
cc @chalin, please check my work on the redirect syntax here. I've added `docs.opentelemetry.io` to the netlify DNS.

add redirect from docs.opentelemetry.io -> /docs route

---

package.json

Update Hugo to [0.93.2](https://github.com/gohugoio/hugo/releases/tag/v0.93.2), which introduces support for:
- [code-block hooks](https://github.com/gohugoio/hugo/releases/tag/v0.93.0)
- [GoAT](https://github.com/bep/goat)
Changes to the generated site files are due to updates to the Chroma lexer, which impacts how HTML for code blocks is generated (as introduced by this PR, in particular, https://github.com/alecthomas/chroma/pull/571).
I've checked several of the changed HTML files and they look the same visually. For example, compare the first code block of these pages:
- https://opentelemetry.io/docs/reference/specification/metrics/api/
- https://deploy-preview-1186--opentelemetry.netlify.app/docs/reference/specification/metrics/api/

Update Hugo to 0.93.2, and other modules

---

content/en/registry/otel-clojure.md

[`clj-otel`](https://github.com/steffan-westcott/clj-otel) provides an idiomatic Clojure API by wrapping the OpenTelemetry implementation for Java.

Added `clj-otel`, a Clojure API for OpenTelemetry

---

i18n/en.toml
layouts/registry/list.html

- Effectively reverts #353 because that only hits a small subset of what would need to be addressed in a full i18n solution. We can revisit this once another language is added to the repo.
- There are no changes to the generated site files.

Registry form: use simple labels rather than i18n keys

---

content/en/_index.md

Given that Java instrumentation pages are not #1 according to recent analytics, this PR adds a Java CTA, which for now, links to the Java instrumentation landing page.
/cc @austinlparker @cartermp 
Preview: https://deploy-preview-1207--opentelemetry.netlify.app/
Screenshot (mobile):
> <img width="300" alt="image" src="https://user-images.githubusercontent.com/4140793/158393866-e6e6afc3-efe9-4fc6-9eef-eeae9836f77f.png">

Homepage: add Java CTA

---

content/en/docs/collector/configuration.md

According to the [Readme of the Authenticator - OAuth2 Client Credentials in the opentelemetry-collector-contrib repo](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.46.0/extension/oauth2clientauthextension) the extension is named `oauth2client` and not `oauth2clientcredentials`.

replace oauth2clientcredentials with oauth2client

---

content/en/docs/concepts/instrumenting-library.md

- Closes #1202, but also make a copy editing pass over that section
Preview: https://deploy-preview-1208--opentelemetry.netlify.app/docs/concepts/instrumenting-library/#events

Concepts > Instr libs: copyedits

---

content/en/docs/instrumentation/java/examples.md
content/en/docs/instrumentation/java/manual.md

The fully-functional example link is only referred in the [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java#getting-started) repository, feel it might be good to show the example link here as well. 
---
Preview: https://deploy-preview-1203--opentelemetry.netlify.app/docs/instrumentation/java/manual/

Java docs: add link to fully functional example

---

content/en/blog/2022/troubleshooting-nodejs.md
content/en/docs/instrumentation/_index.md
content/en/docs/instrumentation/js/_index.md
content/en/docs/instrumentation/js/getting-started/_index.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/js/instrumentation.md
content/en/docs/migration/opentracing.md

Let's settle on the official name used on https://nodejs.org, which is **Node.js**.
Preview, e.g.: https://deploy-preview-1220--opentelemetry.netlify.app/docs/instrumentation/

Settle on Node.js name, and use it consistently

---

content/en/_index.md

As per #799 this PR removes the beta statement from the website. I didn't link to the vendors/adopters since this is called out directly below (OpenTelemetry is adopted and supported by **industry leaders**)

Remove beta statement from index

---

content/en/docs/instrumentation/java/automatic/_index.md
content/en/docs/instrumentation/java/automatic/annotations.md
content/en/docs/instrumentation/java/getting-started.md

- This PR creates an **Automatic** section, in preparation for
- #1229
It was originally proposed in #1178 -- though we now have a firmer case to do so with #1229 :).
- No change in content, other than adjusting page links (and adding an alias).
Preview: https://deploy-preview-1232--opentelemetry.netlify.app/docs/instrumentation/java/
Redirect test: https://deploy-preview-1232--opentelemetry.netlify.app/docs/instrumentation/java/annotations
/cc @Gaurang-Patel @svrnm

Java auto: reorg pages before adding content

---

content/en/docs/instrumentation/java/automatic/agent-config.md

- Contributes to #1229
- This adds https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-config.md to this repo.
- I've chosen to migrate the page almost as is. I'll make a revisions in a followup PR so that it will be easier to track changes.
Preview: https://deploy-preview-1233--opentelemetry.netlify.app/docs/instrumentation/java/automatic/agent-config/
/cc @austinlparker @cartermp @svrnm @jack-berg

Java Agent config page from other repo

---

content/en/docs/collector/getting-started.md

Signed-off-by: Brad Topol <btopol@us.ibm.com>
Updated build local commands in the getting started doc to fix a github permission denied issue, and make sure the
two main executables are placed in the correct directories, and added backslashes to enable the command to work
even when history expansion is enabled in the shell.

updated build command to fix multiple issues with build client and server on local

---

.gitignore

(This should be part of a dev's global .gitignore under macOS, but I suppose that it doesn't hurt to add it here.)

.gitignore: add `.DS_Store`

---

content/en/docs/instrumentation/java/automatic/agent-config.md

- Contributes to #1229
- This adds [docs/suppressing-instrumentation.md] to this repo, as a subsection of Agent config.
- I've chosen to migrate the page as is. I'll make a revisions in a followup PR so that it will be easier to track changes.
Preview: https://deploy-preview-1237--opentelemetry.netlify.app/docs/instrumentation/java/automatic/agent-config/#suppressing-specific-auto-instrumentation
[docs/suppressing-instrumentation.md]: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/3ab1b8516feb5a0065d5b1e0d6a242049f2c7aea/docs/suppressing-instrumentation.md

Java auto config: add  suppressing instr section

---

content/en/docs/instrumentation/rust/_index.md

Follow up on [opentelemetry-rust#776](https://github.com/open-telemetry/opentelemetry-rust/issues/766), add links to all published creates on crates.io
cc @open-telemetry/rust-approvers

Add crates.io links for Rust crates

---

content/en/docs/instrumentation/python/manual.md

Link example  was having issue  because wrong method was called and Link was not defined.

[Python] Update code excerpt in Manual instrumentation page

---

content/en/blog/2022/apisix.md

Found some typos as I was going through the blog again.
1. Change "OpenTelemetry" to "OpenTelemetry" in the topic.
2. Change "affectting" to "affecting".
3. Change "OpenTelemetery" to "OpenTelemetry".
4. Change "docekr-compose.yaml" to "docker-compose.yaml"

Blog: fix typos in APISIX blog

---

content/en/vendors.md

AppDynamics went live with their OpenTelemetry support on March 30. See https://docs.appdynamics.com/22.3/en/application-monitoring/appdynamics-for-opentelemetry

Add AppDynamics to supported vendors page

---

content/en/docs/instrumentation/js/exporters.md

I'm a little unsure, but all other examples show using `@opentelemetry/sdk-metrics-base` and everything works using it, so I think this is a valid change, but maybe there's a reason for using the other package I am not clear on…

Update dependencies for Prometheus exporter

---

content/en/blog/2022/apisix.md

Add canonical URL for APISIX blog, ref: https://github.com/open-telemetry/opentelemetry.io/pull/1254#discussion_r839675423

blog: add canonical_url for APISIX blog

---

assets/scss/_styles_project.scss
content/en/docs/instrumentation/java/automatic/agent-config.md
layouts/shortcodes/config_option.html

Currently, documented config options are formatted as **table entries**. This PR proposes an **alternative layout**, which, in particular, **works much better on mobile** and narrow displays (as shown below).
The layout uses labeled paragraphs, and only shows the environment variable if the reader wants to see it (by **clicking** on the down-arrow chevron). The following screenshot shows the env-var in the Extensions section, but it is hidden in the Config-file section:
> <img width="615" alt="config-options-open-close" src="https://user-images.githubusercontent.com/4140793/161072766-742d1844-4883-4ba1-9737-65eb320d862b.png">
---
**For comparison**, the following screen shot shows both the
- new formatting (green)
- old tabular layout (red)
for two of the "HTTP request and response …

Java docs: config-option formatting proposal

---

content/en/docs/instrumentation/java/automatic/agent-config.md
content/en/docs/instrumentation/java/automatic/annotations.md
layouts/shortcodes/config_option.html

- Followup to #1257
- Closes #1247
- Adds support for a **Default** field
- Converts the rest of the tables in the Java docs.
Preview:
- https://deploy-preview-1259--opentelemetry.netlify.app/docs/instrumentation/java/automatic/agent-config/
- https://deploy-preview-1259--opentelemetry.netlify.app/docs/instrumentation/java/automatic/annotations/#suppressing-withspan-instrumentation
/cc @austinlparker @cartermp

Java docs: rest of the config-option reformatting

---

content/en/docs/concepts/components.md

Most of the docs refer to OTLP and the OpenTelemetry Line Protocol, save docs/concepts/components.md

Docs: OTLP is not the OpenTelemetry Line Protocol

---

content/en/docs/instrumentation/python/cookbook.md

* Include an example of injecting the trace context into a text carrier dict.
* Add more explanatory text about what the different steps do, and which examples are different ways of doing the same thing.
* Add an example of context.attach as well as the pre-existing context=ctx passed to spans.
Followup to discussion in https://cloud-native.slack.com/archives/C01PD4HUVBL/p1648217884184149 .

Update cookbook for manually setting span context.

---

content/en/docs/instrumentation/net/exporters.md
content/en/docs/instrumentation/python/exporters.md

Preview: https://deploy-preview-1261--opentelemetry.netlify.app/docs/instrumentation/python/exporters/
Also includes a tiny one-line change for the .NET exporter equivalent where some words got slightly jumbled.
There is also a Prometheus exporter that could be documented, but I wasn't sure of the best way to use it yet (I've never done metrics + prometheus with python). There is a code sample in the Python repo that hints at a way to do it, but I'm not sure if it represents a good "getting started" best practice or not, so I decided to leave it out for now. Metrics is still under development in SDKs, anways 🙂

Add python exporters doc

---

scripts/adjust-spec-pages.pl

There is no change in the generated site files.

In spec pages, use markdown-friendly relref

---

content/en/blog/2022/apisix.md
content/en/docs/instrumentation/java/getting-started.md
layouts/_default/_markup/render-link.html
scripts/adjust-spec-pages.pl

- Adds a build-time check to enforce #922 
Preview:
- https://deploy-preview-1282--opentelemetry.netlify.app/blog/2022/apisix
- https://deploy-preview-1282--opentelemetry.netlify.app/docs/instrumentation/java/getting-started
- https://deploy-preview-1282--opentelemetry.netlify.app/docs/reference/specification/compatibility/opentracing
/cc @austinlparker @cartermp

Ensure local page refs are local

---

content/en/docs/instrumentation/js/getting-started/nodejs.md

Small change for the examples with node.js: it took me longer than I am happy to admit to find out how I can add debug output, so I thought it would be good to let people know during the getting started (inspired by @blumamir's [blog post](https://opentelemetry.io/blog/2022/troubleshooting-nodejs/), which has a bunch of great tips that should become part of the official docs:) )

Add troubleshooting to node.js

---

content/en/vendors.md

Adding vendor, we have limited support for OTLP now for metrics, so I kept this "no" for now.

Adding logz.io as vendor

---

content/en/vendors.md

Adding LogicMonitor to the list of supported vendors
See: https://www.logicmonitor.com/support/tracing/getting-started-with-tracing

Add LogicMonitor to list of supported vendors

---

content/en/docs/instrumentation/js/exporters.md

@opentelemetrysdk-trace-base instead of @opentelemetry/tracing
Found this while reading the docs

replace the old pkg name with new

---

content/en/docs/instrumentation/java/_index.md
content/en/docs/instrumentation/java/automatic/agent-config.md
content/en/docs/instrumentation/java/automatic/annotations.md

I've updated the versions to 1.13; and changed a few properties that we renamed in the last javaagent release.

Update docs after Java release

---

content/en/docs/instrumentation/net/_index.md

- Reformats the Status section of the .NET landing page
- Updates the statuses, with a mixed (split) status for logs
- Supersedes #1312
Preview: https://deploy-preview-1319--opentelemetry.netlify.app/docs/instrumentation/net/#status-and-releases
/cc @austinlparker @cartermp

.NET: update status section

---

content/en/registry/otel-go-autoinstrumentation.md

This change adds https://github.com/keyval-dev/opentelemetry-go-instrumentation to the registry

registry: add Go automatic instrumentation

---

content/en/docs/instrumentation/js/instrumentation.md

There was a typo in spelling for causal, fixed that.

Fix typo of causal spelling

---

content/en/docs/concepts/data-collection.md

It has been quite some time since the components have been shifted from collector core to collector contrib. Hence updated the doc accordingly.

Update collector repo description in Data Collection doc

---

.github/CODEOWNERS

I noticed in #1307 that @open-telemetry/docs-approvers weren't assigned as reviewers, should they be?

Add docs-approvers on all CODEOWNERS paths

---

content/en/docs/instrumentation/erlang/getting-started.md

The earlier patch that was sent by @ukutaht works but is a more complex form of the configuration. This change fixes both the Erlang and Elixir examples and switches the Elixir one back to the flat configuration, the issue was that the correct config key is `traces_exporter`, not `exporter`.

Erlang/Elixir: fix config key for traces exporter in examples

---

content/en/blog/2022/dotnet-instrumentation-first-beta.md

Adds a blog post to announce the first beta release of the .NET Automatic Instrumentation project.
Relates to open-telemetry/opentelemetry-dotnet-instrumentation#572.

Announce first beta for .NET auto instrumentation

---

content/en/docs/instrumentation/java/manual.md

Now that metrics are stable, it was time to improve the docs to better match tracing.

Improve java metrics documentation

---

content/en/docs/instrumentation/java/manual.md

Forgot to add this in #1341. This adds metrics to the [setup steps](https://opentelemetry.io/docs/instrumentation/java/manual/#set-up).

Add meter provider to java setup steps

---

layouts/registry/list.html

- Closes #1349 
Preview: https://deploy-preview-1350--opentelemetry.netlify.app/registry/?language=lua
Screenshot: note that all of the missing languages (see #1349) are now being shown.
> <img width="175" alt="image" src="https://user-images.githubusercontent.com/4140793/168668425-fd58c883-ef84-4ab9-a18f-713563633302.png">

Registry language menu: add missing titles

---

content/en/registry/otel-kotlin.md
layouts/registry/list.html

- Followup to #1350
- Normalizes menu IDs
- Simplifies scratch maps -- actually drops `$types`.
Preview:
- https://deploy-preview-1351--opentelemetry.netlify.app/registry/
- Language selection example:
- https://deploy-preview-1351--opentelemetry.netlify.app/registry/?language=kotlin

Registry template cleanup

---

assets/scss/_registry.scss
assets/scss/_variables_project.scss

- Followup to #1351
- Adds CSS classes for missing language badges
- Fixes contrast of JS language badge
Feedback @austinlparker @cartermp?
Preview: e.g.: https://deploy-preview-1352--opentelemetry.netlify.app/registry/?language=swift
---
Before: notices how the "swift" badge (in the entries) looks like a plain word 
> <img width="752" alt="image" src="https://user-images.githubusercontent.com/4140793/168690161-959881b6-798b-4686-8495-b245977eddb8.png">
After:
> <img width="751" alt="image" src="https://user-images.githubusercontent.com/4140793/168690538-48af549d-c440-4710-99c2-d4de96e06f81.png">

Registry: add missing CSS class definitions for lang badges

---

content/en/docs/concepts/_index.md
content/en/docs/concepts/components.md
content/en/docs/concepts/data-collection.md
content/en/docs/concepts/data-sources.md
content/en/docs/concepts/distributions.md
content/en/docs/concepts/glossary.md
content/en/docs/concepts/instrumenting-library.md
content/en/docs/concepts/instrumenting.md
content/en/docs/concepts/what-is-opentelemetry.md
content/en/docs/instrumentation/erlang/instrumentation.md
content/en/docs/instrumentation/java/manual.md
content/en/docs/instrumentation/js/api/tracing.md
content/en/docs/instrumentation/js/instrumentation.md
content/en/status.md

- No change in content (other than whitespace changes)
- Mainly ran Prettier over the concepts files.
- Global-replaced Markdown link definitions that were using `relref`s, replacing them with equivalent paths.
/cc @austinlparker @cartermp

Normalize concepts/*.md and drop some relref

---

content/en/blog/2022/metrics-announcement.md

- Adds a shorter `linkTitle`, which will appear in the left-side blog post list. Shorter TOC titles are better (sorry that I missed this addition when reviewing the blog post).
- Followup to #1361
Preview: https://deploy-preview-1363--opentelemetry.netlify.app/blog/

Metrics-RC-blog: add linkTitle

---

content/en/blog/2022/dotnet-instrumentation-first-beta.md

- Adds a shorter linkTitle, which will appear in the left-side blog post list. Shorter TOC titles are better.
- Ran Prettier to format the markdown
- No other change in content for this page

Add linkTitle to .NET-beta blog post, and reformat markdown

---

content/en/docs/concepts/otel-concepts.md
content/en/docs/instrumentation/net/automatic.md
content/en/docs/instrumentation/net/exporters.md
content/en/docs/instrumentation/net/getting-started.md
content/en/docs/instrumentation/net/manual.md
content/en/docs/instrumentation/net/netframework.md
content/en/docs/instrumentation/net/shim.md

Preview link: https://deploy-preview-1392--opentelemetry.netlify.app/docs/instrumentation/net/getting-started/
Now that https://github.com/open-telemetry/opentelemetry.io/pull/1387 is in, we can start linking to these concepts from docs!! It's a dream come true, we've been talking about this since at least October and it's now happening.
This does some linkification to language-agnostic concepts from .NET docs.
* Add them links
* Add some more stuff into the concepts -- these came about when I wanted to link to something, but there wasn't an appropriate sub-header even though the content was there. So I just header-ified stuff and tweaked the words a bit more (including clearing up a few things that are probably kinda inaccurate)
* Fixed a few minor docs bugs in the .NET docs as I came …

Linkify .NET concepts, clarify concepts, fix some minor docs bugs

---

content/en/docs/instrumentation/python/manual.md

This was in the readthedocs stuff, so I'm pulling it over (and adding the environment variables bit).
Preview: https://deploy-preview-1426--opentelemetry.netlify.app/docs/instrumentation/python/manual/#change-the-default-propagation-format

Add section on alternate context propagation in python docs

---

content/en/registry/instrumentation-cpp-otel-webserver-module.md

Adding the otel webserver module from https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/otel-webserver-module to the registry.

Add otel webserver module to registry.

---

.github/CODEOWNERS

As per https://github.com/open-telemetry/opentelemetry.io/pull/1435#issuecomment-1152578527

Add JS Approvers as JS docs code owners

---

content/en/docs/instrumentation/python/manual.md

Tracking in https://github.com/open-telemetry/opentelemetry-python/issues/2732
This updates the manual instrumentation documentation for python with metrics instrumentation.

Add python manual instrumentation docs to include metrics

---

content/en/docs/concepts/signals/_index.md

@svrnm & @cartermp: based on the content of `otel-concepts.md`, it seems that the **Signals** page is the most suitable redirect target. This PR adds such a redirect rule (via `aliases`).
- Closes #1458
Preview redirect tests
- https://deploy-preview-1460--opentelemetry.netlify.app/docs/concepts/otel-concepts
- https://deploy-preview-1460--opentelemetry.netlify.app/docs/concepts/data-sources/

Adds a redirect for otel-concepts.md

---

content/en/docs/instrumentation/js/api/context.md
layouts/index.redirects

Updates the spec to v1.12.0:
```console
$ pwd
.../opentelemetry.io/content-modules/opentelemetry-specification
$ git branch -v
* (HEAD detached at v1.12.0)     ae87c81 Release v1.12.0 (#2612)
```
Preview: 
- https://deploy-preview-1464--opentelemetry.netlify.app/docs/reference/specification/
- https://deploy-preview-1464--opentelemetry.netlify.app/docs/reference/specification/context/
- https://deploy-preview-1464--opentelemetry.netlify.app/docs/reference/specification/context/api-propagators/
Redirect tests (including a #1371 regression):
- https://deploy-preview-1464--opentelemetry.netlify.app/docs/reference/specification/context/context/ --> 301
- https://deploy-preview-1464--opentelemetry.netlify.app/docs/reference/specification/common/common/ --> 301
**Note**: While …

Update spec to v1.12.0

---

scripts/adjust-spec-pages.pl

- No change to the generated site
- The script update is necessary for an upcoming spec change.

adjust-spec-pages: tweak path for logs

---

content/en/vendors.md

This PR updates New Relic's distribution status on the vendor page.  With the removal of the newrelicexporter from Collector Contrib, New Relic no longer has any distributions or company-specific components.
I also added a link to the distributions page to help clarify what a distribution means if you are on the vendor page.

Update New Relic distribution status

---

content/en/docs/instrumentation/java/getting-started.md

Minor fix for [Java - Getting Started](https://opentelemetry.io/docs/instrumentation/java/getting-started/), this makes use of [Linking to releases](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases) to always have the latest version of [opentelemetry-javaagent.jar](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar) downloaded

Use 'latest' url to download java agent.

---

content/en/docs/instrumentation/python/automatic.md

There was some ambiguity in what way auto-instrumentation is compatible
with manual instrumentation. This should reduce that ambiguity.
---
Preview: https://deploy-preview-1311--opentelemetry.netlify.app/docs/instrumentation/python/automatic/

Improve Python automatic-instrumentation docs

---

package.json

- Steps towards #1456
- Changes in the generated site files are shown below. 
```console
$ npm run cd:public -- git diff -bw --ignore-blank-lines -I "Hugo 0." -- . ':(exclude)*.[^h]*' | grep ^diff 
diff --git a/blog/2022/dotnet-instrumentation-first-beta/index.html b/blog/2022/dotnet-instrumentation-first-beta/index.html
diff --git a/registry/index.html b/registry/index.html
```
Notes:
- For the blog entry with footnotes, then changes seem to be the result of https://github.com/gohugoio/hugo/pull/9822.
- I'm not sure why the gRPC entry is moved in the registry page, but this change is inconsequential (and I checked that the entries are identical).
```console
$ npm run cd:public -- git diff -bw --ignore-blank-lines -I "Hugo 0." -- . ':(exclude)*.[^h]*'
```
```diff
diff --git …
```

Upgrade Hugo to 0.98.0

---

layouts/partials/sidebar-tree.html
package.json

In upgrading to Hugo 0.100.2, we were hitting the following issue:
- https://github.com/google/docsy/issues/1065
---
**Update**: I've patched docsy, fixing 1065 in this PR by providing a file override. (I'll upstream the change as soon as I can.)
Other changes in the generated site files:
- Page meta data:
- Descriptions are different in whitespaces
- Word counts differ (even if the page content hasnt' changed)
- No other diffs that I'm aware of:
Note that the diff below is done over normalized pages that ignore the page header content up until the link to `main.css` (and the generator version number):
```console
$ cd public && git diff -bw --ignore-blank-lines -I "Hugo 0." -- . ':(exclude)*.[^h]*'      
$
```

Upgrade to Hugo 0.100.2 + Docsy patch

---

content/en/docs/instrumentation/erlang/_index.md
content/en/docs/instrumentation/erlang/getting-started.md
content/en/docs/instrumentation/erlang/instrumentation.md

Some fixes for the erlang docs from markdownlint

Markdown fixes for erlang docs

---

content/en/docs/collector/_index.md
content/en/docs/collector/configuration.md
content/en/docs/collector/trace-receiver.md

Ran some markdown lint & language checks over the docs, here's a few minor fixes for the collector pages.

Minor markdown & typo fixes for collector

---

content/en/docs/instrumentation/java/automatic/_index.md
content/en/docs/instrumentation/java/automatic/agent-config.md
content/en/docs/instrumentation/java/extensions.md
content/en/docs/instrumentation/java/getting-started.md

Some fixes for the java docs from markdownlint 
---
Preview, e.g.:
- https://deploy-preview-1482--opentelemetry.netlify.app/docs/instrumentation/java/automatic/agent-config/

Markdown fixes for java docs, remove note on agent config

---

content/en/docs/instrumentation/js/instrumentation.md

This is built on https://github.com/open-telemetry/opentelemetry.io/pull/1435 out of convenience, but I'm unopinionated on which order to pull in things.
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/1436
I had to kind of reorg the manual instrumentation docs a bit for JS here. I also decided to pull in some text from other docs to clarify some sections, and linkify some concepts as well now that we have language-agnostic concepts.
Happy to break stuff out if that helps with review.
Since y'all aren't code owners yet, tagging @open-telemetry/javascript-approvers to take a look. I have no doubt that there may be a few technical inaccuracies here that I'd like to catch before merging 🙂 
---
Preview: https://deploy-preview-1445--opentelemetry.netlify.app/docs/instrumentation …

Reorg manual tracing JS docs based on SDK

---

content/en/blog/2022/new-end-user-resources.md

Blog post to announce end user discussion group and end user slack channel 
This relates to https://github.com/open-telemetry/opentelemetry.io/issues/1449
---
Preview: https://deploy-preview-1498--opentelemetry.netlify.app/blog/2022/new-end-user-resources/

Announcing new end user resources

---

content/en/docs/collector/custom-collector.md
content/en/docs/collector/howto-custom-collector.md

Hoping to start a series of "HOW-TO" docs in the collector to help developers learning how to build components like the one I am proposing here [Tutorial on how to build a trace receiver #1265](https://github.com/open-telemetry/opentelemetry.io/pull/1265)
This would be the step one in the journey for component developers.
---
Preview: https://deploy-preview-1277--opentelemetry.netlify.app/docs/collector/howto-custom-collector/

Adding a "HOW-TO: Building your own collector" tutorial to the collector

---

content/en/status.md

The metrics API and SDK are GA in Java and .NET, and in Python there is an RC out already.

Remove outdated statement on metrics status

---

content/en/docs/instrumentation/js/exporters.md

Update the default collector HTTP port to `4318` instead of `55681` since the newest versions of the exporter default to `4318`.

(js) Update Collector HTTP Port to 4318

---

content/en/docs/instrumentation/java/manual.md

The variable `meterProvider` is used as `sdkMeterProvider` later in the code.
This PR changes the name of the variable to be `sdkMeterProvider`.

Fix incorrect variable name (meterProvider -> sdkMeterProvider)

---

content/en/blog/2022/dotnet-instrumentation-metrics.md

Adds a blog post to announce the new release of the .NET Automatic Instrumentation which adds support for metric signal.
Preview: https://deploy-preview-1530--opentelemetry.netlify.app/blog/2022/dotnet-instrumentation-metrics/
Relates to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/870
@open-telemetry/dotnet-instrumentation-approvers PTAL

blog: .NET Auto-instrumentation Metrics

---

content/en/docs/instrumentation/java/manual.md

fixes https://github.com/open-telemetry/opentelemetry.io/issues/1536 -- the old stuff is now deprecated as per the 1.15 packages.

Use AutoConfiguredOpenTelemetrySdk from latest Java packages

---

content/en/docs/instrumentation/python/_index.md
content/en/docs/instrumentation/python/exporters.md

Part of https://github.com/open-telemetry/opentelemetry-python/issues/2732
I tested out the example code to make sure everything is working as well. I also changed around the OTLP sections to present gRPC as the first option to push folks that way and because there isn't an OTLP/HTTP metric exporter yet.

Update Python exporter docs with console, OTLP, and Prometheus metric exporters

---

content/en/docs/instrumentation/php/getting-started.md

When I tried out the PHP Getting Started I got some errors because of the dependencies on `php-http/async-client-implementation` and `psr/http-factory-implementation`, I added those requirements, restructured the doc and also added a section on OTLP.
Preview: https://deploy-preview-1531--opentelemetry.netlify.app/docs/instrumentation/php/getting-started/

Update php docs with requirements and otlp export.

---

content/en/docs/collector/configuration.md

Document escaping `$` using `$$` and demonstrate that curly braces are
optional for environment variables.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/5614

Document additional collector configuration syntax

---

content/en/docs/contribution-guidelines.md

removed 'the' in "How to contribute to the OpenTelemetry"

Fixed typo in heading

---

content/en/blog/2022/new-end-user-resources.md

* Add a link to the calendar for the unaware folks (myself included 😄 )

Add calendar link to blog post

---

content/en/docs/instrumentation/java/automatic/annotations.md
content/en/docs/instrumentation/java/manual.md

Adds links to language-agnostic concepts to java docs, like what was done for .NET and JS.
I also made some formatting tweaks and a few tiny tweaks to a code sample to clarify a point in the docs about using the API, not the SDK.

Link up language-agnostic concepts in java docs + format

---

content/en/blog/2022/demo-announcement.md

Removed -webstore from the repo links in the blog
https://github.com/open-telemetry/opentelemetry-demo/issues/222

updated links on demo blog to reflect new repo name

---

content/en/docs/instrumentation/python/exporters.md

Missing import despite running `pip install opentelemetry-exporter-jaeger`? `pip install opentelemetry-exportert-jaeger` installs `opentelemetry-exporter-jaeger-thrift-1.11.1` by default?

Fix JaegerExporter Import

---

content/en/docs/instrumentation/python/exporters.md

Follow up to https://github.com/open-telemetry/opentelemetry.io/pull/1563#issuecomment-1196120715
Preview: https://deploy-preview-1566--opentelemetry.netlify.app/docs/instrumentation/python/exporters/#jaeger

Update python jaeger export to mention both thrift and proto

---

.github/ISSUE_TEMPLATE/ISSUE_REPORT.md
content/en/blog/2022/apisix.md
content/en/docs/collector/trace-receiver.md
content/en/docs/instrumentation/java/manual.md
content/en/docs/instrumentation/js/instrumentation.md
content/en/docs/instrumentation/net/getting-started.md
content/en/docs/instrumentation/net/manual.md

I noticed some types when running https://github.com/client9/misspell
Side note: I think it may be reasonable to run it in CI
Fix typos

Fix typos detected by misspell

---

content/en/docs/instrumentation/net/exporters.md
content/en/docs/instrumentation/net/getting-started.md
content/en/docs/instrumentation/net/libraries.md
content/en/docs/instrumentation/net/manual.md
content/en/docs/instrumentation/net/netframework.md
content/en/docs/instrumentation/net/shim.md

Fixes https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/958
Relates to https://github.com/open-telemetry/opentelemetry-specification/issues/2336
I agree with @tedsuo regarding the differentiation between "auto-instrumentation" and "instrumentation libraries". Especially that I see that both approaches could coexist. For instance, it looks like both Go and .NET would support both scenarios.
After this PR is merged we can create a page dedicated to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation. Tracked under https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/999
In .NET docs
- Rename the "Automatic Instrumentation" page to "Using instrumentation libraries"
- Reference the beta of Automatic Instrumentation for …

Rename .NET Automatic to Libraries

---

.github/CODEOWNERS

@austinlparker - FYI, I granted [collector-approvers](https://github.com/orgs/open-telemetry/teams/collector-approvers) write access to the repo, which is required for the file to be valid.
/cc @open-telemetry/collector-approvers @open-telemetry/collector-contrib-approvers @cartermp

CODEOWNERS: add entry for collector section

---

content/en/docs/instrumentation/python/getting-started.md

Route listens on /rolldice, not /doroll.

Fix a typo in Python getting started guide

---

content/en/docs/concepts/signals/traces.md

The current section basically doesn't say much. I pulled over some more content based on the spec, but not wholesale since the spec is a little wordy for users of opentelemetry. This was motivated by someone asking about different kinds of data types attributes support in a support channel.

Expand the language-agnostic trace attributes section

---

config.yaml

- Contributes to #1519
---
Just stumbled upon this, when putting a link to opentelemetry.io outside the main page I don't get an image for my "twitter card":
It looks like the required tags (especially meta og:image) are only added if there is a featured-background.jpg in the same path or an images attribute for that page. I set a default attribute in the config.yml -- I am still trying to validate if this not breaking anything else but it looks good so far. 
Note: We could use the images parameter for individual pages to show a different image!

Add images to config for 'Twitter Cards'

---

content/en/docs/instrumentation/python/getting-started.md

Remove the part that says one has to modify the code and then shows the exact same code as above. 
This is not needed and confuses the reader.
Fixes #1578

Clarify exporting via OTLP

---

content/en/docs/collector/configuration.md

As a new user of the OpenTelemetry collector, it was quite confusing to see YAML field names/identifiers with forward slash characters (i.e. `/`) in the config file. While this is clearly allowed by the YAML spec, it was unclear what effect this naming convention would have in the context of the OpenTelemetry collector config file and process. As far as I know, the only place this naming convention is documented is [in code](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/identifiable.go). 
The [`componentID` struct](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.56.0/config/identifiable.go#L34-L41) was particularly helpful in demystifying the component identifier syntax, with the rest of …

Document the component type/name identifier syntax

---

content/en/docs/instrumentation/python/manual.md

Python joins JS, Java, and .NET in having links to language-agnostic concepts!

Link up tracing concepts in python manual instrumentation docs

---

CONTRIBUTING.md

- Closes #1071
- Fixes prose: we support the **active** LTS, not the latest LTS version.
/cc @mic-max - does this address your concerns from #1066?
/cc @nate-double-u: we use this in other projects, it might be worth pulling out these instructions into techdocs page (though it would be nice for our doc pages to be published to a public server first).
**Preview**: https://github.com/chalin/opentelemetry.io/blob/chalin-mb-contrib-win-2022-08-06/CONTRIBUTING.md#local-setup

CONTRIBUTING: add Windows instructions for Node install

---

content/en/docs/reference/specification/status.md
content/en/status.md

- Contributes to #1574
- Moves the Status page content, which was only about the spec's status, (verbatim) into a new Spec status page
- **TODO**: I'll address the page-meta links (like Edit this page) later.
- Adds basic structure and links to the /status page, until this page gets beautified
Preview:
- https://deploy-preview-1606--opentelemetry.netlify.app/status
- https://deploy-preview-1606--opentelemetry.netlify.app/docs/reference/specification/status
/cc @tedsuo @melbgirl

Move spec status into spec section

---

content/en/_index.md

- I've tested this with a screen reader under Safari and it works as intended, when focus hits the button with the elipsis label, the reader reads "All languages"
- Closes #1612
- If @cartermp agrees, this also closes #1614
Preview: https://deploy-preview-1617--opentelemetry.netlify.app

Address accessibility issue of link to instrumentation

---

content/en/registry/instrumentation-dotnet-runtime.md

FYI @open-telemetry/dotnet-contrib-approvers

Add .NET runtime metrics instrumentation to the registry

---

content/en/docs/instrumentation/js/exporters.md

Removing the prometheus metric exporter from javascript docs until we can provide an updated & correct version
See https://github.com/open-telemetry/opentelemetry.io/pull/1621#discussion_r947656433 for details, cc: @pichlermarc , @cartermp

Remove prometheus exporter for JavaScript

---

content/en/blog/2022/new-end-user-resources.md

Adding a quick section about the talks to this post so that everything is a complete circle and we can easily link here to represent the WG's full public activities. The section is copied directly from the other blog post. I'm experimenting with doing this directly in github rather than gitpod so let's see how it goes!

Update new-end-user-resources.md to mention the OTel in practice talks

---

layouts/partials/hooks/head-end.html

Originally included this in in #1648, but splitting it out upon [request](https://github.com/open-telemetry/opentelemetry.io/pull/1648#discussion_r951827203). 
This is the / a [recommended way](https://en.wikipedia.org/wiki/Canonical_link_element) to specify a canonical page, which is good for everyone. 
---
(**Edit**: @chalin)
Previews, e.g.:
- https://deploy-preview-1649--opentelemetry.netlify.app/blog/2021/womens-day/, which now includes the following in its `<head>`:
> ```html
> <link rel=canonical href=https://medium.com/opentelemetry/opentelemetry-observes-international-womens-day-2021-4493a157f119>
> ```

Add head link to canonical_url if present

---

content/en/docs/instrumentation/python/mypy.md

This came up before, but there was some recent conversation here that made me feel like we could do a quick doc explaining how to configure a mypy project: https://github.com/open-telemetry/opentelemetry-python/issues/2591#issuecomment-1206440086
There's mention of potentially needing this in a project configuration file:
```
[mypy-opentelemetry.sdk.*]
implicit_reexport = True
```
I do not know if this is also necessary, but it should be easy to add if it is.

Add mypy doc

---

content/en/blog/2022/go-web-app-instrumentation/index.md

Looking at blog.opentelemetry.io right now the nginx blog post is ahead of the go blog post, although the latter is the most recent one. Moving the date by a day I think we should put it ahead. cc @chalin

Put "Go Web App" blog post before "nginx"

---

content/en/registry/instrumentation-js-prisma.md

Adds [prisma tracing instrumentation](https://github.com/prisma/prisma/tree/main/packages/instrumentation) to the registry.
Please let me know if any modifications to this PR or anything else is needed to get this approved.

Add Prisma tracing instrumentation to the registry

---

content/en/registry/exporter-go-zipkin.md

https://opentelemetry.io/registry/?language=java
There's two zipkin exporter option.

fix go exporter config

---

content/en/docs/instrumentation/js/getting-started/browser.md

`examples/trace-web` has been renamed to `examples/opentelemetry-web` to reflect that it now also includes metrics. This PR changes the docs to reflect that.

[JS] Update link to web example

---

content/en/registry/collector-exporter-google-cloud-operations.md

The Google Cloud Ops exporter used to be called the
Stackdriver exporter, but that was moved some time ago.

Fix broken link

---

content/en/status.md

We chatted about this a little bit in the comms SIG, where it was pondered if it was better to have language SDK stuff first. So I did that! And did some color and words changing stuff too. It's a bikeshed that I'm painting.
Preview: https://deploy-preview-1655--opentelemetry.netlify.app/status/

[bikeshedding] adjusted status page layout

---

content/en/docs/concepts/sdk-configuration/otlp-exporter-configuration.md

In [specification/protocol/exporter](https://opentelemetry.io/docs/reference/specification/protocol/exporter/#configuration-options). 
> SDKs SHOULD default endpoint variables to use http scheme unless they have good reasons to choose https scheme for the default (e.g., for backward compatibility reasons in a stable SDK release).
So I think, the example of `ENDPOINT` should use `http`. If not, newcomer maybe confuse with should I use `https` by default.

`exporter` ENDPOINT default schema

---

content/en/docs/instrumentation/java/manual.md

This PR fixes #1620 by adding more documentation about the auto-configuration.
It provides information about the dependency to add, the minimum code for initialization and a few examples of environment variable (the referring to the official README for more details and supported ones).
---
Preview: https://deploy-preview-1658--opentelemetry.netlify.app/docs/instrumentation/java/manual#auto-configuration

Added more information about using SDK auto-configuration

---

content/en/docs/instrumentation/js/getting-started/browser.md

See https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1110, I need to fix & bring back the browser extension, until then the link is broken, so I removed it.

Remove link to browser extension

---

README.md

Fixes #1448 
Note that this only works properly if you do not have write permissions into the repo. If you have write permission a branch in upstream will be created, but that branch will be protected.

Update blog instructions

---

content/en/docs/instrumentation/java/manual.md

This PR addresses #1539 for java language instrumentation.
follows: https://opentelemetry.io/docs/instrumentation/js/instrumentation/#semantic-attributes
Preview: https://deploy-preview-1683--opentelemetry.netlify.app/docs/instrumentation/java/manual/#semantic-attributes

Added subsection on semantic attributes for java

---

.github/ISSUE_TEMPLATE/DOCS_UPDATE.md

As discussed on slack: this is only true for ruby & go and is just a barrier for new comers to get started, let's remove this.

Remove "READ THIS FIRST" from  DOCS_UPDATE.md

---

content/en/docs/collector/deployment.md

See https://github.com/open-telemetry/opentelemetry-specification/issues/2520:
> [Instrumentation Libraries](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#instrumentation-library) provide instrumentation. It has no control on where the telemetry is exported. So I think the statement "OpenTelemetry instrumentation libraries by default export their data" is incorrect.
It could probably be updated with "SDKs by default export", but this still needs clarification [per my last comment on that matter](https://github.com/open-telemetry/opentelemetry-specification/issues/2520#issuecomment-1230073531)
cc: @cijothomas

Remove incorrect sentence from deployment.md

---

content/en/docs/instrumentation/cpp/_index.md
content/en/docs/instrumentation/erlang/_index.md
content/en/docs/instrumentation/js/_index.md
content/en/docs/instrumentation/php/_index.md
content/en/docs/instrumentation/rust/_index.md
content/en/docs/instrumentation/swift/_index.md

This PR contains changes for signal name consistency on the status page.
Resolves #1121 for the status page of all languages.
Preview: https://deploy-preview-1706--opentelemetry.netlify.app/

consistency of signal names in status page

---

content/en/docs/instrumentation/python/manual.md

Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1539
Preview: https://deploy-preview-1703--opentelemetry.netlify.app/docs/instrumentation/python/manual/#add-semantic-attributes

Add semantic attributes section to python manual instrumentation doc

---

README.md
archetypes/blog.md

Related: #1632
Changes:
* Make blog posts in a folder the default
* Make short title mandatory
* Provide instructions for date
* Add instructions on how to add an organisation to an authors name
* Provide instructions for canonical url
* Provide instructions for images

Add some more instructions for blog posts.

---

content/en/registry/tools-go-mralias-redact.md

[redact](https://github.com/MrAlias/redact) is a 3rd-party open-source Go package under the Apache 2 license. It provides a set of utilities for OpenTelemetry-Go that help remove sensitive information from tracing data.

Add registry entry for github.com/MrAlias/redact

---

.github/CODEOWNERS

For the languages with a (content_module) I added a comment to clarify why they are missing

Update code owners to contain all language sigs.

---

content/en/docs/instrumentation/js/instrumentation.md

Now that all the JS artifacts on NPM are up to date, we can add this as the main way to get the current span!
Preview: https://deploy-preview-1708--opentelemetry.netlify.app/docs/instrumentation/js/instrumentation/#get-the-current-span

Add getActiveSpan to docs

---

content/en/docs/instrumentation/js/instrumentation.md

Just some minor cleanup, but it's a little jarring to mix and match `const fName = (args) => {}` and `function fName(args)`, so I standardized on the former.

Use consistent function declarations in JS code samples

---

content/en/docs/instrumentation/js/examples.md
content/en/docs/instrumentation/js/exporters.md
content/en/docs/instrumentation/js/instrumentation.md
content/en/docs/instrumentation/js/libraries.md

Adds a document showing how to use instrumentation libraries for JS. Mostly node-based right now (although the reality is that node makes up the large majority of otel-js usage today, and that's reflected by how many libraries there are compared to otel-browserjs).
This brings the JS docs up to par with java/.net in terms of completeness of documentation.
Preview: https://deploy-preview-1736--opentelemetry.netlify.app/docs/instrumentation/js/libraries/

[JS Docs] Add instrumentation libraries doc

---

content/en/docs/concepts/glossary.md
content/en/docs/instrumentation/net/automatic.md
content/en/docs/instrumentation/net/exporters.md
content/en/docs/instrumentation/net/libraries.md
content/en/docs/instrumentation/net/manual.md
content/en/docs/instrumentation/net/netframework.md

Related https://github.com/open-telemetry/opentelemetry.io/issues/972
Follow-up after:
- https://github.com/open-telemetry/opentelemetry.io/pull/1565
- https://github.com/open-telemetry/opentelemetry-specification/pull/2700
Solves https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/999
This PR creates a very simple page. However, it can be further enhanced in the next PRs.
Preview: https://deploy-preview-1740--opentelemetry.netlify.app/docs/instrumentation/net/automatic/
PTAL @open-telemetry/dotnet-maintainers @open-telemetry/dotnet-instrumentation-maintainers @theletterf

Add basic .NET Automatic Instrumentation doc page

---

content/en/docs/instrumentation/erlang/testing.md

Missed a couple bits of unneeded lines in the example code in my review.

erlang/elixir testing: cleanup unneeded code in examples

---

content/en/docs/instrumentation/js/exporters.md

When people try to setup opentelemetry with a browser application they commonly run into the following issues:
* They try to use GRPC
* They don't have a CSP set up for their collector
* They don't have CORS headers send by their collector
* They are not aware that they need to expose their collector to the public
While trying to [bring back the otel browser extension](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1152) I ran into those issues myself, so I documented what I have done and with that I tried to address them here with a few words as well. 
Not perfect yet, but hopefully a starting point.

Add instructions for web tracer & exporting

---

content/en/docs/instrumentation/js/getting-started/nodejs.md

This PR adds an `npm init -f` to the node.js example, while not strictly needed, I ran into the bug that npm installed packages into a parent folder which had a node_modules folder already, which is confusing. This makes sure that everything is contained in the same folder. It will also help in another addition I plan to do (resource detection)

Initialize npm for the node.js example

---

.github/CODEOWNERS
content/en/docs/k8s-operator/_index.md

@open-telemetry/operator-approvers , @open-telemetry/operator-maintainers: we thought it would be great to have the operator also represented within the documentation (see #1701)
This is a first draft which mainly is copied over from the README.md. So for now the main purpose is, that it allows people to find the operator more easily.
We can grow this into a user-facing documentation from there.
Please note that I also added you as CODEOWNER for the folder containing the documentation, so you will get notified and asked for approval when contributors add to it.

Add documentation landing page for k8s operator

---

content/en/registry/exporter-dotnet-otlp.md
templates/registry-entry.md

I noticed we didn't have a registry entry for the OTLP exporter in .NET. 
Also: I _think_ the `isThirdParty` field had a misleading comment so I modified that as well. I hope it's ok to bundle this together with this change.

Add registry entry for the official .NET OTLP exporter

---

content/en/docs/migration/opentracing.md

A backtick is present in between paragraphs in the "Migrating from OpenTracing" page.
I believe this was mean to be a simple paragraph break.
This PR removes the backtick, leaving an empty new line to create the paragraph break.
Before: https://opentelemetry.io/docs/migration/opentracing/#baggage
After: https://deploy-preview-1798--opentelemetry.netlify.app/docs/migration/opentracing/#baggage

Fix rogue ` in opentracing migration guide

---

content/en/docs/instrumentation/net/automatic.md

Quick fix 😉 
`After you have set up instrumentation libraries,` -> `After you have set up the automatic instrumentation,`

Fix "Next steps" in .NET Automatic Instrumentation

---

content/en/docs/instrumentation/net/manual.md

- Reorder using directives
- Fix compiler errors for missing assignment operator and line ending
- Reformat line continuations

Fix manual instrumentation examples in .NET

---

.github/CODEOWNERS
content/en/community/demo.md
content/en/community/demo/_index.md

This is giving the demo project a home within the website. Documentation can grow from here.
cc @open-telemetry/demo-maintainers , @open-telemetry/demo-approvers 
---
Preview: https://deploy-preview-1826--opentelemetry.netlify.app/community/demo/

Initial content for demo page

---

content/en/docs/instrumentation/net/resources.md

Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1773
Similar to the JS one, but with some notable changes:
* No process detection section (can add later if there's a good way to do it)
* Code sample is different, as there is no semantic attributes package for .NET yet
* Elided adding docker resources, but could add later if there's a package for that

Add resources doc for .NET

---

.github/CODEOWNERS

This will make sure that the end-user-wg will be asked for approval on changes within the end-user folder and they can approve changes.
cc @chalin , @cartermp , @open-telemetry/end-user-wg

Add @open-telemetry/end-user-wg to codeowners.

---

content/en/_index.md
content/en/community/mission.md

As discussed yesterday we move the mission, vision, values below /community
#1809 will not change because of that, later we will source that page from the submodule.

Move mission page to community

---

content/en/docs/instrumentation/java/_index.md
data/instrumentation.yaml
layouts/shortcodes/lang_instrumentation_index_head.md

This updates the _index.md for java to make use of the shortcode that displays the table for stability and some standard text at the top of the page.

Use status and releases shortcode for java

---

content/en/docs/instrumentation/net/_index.md
data/instrumentation.yaml

This updates the _index.md for .NET to make use of the shortcode that displays the table for stability and some standard text at the top of the page. Also some cleanups & markdown fixes.

Use status and releases shortcode for .NET

---

content/en/blog/2022/exponential-histograms/index.md
content/en/docs/instrumentation/python/exporters.md
layouts/index.redirects
scripts/adjust-spec-pages.pl

Updates the spec to v1.14.0 from v1.12.0 (compare spec changes via https://github.com/open-telemetry/opentelemetry-specification/compare/v1.12.0...v1.14.0):
- Closes #1846
- Fixes broken links into the updated spec pages.
Preview:
- https://deploy-preview-1851--opentelemetry.netlify.app/docs/reference/specification
- New schema files:
-  https://deploy-preview-1851--opentelemetry.netlify.app/schemas/1.13.0
-  https://deploy-preview-1851--opentelemetry.netlify.app/schemas/1.14.0
- Redirect test:
- https://deploy-preview-1851--opentelemetry.netlify.app/docs/reference/specification/metrics/datamodel/#temporality
/cc @tigrannajaryan 
---
```console
$ (cd content-modules/opentelemetry-specification && git branch -v | grep \*)
* (HEAD detached at v1.14.0) 8c73c16 Release 1.14.0 (#2851)
```

Update specification to 1.14.0, and fix broken links

---

layouts/shortcodes/lang_instrumentation_index_head.md

Small improvement for the tables with the stability matrix: if the value is "Stable" or "Experimental" it will automatically link the definition in the spec like some of the pages are doing it already.

Auto link in stability table

---

assets/scss/_external_link.scss
content/en/docs/instrumentation/java/_index.md
content/en/docs/instrumentation/java/api.md
content/en/docs/instrumentation/java/extensions.md

- A first contribution to #1808
- Adds Java API-reference link to the side nav, as last entry in the section's subnav
Preview:
- https://deploy-preview-1859--opentelemetry.netlify.app/docs/instrumentation/java/
> <img width="1036" alt="Screen Shot 2022-10-12 at 14 08 46" src="https://user-images.githubusercontent.com/4140793/195416822-185ac7b4-f4cc-4868-935c-4628ce586c57.png">
> <img width="1036" alt="Screen Shot 2022-10-12 at 14 10 08" src="https://user-images.githubusercontent.com/4140793/195416952-7a3283d2-20b1-4ef8-b75a-13f37545178e.png">

Adds Java API-reference link to side nav

---

content/en/blog/2022/gc-elections-2022-list-of-candidates.md

Blog post announcing the list of candidates for the 2022 GC elections.

Blog post: list of candidates for 2022 GC elections

---

content/en/blog/2022/gc-candidates.md
content/en/blog/2022/gc-elections.md
layouts/partials/banner.md

- Following through from #1863
- Also, "normalized" titles and paths of earlier 2022 GC posts, to match what we did in 2021; and, we don't need the year in the file name since each post is in a folder for a given year.
Preview:
- Homepage for the banner: https://deploy-preview-1864--opentelemetry.netlify.app
- Posts redirect tests (for the two that were renamed):
- https://deploy-preview-1864--opentelemetry.netlify.app/blog/2022/gc-elections-2022
- https://deploy-preview-1864--opentelemetry.netlify.app/blog/2022/gc-elections-2022-list-of-candidates
/cc @jpkrohling 
---
> <img width="300" alt="image" src="https://user-images.githubusercontent.com/4140793/195631341-0db5fe10-7934-48cf-8a9b-e63eae9b4b10.png">

Banner: link to candidate-list and election posts

---

content/en/docs/instrumentation/cpp/_index.md
content/en/docs/instrumentation/cpp/exporters.md
content/en/docs/instrumentation/cpp/getting-started.md
content/en/docs/instrumentation/cpp/manual.md

Since I was playing around with c++ opentelemetry anyways I thought it might be a nice exercise to get the docs drafted for it. This first version is not ideal, but hopefully a good start:
* Getting Started leads people to have a http_server & http_client up and running
* Manual & Exporters are mostly text copys from https://opentelemetry-cpp.readthedocs.io/, they still lack some context with the getting started
Preview: https://deploy-preview-1857--opentelemetry.netlify.app/docs/instrumentation/cpp/getting-started/

Add initial version of C++ Getting Started, Manual & Exporters

---

content/en/blog/2022/collector-builder-sample/index.md

GCP is working on a [samples repo](https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample) for using the otel Collector-builder. Even though the repo has use cases geared toward GCP users, we thought it would be nice to promote this on the opentelemetry blog since a lot of what we're providing can be useful on any vendor.

[blog] Collector builder sample repo from GCP

---

content/en/docs/instrumentation/cpp/manual.md

Shamelessly copied from https://github.com/open-telemetry/opentelemetry-cpp/tree/main/examples/metrics_simple
We want to have more docs on Metrics for Kubecon, I think that example already has everything we need for a great start, so I took the chance to have one for C++, hope that's ok @open-telemetry/cpp-approvers 
Preview: https://deploy-preview-1869--opentelemetry.netlify.app/docs/instrumentation/cpp/manual/#metrics

Add metrics to cpp docs

---

content/en/docs/instrumentation/python/getting-started.md

Minor addition to the python metrics in the "Getting Started": instrumentation libraries for flask and other frameworks come with ootb metrics (http.server.active_requests & http.server.duration), which I found worth mentioning.

Add a note about ootb metrics to python getting started.

---

content/en/docs/instrumentation/js/_index.md
data/instrumentation.yaml

This brings the JS index page up to par with the others, also addressing https://github.com/open-telemetry/opentelemetry.io/issues/1777 in the process
Preview: https://deploy-preview-1884--opentelemetry.netlify.app/docs/instrumentation/js/

Add JS shortcode support for index page

---

content/en/docs/concepts/instrumenting-library.md

A minor fix that replaces the use of "auto-instrumentation" where "Instrumentation Library" is more appropriate.

Update "Instrumenting Libraries" wording

---

scripts/check-registry-urls

Nothing to fancy, just a small script that outputs a list of URLs in the registry that are not working which can be copied into a github issue (https://github.com/open-telemetry/opentelemetry.io/issues/1895)

Add a script to scan registry repo urls.

---

content/en/docs/instrumentation/java/examples.md
content/en/docs/instrumentation/java/getting-started.md

Following the example from [Go](https://opentelemetry.io/docs/instrumentation/go/)
This will remove the "Community Resources", which has exactly 1 entry for a really long time, which I find looks a little bit odd.

Update Java Examples to external link

---

content/en/docs/instrumentation/java/examples.md
content/en/docs/instrumentation/java/getting-started.md
layouts/index.redirects

- Closes #1911
Preview: https://deploy-preview-1910--opentelemetry.netlify.app/docs/instrumentation/java/
- Placeholder page:
- https://deploy-preview-1910--opentelemetry.netlify.app/docs/java/examples
- Aliases:
- https://deploy-preview-1910--opentelemetry.netlify.app/docs/java/instrumentation_examples
- https://deploy-preview-1910--opentelemetry.netlify.app/docs/instrumentation/java/instrumentation_examples

Recover aliases to Java examples

---

.htmltest.yml
content/en/docs/instrumentation/java/api.md
content/en/docs/instrumentation/java/examples.md
layouts/index.redirects

For a **detailed explanation of this feature, see** https://github.com/open-telemetry/opentelemetry.io/issues/1914#issuecomment-1291246238
- Contributes to #1914 for Java
- Followup to #1910
---
**Preview**: https://deploy-preview-1915--opentelemetry.netlify.app/docs/instrumentation/java/
- Placeholder pages:
- https://deploy-preview-1915--opentelemetry.netlify.app/docs/java/api/
- https://deploy-preview-1915--opentelemetry.netlify.app/docs/java/examples/
- Aliases, whose redirects should still work:
- https://deploy-preview-1915--opentelemetry.netlify.app/docs/java/instrumentation_examples
- https://deploy-preview-1915--opentelemetry.netlify.app/docs/instrumentation/java/instrumentation_examples

Make .../api and .../example valid paths (Java)

---

content/en/docs/instrumentation/cpp/_index.md
content/en/docs/instrumentation/cpp/api.md
content/en/docs/instrumentation/cpp/examples.md
content/en/docs/instrumentation/cpp/getting-started.md

- Adds API and Examples to C++ sidenav and as main-page sections.
- Contributes to #1808
- Replaces previous "further reading" section (since it mainly linked to the API reference and Examples, and these are now separate links in the sidnav and subsections at the bottom of the page) by **Repositories** section
- Also adds a link to contrib repo
Preview:
- https://deploy-preview-1928--opentelemetry.netlify.app/docs/instrumentation/cpp/
- https://deploy-preview-1928--opentelemetry.netlify.app/docs/instrumentation/cpp/api
- https://deploy-preview-1928--opentelemetry.netlify.app/docs/instrumentation/cpp/examples
Screenshot:
> <img width="800" alt="Screen Shot 2022-10-26 at 19 58 10" src="https://user-images.githubusercontent.com/4140793/198160657-4fe9ac1b-6777-4e7c-9023-5129d07 …

Add API and Examples to C++ sidenav

---

content/en/docs/instrumentation/cpp/exporters.md
data/instrumentation.yaml

- Update Metrics release status as alpha.
- Add Metrics OTLP exporters examples.

OpenTelemetry C++ - Update Metrics release status, and add metrics otlp exporter doc

---

content/en/docs/instrumentation/java/automatic/_index.md
content/en/docs/instrumentation/java/manual.md

While working on #1915 I noticed a few alias paths that needed to be normalized -- strictly speaking they don't have to start with a slash, but I think that it is good practice to avoid any possible ambiguity.
You can ignore whitespace changes since they aren't significant.
Redirect tests, to ensure that they still work:
- content/en/docs/instrumentation/java/automatic:
- https://deploy-preview-1926--opentelemetry.netlify.app/docs/java/automatic_instrumentation
- https://deploy-preview-1926--opentelemetry.netlify.app/docs/instrumentation/java/automatic_instrumentation
- content/en/docs/instrumentation/java/manual:
- https://deploy-preview-1926--opentelemetry.netlify.app/docs/java/getting_started
- https://deploy-preview-1926--opentelemetry.netlify.app/docs/java/manual_instrumentation
- …

Start all alias paths with a slash

---

content/en/docs/instrumentation/js/instrumentation.md

"Automatic Instrumentation Libraries" to "Instrumentation Libraries"

Remove "automatic" in JS Instrumentation page

---

content/en/docs/concepts/distributions.md

The term "automatic instrumentation libraries" is misleading, so I removed the "automatic"

Remove "automatic" in distributions page

---

assets/scss/_styles_project.scss

- Closes #1866
- Followup to #1916 
- Fixes link-color contrast for Registry page -- see screenshots below
- Makes styling a little les brittle by dropping the `p >` constraint and using `lighten/darken` functions over the `$primary` color
- Also removes external-link icons from the CNCF section of the homepage.
Preview:
- https://deploy-preview-1937--opentelemetry.netlify.app
- Preview: https://deploy-preview-1937--opentelemetry.netlify.app/registry/
Before
> <img width="1052" alt="image" src="https://user-images.githubusercontent.com/4140793/198310033-3a5aa010-38cb-4d4f-8b03-9f08ec4249d0.png">
After
> <img width="1050" alt="image" src="https://user-images.githubusercontent.com/4140793/198310126-9e6007c1-1640-4724-bb83-ca22418c72cb.png">

More style tweaks for links over dark bg

---

content/en/docs/instrumentation/net/exporters.md
content/en/docs/instrumentation/net/framework-config.md
content/en/docs/instrumentation/net/netframework.md
content/en/docs/instrumentation/net/resources.md
content/en/docs/instrumentation/net/shim.md

The original intent of this PR was to propose improved linkTitles (that show up in the sidenav) for two pages. Here are the linkTitle changes
- _.NET Framework instrumentation configuration_
- Old linkTitle: .NET Framework
- New linkTitle: Framework config
- Rational: we're already under the .NET section so the prefix ".NET" isn't that helpful in a short linkTitle. Added config to the linkTitle (and renamed the page to match), since that's what the page seems to be about
- _OpenTelemetry Tracing Shim_
- Old linkTitle: OpenTelemetry API Shim
- New linkTitle: Tracing Shim
- Rational: the entire site is about OTel so the prefix "OpenTelemetry" isn't that helpful. "Tracing Shim" seems like the most appropriate short title.
Also did other minor front-matter cleanup and fixed capitalization.

Improve linkTitles for .NET

---

content/en/community/end-user/_index.md
content/en/community/end-user/discussion-group.md
content/en/community/end-user/otel-in-practice.md
content/en/community/end-user/slack-channel.md

I thought it would look better in the /community if the content for the end user forums is in sub-pages, let me know what you think
https://deploy-preview-1872--opentelemetry.netlify.app/community/end-user/

Restructure end-user section in /community

---

content/en/registry/instrumentation-cpp-otel-webserver-module.md
content/en/registry/instrumentation-dotnet-aspnet.md
content/en/registry/instrumentation-dotnet-aws.md
content/en/registry/instrumentation-dotnet-awslambda.md
content/en/registry/instrumentation-dotnet-elasticsearchclient.md
content/en/registry/instrumentation-dotnet-entityframeworkcore.md
content/en/registry/instrumentation-dotnet-eventcounters.md
content/en/registry/instrumentation-dotnet-grpccore.md
content/en/registry/instrumentation-dotnet-hangfire.md
content/en/registry/instrumentation-dotnet-masstransit.md
content/en/registry/instrumentation-dotnet-mysqldata.md
content/en/registry/instrumentation-dotnet-owin.md
content/en/registry/instrumentation-dotnet-process.md
content/en/registry/instrumentation-dotnet-quartz.md
content/en/registry/instrumentation-dotnet-stackexchangeredis.md
content/en/registry/instrumentation-dotnet-wcf.md

DotNet instrumentations to registry.
I also added a small update for the registry entry for otel-webserver-module since it now has nginx support as well, didn't want to have a standalone PR for that.

Add DotNet instrumentations to registry (+ fix for otel webserver module)

---

.htmltest.yml
content/en/docs/instrumentation/java/getting-started.md

- Adjusts link-checker ignore-path rule so that it covers all language SIGs over the full path `/docs/instrumentation/<lang>`.
- Drops support for relative paths, opting for use of `relref` instead.

Link-checker ignore-path rule adjustment

---

content/en/docs/instrumentation/erlang/api.md
content/en/docs/instrumentation/erlang/examples.md

Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1808
https://deploy-preview-1943--opentelemetry.netlify.app/docs/instrumentation/erlang/api/
https://deploy-preview-1943--opentelemetry.netlify.app/docs/instrumentation/erlang/examples/

Add API&Examples link to erlang docs

---

data/instrumentation.yaml

The latest otel-cpp release (https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.7.0) is also the stable release for Metrics. The status is also updated in the otel-cpp repo - https://github.com/open-telemetry/opentelemetry-cpp#project-status

Update metrics to stable for otel-cpp

---

content/en/docs/instrumentation/python/_index.md
content/en/docs/instrumentation/python/examples.md

- There's an undefined link in the Python landing page, see https://opentelemetry.io/docs/instrumentation/python/#learn-more:
> <img width="150" alt="image" src="https://user-images.githubusercontent.com/4140793/198607561-b1a0049d-dac5-4431-8289-83e89744a8d0.png">
This PR fixes that by replacing the final "Learn more" section by a "Repositories and benchmarks" section, since this is the pattern we've started to follow for other language SIGs. A link to the API reference is already in the sidenav and subsection TOC (added via #1934).
- Adds "Examples" to sidenav
- Contributes to #1808, which also adds Examples for those SIGs that have them
- Followup to #1934
Preview: https://deploy-preview-1946--opentelemetry.netlify.app/docs/instrumentation/python/
Redirect test: …

Python: fix API link, add examples to sidenav and repos section

---

content/en/docs/reference/specification/status.md

- Provide a consistent title style of capitalization with other pages
- Fix typo and grammar

[Docs] Fix typos in /reference/specification/status.md

---

content/en/blog/2022/jaeger-native-otlp/index.md

Feedback welcome. Thanks!
Preview: https://deploy-preview-1892--opentelemetry.netlify.app/blog/2022/jaeger-native-otlp/

Add blog entry about Jaeger OTLP and deprecation

---

content/en/docs/instrumentation/net/manual.md

This fixes https://github.com/open-telemetry/opentelemetry.io/issues/1073 and brings the manual instrumentation bit up to par with JS.

.NET manual: independent and new root docs

---

.github/CODEOWNERS

Resolves https://github.com/open-telemetry/opentelemetry.io/issues/1942

Add ruby docs approvers to relevant section in CODEOWNERS

---

content/en/docs/concepts/signals/traces.md

Spec language is soft in regards to clients/server span relationships:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind
Server span does not need to have a parent, it could also be that multiple server instrumentations that are not aware of each other create server->server spans. While not ideal, this is a reality.
Client spans can be nested under other client spans.  E.g.  DB ORM creates a client span and the underlying DB driver creates a client span. They are unaware of each other and have no knowledge if they are both enabled in the same application.

Make span kind description softer and closer the the spec

---

content/en/docs/collector/trace-receiver.md

Find a grammar issue about `it's` and `its` frequently occurred on this page:
```
content/en/docs/collector/trace-receiver.md
```
**Grammar tips:**
- `It’s` is a contraction of “it is” or “it has.” 
- `Its` is a possessive determiner we use to say that something belongs to or refers to something.

Fix grammar issues in /trace-receiver.md

---

content/en/docs/instrumentation/js/exporters.md

When reading this page, find some typos and grammar issue.
```
content/en/docs/instrumentation/js/exporters.md
```

Fix some typos and grammar in /exporters.md

---

scripts/adjust-spec-pages.pl

- https://github.com/open-telemetry/opentelemetry-specification/pull/2925 is ready, but attempting to build the spec in the context of the website is currently failing for #1977 as can be seen from this build log:
- https://app.netlify.com/sites/opentelemetry/deploys/636ab38fc9bcfb000a4b90ab:
```nocode
2:53:14 PM: ERROR 2022/11/08 19:53:14 [en] REF_NOT_FOUND: Ref "../../experimental/serialization/json.md": "/opt/build/repo/tmp/specification/logs/data-model.md:431:27": page not found
2:53:16 PM: Error: Error building site: logged 1 error(s)
```
The problem is that the spec page has a link defined via a local path that points _outside_ of the specification. Hence, such links need to be encoded as a full URL to the corresponding page. This PR fixes such links for paths that refer to the …

Specification: handle spec-local paths into experimental directory

---

content/en/docs/getting-started/ops.md

* Fixes a small grammatical issue in the rhetorical question

Fix typo in Ops readme

---

layouts/index.redirects

- Closes #1850 since the rule is now being added via an alias in the appropriate spec page:
```console
$ (cd public; g diff )
diff --git a/_redirects b/_redirects
index aaabcc33..784ac0fa 100644
--- a/_redirects
+++ b/_redirects
@@ -97,5 +97,3 @@
/docs/swift   /docs/instrumentation/swift
/docs/swift/*  /docs/instrumentation/swift/:splat
/featured-background.jpg  /img/social/logo-wordmark-001.png 
-
-/docs/reference/specification/metrics/datamodel  /docs/reference/specification/metrics/data-model
$ grep datamodel public/_redirects # This is the rule added via the spec aliases entry
/docs/reference/specification/metrics/datamodel /docs/reference/specification/metrics/data-model/
```
/cc @tigrannajaryan @carlosalberto @svrnm

Drop temporary spec redirect rule

---

content/en/docs/collector/_index.md
content/en/docs/collector/trace-receiver.md
content/en/docs/getting-started/ops.md
content/en/docs/instrumentation/js/resources.md
content/en/docs/instrumentation/net/manual.md
content/en/docs/instrumentation/python/distro.md

Find some typos about setup and set up.
- `setup`: a noun (e.g., it was a setup!) or an adjective (e.g., follow the setup instructions). 
- `set up`: a verb, e.g., I will set up my computer.

Fix verb about setup and set up

---

content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/getting-started/nodejs.md

Ref #1800 and #1888
@svrnm @chalin @cartermp kindly take a look

Adding TypeScript to "Getting Started" 

---

data/instrumentation.yaml

Updates the stability data for the Javascript SDK and API which recently took its `metrics` implementation stable with the 1.8.0 release. 
Source: https://github.com/open-telemetry/opentelemetry-js/releases/tag/v1.8.0

Note JS metrics are stable as of 1.8.0

---

content/en/docs/concepts/signals/traces.md

Tweak long lines in the file:
```
content/en/docs/concepts/signals/traces.md
```
also changed three singular and plural issues:
```
so that common kinds of metadata are
A client span represents
A server span represents
```

Tweak line wrappings in /signals/traces.md

---

.github/CODEOWNERS

see https://github.com/open-telemetry/community/issues/1291

Fix swift-maintainers team name in CODEOWNERS

---

content/en/docs/instrumentation/ruby/getting-started.md
content/en/docs/instrumentation/ruby/manual.md

Ready for review!
Preview link: https://deploy-preview-1994--opentelemetry.netlify.app/docs/instrumentation/ruby/manual/
App I used to validate things: https://github.com/cartermp/otel-lang-samples/blob/main/ruby/app/app/controllers/app_controller.rb (sent traces to honeycomb)
Remaining:

Bring ruby manual instrumentation docs up to par with rest of languages

---

content/en/docs/concepts/instrumenting.md

I fixed the first paragraph of the page on Instrumenting, since the details on repositories are not really relevant to the end user and also some of the information is misleading and again the term "Instrumentation Libraries" is used ambiguous.

Update first paragraph of Instrumenting page

---

content/en/docs/instrumentation/java/automatic/annotations.md

artifact was marked stable in 1.20.0 (fixing automation for next time: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7219)
and property name was updated in the 1.20.0 release: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7196

Update to stable and update property name

---

layouts/_default/baseof.html

This PR adds an empty link to the body in order to verify the OpenTelemetry Mastodon account.

Add link for Mastodon verification

---

content/en/docs/instrumentation/js/getting-started/nodejs.md

fixing 2 minor issues I spotted in typescript [Example Application](https://opentelemetry.io/docs/instrumentation/js/getting-started/nodejs/#example-application):
1. `npm install` lists the `express` dependency twice, which is redundant. Removed one of these.
2. when calling `app.listen()` on the express `app`, the arrow function that prints a message to log should actually be a second parameter to the `listen` function. The parentheses are currently closed too early (after the `PORT` parameter), causing no message to be output to the console as intended.
3. `parseInt` function on the `PORT` is invoked in different patterns in js and ts examples (when extracting env variable in ts, and when invoking `app.listen` in js). I aligned them so the call is done in the same place for both …

fix: typescript example application

---

content/en/docs/instrumentation/java/manual.md

- Fix some issues caused by `npx prettier`
- Fix some typos
```
content/en/docs/instrumentation/java/manual.md
```

Fix typos and prettier issues in /instrumentation/java/manual.md

---

content/en/docs/instrumentation/java/extensions.md

Performed two actions:
- Run `npx prettier --w` to tweak long lines
- Improve the reading experience of a long unordered list
```
content/en/docs/instrumentation/java/extensions.md
```

Tweak line wrappings in instrumentation/java/extensions.md

---

content/en/docs/instrumentation/net/manual.md

Opened a separate PR to add a note about using the `--prerelease` flag here in case it's considered redundant due to https://github.com/open-telemetry/opentelemetry.io/pull/2038/files, which adds the same note to the [Getting Started page](https://opentelemetry.io/docs/instrumentation/net/getting-started/#aspnet-core). Alternatively, could link back to the Getting Started section if verbosity/repetition is a concern.

Add note about using the --prerelease flag in Manual section

---

content/en/docs/instrumentation/net/getting-started.md

This PR adds a brief note about the use of the `--prerelease` flag when adding OTel instrumentation packages via the CLI. For additional context, see this [Slack thread](https://cloud-native.slack.com/archives/C02UN96HZH6/p1669067199829659).

Add brief note about using --prerelease flag

---

content/en/docs/reference/specification/status.md
content/en/docs/workshop/resources.md

Updated two files:
```
content/en/docs/reference/specification/status.md
content/en/docs/workshop/resources.md
```

Tweak lines and fix a typo in workshop/resources.md

---

content/en/docs/instrumentation/js/instrumentation.md

This is a first cut at documenting metrics for JS!
Preview: https://deploy-preview-2037--opentelemetry.netlify.app/docs/instrumentation/js/instrumentation/#metrics
You'll notice there's two major things missing:
* Observable instruments
* Views
I still need to learn more about Views to effectively document + add good commentary for them.
I have skipped Observable instruments because I need to talk with people about how they're supposed to actually work. The spec is confusing and so is the behavior when I use them (e.g., observable counters let you add negative numbers, counters don't appear to accumulate values, etc.)

JS Metrics - simple docs

---

content/en/registry/collector-exporter-apiclarity.md
content/en/registry/instrumentation-python-tortoiseorm.md

As the title suggests 2 additions to the registry:
* APIClarity Exporter: https://github.com/openclarity/apiclarity/tree/master/plugins/otel-collector
* TortoiseORM instrumentation https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tortoiseorm
Preview: https://deploy-preview-2053--opentelemetry.netlify.app/registry/

Add apiclarity exporter & tortoiseORM instrumentation to registry

---

content/en/community/marketing-guidelines.md

Just saw that this was missing and creates an empty link

Add title and linkTitle to marketing page

---

content/en/docs/instrumentation/js/exporters.md

In the Getting Started, we created two files `app.js|ts` and `tracing.js|ts` and the configuration is made in the `tracing.js|ts` file, so the ref is wrong.

Change file-ref to tracing.js|ts

---

content/en/community/end-user/discussion-group.md

Update this page to include the new APAC sessions, and remove the past November sessions.

Add APAC session and remove November dates

---

content/en/docs/instrumentation/python/cookbook.md

Importing `opentelemetry.baggage` is missing in the sample code in "Capturing baggage at different contexts" section in python cookbook page, so I added it.

Add `baggage` to the import line of sample code in python cookbook page

---

content/en/blog/2022/end-user-discussion-group-apac/index.md

This blog post has the following goals:
1. To announce the **new** End User Discussion Groups for the APAC region, starting January 2023
2. To promote the upcoming EMEA and AMER sessions
3. To raise awareness and increase attendance of these sessions, particularly to newer members of the community

Announcement blog for new EUDG

---

content/en/registry/instrumentation-go-aws.md
content/en/registry/instrumentation-go-kit.md
content/en/registry/instrumentation-go-lambda.md

Add kit, aws & lambda instrumentation for go to registry

[Registry] Add more go instrumentation libraries

---

content/en/docs/instrumentation/erlang/testing.md

Tweak some long lines in this doc:
```
content/en/docs/instrumentation/erlang/testing.md
```
No any other changes.

Tweak lines in /erlang/testing.md

---

content/en/docs/instrumentation/python/automatic.md

I was running through the python automatic instrumentation doc and found this command out of date.  Before adding `metrics_exporter` I got this error
```
Configuration of configurator failed
Traceback (most recent call last):
File "/Users/tylerhelmuth/projects/honeycomb/python_auto_instrumentation/lib/python3.10/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 105, in _load_configurators
entry_point.load()().configure(auto_instrumentation_version=__version__)  # type: ignore
File "/Users/tylerhelmuth/projects/honeycomb/python_auto_instrumentation/lib/python3.10/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 321, in configure
self._configure(**kwargs)
File "/Users/tylerhelmuth/projects/honeycomb/python_auto_instrumentation/lib/pytho …
```

Update Python auto-instrumentation command

---

content/en/docs/instrumentation/java/manual.md

See https://github.com/open-telemetry/opentelemetry.io/issues/2029 Manual Instrumentation example in Java is missing dependencies and imports and this makes it a time waster. Both are added as a collapsible section.

Manual setup example in Java is incomplete

---

content/en/docs/instrumentation/js/instrumentation.md

I think it should be `and` instead of `an` in the context of the sentence.

Spelling mistake

---

scripts/adjust-spec-pages.pl

- Closes #2079
- Preview: https://deploy-preview-2109--opentelemetry.netlify.app/docs/reference/specification/metrics/semantic_conventions/hardware-metrics/
- Note that I'll be submitting a followup change to the spec since front matter (linkTitle) is missing for the new Hardware page.
The following diff of the generated site files confirms that the only change resulting from this PR (other than fixes to the docs side-nav), is the added content for the hardware page:
```console
$ (cd public && git diff -bw -I 'm-docsreferencespecification|^\s+' --ignore-blank-lines) | grep ^diff | grep -v \.xml
diff --git a/docs/reference/specification/metrics/semantic_conventions/hardware-metrics/index.html b/docs/reference/specification/metrics/semantic_conventions/hardware-metrics/index.html
$
```

adjust-spec-pages: be more precise in selecting front matter

---

content/en/docs/instrumentation/other/_index.md
content/en/registry/otel-crystal.md
content/en/registry/otel-dart.md
content/en/registry/otel-haskell.md
content/en/registry/otel-julia.md
content/en/registry/otel-lua.md
content/en/registry/otel-perl.md

Addresses #1807
Preview: 
* https://deploy-preview-2062--opentelemetry.netlify.app/docs/instrumentation/other/
* Registry examples: [Perl](https://deploy-preview-2062--opentelemetry.netlify.app/registry/?s=perl&component=&language=), [Julia](https://deploy-preview-2062--opentelemetry.netlify.app/registry/?s=julia&component=&language=)
copying your comments from there @chalin:
> For unofficial implementations that are sufficiently well developed, we could grant them their own page.
This sounds like a potential step 2, but we need to see if those sufficiently well developed projects move to become an "official" implementation eventually.
> For all others, I'd mention them on the [Instrumentation](https://opentelemetry.io/docs/instrumentation/) page.
Putting it there prominently enough …

Add page for other languages

---

.vscode/cspell.json
scripts/adjust-spec-pages.pl

- #906
- https://github.com/open-telemetry/opentelemetry-specification/issues/2558
- Ensure img paths get processed properly for the schemas section once the following lands and the spec is updated in this repo: https://github.com/open-telemetry/opentelemetry-specification/pull/3046
- This PR **has no effect on the currently generated site files** (but it will, once the spec PR 3046 is integrated), so it is safe to merge before (or whether) PR 3046 is merged.
/cc @yurishkuro @bogdandrutu 
---
Here's a screenshot of one of the file format pages once PR 3046 is integrated, along with this PR:
> <img width="1194" alt="Screen Shot 2022-12-16 at 15 27 29" src="https://user-images.githubusercontent.com/4140793/208183929-25534368-aaa4-4928-b161-4421044c2111.png">

adjust-spec: process img paths of schemas index page

---

content/en/docs/collector/getting-started.md

Changed the word to "required"

Errata: Linux Packaging Section Misspelling

---

content/en/docs/instrumentation/other/_index.md
layouts/index.redirects

- Followup to #2062
- Copyedits to new "Other languages" page
- Skips the creation of a redirect rule of the form `/docs/<lang>` (to `/docs/instrumentation/<lang>`) for "other", since it isn't a language.
/cc @svrnm

Don't create a docs alias for the "other" instrumentation page

---

scripts/adjust-spec-pages.pl

- Closes #1467
- There is no change to the generated site files:
```console
$ npm run check-links
...
✔✔✔ passed in 2.445121828s
tested 891 documents
$ npm run cd:public -- git diff # No diffs
```

Drop hardcoded spec front-matter from script

---

config.yaml
layouts/_default/baseof.html

Related: #2104
the best place for having the link to the mastodon account would be the footer where we have all those other links.
Only challenge: I can not set the `rel="me"` easily, this is something that probably needs to be fixed in docs, @chalin?

Add Mastodon link to footer

---

content/en/registry/instrumentation-java-jms.md
content/en/registry/resource-detector-go-aws.md

- instrumentation-java-jms.md: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/jms-1.1, error 404
- resource-detector-go-aws.md: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/detectors/aws/, error 301

Fix broken links in registry

---

content/en/docs/reference/specification/status.md

Fixes https://github.com/open-telemetry/opentelemetry.io/issues/2108#issuecomment-1357670881

Remove instrumentation status blurb from spec status page

---

CONTRIBUTING.md

When using nvm, whether your are installing the active LTS version of Node afresh, or upgrading, the instructions are the same. Also, we can simplify the command (drop the LTS argument), if you run the install command from within the repo directory. This PR updates the contrib instructions accordingly.
Preview: https://github.com/chalin/opentelemetry.io/blob/chalin-im-contrib-node-upgrade-2022-12-19/CONTRIBUTING.md
/cc @cartermp @svrnm

CONTRIBUTING: document how to upgrade node using nvm

---

content/en/docs/concepts/signals/baggage.md
content/en/docs/concepts/signals/traces.md

This fixes https://github.com/open-telemetry/opentelemetry.io/issues/2065 (or at least tries to)
I removed a section that was sorta useless and I think ultimately confusing because it's describing abstract concepts with slightly different words than concrete ones. Might need some more tweaks. I also clarified some parts of Baggage and tried to get rid of unrelated stuff and the use of the phrase "trace context".

Change/clean up uses of 'Context' in conceptual stuff

---

content/en/docs/workshop/resources.md

fixes https://github.com/open-telemetry/opentelemetry.io/issues/1596
Preview: https://deploy-preview-2127--opentelemetry.netlify.app/docs/workshop/resources/

Call out workshop resources are legacy

---

content/en/vendors.md

DaoCloud provides a k8s-based platform, named DCE, in China past and recently exploring international market.
DCE well supports for observability with OTel.

Add DaoCloud to the vendor list of OTel

---

content/en/community/end-user/otel-in-practice.md

The previous link sends users to the DE version of Meetup.

Update OTel in Practice Meetup group link

---

content/en/docs/collector/trace-receiver.md
content/en/docs/instrumentation/python/automatic.md

- Fix some minor typos
- Fix a consistency about `Ctrl + C`, which have more hits than `Control+C` though it's not wrong:

fix typos and consistency

---

content/en/docs/instrumentation/java/automatic/_index.md
content/en/docs/instrumentation/java/automatic/agent-config.md

Also:
- Added docs explaining the mapping of system properties to environment variables. 
- Moved the section for "Enable manual instrumentation only" to be grouped better.
- Added `JAVA_TOOL_OPTIONS` setup instructions.

[Java] Add docs to enable only specific instrumentation

---

content/en/docs/collector/configuration.md

Uses new `${env:ENV}` style syntax for environment variable expansion. This is the recommended way as of recent Collector versions.
Relates to open-telemetry/opentelemetry-collector-contrib/issues/17299

[collector] Use ${env:ENV} style syntax for env variable expansion

---

content/en/docs/collector/configuration.md

After playing around with the example configuration, the collector was complaining that the swap scraper for `hostmetrics` receiver does not exist, it might have been the initial naming for the paging scraper. Fixing this in the configuration doc.

Replace swap scraper with the paging scrape

---

content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/getting-started/nodejs.md

Tweak long lines in 2 files:
```
content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
```

Tweak long lines in /js/getting-started/

---

content/en/docs/concepts/semantic-conventions.md

Adds it so you can navigate to this very important concept easily.
It should have more commentary and all that, but for now let's surface it more.

Add semantic conventions to the concepts TOC in docs

---

content/en/docs/concepts/sdk-configuration/otlp-exporter-configuration.md

- Fix typo
- Add some spaces
- For `Example`: if only an example is listed, putting it into a single line might be more natural

Fix some style issues in otlp-exporter-configuration.md

---

content/en/docs/instrumentation/js/serverless.md

Preview: https://deploy-preview-2091--opentelemetry.netlify.app/docs/instrumentation/js/serverless/#gcp-function

GCP function instructions

---

package.json

- Closes #2133
- Updates NPM packages for Hugo and Docsy deps
- Tweaks NPM scripts
There is no change in the generated site files:
```console
$ npm run update:pkg:hugo+
...
$ npm run check-links               
...
Start building sites … 
hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended darwin/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio
...
htmltest started at 03:45:46 on public
========================================================================
✔✔✔ passed in 2.344007504s
tested 901 documents
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0\.")
$ 
```

Update Hugo and Docsy deps

---

content/en/docs/instrumentation/swift/manual.md

I followed the swift instructions from the OpenTelemetry website and there is a comma missing in the Setup example:
From [the swift docs](https://docs.swift.org/swift-book/LanguageGuide/Functions.html):
> You call the greet(person:alreadyGreeted:) function by passing it both a String argument value labeled person and a Bool argument value labeled alreadyGreeted in parentheses, separated by commas
According to the swift website, when calling a function, there should be a comma

fix(swift): add missing comma in Setup code example

---

content/en/_index.md
content/en/docs/opentelemetry-demo.md

- Contributes to #2158
- Proposes to drop the demo sidebar placeholder under `/docs` in favor of a homepage link to the demo. Part of the rational here is to try to keep the docs top-level as short and coherent as possible. This is just a proposal, feedback is welcome.
/cc @cartermp

Add demo link to homepage and drop docs placeholder

---

content/en/registry/collector-receiver-snmp.md

It looks like the SNMP receiver description was mangled. I copied the text here from the collector-contrib description in the README.

Fix description for SNMP receiver

---

content/en/registry/instrumentation-go-connect-rpc.md

Adds https://github.com/bufbuild/connect-opentelemetry-go to registry. 
This instrumentation implements both [grpc trace/metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md#grpc) standard plus the [connect rpc](https://github.com/open-telemetry/opentelemetry-specification/pull/3116) conventions which is why it has both `grpc` and `connect` tags

Add connect-rpc to registry

---

content/en/docs/instrumentation/js/instrumentation.md

Notes:
- added descriptions and code examples for various async instruments
- i would like to point out that the descriptions earlier in the document for synchronous counters, etc. slightly deviate from my description. in particular, i reference the terms `additive` and `monotonic` which are not necessarily referenced in earlier descriptions. i think we should agree on making all of these consistent before merging.
- i relied on this page to inform my descriptions, and this is also how i interpreted the various metrics when implementing them in Golang: https://opentelemetry.io/docs/reference/specification/metrics/supplementary-guidelines/
---
Preview: https://deploy-preview-2144--opentelemetry.netlify.app/docs/instrumentation/js/instrumentation

add examples for async counter, updown counter, gauge

---

content/en/docs/instrumentation/cpp/getting-started.md
content/en/registry/instrumentation-js-mongoose-instrumentation.md

I added instructions for building C++ with alpine/apk, I also found that the http examples can not be build anymore without adding a flag to cmake

Add apk instructions to C++ & fix cmake issue

---

content/en/docs/instrumentation/python/automatic/agent-config.md
content/en/docs/k8s-operator/automatic.md

Prettifies 2 files that I touched in https://github.com/open-telemetry/opentelemetry.io/pull/2196 that were out of compliance.
Exact commands were:
`npx prettier --write content/en/docs/k8s-operator/automatic.md`
`npx prettier --write content/en/docs/instrumentation/python/automatic/agent-config.md`

[chore] prettify 2 files

---

layouts/_default/baseof.html

resolve https://github.com/open-telemetry/opentelemetry.io/issues/2199

Address accessibility issues of Mastodon rel=me link

---

content/en/docs/collector/configuration.md

This PR adds reference to otelcol's file config provider, which allows the config to make reference to other YAML files.

Add configprovider doc to otelcol doc

---

content/en/_index.md
layouts/_default/baseof.html

- Relocates the Mastondon `rel="me"` link from the layout (which applied to several site pages), into the homepage (which is the only page that needs to have the verification link).
- Closes #2104
- Followup to #2206 
- According to https://www.boia.org/blog/is-it-okay-to-hide-content-from-screen-readers#:~:text=If%20you%20use%20HTML%20hidden,so%20aria%2Dhidden%20is%20redundant:
> If you use HTML hidden or the CSS display:none, you don’t need aria-hidden
Preview: https://deploy-preview-2216--opentelemetry.netlify.app
/cc @Arhell

Move Mastodon verification link to homepage (only)

---

content/en/registry/instrumentation-js-bullmq.md

A few months ago I wrote an auto-instrumentation for the BullMQ javascript package. It's been in regular use by several projects since then, and I'd like to add it to the registry to hopefully make it easier for others to find.

Add BullMQ instrumentation to the registry

---

content/en/docs/collector/configuration.md

When copying the snippet I had for the config loading an external YAML content, I changed the file name in one place but not on the other. This PR fixes that.

Fix file name in otelcol config example

---

content/en/docs/instrumentation/python/automatic/agent-config.md
content/en/docs/k8s-operator/automatic.md

Adds docs to Python's auto-instrumentation config and the k8s operator auto-instrumentaiton config for python explaining how to omit specific packages from instrumentation.  This is an important feature in auto-instrumentation as instrumenting everything can lead to too much data or noise.

[python] Add doc for disabling instrumentation for python

---

content/en/blog/2023/http-conventions-stability.md

follow up to the blog post, set's it to the proper date & moves it out from the directory.

Update and move http conventions stability blog post

---

content/en/blog/2023/otel-end-user-discussions-january-2023.md

Updated author list for [OTel End User Discussions January 2023](https://opentelemetry.io/blog/2023/otel-end-user-discussions-january-2023/) to include list of contributors.

Update author list for OTel End User Discussion Summary for January 2023

---

content/en/ecosystem/integrations.md

Adding a bunch more projects that have started to integrate OpenTelemetry.

Add more projects with otel integration

---

.htmltest.yml
content/en/community/roadmap.md

A quick addition so that the site path is reserved for the roadmap (and so it can potentially be used in the 2023/10 OTel in Focus).
**Preview**: https://deploy-preview-2239--opentelemetry.netlify.app/community/
> <img width="994" alt="Screen Shot 2023-01-31 at 18 26 57" src="https://user-images.githubusercontent.com/4140793/215907107-0b937875-72ab-47ac-abb9-db2049dd04cb.png">

Add Roadmap to Community side-nav as redirect

---

.gitmodules

Followup to:
- #1111
The Python git submodule should have been dropped back then. Apparently I forgot to do so.
No changes to generated site pages:
```console
$ (cd public && git diff -bw --ignore-blank-lines) 
$
```

Drop OTel Python git submodule

---

.htmltest.yml
assets/js/registrySearch.js
assets/scss/_styles_project.scss
content/en/ecosystem/registry.md
content/en/ecosystem/registry/_index.md
layouts/ecosystem/registry.json.json
layouts/index.redirects
layouts/registry/list.json.json
layouts/shortcodes/registry-search-form.html

- Contributes to #2202
- Fully migrates the registry to be under `/ecosystem`
- There are no more site pages or resources under `/registry`
- Redirects `/registry/*` to `/ecosystem/registry`
- Query parameter are preserved in the redirect
- Tweaks the page design a bit:
- New page section colors (see screenshot below)
- Ensures that the JSON data file is generated
- Ensure that the JS search uses updated paths, in particular to be able to access the JSON entries data
- Ran Prettifier on the main `.md` file
Preview:
- https://deploy-preview-2252--opentelemetry.netlify.app/ecosystem/registry
- https://deploy-preview-2252--opentelemetry.netlify.app/ecosystem/registry/?s=emf - shows that fuzzy search works
- https://deploy-preview-2252--opentelemetry.netlify.app/ecosystem/registry/?component=r …

Final move of registry into ecosystem section, and fix keyword search

---

README.md

- Updates the "Submitting a blog post" instructions, distinguishing between a simple post (w/o assets) and posts with assets.
- Other minor copyedits

Update blog-post submission instructions

---

.htmltest.yml
content/en/blog/2022/apisix/index.md
content/en/docs/collector/configuration.md
content/en/docs/concepts/distributions.md
content/en/docs/concepts/instrumenting-library.md
content/en/docs/concepts/instrumenting.md
content/en/docs/instrumentation/erlang/getting-started.md
content/en/docs/instrumentation/erlang/instrumentation.md
content/en/docs/instrumentation/java/manual.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/js/libraries.md
content/en/docs/instrumentation/net/libraries.md
content/en/docs/instrumentation/other/_index.md
content/en/docs/instrumentation/python/_index.md
content/en/docs/instrumentation/python/automatic/_index.md
content/en/ecosystem/registry/_index.md

- Contributes to #2202
- We can't drop the link-checker ignore rule yet because we're waiting on Go docs update:
https://github.com/open-telemetry/opentelemetry-go/pull/3638
/cc @svrnm

Use canonical path to registry throughout the website

---

content/en/docs/getting-started/_index.md
content/en/docs/getting-started/demo.md

- Final contribution to #2158
- Adds Call-To-Action buttons to the **Getting Started** page
- Drops the demo alias / placeholder page
- Drops the **Getting Started** subpage list
Preview: https://deploy-preview-2257--opentelemetry.netlify.app/docs/getting-started/
Before:
> <img width="860" alt="image" src="https://user-images.githubusercontent.com/4140793/216477731-30b5f733-cfd2-46d7-87e9-4b351d519f96.png">
After:
> <img width="858" alt="image" src="https://user-images.githubusercontent.com/4140793/216477653-9a89684d-c998-445a-8d47-39eeba6c7900.png">
/cc @svrnm @cartermp

Use CTA buttons in Getting started page

---

content/en/docs/collector/_index.md
content/en/docs/collector/configuration.md
content/en/docs/collector/custom-auth.md
content/en/docs/collector/distributions.md
content/en/docs/collector/getting-started.md

- Make `collectorVersion` param available to entire **Collector** section
- #1194
- #2090
- Includes other minor front-matter cleanup
- There are no changes to the generated site files (except for Git info)
Preview, e.g.:
- https://deploy-preview-2259--opentelemetry.netlify.app/docs/collector/getting-started/#docker - see that the page still refers to `0.70.0`

Make collectorVersion available to entire Collector section

---

content/en/docs/collector/custom-collector.md

- Closes #2262
- Contributes to #1194
- Uses `collectorVersion` param instead of a hard-coded value
Preview: https://deploy-preview-2263--opentelemetry.netlify.app/docs/collector/custom-collector/
/cc @svrnm

Build custom collector: refer to latest vers of collector

---

.htmltest.yml

- Brings in #3638, and no other doc changes
- Contributes to #2202
/cc @open-telemetry/go-instrumentation-approvers @svrnm

Update opentelemetry-go and drop registry link-check ignore rule

---

.gitmodules
hugo.yaml
scripts/adjust-spec-pages.pl
scripts/cp-spec-pages.sh

- Closes #2173 by bringing in the demo docs _as is_, via a git submodule.
- I propose this as a first cut, until the demo docs are frozen, after which we'll be able to migrate them from the demo repo to here. In the meantime, I'll submit some front-matter parameters to the demo repo to change the section weight, add linkTitles, etc.
WDYT @svrnm @cartermp @austinlparker @open-telemetry/demo-approvers ?
**Preview**: https://deploy-preview-2246--opentelemetry.netlify.app/docs/demo
p.s. I know that the scripts are misnamed, but I wanted to keep changes to a minimum in this PR.

Add demo docs

---

content/en/docs/collector/trace-receiver.md

- Alerts readers that an old version of the collector is used in "Building a Trace Receiver" and that it doesn't yet work with the latest release
- Modifies page instructions to use `collectorVersion` param rather than hard-coded value
- #1194
- #2090
- Copyedits
Preview: https://deploy-preview-2261--opentelemetry.netlify.app/docs/collector/trace-receiver/
Followup:
- #2260
/cc @svrnm 
> <img width="740" alt="image" src="https://user-images.githubusercontent.com/4140793/216658684-65e4ad1a-ea67-43e5-a14e-37526110665d.png">

Alert that old vers of collector is used in Building a Trace Receiver

---

content/en/docs/collector/scaling.md

Adds a new page to the collector documentation on how to scale the collector.
This content was originally written by @jpkrohling and published here: https://grafana.com/docs/opentelemetry/collector/how-to-scale/.  I was given permission to reuse that content for the OpenTelemetry  docs.
The content has been largely untouched; only very slight grammatical touch-ups have been made.
Thank you so much @jpkrohling for writing this article and donating it to the project!

[Collector] Add scaling collector doc

---

.github/workflows/scripts/check-collector-version.sh

Followup to:
- #2266
Which broke the script under Linux, despite my attempt at addressing the `sed` differences between Linux and macOS. The result was action failures:
- https://github.com/open-telemetry/opentelemetry.io/actions/runs/4101553729/jobs/7073465659
Take 2. Tested script under macOS. Tested command change under Linux. 🤞 😄

check-collector-version.sh: fix for Linux sed

---

content/en/docs/concepts/instrumenting.md

The original version implied that the code itself emits metrics, which I don't think is precisely true. Isn't it the system that emits?
Great docs, by the way!

Clarify instrumentation definition

---

.prettierignore
CONTRIBUTING.md
README.md
hugo.yaml
package.json

- Preparation for use of Prettier as part of CI
- Sets up a base config for use of Prettier, that makes it easy for contributors to use
- Defines NPM scripts for checking all files
- Offers an alternative base to #2179
- Includes minor Prettier fixes for a few top-level files
---
The `check-all` script will then be useful for a GH action since it fails which a human friendly message when formatting needs to be applied. For example:
```console
$ npm run prettier:check-all ; echo $?        
...
Checking formatting...
[warn] README.md
[warn] Code style issues found in the above file. Forgot to run Prettier?
1
```
To fix the issues add the `-w` flag:
```console
$ npm run prettier:check-all -- -w    
...
Checking formatting...
[warn] README.md
[warn] Code style issues …
```

Prettier base config and NPM scripts in preparation for CI integration

---

content/en/blog/2022/exponential-histograms/index.md

See https://github.com/open-telemetry/opentelemetry-specification/pull/3174

Update opentelemetry-specification submodule to include the 1.18.0 schema.

---

content/en/docs/demo/metric-features.md
content/en/docs/demo/trace-features.md

- Closes #2280
- Switches to using ✅ rather than 💯 -- in particular because the shape and color (green) of the check mark seems more visually imposing as a means of reflecting the "done" status
- Runs Prettier
- Moves the legend to after the tables
**Preview**:
- https://deploy-preview-2288--opentelemetry.netlify.app/docs/demo/trace-features/
- https://deploy-preview-2288--opentelemetry.netlify.app/docs/demo/metric-features/

Demo service feature tables: recover icons

---

content/en/docs/concepts/signals/traces.md

In docs under `Sample Trace` in [#tracing-in-opentelemetry](https://opentelemetry.io/docs/concepts/signals/traces/#tracing-in-opentelemetry) timestamp of the *second event* is greater than the *end_time* of the span itself. 
> Hence, it has been updated!
fixes : #2287 
cc : @svrnm @cartermp

updated trace timestamps

---

.prettierignore
content/en/docs/_index.md
content/en/docs/acknowledgements/_index.md
content/en/docs/contribution-guidelines.md
content/en/docs/getting-started/_index.md
content/en/docs/getting-started/dev.md
content/en/docs/getting-started/ops.md
content/en/docs/k8s-operator/_index.md
content/en/docs/migration/opentracing.md
content/en/docs/reference/specification/status.md
content/en/docs/workshop/resources.md

- Enables format checking over the following under `/content/en/docs`:
- `_index.md`
- `acknowledgements`
- `contribution-guidelines.md`
- `getting-started`
- `k8s-operator`
- `migration`
- `reference`
- `workshop`
Preview: https://deploy-preview-2309--opentelemetry.netlify.app/docs

Enable Prettier check over some /docs

---

assets/scss/_styles_project.scss

- Closes #2281?
@mviitane WDYT?
- This doesn't provide a pop-up, but I'd suggest we create a separate issue for that.
- **Preview**: https://deploy-preview-2317--opentelemetry.netlify.app/docs/demo/architecture/
> <img width="1000" alt="image" src="https://user-images.githubusercontent.com/4140793/217974980-294bc930-c295-4b47-b5e0-5e139067cb12.png">
> <img width="1797" alt="image" src="https://user-images.githubusercontent.com/4140793/217975048-a73a284b-6d8f-4005-bcad-5a38de195c64.png">
> <img width="1458" alt="image" src="https://user-images.githubusercontent.com/4140793/217975252-098aa07f-0a7e-4e8f-85a4-75de023ed853.png">

Demo docs: fix architecture diagram layout

---

assets/scss/_styles_project.scss

- Closes #2281?
- **Preview**: https://deploy-preview-2320--opentelemetry.netlify.app/docs/demo/architecture/
- Tested under Chrome, FF and Safari.
- For screenshots, see #2318.

Demo docs: fix mermaid diagram width on FF and Safari

---

README.md
content/en/ecosystem/registry/_index.md
content/en/ecosystem/registry/adding.md

- Moves the "how to add a registry entry" entry of the repo README into Ecosystem > Registry section under Adding
- Contributes to #2202
**Preview**:
- https://deploy-preview-2310--opentelemetry.netlify.app/ecosystem/registry/adding/
- https://deploy-preview-2310--opentelemetry.netlify.app/ecosystem/registry/

Move "how to add a registry entry" into website

---

content/en/docs/instrumentation/ruby/manual.md

Duplicate of PR #2321 
I had to close the above PR because EasyCLA didn't work.

docs: fix typo in ruby instrumentation

---

data/registry/tools-cpp-alpine-apk.yml
data/registry/tools-cpp-conan.yml
data/registry/tools-cpp-vcpkg.yml

Since I created one of them, I thought it would be great to have these different options to install OpenTelemetry C++ via package managers listed in our registry.
Source: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#using-package-managers

Add C++ packages to registry

---

content/en/blog/2023/otel-end-user-q-and-a-series-otel-and-graphql.md

Traces doesn't need to be capitalized everywhere.

minor fix to capitalization

---

content/en/docs/collector/transforming-telemetry.md

Have recently received feedback from several new collector users around usability of docs in the [various processors in collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor). Specifically, it's difficult to know where to start for some very simple (and common) use cases like adding an attribute to a span or filtering based on service name.
This PR proposes a new section under the collector docs called "Transforming telemetry" that documents some simple examples/use-cases and links to processors for more information. 
Goal of the doc isn't to exhaustively document all configurations or duplicate what is already in the contrib repo, but to provide a friendly "new to collector processors" introduction to users with some simple examples …

Add "transforming telemetry" section to collector docs 

---

content/en/docs/k8s-operator/automatic.md

Adds a section in the k8s operator instrumentation docs for Java.
Preview: https://deploy-preview-2253--opentelemetry.netlify.app/docs/k8s-operator/automatic/#java

[operator/java] Add instrumentation doc for java

---

data/registry/instrumentation-dotnet-honeycomb.yml
data/registry/instrumentation-go-honeycomb.yml
data/registry/instrumentation-java-honeycomb.yml
data/registry/instrumentation-js-node-honeycomb.yml

Follow-up from #2254
Streamline title and authors language across Honeycomb distros in the Registry.

[registry] streamline Honeycomb distro language

---

content/en/blog/2022/announcing-opentelemetry-demo-release.md
content/en/blog/2022/demo-announcement/index.md
content/en/blog/2022/frontend-overhaul/index.md
content/en/blog/2022/otel-demo-app-nomad/index.md
content/en/blog/2023/jmx-metric-insight/index.md
content/en/blog/2023/php-beta-release.md
content/en/docs/demo/architecture.md

- Contributes to #2289
- Replaces all (now invalid) external links to the former demo docs folder by local paths.
- Runs the formatter
Note that there's one change left, but it's in the scope of the earlier PR, #2342.

Fix broken external links to demo docs

---

content/en/docs/instrumentation/java/_index.md
content/en/docs/instrumentation/java/manual.md

It is best to keep things DRY and have a single "version" variable.
**Preview**:
- https://deploy-preview-2352--opentelemetry.netlify.app/docs/instrumentation/java/
- https://deploy-preview-2352--opentelemetry.netlify.app/docs/instrumentation/java/manual/ 
/cc @trask @svrnm

Java pages need only one version parameter

---

assets/scss/_styles_project.scss
content/en/blog/2022/why-and-how-ebay-pivoted-to-opentelemetry/index.md
content/en/docs/collector/configuration.md
content/en/docs/concepts/data-collection.md
content/en/docs/instrumentation/cpp/_index.md
content/en/docs/instrumentation/erlang/_index.md
content/en/docs/instrumentation/java/_index.md
content/en/docs/instrumentation/js/_index.md
content/en/docs/instrumentation/net/_index.md
content/en/docs/instrumentation/php/_index.md
content/en/docs/instrumentation/python/_index.md
content/en/docs/instrumentation/ruby/_index.md
content/en/docs/instrumentation/rust/_index.md
content/en/docs/instrumentation/swift/_index.md
hugo.yaml

- Closes #2358 using styles only. Maybe we can consider use of a render hook later.
- Ensures that image elements in markdown are treated as block-level elements
- Adds a light border around images, which is necessary (in most cases) when the image background is white. The border around barker images isn't a problem in general. 
- Supports an easy way to declare that an image:
- Shouldn't have a border by adding `{.border-0}` after an image. There's an example of this in the PR.
- Isn't a figure, by using the `img-initial ` class.
- Closes #2271
Preview:
- https://deploy-preview-2359--opentelemetry.netlify.app/blog/2022/otel-demo-app-nomad/#4--see-it-in-nomad - illustrates how most images benefit from a border. This was also the target of #2271
- …

Style inline images as blocks with a border

---

content/en/ecosystem/demo.md

https://github.com/open-telemetry/opentelemetry.io/issues/2317#issue-1578836510
What happened?
https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/current_architecture.md
returned 404
The link is not accessible from - https://opentelemetry.io/ecosystem/demo/

Updated broken architecture link

---

.prettierignore
content/en/docs/instrumentation/java/_index.md
content/en/docs/instrumentation/java/automatic/_index.md
content/en/docs/instrumentation/java/automatic/agent-config.md
content/en/docs/instrumentation/java/automatic/annotations.md
content/en/docs/instrumentation/java/getting-started.md
content/en/docs/instrumentation/java/manual.md
layouts/shortcodes/config_option.html

- Enables format checking over `instrumentation/java` section
- Replaces one `relref` link by standard markdown link
- Tweaked two code blocks (changed from console to shell)
Preview: https://deploy-preview-2363--opentelemetry.netlify.app/docs/instrumentation/java/

Enable Prettier check over instrumentation/java

---

.prettierignore
content/en/docs/instrumentation/net/_index.md
content/en/docs/instrumentation/net/automatic.md
content/en/docs/instrumentation/net/exporters.md
content/en/docs/instrumentation/net/getting-started.md
content/en/docs/instrumentation/net/libraries.md
content/en/docs/instrumentation/net/manual.md
content/en/docs/instrumentation/net/netframework.md
content/en/docs/instrumentation/net/resources.md
content/en/docs/instrumentation/net/shim.md

- Enables format checking over `instrumentation/net` section
- Replaces `relref` link(s) by standard markdown link(s)
- Adjusts some code-block languages
Preview: https://deploy-preview-2368--opentelemetry.netlify.app/docs/instrumentation/net/

Enable Prettier check over instrumentation/net

---

.htmltest.yml

- Closes #663
- Updates otel-go submodule
**Preview**: https://deploy-preview-2379--opentelemetry.netlify.app/docs/instrumentation/go/
/cc @open-telemetry/go-instrumentation-approvers

Update Go docs

---

assets/scss/_external_link.scss
assets/scss/_styles_project.scss
assets/scss/_variables_project.scss
content/en/blog/2023/http-conventions-stability.md
content/en/blog/2023/jmx-metric-insight/index.md
content/en/blog/2023/php-beta-release.md
content/en/blog/2023/submitting-your-first-conference-talk.md
content/en/docs/collector/configuration.md
content/en/docs/collector/custom-collector.md
content/en/docs/collector/getting-started.md
content/en/docs/collector/management.md
content/en/docs/collector/scaling.md
content/en/docs/collector/transforming-telemetry.md
content/en/docs/instrumentation/net/exporters.md
content/en/docs/k8s-operator/automatic.md
hugo.yaml
package.json

My original inclination (supported by @svrnm and @cartermp) was to opt for single quotes (https://github.com/open-telemetry/opentelemetry.io/pull/2290#discussion_r1098882987), but I reverted after seeing that YAML code blocks were being changed. Well, in retrospect (and given the situation we're facing in https://github.com/open-telemetry/opentelemetry.io/pull/2372#pullrequestreview-1306451171), I'd rather opt for single quotes for all (including JS code blocks, given that it's part of the OTel-JS standard).
WDYT @svrnm @cartermp?
This PR:
- Enables Prettier's single-quotes option
- Drops quotes from YAML code blocks in those situations where quotes are unnecessary
Two situations where I wasn't sure if the YAML key value type was important, so I didn't drop the …

Prettier: switch to single-quotes by default

---

.prettierignore
content/en/docs/instrumentation/js/_index.md
content/en/docs/instrumentation/js/context.md
content/en/docs/instrumentation/js/examples.md
content/en/docs/instrumentation/js/exporters.md
content/en/docs/instrumentation/js/getting-started/_index.md
content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/js/instrumentation.md
content/en/docs/instrumentation/js/libraries.md
content/en/docs/instrumentation/js/propagation.md
content/en/docs/instrumentation/js/resources.md
content/en/docs/instrumentation/js/serverless.md

- Enables format checking over `instrumentation/js` section
- Replaces `relref` link(s) by standard markdown link(s)
- Copyedits (minor)
⚠️ **Note**: code excerpts in code blocks also get reformatted per Prettier rules.
Preview: https://deploy-preview-2372--opentelemetry.netlify.app/docs/instrumentation/js/

Enable Prettier check over instrumentation/js

---

.prettierignore
content/en/docs/instrumentation/cpp/exporters.md
content/en/docs/instrumentation/cpp/getting-started.md
content/en/docs/instrumentation/cpp/manual.md

- Enables format checking over `instrumentation/cpp` section
- Fixes code-block languages for commands
Preview: https://deploy-preview-2389--opentelemetry.netlify.app/docs/instrumentation/cpp/

Enable Prettier check over instrumentation/cpp

---

.prettierignore
content/en/docs/instrumentation/erlang/_index.md
content/en/docs/instrumentation/erlang/getting-started.md
content/en/docs/instrumentation/erlang/instrumentation.md
content/en/docs/instrumentation/erlang/testing.md

- Enables format checking over instrumentation sections for Erlang/Elixir
- Fixes code-block languages for commands (inside `ot-tabs`)
- Replaces `relref` link(s) by standard markdown link(s)
Preview: https://deploy-preview-2393--opentelemetry.netlify.app/docs/instrumentation/erlang/

Enable Prettier check over instrumentation/erlang

---

.prettierignore
content/en/docs/instrumentation/go
hugo.yaml

- In preparation for #2380
- Deletes the `/content/en/docs/instrumentation/go` symlink
- (Hugo) mounts the Go `website_docs` as `/content/en/docs/instrumentation/go`
- There is no net change in the generated site files (Other than reordering of redirect rules and changes in .xml files)

Mount Go website_docs rather than symlink to it

---

.prettierignore
content/en/docs/concepts/data-collection.md
content/en/docs/concepts/distributions.md
content/en/docs/concepts/glossary.md
content/en/docs/concepts/instrumenting-library/index.md
content/en/docs/concepts/instrumenting.md
content/en/docs/concepts/observability-primer.md
content/en/docs/concepts/sdk-configuration/_index.md
content/en/docs/concepts/sdk-configuration/general-sdk-configuration.md
content/en/docs/concepts/sdk-configuration/otlp-exporter-configuration.md
content/en/docs/concepts/semantic-conventions.md
content/en/docs/concepts/signals/baggage.md
content/en/docs/concepts/signals/logs.md
content/en/docs/concepts/signals/metrics.md
content/en/docs/concepts/signals/traces.md
content/en/docs/concepts/what-is-opentelemetry.md

- Enables format checking over concepts section
- Replaces `relref` link(s) by standard markdown link(s)
- Normalizes some front matter
Preview: https://deploy-preview-2399--opentelemetry.netlify.app/docs/concepts/

Enable Prettier check over concepts section

---

.prettierignore

- Enables format checking over `instrumentation/go` section, which is a mount of otel-go content-module's `website_docs` folder
- Updates Go submodule to latest, in particular, bring in:
- https://github.com/open-telemetry/opentelemetry-go/pull/3762
Preview: https://deploy-preview-2380--opentelemetry.netlify.app/docs/instrumentation/go

Enable Prettier check over instrumentation/go & update go

---

content/en/ecosystem/vendors.md
data/registry/tools-traceloop.yml
static/refcache.json

Adds Traceloop (www.traceloop.dev) to vendors list and registry.

add traceloop to vendors table and registry

---

content/en/docs/collector/configuration.md

Remove suffix  `/v1/traces` from endpoint url, as the collector is automatically adding `/v1/traces` and cannot send the trace otherwise, as the url would be `http://localhost:4318/v1/traces/v1/traces` and fails.
Change from:
```yaml
otlphttp:
endpoint: http://localhost:4318/v1/traces
```
To:
```yaml
otlphttp:
endpoint: http://localhost:4318
```
<details>
<summary>Error</summary>
2023-02-27T07:39:22.117Z	error	exporterhelper/queued_retry.go:401	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "traces", "name": "otlphttp/1", "error": "Permanent error: error exporting items, request to http://localhost:4318/v1/traces/v1/traces responded with HTTP Status Code 404", "dropped_items": 30}
2023-02-27T07:39:22.118798298Z …

Fix Collector endpoint URL

---

content/en/blog/2023/new-apac-meetings.md

- Applies edits (suggested by @codeboten) marked resolved in #2385, but that didn't show up in the final text of that PR
- Followup to #2410 
- Renames the file (and adds an alias) to better correspond to the updated title

Blog: apply missing updates to "New APAC Collector-SIG meetings"

---

.htmltest.yml

- Closes #2203
**Preview**: https://deploy-preview-2411--opentelemetry.netlify.app/docs/instrumentation/go/exporters/

Fix link to Traces concepts page in Go docs

---

data/instrumentation.yaml

* From what I can tell Rust's status was incorrectly marked as stable. 
** Introduced in #1732 as what might be a typo.
Opened ticket on open-telemetry/opentelemetry-rust#977 to verify.

Set correct stability for Rust

---

content/en/docs/collector/getting-started.md

Add depth 1 to git clone in demo section for faster clone and smaller repo size.

Add depth 1 to git clone for collector demo

---

content/en/docs/collector/trace-receiver.md

This PR is to address outdated trace receiver documentation. Recently I followed this document, and a lot of interfaces and implementations were outdated. Thanks to some knowledge I have about the collector, I was able to find the issues in the document and implement a receiver. As a result I thought I would update the document to reflect these latest changes.
- dev-otelcol changed to otelcol-dev to align with [custom-collector document](https://opentelemetry.io/docs/collector/custom-collector/)'s update.
- updated implementation details, aligning them with the most recent refactoring in the code base of open telemetry collector.
- tested the updated document on myself by following the steps from scratch.
Here is the link to the updated page via netlify: …

Update trace receiver documentation to align with the most recent updates to open telemetry collector.

---

content/en/docs/collector/trace-receiver.md

- Followup to #2190
- Drops local `collectorVersion`
- Fixes code-block lang for command blocks
- Applies some minor copyedits
**Preview**: https://deploy-preview-2427--opentelemetry.netlify.app/docs/collector/trace-receiver/

Collector trace-receiver: reapply lost changes + copyedits

---

content/en/community/end-user/_index.md

Adds a link to the newly added page about user interview/feedback sessions (https://github.com/open-telemetry/opentelemetry.io/pull/2297).

Add link to interview/feedback sessions resource

---

content/en/docs/instrumentation/php/exporters.md
content/en/docs/instrumentation/php/getting-started.md
content/en/docs/instrumentation/php/manual.md
content/en/docs/instrumentation/php/propagation.md
content/en/docs/instrumentation/php/resources.md
static/refcache.json

**Preview**: https://deploy-preview-2415--opentelemetry.netlify.app/docs/instrumentation/php/

adding PHP documentation for exporters, resources, propagation

---

content/en/docs/instrumentation/js/instrumentation.md
content/en/docs/instrumentation/js/propagation.md
content/en/docs/instrumentation/js/serverless.md

I was working on adding a gauge to an example app and realized these docs had a mis-typed variable name. In my drive-by I updated a few other typos as well. Changes made:
- Update two variable names used in the JS metrics docs
- Fix a few typos I came across in the process

Update JS docs for examples and typos

---

assets/scss/_registry.scss
assets/scss/_variables_project.scss

- Contributes to #2419
- Closes #2439
- Places OTel specific colors into maps
- Drops unused SCSS variables and classes
- Generates OTel badge colors by iterating over the appropriate color map
**Preview**:
In particular, you'll note that badge colors have not changed:
- Before: https://opentelemetry.io/ecosystem/registry/
- After https://deploy-preview-2440--opentelemetry.netlify.app/ecosystem/registry/

SCSS variable cleanup in prep for Docsy upgrade

---

content/en/blog/2023/otel-in-focus-02.md

What you think about **linking core components** to their **website landing pages** -- @austinlparker @svrnm @cartermp? This makes it easier for readers to find out more about the component.
Here's a screenshot of what it could look like:
> <img width="787" alt="image" src="https://user-images.githubusercontent.com/4140793/222709322-2ba18e2d-b914-48ee-ac40-ce2f22f2e619.png">
In contrast, this is what is was before this PR:
> <img width="800" alt="image" src="https://user-images.githubusercontent.com/4140793/222708562-98068ac0-7754-40b8-851d-d689013ae764.png">
Note that I moved the PHP news into the Releases and Updates section.

OTel-in-focus: link core components to website section

---

.htmltest.yml
content/en/docs/demo/features.md
content/en/ecosystem/integrations.md
static/refcache.json

- Closes #2361
- Contributes to #2429
/cc @svrnm

Fix links in demo features and integrations pages

---

.htmltest.yml
static/refcache.json

See https://github.com/open-telemetry/opentelemetry-specification/pull/3285

Update OpenTelemetry submodule to include the 1.19.0 schema.

---

content/en/blog/2022/k8s-otel-expose/index.md
content/en/docs/instrumentation/cpp/_index.md
content/en/docs/instrumentation/erlang/_index.md
content/en/docs/instrumentation/java/_index.md
content/en/docs/instrumentation/js/_index.md
content/en/docs/instrumentation/net/_index.md
content/en/docs/instrumentation/php/_index.md
content/en/docs/instrumentation/python/_index.md
content/en/docs/instrumentation/ruby/_index.md
content/en/docs/instrumentation/rust/_index.md
content/en/docs/instrumentation/swift/_index.md
package.json

- Closes #2452
- Upgrades to [Hugo 0.111.1](https://github.com/gohugoio/hugo/releases/tag/v0.111.1)
- Fixes a bug in a page that was missing an end-tag marker for a shortcode
- Fixes YAML sample in 2022 blog since some of the content is meant to be in comments (and otherwise results in pretty-printed YAML).
- Drops unnecessary quotes around shortcode arguments
The only changes to the generated site files, other than the updated Hugo version, are due to pretty-printer changes and the YAML fragment update:
```console
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0\.") | grep ^diff | grep -v \.xml
diff --git a/blog/2022/k8s-otel-expose/index.html b/blog/2022/k8s-otel-expose/index.html
diff --git a/docs/demo/services/shipping/index.html b/docs/demo/services/shipping/index.html …
```

Upgrade Hugo to 0.111.1 and fix doc issues

---

data/instrumentation.yaml

Towards https://github.com/open-telemetry/opentelemetry-go/issues/3830
Preview: 
1. https://deploy-preview-2451--opentelemetry.netlify.app/docs/instrumentation/go/#status-and-releases
2. https://deploy-preview-2451--opentelemetry.netlify.app/docs/instrumentation/
PTAL @open-telemetry/go-approvers

Update OTel Go metrics status to beta

---

content/en/docs/collector/troubleshooting.md

This adds a short page that generally points users to the existing collector [troubleshooting docs](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md).
Two minor additions not covered in the main doc:
- Specifically calls out the "sending test data"/local exporter guidance (anecdotally a useful troubleshooting step for users doing first-time collector setup and not seeing data)
- Adds a high-level checklist of things to verify for complex setups (collectors to collectors, etc)
Think a future section that goes deeper into collector observability would be a great future addition.
---
Preview: https://deploy-preview-2382--opentelemetry.netlify.app/docs/collector/troubleshooting/

Add "collector troubleshooting" doc

---

content/en/blog/2022/why-and-how-ebay-pivoted-to-opentelemetry/index.md

- Closes #2461
- **Preview**: https://deploy-preview-2462--opentelemetry.netlify.app/blog/2022/why-and-how-ebay-pivoted-to-opentelemetry/#limitations-of-metrics-scraping-via-daemonsets
---
Before:
> <img width="500" alt="image" src="https://user-images.githubusercontent.com/4140793/223567588-600670f5-4777-4306-9410-9348c0e02f69.png">
After:
> <img width="500" alt="image" src="https://user-images.githubusercontent.com/4140793/223569193-6e8ce9d8-abf2-43c0-a6fb-03213829f25c.png">

Blog: fix borderless images

---

content/en/blog/2023/otel-in-focus-01.md
content/en/blog/2023/otel-in-focus-02.md

- Addresses https://github.com/open-telemetry/opentelemetry.io/pull/2444#issuecomment-1454728160
- Drops the in-page `<style>`s
- Reformats the latest OTel-in-focus post, replacing the definition list by plain level-5 headings (which don't appear in the ToC) and section text. (Btw, we don't want the headings to appear in the ToC because the headings contain links and the ToC element doesn't handle links gracefully.)
- Makes a few copyedits
Preview: https://deploy-preview-2465--opentelemetry.netlify.app/blog/2023/otel-in-focus-02/

Styling fix for OTel in focus

---

content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/getting-started/nodejs.md

[Node is hit a lot more in our docs](https://play.honeycomb.io/opentelemetry-web/datasets/opentelemetry.io/result/ENZskzNonnB?useStackedGraphs). From my own work, I can also say that teams using node are ~4.5x more numerous than teams sending instrumentation from the browser. So let's have the TOC reflect that.

Order node.js over browser for TOC

---

content/en/docs/concepts/sampling/index.md

Fixes https://github.com/open-telemetry/opentelemetry.io/issues/2457
This still leaves our sampling docs in a very, very incomplete state. But in the name of incremental progress, here's something.
Preview: https://deploy-preview-2463--opentelemetry.netlify.app/docs/concepts/sampling/

Add head sampling section + elaborate tail sampling

---

content/en/docs/instrumentation/python/automatic/agent-config.md

- Followup to #2272
- Context: https://github.com/open-telemetry/opentelemetry.io/pull/2272#pullrequestreview-1333092435
- Adjusts headings:
- Drops top-level heading (the only h2 heading) at the start of the page since it's redundant relative to the page title
- Promotes all remaining h3 headings to h2
- Makes a few copyedits
- Fixes a link so that it refers to the local spec page.
- **Preview**: https://deploy-preview-2475--opentelemetry.netlify.app/docs/instrumentation/python/automatic/agent-config/
/cc @cartermp

Python agent config headings clean up

---

content/en/docs/instrumentation/js/getting-started/nodejs.md

Several things here:
* Doesn't introduce people to the confuse-o-tron of different SDK packages and exporters just yet, sticking just with the defaults the Node SDK gives you
* Shortens width of install sections
* Expands SDK init promise-y kinda stuff
* Uses latest packaging
* Removes diagnostic logging in the main example and just keeps that to the troubleshooting section below

Cleanup + correct node getting started

---

assets/scss/_registry.scss
assets/scss/_variables_project.scss

- Prep for #2419
- Adds a badge color class for `resource-detector`
- Adds default badge color attributes in case we miss a component again
- **Preview**: https://deploy-preview-2481--opentelemetry.netlify.app/ecosystem/registry/?component=resource-detector
---
Before:
> <img width="918" alt="image" src="https://user-images.githubusercontent.com/4140793/224451004-d2be3c49-846b-4a39-91a7-f0ae8fe76dad.png">
After:
> <img width="908" alt="image" src="https://user-images.githubusercontent.com/4140793/224451039-60fd94ff-cfa5-4856-8f83-8fdabf4d9059.png">

Add entry for missing OTel component color

---

layouts/_default/_markup/render-link.html
scripts/content-modules/adjust-pages.pl

- Contributes to #2429
- Warns if a spec page contains an external URL to a local spec page, and then translates the external URL into a local path reference.
- Hugo reports an error if a website page contains an external URL to a local spec page

Report issue if an external link is used to a local spec page

---

assets/js/registrySearch.js
assets/scss/_styles_project.scss
content/en/_index.md
content/en/docs/getting-started/_index.md
content/en/ecosystem/registry/_index.md
content/en/status.md
layouts/shortcodes/registry-search-form.html
static/refcache.json

- A core contribution to #2419
- More changes will follow, but this seems ready for fielding
- Main OTel-specific change was to rework the registry form and entry display:
- Note: entry description markdown is now rendered in the original entry list. I still need to fix the `fuse.js`-generated entries, as noted in #2491
> **⚠️ NOTE:** website contributors should run the following commands after this PR gets merged:
> 
> ```console
> $ nvm use
> $ npm install
> ```
@svrnm @cartermp - I've walked through most of the site and addressed all problems or created a corresponding issue. PTAL. Note that slight layout changes are to be expected, a result of Bootstrap style tweaks.
**Preview**: https://deploy-preview-2490--opentelemetry.netlify.app/

Docsy upgrade including Bootstrap v5

---

layouts/_default/_markup/render-link.html

- The site build fails under Windows, apparently because of the difference in behavior of the [adjust-pages.pl](https://github.com/open-telemetry/opentelemetry.io/blob/main/scripts/content-modules/adjust-pages.pl) script.
- For now, turn those errors into warnings. I'll reintroduce the errors separately, via: #2448
- Contributes to #2448
/cc @svrnm @tsloughter

CI: warn about external links to local pages rather than abort with an error

---

content/en/_index.md
content/en/ecosystem/demo.md

- Changes homepage demo button link to refer to the demo docs
- Crosslinks [/ecosystem/demo](https://deploy-preview-2502--opentelemetry.netlify.app/ecosystem/demo/) and [/docs/demo](https://deploy-preview-2502--opentelemetry.netlify.app/docs/demo/)
- Copyedits to `/ecosystem/demo` page: add links to "more info" through demo docs and demo repo
Preview:
- https://deploy-preview-2502--opentelemetry.netlify.app/
- https://deploy-preview-2502--opentelemetry.netlify.app/docs/demo/
- https://deploy-preview-2502--opentelemetry.netlify.app/ecosystem/demo/

Link homepage demo CTA button to demo docs

---

content/en/docs/demo/docker-deployment.md
content/en/docs/demo/kubernetes-deployment.md

- Reworks layout of steps in docker page
- Fix indentation of code blocks
- Some minor copyedits
**Preview**:
- https://deploy-preview-2503--opentelemetry.netlify.app/docs/demo/docker-deployment/
- https://deploy-preview-2503--opentelemetry.netlify.app/docs/demo/kubernetes-deployment/
---
Before:
> <img width="957" alt="image" src="https://user-images.githubusercontent.com/4140793/224860700-efb147a8-f5b7-49e0-8e96-d1d85ab01071.png">
After:
> <img width="1159" alt="image" src="https://user-images.githubusercontent.com/4140793/224860765-f00af0f5-3b92-405a-a24e-c57f395f8590.png">

Copyedits of demo deployment pages

---

content/en/docs/instrumentation/ruby/api.md

This appears to be the right place

Point to rubydoc for ruby API

---

assets/scss/_styles_project.scss
layouts/shortcodes/registry-search-form.html

- Closes #2509
- Why did this happen? Because Go templates escape content based on context. For details see:
- https://gohugo.io/functions/safehtmlattr/
- https://discourse.gohugo.io/t/avoid-string-variable-escaping/13244/11
To test this fix:
- Visit https://deploy-preview-2511--opentelemetry.netlify.app/ecosystem/registry/?s=kotlin
- Click on any of the links in the search results

Registry search results: fix Fuse template

---

content/en/docs/instrumentation/js/getting-started/nodejs.md

I ran into this earlier while using vanilla JS (it crashed on the `then`)
And just now when using TS it says `start` returns void.

SDK.start doesn't seem to return a promise

---

content/en/docs/instrumentation/ruby/_index.md

- Contributes to #2512, maybe closes it
- Drops links to API and Examples in Ruby landing page text, since they appear in the left-nav and the page listing at the bottom of the page (see the screenshot below)
**Preview**: https://deploy-preview-2515--opentelemetry.netlify.app/docs/instrumentation/ruby/
> <img width="1179" alt="Screen Shot 2023-03-15 at 13 37 55" src="https://user-images.githubusercontent.com/4140793/225395955-ec297769-2f3e-413d-8ddb-d0d8bae6373e.png">
/cc @cartermp

Ruby landing page cleanup of links to API ref and examples

---

.github/workflows/pr-actions.yml

- A first attempt at a comment-triggerable bot action to reformat files in a PR.
- Contributes to #2448

PR-actions workflow with support for `/fix:format`

---

content/en/blog/2022/otel-demo-app-nomad/index.md
static/refcache.json

- Contributes to #2429
- Copyedits
**Preview**: https://deploy-preview-2522--opentelemetry.netlify.app/blog/2022/otel-demo-app-nomad/

Adjust blog to use local link path to homepage and demo

---

content/en/docs/demo/kubernetes-deployment.md

Fixes [#776 from the demo repo](https://github.com/open-telemetry/opentelemetry-demo/issues/776). 
Now that the demo has standard Kubernetes manifests part of it, we can include instructions on installing using `kubectl`.
Also updates the requirement for Helm to 3.9+

[demo] add kubectl install instructions

---

content/en/ecosystem/vendors.md

- Temporary "fix" (until the Vendors table is data driven) to avoid rebase conflicts when entries are added to the vendor table via separate commits: don't run the formatter over the vendor table.
- Trimmed `https://` from the start of the link text (not the link URL) of the new ITRS entry.
- Dropped the trailing `|` from the end of the table markdown to make it easier to add entry (and not worry about padding the last row cell with spaces.
- Other than that the table entries are the same
- Kinda contributes to #2178

Don't format the Vendors table

---

content/en/blog/2023/php-auto-instrumentation/index.md

thanks to @mhausenblas for calling this out.

Minor fixes for php blog post

---

.vscode/cspell.json
content/en/_index.md
content/en/blog/2022/otel-demo-app-nomad/index.md
content/en/docs/_index.md
content/en/docs/concepts/_index.md
content/en/docs/concepts/glossary.md
content/en/docs/concepts/observability-primer.md
content/en/docs/concepts/signals/traces.md
content/en/docs/demo/_index.md
content/en/docs/getting-started/_index.md
content/en/docs/getting-started/dev.md
content/en/docs/getting-started/ops.md
content/en/docs/instrumentation/erlang/instrumentation.md
content/en/docs/instrumentation/java/automatic/annotations.md
content/en/docs/instrumentation/java/manual.md
content/en/docs/instrumentation/js/instrumentation.md
content/en/docs/instrumentation/js/libraries.md
content/en/docs/instrumentation/net/getting-started.md
content/en/docs/instrumentation/net/libraries.md
content/en/docs/instrumentation/net/manual.md
content/en/docs/instrumentation/net/shim.md
content/en/docs/instrumentation/php/manual.md
content/en/docs/instrumentation/python/manual.md
content/en/docs/instrumentation/ruby/manual.md
content/en/docs/instrumentation/swift/manual.md
content/en/docs/what-is-opentelemetry.md

- (**Main change**) **Moves "What is OpenTelemetry?" to the top level,** out of "Concenpts".
- Adds a "What next?" section at the end of the "What is OpenTelemetry?" page
- Changes homepage "Learn more" link to "What is OpenTelemetry?"
- **Getting-started pages for Dev and Ops** pages:
- Moves each page description into main text, reformatted as a bulleted list, following the new introductory sentence "This is the getting-started page for you if:"
- In the docs left nav: relocates the demo docs to be just below "Concepts"
- Traces signal page:
- Fixes #2558
- Renames "Spans in OpenTelemetry" section to just "Spans" (to be consistent with other section headings)
- Tweaks "Concepts" page title, description, and introductory paragraph
- Makes other copyedits
**Preview**:
- …

Docs flow fix for beginners, move "What is OpenTelemetry?" to top level

---

content/en/docs/instrumentation/php/getting-started.md
content/en/docs/instrumentation/php/logging.md
content/en/docs/instrumentation/php/manual.md
content/en/docs/instrumentation/php/sdk.md
data/instrumentation.yaml
static/refcache.json

as PHP moves closer to GA, it's time to migrate a bunch of
existing documentation from our main readme over to opentelemetry.io
https://github.com/open-telemetry/opentelemetry-php/pull/946 is the related PR where content is being removed from opentelemetry-php's readme and linked back to opentelemetry.io or removed completely. Trying to promote opentelemetry.io as the official source of doco.
---
Preview: https://deploy-preview-2552--opentelemetry.netlify.app/docs/instrumentation/php/

PHP instrumentation improvements

---

content/en/docs/instrumentation/python/exporters.md

- Fixes #2549
---
Preview: https://deploy-preview-2551--opentelemetry.netlify.app/docs/instrumentation/python/exporters/#temporality-presets

Document temporality presets in Python

---

content/en/docs/k8s-operator/automatic.md

Adds a section in the k8s operator instrumentation docs for dotnet.
---
Preview: https://deploy-preview-2565--opentelemetry.netlify.app/docs/k8s-operator/automatic/#net

[operator/dotnet] Add instrumentation docs for dotnet

---

content/en/blog/2023/kubecon-eu.md

This is to reflect the most recent change to the schedule (see [here](https://sched.co/1JWS7)).

Update time for OTel Project Meeting

---

layouts/partials/banner.md

The event is less than two weeks away, it seems that a switch in banner might be in order? /cc @cartermp @svrnm @austinlparker
**Preview**: https://deploy-preview-2579--opentelemetry.netlify.app/

Add banner for KubeCon EU '23

---

content/en/docs/concepts/instrumenting-library/index.md

@chalin stated that
> the status being referred to in "Metrics API is not
> stable" is the implementation across supported languages: which is about
> 50% at the moment -- that is 50% of languages have "stable" metrics in
> contrast to some other status (beta, alpha, experimental or not
> implemented). So, in a sense, the statement is 50% correct 😅.
and @cartermp suggested that we remove the problematic paragraph and section altogether.
See: https://github.com/open-telemetry/opentelemetry.io/issues/2575
cc: @alolita

Remove metrics section in instrumenting library

---

content/en/docs/reference/specification/status.md
static/refcache.json

See:
- https://github.com/open-telemetry/opentelemetry-specification/pull/3364
**Preview**:
- https://deploy-preview-2584--opentelemetry.netlify.app/docs/reference/specification/
- https://deploy-preview-2584--opentelemetry.netlify.app/docs/reference/specification/status/

Update OTel spec submodule to include the 1.20.0 schema.

---

content/en/docs/instrumentation/ruby/getting-started.md

Ruby 2.7 support dropped by the maintainers as of March 31, 2023. The 2.7 support has been removed from the Ruby OTel libraries as part of https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/389

Set MRI ruby limit to >= 3.0

---

content/en/docs/instrumentation/js/exporters.md
content/en/docs/instrumentation/js/getting-started/nodejs.md

The auto instrumentation for http/express in Node.JS provides some out of the box metrics. By initializing a metricReader & exporter they get print out in the getting started. 
I also updated the exporters file accordingly  
Preview: 
* https://deploy-preview-2576--opentelemetry.netlify.app/docs/instrumentation/js/getting-started/nodejs/
* https://deploy-preview-2576--opentelemetry.netlify.app/docs/instrumentation/js/exporters/

Add metrics to JS getting started

---

content/en/docs/k8s-operator/automatic.md

Annotation used to carry our auto instrumentation can take other values beyond `true` as mentioned here https://github.com/open-telemetry/opentelemetry-operator/blob/main/README.md#opentelemetry-auto-instrumentation-injection
It would be helpful if documented these in the main documents.

Added section describing possible values for `Instrumentation` annotation

---

content/en/docs/collector/getting-started.md

The existing URL returns a not found. I have verified that the new URL is valid and correct in both bash and ZSH.

Fix collector download URL for macOS

---

package.json

Inspired by my recent misadventure of running:
```
npm run format
npm run format:write
npm run prettier:write
```
because I don't read instructions, I expect others won't, so here's an attempt to help things

Also add format commands

---

content/en/docs/instrumentation/python/_index.md

- This is a proposed fix for #2354
- Drops the link to the benchmarks page, which is currently offline. For context, see https://github.com/open-telemetry/opentelemetry.io/issues/2354#issuecomment-1503969450.
- Fixes code-blocks for commands: changes the language and drops prompts since the blocks contain no command output
- Other minor copyedits
**Preview**: https://deploy-preview-2598--opentelemetry.netlify.app/docs/instrumentation/python/

Drop link to Python benchmarks, and copyedits

---

content/en/ecosystem/vendors.md
static/refcache.json

[Teletrace](https://github.com/teletrace/teletrace) is an open-source tracing platform. In short, the project architecture includes an [OTel distribution](https://github.com/teletrace/teletrace/tree/main/teletrace-otelcol), query backend, and a UI.

Add Teletrace to vendor list

---

.htmltest.yml
.vscode/cspell.json
content/en/blog/2023/ecs-otel-semconv-convergence.md
static/refcache.json

The stakeholders of ECS (Elastic Common Schema) and OpenTelemetry have been making progress since the past 12 months with the outcome of [OTEP 199](https://github.com/open-telemetry/oteps/pull/222). Since the OTEP 199 got approved/merged, we've had multiple discussions among the ECS stakeholders from Elastic, OpenTelemetry GC (Governance Committee) and TC (Technical Committee) members, now we've reached to a point that we are ready to publicly announce this merge in the upcoming [EU KubeCon](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/) event ❤️🍾🥳!
The plan is that Elastic and OpenTelemetry will each publish an official post/announcement at **7am Amsterdam time on April 18th which is 10pm PT on April 17th** (right before KubeCon). This PR covers the blog post from …

Blog post regarding ECS and OTel SemConv Convergence

---

.htmltest.yml
content/en/community/end-user/community-feedback-survey.md
content/en/community/end-user/discussion-group.md
content/en/community/end-user/feedback-survey.md
content/en/community/end-user/interviews-feedback.md
content/en/community/end-user/otel-in-practice.md
content/en/community/end-user/slack-channel.md

@tedsuo what we discussed today at the booth
@open-telemetry/end-user-wg please take a look. The idea is to have an alias for the End-User Feedback Survey, easier to memorize than the long google docs URL. 
Previews:
https://deploy-preview-2615--opentelemetry.netlify.app/community/
&
https://deploy-preview-2615--opentelemetry.netlify.app/community/end-user/feedback-survey/
&
https://deploy-preview-2615--opentelemetry.netlify.app/community-feedback/
Final URLs will replace with "opentelemetry.io" so we will have `opentelemetry.io/community-feedback`. 
We could go even shorter, `opentelemetry.io/feedback` ?

Add link to community feedback survey

---

content/en/docs/instrumentation/php/getting-started.md

Fixes a typo in the composer command / package name

docs: fix typo in getting-started.md

---

content/en/docs/reference/specification/status.md

The Logs Bridge API / SDK is now [stable](https://github.com/open-telemetry/opentelemetry-specification/pull/3376)! Updating the specification status document text to reference the document status from the spec, and updating the text to reflect the current status of things.

Update log status

---

content/en/blog/2023/sunsetting-opencensus.md
static/refcache.json

**Please publish on Monday, May 1**
https://deploy-preview-2629--opentelemetry.netlify.app/blog/2023/sunsetting-opencensus/

Add "Sunsetting OpenCensus" blog post

---

data/registry/exporter-go-otlpr.yml
static/refcache.json

[`otlpr`](https://github.com/MrAlias/otlpr) is a 3rd-party, open source, Go project that provides a [logr.Logger](https://pkg.go.dev/github.com/go-logr/logr#Logger) that exports messages as OTLP logs.

Add registry entry for otlpr

---

.htmltest.yml
content/en/docs/migration/_index.md
content/en/docs/migration/opencensus.md
content/en/docs/migration/opentracing.md
static/refcache.json

Some incremental improvements for migration docs:
* Some introduction for where Otel comes from and why we provide oc & ot migration (copied some of your words @aabmass, hope that's OK :))
* Also some words about jaeger (copied from the jaeger docs (cc @pavolloffay) & @jpkrohling [blog post](https://medium.com/jaegertracing/migrating-from-jaeger-client-to-opentelemetry-sdk-bd337d796759))
* Linked to the spec for OpenCensus for now, not sure if this works in the long run and if we might need a separate migration guide like we have one for ot

Incremental improvements for migration docs

---

.github/workflows/auto-update-versions.yml
.github/workflows/scripts/auto-update-version.sh

- Prep for #2387
- When searching for version fields, the script now only matches:
- At word boundaries (for the "variable" name)
- An entire line
- Executes `git reset --hard origin/main` at the start of the script when run GH
- Adds support for running the script locally (macOS and Linux)
- When run locally, the script defaults to a dry run. Use `-f` to force a regular run.
/cc @trask

Auto-update script: only match whole words, and other improvements

---

scripts/content-modules/adjust-pages.pl

Hi @open-telemetry/specs-approvers: before setting up a script to automatically fetch the latest version of the spec (#2387), I wanted to ensure that we agreed on how the version will be displayed. This PR is such a proposal, it:
- Adds the spec version to:
- The Spec landing page title -- see the preview
- The `linkTitle` so that the version appears in the:
- Left sidenav
- Breadcrumbs, and hence in every spec page
- Contributes to #2387
**Preview**: https://deploy-preview-2666--opentelemetry.netlify.app/docs/reference/specification/
> <img width="1562" alt="Screen Shot 2023-05-07 at 15 05 08" src="https://user-images.githubusercontent.com/4140793/236697603-8fd4fec3-77b4-40c9-bbf7-053e121f0234.png">
/cc @open-telemetry/specs-approvers @tigrannajaryan

Spec: add version to title

---

.gitmodules
.htmltest.yml
content/en/docs/instrumentation/erlang/getting-started.md
content/en/docs/instrumentation/erlang/propagation.md
content/en/docs/instrumentation/js/instrumentation.md
content/en/docs/reference/_index.md
content/en/docs/specification/_index.md
content/en/docs/specification/otel/status.md
hugo.yaml
layouts/index.redirects
layouts/shortcodes/spec_status.html
scripts/content-modules/adjust-pages.pl
scripts/content-modules/cp-pages.sh

- Prep for #2642
- Adds OTLP repo as a submodule under `content-modules/opentelemetry-proto`
Note: the content is not yet displayed, this PR only adds the submodule
- Moves `/docs/reference/specification` to `/docs/specification/otel`
- Accordingly adjusts some links to refer to the new OTel spec home, but not all (I've temporarily added an ignore rule to the link checker config)
**Preview**:
- https://deploy-preview-2677--opentelemetry.netlify.app/docs/specification
- https://deploy-preview-2677--opentelemetry.netlify.app/docs/specification/otel/
**Redirect rule tests**:
- https://deploy-preview-2677--opentelemetry.netlify.app/docs/reference
- https://deploy-preview-2677--opentelemetry.netlify.app/docs/reference/specification
- https://deploy-preview-2677--opentelemetry.netlify.app/docs/r …

Rename reference/spec to specification/otel and add OTLP submodule 

---

content/en/ecosystem/vendors.md

Incorrectly stated the new product name updated to state current and prior company using the format for Aria/wavefront.

Disambiguate LogScale company

---

content/en/docs/instrumentation/python/getting-started.md

Issue number: #2687 
Changes:
Added double quotes to make sure that example will work.

Docs: fix getting started with Python example

---

scripts/content-modules/adjust-pages.pl
scripts/content-modules/cp-pages.sh

Some spec page links to GitHub page source were broken by #2677. This fixes those links and brings in a bit more code in prep for hosting the OTLP spec pages.
This PR impacts only the OTel spec pages and only the GH link URLs.
```console
$ cd public
$ g diff | grep ^diff | grep -v 'docs/spec' # only spec pages are affected
$ g diff | grep ^diff | wc -l                                   
96
$ g diff | grep ^diff | grep -E '^diff.*index.html$' | wc -l    # only index pages are affected
96
$ g diff -I 'View page source|Edit this page| Create child page' # only the GH links are affected
$
```
Contributes to:
- #2642
/cc @tigrannajaryan

Fix OTel spec links to page source

---

content/en/docs/instrumentation/python/getting-started.md

1. Added surrounding double quotes to the metrics example.
2. Added port flag instructions to all flask run instances.

Python getting started: use port 8080 consistently

---

content/en/docs/instrumentation/java/automatic/agent-config.md

We've changed it to match the module name in the latest release

Update the `executors` instrumentation name

---

scripts/content-modules/adjust-pages.pl
static/refcache.json

- Contributes to #2698
- Fixes rewrite rule for links into the `experimental` folder
- Rewrites links to top-level supplementary-guidelines as version-specific URL into spec repo
- Updates refcache, with entries necessary for processing the spec `@HEAD` since there are a lot of new entries
- No change in generated site files, other than the refcache

Spec: link to supplementary guidelines in repo, update refcache and more

---

.htmltest.yml
content/en/docs/demo/services/frontend.md
content/en/docs/demo/services/load-generator.md
content/en/docs/instrumentation/erlang/getting-started/_index.md
content/en/docs/instrumentation/js/automatic/module-config.md
content/en/docs/instrumentation/php/exporters.md
content/en/docs/instrumentation/python/automatic/agent-config.md
scripts/content-modules/adjust-pages.pl

- Contributes to #2698
- Closes #2704
- Brings spec to the commit just before v1.21.0
- **After this PR is merged**, we'll **test the spec-version auto-update**
(depends on #2767).
**Preview**: https://deploy-preview-2724--opentelemetry.netlify.app/docs/specs

Update OTel specification, drop workarounds, fix links

---

content/en/blog/2022/apisix/index.md
content/en/blog/2022/debug-otel-with-otel/index.md
content/en/blog/2022/demo-announcement/index.md
content/en/blog/2022/instrument-apache-httpd-server/index.md
content/en/blog/2022/instrument-nginx/index.md
content/en/blog/2023/end-user-q-and-a-02.md
content/en/docs/collector/getting-started.md
content/en/docs/demo/docker-deployment.md
content/en/docs/demo/tests.md
static/refcache.json

This PR addresses #2717 and replaces every instance of `docker-compose` with `docker compose`. There is also a commit included that adds a footnote to all pages that mention `docker compose` pointing out the migration to Compose V2

Fix #2717: Replace docker-compose with docker compose

---

content/en/docs/collector/getting-started.md

The docker registry example used `opentelemetry-collector` while the ghcr example uses `opentelemetry-collector-contrib`
This was causing an issue as the location where the configuration file must be mounted differs from one image to the other.

consistent image name

---

content/en/blog/2022/apisix/index.md
content/en/blog/2022/debug-otel-with-otel/index.md
content/en/blog/2022/demo-announcement/index.md
content/en/blog/2022/instrument-apache-httpd-server/index.md
content/en/blog/2022/instrument-nginx/index.md
content/en/blog/2023/end-user-q-and-a-02.md
content/en/docs/collector/getting-started.md
content/en/docs/demo/docker-deployment.md
content/en/docs/demo/tests.md
hugo.yaml
layouts/shortcodes/_param.md

- Followup to #2775
- Introduces a new shortcode named `_param`, that is like the Hugo `param` shortcode, but can be used with Markdown content.
- Replaces all hard-coded notes and footnotes with the text "`docker-compose` is deprecated" with in invocation of `_param`
- Adds the shared note content to `hugo.yaml` under `param.notes`
- In `content/en/docs/collector/getting-started.md`, turns the `**Note**` into a Docsy `alert`
**Preview** (sampling of edited pages):
- https://deploy-preview-2781--opentelemetry.netlify.app/docs/collector/getting-started/#demo
- https://deploy-preview-2781--opentelemetry.netlify.app/blog/2023/end-user-q-and-a-02/#fn:1
/cc @svrnm @cartermp

Add and use _param shortcode to keep notes DRY

---

scripts/content-modules/adjust-pages.pl

Concretely, this eliminates the following warnings (which are no longer relevant because the pages have moved):
```
WARNING: link to spec page encoded as an external URL, but should be a local path, fix this upstream;
File: /Users/chalin/git/lf/open-telemetry/opentelemetry.io/tmp/otel/specification/metrics/semantic_conventions/http-metrics.md 
Link: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-advice
WARNING: link to spec page encoded as an external URL, but should be a local path, fix this upstream;
File: /Users/chalin/git/lf/open-telemetry/opentelemetry.io/tmp/otel/specification/metrics/semantic_conventions/http-metrics.md 
Link: https://github.com/open-telemetry/opentelemetry-specification/blob/mai …
```

Semconv pages: don't warn about external links to spec

---

hugo.yaml
scripts/content-modules/adjust-pages.pl
scripts/content-modules/cp-pages.sh

- Contributes (possibly closes) #2642
- Adds the OTLP spec under `/docs/specs`
**Preview**: https://deploy-preview-2786--opentelemetry.netlify.app/docs/specs/otlp
/cc @tigrannajaryan

Add OTLP to docs/specs

---

content/en/docs/specs/otel/status.md
layouts/shortcodes/spec_status.html

As of
- https://github.com/open-telemetry/opentelemetry-specification/pull/3454
the `spec_status` shortcode **fails** to extract the OTLP status, because it has been removed from the OTel spec pages.
This PR:
- Adjusts `spec_status` shortcode to take the spec (`otel` or `otlp`) as part of file path
- #2642
- #2793
**Preview**: https://deploy-preview-2794--opentelemetry.netlify.app/docs/specs/otel/status/
/cc @tigrannajaryan

Get OTLP status from OTLP spec

---

content/en/docs/specs/status.md
content/en/status.md
scripts/content-modules/adjust-pages.pl

- Moves `/docs/specs/otel/status` to `/docs/specs/status`, since the status page covers status from both the OTel and OTLP specs.
- Adjusts the `linkTitle` of the OTel spec to be "OTel <vers>"
- #2642
- #2793
---
**Preview**: https://deploy-preview-2796--opentelemetry.netlify.app/docs/specs/status
> <img width="1060" alt="Screen Shot 2023-05-25 at 18 50 14" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/854d4d56-a4e8-4e8b-81e1-8c8654961f72">
/cc @tigrannajaryan @open-telemetry/specs-approvers

Move spec-status page to be immediately under /docs/specs

---

content/en/docs/instrumentation/js/exporters.md

The example instrumentation.js had a missing library: PeriodicExportingMetricReader
When running the example as-is with: node --require ./instrumentation.js app.js
The user would get an error:
ReferenceError: PeriodicExportingMetricReader is not defined

Update exporters.md - Adding missing library to example instrumentation.js

---

content/en/docs/collector/deployment/agent.md

Moves `insecure` option on Agent Deploy docs under `tls`
re: https://github.com/open-telemetry/opentelemetry-collector/pull/4063/files

Move insecure option under `tis`

---

content/en/blog/2023/sunsetting-opencensus.md
content/en/docs/migration/opencensus.md

Eventually, there should be a page dedicated to the OpenCensus migration. In the meantime, the Sunsetting OpenCensus (especially the "how to migrate" section), is the next best thing.
The main motivation for this PR is to:
- Redirect `/docs/migration/opencensus` to the Sunsetting OpenCensus blog -- specifically the how-to migration section -- rather than directly to the spec. The blog mentions the spec, and more, and seems better suited as a target IMHO.
Applied copyedits to the sunsetting blog post, e.g.:
- Slightly repositioned a few footnotes to make them easier to see. (They're hard to see when next to an external-link icon.)
- Drops the "OpenCensus Compatibility specification is marked stable for the next specification release" since that release is not published on the website. …

Redirect Docs > Migration > OpenCensus to the Sunsetting OpenCensus blog

---

scripts/content-modules/adjust-pages.pl
static/refcache.json

- Contributes to #2642
- Updates OTLP spec to pick up https://github.com/open-telemetry/opentelemetry-proto/pull/479
- Drops temporary tweak to `adjust-pages.pl` script.
**Preview**: https://deploy-preview-2816--opentelemetry.netlify.app/docs/specs
/cc @open-telemetry/specs-approvers

Update OTLP spec page

---

content/en/docs/instrumentation/java/api.md
content/en/docs/instrumentation/java/automatic/_index.md
content/en/docs/instrumentation/java/automatic/agent-config.md
content/en/docs/instrumentation/java/automatic/annotations.md
content/en/docs/instrumentation/java/automatic/extensions.md
content/en/docs/instrumentation/java/examples.md
content/en/docs/instrumentation/java/getting-started.md
content/en/docs/instrumentation/java/manual.md

Common weights for Java pages

---

content/en/docs/instrumentation/js/api.md
content/en/docs/instrumentation/js/automatic/_index.md
content/en/docs/instrumentation/js/automatic/module-config.md
content/en/docs/instrumentation/js/context.md
content/en/docs/instrumentation/js/examples.md
content/en/docs/instrumentation/js/exporters.md
content/en/docs/instrumentation/js/getting-started/_index.md
content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/js/libraries.md
content/en/docs/instrumentation/js/manual.md
content/en/docs/instrumentation/js/propagation.md
content/en/docs/instrumentation/js/resources.md
content/en/docs/instrumentation/js/sampling.md
content/en/docs/instrumentation/js/serverless.md

Common weights for JS pages

---

content/en/docs/instrumentation/ruby/api.md
content/en/docs/instrumentation/ruby/automatic.md
content/en/docs/instrumentation/ruby/examples.md
content/en/docs/instrumentation/ruby/exporters.md
content/en/docs/instrumentation/ruby/getting-started.md
content/en/docs/instrumentation/ruby/manual.md
content/en/docs/instrumentation/ruby/sampling.md

Common weights for ruby pages

---

data/registry/otel-go-autoinstrumentation.yml
static/refcache.json

The Go auto instrumentation has been merged into the Open Telemetry organization.
This change reflects the new home for this code.

Update the Go Auto Instrumentation repo

---

content/en/docs/instrumentation/java/manual.md
data/instrumentation.yaml

Publishing a release tomorrow in which logs will be marked as stable. Updating the docs to reflect this.

Reflect stable logs in java docs

---

package.json
scripts/content-modules/adjust-pages.pl

- Followup to #2856
- Closes #2642
- Ensures that external links to the OTLP spec become a local path inside OTel spec pages
- Also includes a workaround for the `_serve:hugo` script, avoiding the error message `Error: command error: unknown command "-DFE" for "hugo server"` when stopping the server
Here are the affected files:
```console
$ (cd public && git diff | grep ^diff)                                                               
diff --git a/docs/specs/otel/protocol/exporter/index.html b/docs/specs/otel/protocol/exporter/index.html
diff --git a/docs/specs/otel/protocol/file-exporter/index.html b/docs/specs/otel/protocol/file-exporter/index.html
diff --git a/docs/specs/otel/protocol/index.xml b/docs/specs/otel/protocol/index.xml
diff --git …
```

OTel spec: link to local OTLP, and fix README link

---

content/en/community/end-user/discussion-group.md

This PR updates the End User Discussion Group meetings with the dates for the next three months.

Update discussion meeting dates

---

content/en/docs/demo/services/cart.md

Corresponding demo PR https://github.com/open-telemetry/opentelemetry-demo/pull/943

[demo/cartservice] Avoid warning - hiding variables

---

content/en/docs/concepts/signals/metrics.md
layouts/shortcodes/metrics_support_table.md

Based on the feedback from https://github.com/open-telemetry/opentelemetry.io/issues/2877, I tried to improve some of the metrics concept page:
* I gave it a structure that is closer to the one we have for traces already (i.e. calling out components like MeterProvider, Meter, etc.)
* Added a metrics support table that (a) provides a link to the languages, and (b) calls out metric stability across them, such that an end user is not going to be surprised if for a specific language they can not find metric instructions
If the latter proves valuable for metrics I can create the same for traces (and later for logs)

Add more details to metrics concept page

---

content/en/docs/concepts/signals/logs.md

Mention logs, not metrics.
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/2898

Fix typos in logs language support

---

content/en/docs/instrumentation/go/getting-started.md

The Fibonacci demo on the getting started page does not account for overflows. This fix improves it by throwing an error upon overflow (fib 94 or above for uint64). 
**Old:**
```
What Fibonacci number would you like to know: 
1
Fibonacci(1) = 1
What Fibonacci number would you like to know: 
93
Fibonacci(93) = 12200160415121876738
What Fibonacci number would you like to know: 
94
Fibonacci(94) = 1293530146158671551
What Fibonacci number would you like to know: 
95
Fibonacci(95) = 13493690561280548289
What Fibonacci number would you like to know: 
100
Fibonacci(100) = 3736710778780434371
```
**New:**
```
What Fibonacci number would you like to know: 
1
Fibonacci(1) = 1
What Fibonacci number would you like to know: 
93
Fibonacci(93) = 12200160415121876738
What Fibonacci number would you like …
```

Improve fibonacci code in Getting Started page

---

content/en/docs/instrumentation/go/getting-started.md

Reverts open-telemetry/opentelemetry.io#2901
The error is intentional so its fix can be used later to instruct users how to add errors to spans: https://github.com/MitchellGale/opentelemetry.io/blob/806d4094e6a1fcf6ce681643dad0f86b534853e2/content/en/docs/instrumentation/go/getting-started.md#bonus-errors

Revert "Improve fibonacci code in Getting Started page"

---

content/en/docs/instrumentation/go/getting-started.md

- Closes #2913
- Adds a discrete footnote mentioning that the error is intentional.
- Copyedits
**Preview**: https://deploy-preview-2914--opentelemetry.netlify.app/docs/instrumentation/go/getting-started
/cc @MrAlias @svrnm @pellared

Go > Getting started: add note about intentional error

---

content/en/docs/concepts/sampling/index.md
data/instrumentation.yaml
layouts/shortcodes/sampling-support-list.md
package.json

This PR adds a section to the footer of the sampling concept page to point to relevant collector processors and to languages that have documentation on sampling (well-aware that for some languages just the docs are missing). This way readers can read on after going through the concepts, if this proves valuable we can use it as a pattern on other pages as well.

Add collector and language support to sampling concept page

---

.gitmodules
hugo.yaml

- Brings in https://github.com/open-telemetry/semantic-conventions as a `content-modules`
- Closes #2907
- Also ensure that we temporarily get the 1.21.0 schema from the OTel spec repo (will track removal of this special case via 2721)
There are no changes in the generated site files:
```console
$ npm run build
...
$ (cd public && git diff) # no change
$
```

Add semantic-conventions as a submodule and get schemas from there, with one exception

---

content/en/docs/instrumentation/php/automatic.md
content/en/docs/instrumentation/php/exporters.md
content/en/docs/instrumentation/php/getting-started.md
content/en/docs/instrumentation/php/manual.md
static/refcache.json

- Make sure that the examples all run if copy/pasted
- Update/improve the PHP documentation
Fixes: https://github.com/open-telemetry/opentelemetry-php/issues/1042
---
Preview: https://deploy-preview-2896--opentelemetry.netlify.app/docs/instrumentation/php/

Make php examples runnable

---

CONTRIBUTING.md
package.json

- Updates `CONTRIBUTING.md`: we don't use symlinks anymore; clarifies where content comes from.
- `package.json`:
- Adds `engines.node` entry to require active LTS version (currently 18.x)
- Moves dependencies entries to be before `textlint` config etc.

Add Node version constraint to package.json & update contrib notes

---

content/en/docs/specs/semconv/_index.md
hugo.yaml
scripts/content-modules/cp-pages.sh
static/refcache.json

- Supersedes #2908
- Adds semconv spec to `docs/specs`
- Pages will only appear in deploy previews, not on the production server, since all spec pages are marked as `draft: true`
- We won't want to publish the semconv spec until the following restructuring is complete, IMHO:
https://github.com/open-telemetry/semantic-conventions/issues/137
**Preview**: https://deploy-preview-2920--opentelemetry.netlify.app/docs/specs/semconv/
/cc @jsuereth @joaopgrassi

Add SemConv spec under docs/specs (preview)

---

content/en/docs/instrumentation/cpp/manual.md
content/en/docs/instrumentation/erlang/exporters.md
content/en/docs/instrumentation/erlang/getting-started.md
content/en/docs/instrumentation/erlang/manual.md
content/en/docs/instrumentation/go/manual.md
content/en/docs/instrumentation/java/manual.md
content/en/docs/instrumentation/js/manual.md
content/en/docs/instrumentation/net/manual.md
content/en/docs/instrumentation/php/manual.md
content/en/docs/instrumentation/python/manual.md
content/en/docs/instrumentation/ruby/manual.md
content/en/docs/instrumentation/swift/manual.md

Another consistency update for the manual instrumentation pages. After this PR gets merged:
* all languages more or less have the same structure:
```
Setup
Traces
Metrics
Logs
...
Next Steps
```
* if a signal is not yet stable or documentation is missing, this is called out in place. if the signal is stable, readers are asked to contribute
* Moved the section about OTLP Exporter for erlang to a separate page to follow the structure of other languages
* Some other structural updates to create consistency

Consistency update for TOCs of manual instrumentation pages

---

static/refcache.json

The refcache shouldn't contain entries with HTTP status 4xx.
- Removes such entries, which are all from `crates.io` -- we've had an ignore rule for that domain for a while.

Clean up refcache.json: drop 4xx status entries

---

gulp-src/README.txt
gulp-src/_util.js
gulp-src/default.js
gulp-src/prune.js
gulpfile.js
package.json
static/refcache.json

- #2429
- #2554
- Adds a Gulp task to prune the _n_ oldest entries from the `refcache.json` file.
- Refreshes about 150 entries from the `refcache.json` file. Note that deleted entries are external links that are no longer used.
- The idea will be to eventually setup a cron job to refresh the refcache.

CI: gulp task in support of refcache cleanup & some refcache updates

---

content/en/docs/collector/configuration.md

- Closes #2949
- Moves component icons into headings and adjusts the heading anchor IDs accordingly.
- Moves component icons to be after any element text.
We could have kept them before, and only have added `&nbsp;`, but I think that it works better (and is more consistent) to put the icon after the text in the component list and in the headings. If you prefer the icons before the text, let me know.
**Preview**: https://deploy-preview-2953--opentelemetry.netlify.app/docs/collector/configuration/#basics
> ![image](https://github.com/open-telemetry/opentelemetry.io/assets/4345663/2250686a-26ec-4001-bcb8-a5d0c4893435)
> <img width="537" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/6d7e0124-6dfa-499f-946f-507c78e89e10">

Collector config: fix icon display + copyedits

---

content/en/docs/faas/lambda-auto-instrument.md

- Followup to #2945
- Fixes build warning: `WARN 2023/06/30 06:38:23 docs/faas/lambda-auto-instrument.md: use a local path, not an external URL ...`
- Did a few copyedits while in there :)
**Preview**: https://deploy-preview-2952--opentelemetry.netlify.app/docs/faas/lambda-auto-instrument/#language-requirements
/cc @tylerbenson

Lambda-auto-instrument.md: fix link + copyedits

---

gulp-src/prune.js
static/refcache.json

- Updates `prune` task with new options / functionality:
- Status 4xx entries are pruned by default now.
- Use `--before <date>` to only prune the oldest before the given date
- Refreshes all remaining refcache entries that has last been visited prior to June 1, 2023. That is, **all entries now have a "LastSeen" of June 1, 2023 or later**; none have 4xx HTTP status.
```console
$ npx gulp prune --before 2023-06-01
[14:43:24] Using gulpfile ~/git/lf/open-telemetry/opentelemetry.io/gulpfile.js
[14:43:24] Starting 'prune'...
INFO: no entries to prune under given options.
[14:43:24] Finished 'prune' after 14 ms
```

Refcache refresh (final for 23Q2) + prune task updated options and features

---

.htmltest.yml
content/en/ecosystem/adopters.md
static/refcache.json

- Contributes to #2947
- Updates the community repo submodule (not mandatory, but useful to do now and again)
- Adds an adopters page under `/ecosystem`, with the content copies from the community repo ADOPTERS.md file
- My plan, in a followup PR, is to make this page be data-driven
**Preview**: https://deploy-preview-2961--opentelemetry.netlify.app/ecosystem/adopters/

Add adopters page, with content taken from the community repo

---

content/en/docs/collector/deployment/agent.md
content/en/docs/collector/deployment/gateway.md
content/en/docs/collector/getting-started.md
content/en/docs/instrumentation/cpp/getting-started.md
content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/js/manual.md
content/en/docs/instrumentation/js/sampling.md
content/en/docs/instrumentation/php/automatic.md
content/en/docs/instrumentation/php/getting-started.md
content/en/docs/instrumentation/php/manual.md
content/en/docs/instrumentation/ruby/exporters.md

- Updates Docsy, which adds support for tab-pane header persistence, rather than only tab-pane language
- Drops `tabpane.persistLang` parameter from all pages in the docs
From the following preview page you can see that the tab choice is persisted (refresh the page and the active tab remains active), and the choice (from any tab pane) is synchronized across all tab-panes:
**Preview**:
- https://deploy-preview-2972--opentelemetry.netlify.app/docs/collector/getting-started/ - persists DockerHub vs ghcr.io, and architecture choice (later in the page)
- https://deploy-preview-2972--opentelemetry.netlify.app/docs/instrumentation/js/getting-started/nodejs/#dependencies -persist Javascript vs Typescript

Docsy upupdate + drop `tabpane.persistLang` parameter

---

content/en/docs/instrumentation/python/manual.md

It was previously under the Traces header.

fix meter provider configuration

---

content/en/ecosystem/adopters.md
static/refcache.json

this adds the 2 companies we had in the End User Q&A blog posts to the adopters pages
cc @open-telemetry/end-user-wg

Add End User Q&A series companies to adopters

---

content/en/docs/collector/benchmarks.md
content/en/docs/collector/trace-receiver.md
static/refcache.json

This is based on the work that @mwear started in the collector repository. Rather than publishing a github page from the collector repo, I suggest this should live in the opentelemetry.io repository and be displayed on the website as well.
For reviewers, is including style/html in the markdown ok? Or should this be moved somewhere else?
---
**Preview**: https://deploy-preview-2975--opentelemetry.netlify.app/docs/collector/benchmarks/

add collector benchmark page

---

content/en/docs/instrumentation/php/automatic.md
content/en/docs/instrumentation/php/manual.md

* use guzzle http client to satisfy simplified http client/message requirements
* update pickle installation instructions to work now that we've moved the extension source
into a subdirectory
* disable metrics by default, since it often trips up users trying out tracing

php updates

---

scripts/content-modules/cp-pages.sh

- **Preview**: https://deploy-preview-2998--opentelemetry.netlify.app/docs/specs/semconv/
/cc @jsuereth @joaopgrassi

Update semantic-conventions to c6efa4b, and drop normalization step

---

.prettierignore

- Followup to #3002
- Context: https://prettier.io/blog/2023/07/05/3.0.0.html#ignore-gitignored-files-by-default-14731httpsgithubcomprettierprettierpull14731-by-fiskerhttpsgithubcomfisker

Update .prettierignore: drop .gitignore entries + comment tweak

---

.github/workflows/check-format.yml

I'm not 100% sure that this is properly setup, but it does reduced the action execution time by more than 50%.
The action does contain the following warning, so I'm not sure that `npm install` is actually being called or not:
> npm WARN exec The following package was not found and will be installed: prettier@3.0.0
/cc @trask

CI: cache dependencies for check-format GH action

---

assets/scss/_styles_project.scss
scripts/content-modules/adjust-pages.pl

@jsuereth @joaopgrassi - my apologies, but #2984 inadvertently caused the semconv pages to be published to the production server (confusion arose as I switched to using the name-title adjustment script and forgot that I had dropped the `draft: true` front matter field).
This PR:
- Adds a DRAFT ~(was: PREVIEW-ONLY)~ wartermark for the semconv draft pages
- Drops the semconv pages from the production server
Given that the semconv pages are pretty much in their final form (given that the reorg is done), maybe we can keep the pages in production, but with the watermark. Or even just forget about the watermark too? Your call, let me know.
**Preview**: https://deploy-preview-3008--opentelemetry.netlify.app/docs/specs/semconv/
**Screenshot**:
> <img width="971" alt="image" …

Ensure that semconv pages are preview only, not in production + add watermark

---

assets/scss/_styles_project.scss

- Followup to #3008
- Ensures that the watermark is better positioned for very wide displays (currently is moves above the top edge of the view). It also improves positioning on mobile.

Better DRAFT watermark position for all screens

---

scripts/content-modules/adjust-pages.pl

- Prep for #2721
- Now only replaces URLs to OTel-spec repo spec pages if the URL references `main` or the current OTel version
- Fixes links to OTLP non-page resources -- was missing the `v` in the tag name (this didn't get caught by the link checker because we do not yet check links to GH resources)

Adjust-pages: link to local OTel spec for main and current vers + other fixes

---

content/en/docs/instrumentation/php/automatic.md
static/refcache.json

Calling out that composer autoloader is required for PHP auto-instrumentation.

adding php composer note

---

content/en/blog/2023/end-user-q-and-a-03.md
layouts/_default/_markup/render-link.html
scripts/content-modules/adjust-pages.pl

- Updates semconv submodule
- Brings in https://github.com/open-telemetry/semantic-conventions/pull/185
- Adds Hugo build warning for pages containing external links to OTLP spec or semconv pages
- Adjust-pages: enhances regex used to replace external links to OTel and OTLP pages; the regex now matches inline markdown links and markdown link-definitions
- Fixes link in blog post to refer to local OTLP page
- Note that semconv pages are still **only in preview**: 
https://deploy-preview-3021--opentelemetry.netlify.app/docs/specs/semconv
There are no changes other than more instances of external spec-page links being replaced by local paths (the two changed files are expected):
```console
$ (cd public && git diff -bw -I "(blob|tree)/v1.2" -I "href=\"/docs" -- . ':(exclude)*.xml') | grep …
```

Update semconv, adjust link-checks, and more

---

content/en/ecosystem/registry/_index.md
scripts/content-modules/adjust-pages.pl

- Followup to #3021
- Eliminates adjust-pages.pl warning
- Adjusts aliases path order -- Netlify staff recommendation to help debug https://github.com/open-telemetry/opentelemetry.io/issues/3013#user-content-fn-1-edc581236bf4ec19e880c101ccc439bc

Adjust-pages: fix regex to avoid warning + tweak alias order

---

scripts/content-modules/cp-pages.sh

Followup to:
- #3023
No changes to the generated site files:
```console
$ (cd public && git diff)
$
```

Adjust-pages: drop OTel spec fixes now that 1.23 has landed

---

.github/workflows/check-links.yml
.warnings-skip-list.txt
Makefile
package.json
scripts/check-build-log.sh

- Contributes to #2814
- Enable simple node-based caching
- Separates concerns. We now have separate jobs for:
- Building the site and running the link checker
- Checking for required refcache updates
- Checking for build issues (including warnings about use of external links when a local path should be used)
- I've disabled the failure of the BUILD WARNINGS job until #2721 is fully resolved
https://github.com/open-telemetry/opentelemetry.io/actions/workflows/check-links.yml used to take almost 3 minutes, it is now down to ~1 min 40 sec~. Update: it's now 2 min 15 sec on a rerun; I couldn't get it to work using a partial install. Not as much an improvement as I would have hoped, but it is an improvement. I could probably trim `devDependencies`, but this will do for now.

CI: check-links: enable caching and check for warnings

---

content/en/docs/instrumentation/python/automatic/agent-config.md

Correct environment variable name when converting from configuration property.

Fix typo in agent-config.md

---

.github/workflows/pr-actions.yml

- Drops use of `stefanzweifel/git-auto-commit-action@v4`
- Reverts to using `git` CLI instead
- Adds caching of NPM packages

Fixing fix-format: use git CLI rather than git-auto-commit-action

---

.github/workflows/auto-update-versions.yml
hugo.yaml
scripts/content-modules/adjust-pages.pl

- Updates semconv submodule to 1.21.0
- Enabled the publication of schema for 1.21.0
- Removes `draft` status from semconv pages -- **SEMCONV PAGES WILL APPEAR ON THE PRODUCTION SERVER**
- Enabled auto-update of the semconv version
- Note that the OTel spec is at 1.23.0, so links into the OTel spec at 1.22.0 appear as external links; they do not link to the corresponding OTel website spec page
**Preview**: https://deploy-preview-3033--opentelemetry.netlify.app/docs/specs/semconv
/cc @jsuereth @joaopgrassi

Update semantic-conventions to 1.21.0, publish all schemas, drop draft status, enable auto-update

---

content/en/docs/demo/architecture.md

Loadgenerator now sends requests through FrontEndProxy. 
And OTelCollector is using OTLPExporter instead of JaegerExporter (which was deprecated) for traces.

Update demo architecture

---

content/en/ecosystem/registry/_index.md
layouts/index.redirects

- Closes #3013
- Adds support for page-specific `redirects` rules that have `from` and `to` URL parameters; the page permalink is assumed for these parameters, unless they start with a `/`.

Add page redirects feature and fix registry catch-all

---

data/registry/exporter-go-otlp.yml

exporter-go-otlp.yml pointed to the Java repository instead of the Go repository.

Fix registry entry for Go OTLP

---

.github/CODEOWNERS
content/en/docs/kubernetes/helm/_index.md
content/en/docs/kubernetes/helm/collector.md
static/refcache.json

Adds new documentation for the Collector helm chart.
As I was writing I realized it would be unfeasible to include sections for all three charts in the same file so I created a folder.  This PR adds only the Collector helm chart docs but I will add a file for the operator and demo charts in future PRs.

[Kubernetes] Add Collector helm chart docs

---

content/en/docs/kubernetes/helm/operator.md
static/refcache.json

Adds new documentation for the Operator helm chart.

[Kubernetes] Add Operator helm chart docs

---

content/en/docs/kubernetes/helm/collector.md
content/en/docs/kubernetes/helm/demo.md
content/en/docs/kubernetes/helm/operator.md

Adds new documentation for the Demo helm chart.

[kubernetes] Add demo helm chart docs

---

static/refcache.json

Why? Well, a PR I merged was 100% green. However, it wasn't -- github actions was just taking its sweet time deciding to even queue up a job. And so the refcache job hadn't even been run yet.

update refcache again

---

.github/workflows/pr-actions.yml
content/en/docs/collector/_index.md

Maybe, just maybe, this will let us just update the refcache in PR comments. Let's find out with https://www.gooddeals.com/

Add /fix:refcache action

---

data/instrumentation.yaml

Accordingly to release v1.16.0 of Open Telemetry Go, `metrics` is now stable. Updating the docs to reflect that.
Reference
* https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.16.0
> This release contains the first stable release of the OpenTelemetry Go [metric AP](https://pkg.go.dev/go.opentelemetry.io/otel/metric) 
---
**Preview**: https://deploy-preview-3075--opentelemetry.netlify.app/docs/instrumentation/go/#status-and-releases

update go metric status

---

data/instrumentation.yaml
layouts/shortcodes/docs/instrumentation/index-intro.md
layouts/shortcodes/logs-support-table.md
layouts/shortcodes/metrics-support-table.md
layouts/shortcodes/sampling-support-list.md
layouts/shortcodes/telemetry-support-table.md

- Prep for #3077 
- Simplifies `data/instrumentation.yaml`:
- Drops top-level `languages` key
- Drops `urlName` since it always matches the key; adds a comment to that effect
- Updates all shortcodes that make use of `data/instrumentation.yaml`
- Fixes `layouts/shortcodes/sampling-support-list.md` so that the markdown list that it generates doesn't have any extra spacing.
---
Other than the page using `sampling-support-list.md`, the generated site files are the same:
```console
$ (cd public && git diff) | grep ^diff | grep -v '\.xml$'
diff --git a/docs/concepts/sampling/index.html b/docs/concepts/sampling/index.html
```
Here's the diff of the concepts sampling page:
```diff
diff --git a/docs/concepts/sampling/index.html b/docs/concepts/sampling/index.html
index b7b6ddd85..e7e71525d 100644 …
```

Refactoring of data/instrumentation.yaml and associated shortcodes

---

hugo.yaml

Fix broken link to CNCF logos

---

hugo.yaml

- Contributes to #3081
- Replaces the "CNCF branding" label by "OTel logos" because the link that actually refers to logos :)

Footer: update OTel-logos label and description

---

content/en/docs/kubernetes/collector/components.md

Adds documentation for the k8sclusterreceiver component.
For the sake of working these in parallel im going to start opening multiple and always adding the new ones as low in the file as I can.  If there is a better way to organize I'll rearrange when they are all in.

[kubernetes] Add docs for k8sclusterreceiver

---

hugo.yaml
layouts/shortcodes/community-lists.md

- Contributes to #3079
- Updates the community submodule
- Links to the local Marketing Guidelines page in the footer
- Tweaks the community links-list so that external link icons are shown for external links
- **Preview**:
- https://deploy-preview-3088--opentelemetry.netlify.app/community/
- Also see the footer of the above page

Update community repo + link to local marketing guidelines

---

content/en/ecosystem/vendors.md
layouts/shortcodes/ecosystem/vendor-table.md

- Vendor page copyedits, in particular removes the stutter "via via"
- Adds a heading for "Add your organization", which more clearly separates the instructions from the table, and gives us a linkable target
- **Preview**: https://deploy-preview-3092--opentelemetry.netlify.app/ecosystem/vendors/

Vendor page copyedits

---

.github/workflows/pr-actions.yml

`/fix:refcache` is still failing, for example: https://github.com/open-telemetry/opentelemetry.io/actions/runs/5693957168/job/15434151382: git can't find a submodule commit. The most likely reason is that we're doing shallow clones, so let's clone more deeply :). The number I use is arbitrary, but it should be sufficient for more than 80% of the cases.

[CI] Clone submodules more deeply for `/fix:refache`

---

content/en/docs/kubernetes/collector/components.md

Adds documentation for the k8sobjectsreceiver.

[kubernetes] Add docs for k8sobjectsreceiver

---

content/en/docs/kubernetes/operator/automatic.md

Fixes a mistype and bolding that we missed in review.

Update header in k8s operator autoinstrumentation doc

---

.github/workflows/check-spelling.yml
content/en/docs/collector/build-connector.md

- Contributes to #3083
- Adds a check after running `fix:dict` to ensure that no files have been updated; if files have changed, the workflow fails and gives instructions
- ~**NOTE**: the action will fail now because some files don't have their dictionaries normalized~

[CI] fix:dict - ensure workflow fails if files have changed

---

content/en/docs/instrumentation/net/_index.md
static/refcache.json

Rename .NET Core to .NET
.NET Core is legacy name and was renamed to .NET in 5.0 release

Rename .NET Core to .NET

---

.github/workflows/scripts/textlint.sh
content/en/docs/instrumentation/php/automatic.md

- Closes #3119
- Uses `npm run _check:text` rather than raw call to textlint, so that we get the same files checked as when we run `check:text`
- ~**NOTE**: if all goes well, this PR's textlint action will report an error.~
- Adds ignore directives to a PHP file that textlint reports an issue on

[CI] textlint workflow: use npm script for same coverage

---

content/en/docs/kubernetes/collector/components.md

Adds documentation for the host metrics receiver.
---
**Preview**: https://deploy-preview-3118--opentelemetry.netlify.app/docs/kubernetes/collector/components/#prometheus-receiver

[kubernetes] Add hostmetrics recevier doc

---

content/en/docs/instrumentation/cpp/getting-started.md
content/en/docs/instrumentation/erlang/getting-started.md
content/en/docs/instrumentation/go/getting-started.md
content/en/docs/instrumentation/java/getting-started.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/net/getting-started.md
content/en/docs/instrumentation/php/getting-started.md
content/en/docs/instrumentation/python/getting-started.md
content/en/docs/instrumentation/ruby/getting-started.md

@open-telemetry/docs-approvers & @open-telemetry/go-approvers  please take a look first, wdyt? I thought it would be nice to link from each language to the respective services within the demo

add links to demo services from getting started pages

---

content/en/docs/instrumentation/js/_index.md
content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/manual.md
hugo.yaml

We have the same warning now for [Manual instrumentation - Browser](https://opentelemetry.io/docs/instrumentation/js/manual/#browser), I think the [getting started](https://opentelemetry.io/docs/instrumentation/js/getting-started/browser/) should have it as well, because at least I get ~weekly questions around OTel for browser/mobile/etc.

Add a warning to browser getting started

---

assets/scss/_styles_project.scss
content/en/docs/collector/getting-started.md
content/en/docs/faas/lambda-auto-instrument.md
content/en/docs/instrumentation/js/getting-started/nodejs.md

- **Draft** because it is currently waiting on https://github.com/google/docsy/issues/1641 -- without which the changed tabbed panes don't get persisted.
- Contributes to #3127
- This proof-of-concept (POC) PR illustrates a proposal to simplify how we make use of `tabpane` shortcodes. The goal is to:
- **Eliminate** the need for checker and linter **directives** like
``, 
``, etc.
- **Improve IDE** and other **tooling support**: most tabbed panes in the docs contain code. Part of the problem with the current encoding is that the tools don't know that the content of a `tab` is code. The proposal illustrated here is to use code-block fences. I feel that the gains outweigh the extra code-fence lines that we need to write.
- Updates docsy theme again.
- 
WDYT @svrnm @cartermp et al.? If y'all …

Use of tabpanes that obviates the need for Prettier/linter-ignore directives

---

.github/workflows/pr-actions.yml

Sometimes the `push` of `/fix:*` fails because it doesn't know what the remote branch is. For example, see https://github.com/open-telemetry/opentelemetry.io/actions/runs/5766508852/job/15634603745.
- Fixes the situation by pushing to a named remote branch
- Refactors code a bit

[CI] Ensure PR `/fix` actions push to named remote branch

---

content/en/docs/instrumentation/js/exporters.md

**Preview**: https://deploy-preview-3133--opentelemetry.netlify.app/docs/instrumentation/js/exporters/

WebTracer now supports http/protobuf exporter

---

content/en/docs/collector/deployment/agent.md
content/en/docs/collector/deployment/gateway.md
content/en/docs/collector/getting-started.md
content/en/docs/demo/services/frontend.md
content/en/docs/instrumentation/cpp/getting-started.md
content/en/docs/instrumentation/erlang/exporters.md
content/en/docs/instrumentation/erlang/getting-started.md
content/en/docs/instrumentation/erlang/manual.md
content/en/docs/instrumentation/erlang/propagation.md
content/en/docs/instrumentation/erlang/resources.md
content/en/docs/instrumentation/erlang/sampling.md
content/en/docs/instrumentation/erlang/testing.md
content/en/docs/instrumentation/js/exporters.md
content/en/docs/instrumentation/js/getting-started/browser.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/js/libraries.md
content/en/docs/instrumentation/js/manual.md
content/en/docs/instrumentation/js/sampling.md
content/en/docs/instrumentation/php/automatic.md
content/en/docs/instrumentation/php/exporters.md
content/en/docs/instrumentation/php/getting-started.md
content/en/docs/instrumentation/php/manual.md
content/en/docs/instrumentation/ruby/exporters.md
scripts/norm-tabpanes.pl

- Contributes to #3127
- Converts `tabpane` shortcode uses per #3127. For details, see the issue.
- Now that Prettier knows which language a code excerpt is coded in, it has formatted a few of the TS and JS code in tabs.
- In two or three instances, superfluous quotes were removed from YAML strings
**Preview:** (selected pages)
- https://deploy-preview-3137--opentelemetry.netlify.app/docs/collector/deployment/agent/
- https://deploy-preview-3137--opentelemetry.netlify.app/docs/instrumentation/erlang/getting-started/#creating-a-new-mixrebar-project
- https://deploy-preview-3137--opentelemetry.netlify.app/docs/instrumentation/js/exporters/#otlp-endpoint
- https://deploy-preview-3137--opentelemetry.netlify.app/docs/instrumentation/php/getting-started/#add-automatic-instrumentation
- …

Normalize tabpane shortcode use

---

content/en/docs/instrumentation/swift/_index.md
content/en/docs/instrumentation/swift/examples.md

Adding this for completeness & consistency with other languages

Add examples link to swift docs

---

content/en/blog/2023/end-user-discussions-03.md
content/en/docs/kubernetes/operator/automatic.md

follow up to #2988 there are 2 references to an anchor that doesn't exist anymore
https://github.com/open-telemetry/opentelemetry.io/actions/runs/5823034717/job/15789009119
```
htmltest started at 03:25:00 on public
========================================================================
docs/kubernetes/operator/automatic/index.html
hash does not exist --- docs/kubernetes/operator/automatic/index.html --> /docs/instrumentation/js/libraries/#node-autoinstrumentation-package
docs/specs/otel/logs/supplementary-guidelines/index.html
hitting --- docs/specs/otel/logs/supplementary-guidelines/index.html --> https://javadoc.io/doc/org.apache.logging.log4j/log4j-api/latest/org.apache.logging.log4j/org/apache/logging/log4j/Logger.html
blog/2023/end-user-discussions-03/index.html
hash does not exist …
```

Fix broken links to JS library instrumentation page

---

data/registry/instrumentation-dotnet-instrumentation-aws.yml

Based on https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1275

Registry - fix link for .NET AWS Instrumentation package

---

.github/workflows/pr-actions.yml

- Fixes "Please tell me who you are" error reported by git; e.g., see https://github.com/open-telemetry/opentelemetry.io/actions/runs/5833875186/job/15822229807

[CI] Set user info before calling git cmd in fix:refcache

---

content/en/docs/instrumentation/rust/getting-started.md

- Links to pages that are redirects need to be absolute, otherwise the link checker will complain.

Fix links in Rust getting-started

---

hugo.yaml
package.json

The only changes in the generated files are minor: they have to do with syntax highlighting (styling correction):
```console
$ git diff -bw --ignore-blank-lines -I "Hugo 0.11" | grep ^diff | grep -v \.xml | grep -v site
diff --git a/blog/2022/exponential-histograms/index.html b/blog/2022/exponential-histograms/index.html
diff --git a/docs/demo/services/ad/index.html b/docs/demo/services/ad/index.html
diff --git a/docs/instrumentation/java/getting-started/index.html b/docs/instrumentation/java/getting-started/index.html
diff --git a/docs/instrumentation/java/manual/index.html b/docs/instrumentation/java/manual/index.html
$ git diff -bw --ignore-blank-lines -I "Hugo 0.11" -I "display:flex" | grep ^diff | grep -v \.xml | grep -v site
$
```

Upgrade Hugo to 0.117.0

---

content/en/docs/instrumentation/erlang/resources.md
content/en/docs/instrumentation/erlang/sampling.md

Adding the OTP app name to the config examples so that they can simply be copy/pasted and don't cause any confusion.

Improve erlang/elixir config examples

---

.markdownlint.json
content/en/blog/2022/k8s-otel-expose/index.md
content/en/docs/collector/build-connector.md
content/en/docs/collector/scaling.md
content/en/docs/demo/services/accounting.md
content/en/docs/demo/services/ad.md
content/en/docs/demo/services/cart.md
content/en/docs/demo/services/checkout.md
content/en/docs/demo/services/currency.md
content/en/docs/demo/services/email.md
content/en/docs/demo/services/frontend.md
content/en/docs/demo/services/load-generator.md
content/en/docs/demo/services/product-catalog.md
content/en/docs/demo/services/quote.md
content/en/docs/demo/services/recommendation.md
content/en/docs/demo/services/shipping.md
content/en/docs/faas/lambda-collector.md
content/en/docs/instrumentation/erlang/getting-started.md
content/en/docs/instrumentation/erlang/manual.md
content/en/docs/instrumentation/erlang/sampling.md
content/en/docs/instrumentation/net/getting-started.md
content/en/docs/instrumentation/php/getting-started.md
content/en/docs/instrumentation/php/manual.md
content/en/docs/instrumentation/swift/manual.md
gulp-src/_md-rules/trim-code-block-and-unindent.js
gulp-src/_util.js
gulp-src/lint-md.js
package.json

- This PR is best reviewed by **ignoring whitespace changes**
- Adds an NPM script named `fix:markdwon` which will run markdownlint in "fix" mode
- Adds a custom markdownlint rule, named `trim-code-block-and-unindent`, to check and optionally clean up fenced code blocks of:
- Excessive blank lines at the start or end of the code
- Unnecessary indentation
- Adds `trim-code-block-and-unindent:true` and `no-trailing-spaces:true` to the markdownlint config
- Fixes fenced code blocks in our docs using the new rule
- **Notes**:
- Custom rules are controlled in the same way as other rules. So they can be turned on/off for the project or selectively within a file.
- The added custom rule is a bit hacky (I didn't quite understand how markdownlint rules worked when I started …

[CI] Add markdown check for normalized code-blocks + .md page fixes

---

content/en/docs/demo/architecture.md

The cartservice calls the featureflagservice (see open-telemetry/opentelemetry-demo#824). This adds a gRPC link between those services. I adjusted a couple link lengths to try to get a cleaner diagram.

Add missing link to demo architecture diagram

---

gulp-src/_md-rules/trim-code-block-and-unindent.js
gulp-src/lint-md.js

- Ensures that the new markdownlint custom rule `trim-code-block-and-unindent` only fixes it's own issues (not issues of other rules).
- Refactored the rule's code
- Note that further work is needed, but that will be done in the scope of:
- #3183

[CI] Ensure that `lint-md --fix` only fixes code-block issues

---

scripts/normalize-cspell-front-matter.pl

- Closes #3187
- Switches to using the core Perl module `JSON::PP` instead of `JSON`
- I tested this on GitPod (which doesn't have the `JSON` module installed by default), and it works.
- @julianocosta89 - if you still have issues, I'll find another solution.

[CI] Use Perl Core module JSON::PP

---

content/en/docs/collector/configuration.md

The kafka exporter and receiver support traces, metrics, and logs, not just traces.
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/3196

content/en/docs/collector: fix listed kafka receiver/exporter support

---

data/instrumentation.yaml

Logging support got added in the most recent release. https://github.com/open-telemetry/opentelemetry-rust#project-status

Update Logging signal status for Rust to alpha

---

content/en/docs/kubernetes/operator/automatic.md
static/refcache.json

Adds Go documentation to the Operator auto-instrumentation docs.  Go instrumentation is much more involved so  mentions of it needed sprinkled throughout the page.

[operator] Add go instrumentation section

---

data/ecosystem/vendors.yaml

Lightstep is now part of ServiceNow, and the official name is "ServiceNow Cloud Observability".

Update Lightstep name on vendors page

---

content/en/docs/instrumentation/ruby/getting-started.md

The previous alert stated the latest JRuby version was mapped to Ruby 2.6.8. This is no longer true. The latest version, 9.4.3.0, maps to Ruby 3.1. This is the version the CI uses.

Update JRuby support alert

---

README.md
content/en/blog/2022/go-web-app-instrumentation/index.md
content/en/blog/2023/end-user-discussions-03.md

The correct name for GitHub is indeed "GitHub," and it should be adjusted to its proper trademarked name.
Ref: [GitHub](https://github.com/),[GitHub Wiki](https://en.wikipedia.org/wiki/GitHub)

`GitHub` adjusted to the correct name

---

content/en/docs/contribution-guidelines.md

Update reference to CNCF Community Code of Conduct
In this commit, we have updated the reference to the CNCF Community Code of Conduct to use the main branch URL. This ensures that we are following the latest version of the code of conduct.

Update Code of Conduct from CNCF

---

content/en/docs/collector/transforming-telemetry.md
content/en/docs/kubernetes/helm/collector.md

The reasons for this correction are as follows:
- Correction of the word "kubernetes" from its original spelling mistake to the correct form.
- Rectification of some grammatical errors, such as the addition of periods or the removal of redundant words.

Fix typo in transforming-telemetry.md and collector.md

---

data/ecosystem/integrations.yaml
static/refcache.json

The Elasticsearch Java API Client comes with a native OpenTelemetry instrumentation.
This PR adds it to the list of integrations in the OTel ecosystem.

Added Elasticsearch Java API Client to the integrations

---

content/en/docs/instrumentation/java/exporters.md
static/refcache.json

Describe java OTLP exporter options

---

content/en/docs/concepts/signals/metrics.md
content/en/docs/instrumentation/go/manual.md
content/en/docs/instrumentation/js/manual.md
static/refcache.json

Towards https://github.com/open-telemetry/opentelemetry-go/issues/3186 
I will add examples showing how to drop metrics/attributes in a separate PR when https://github.com/open-telemetry/opentelemetry-go/pull/4527 is merged.
The content is based on:
- first part:  https://opentelemetry.io/docs/concepts/signals/metrics/#views
- second part: https://opentelemetry.io/docs/instrumentation/java/manual/#views
- third part: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric

Go: Add Registering Views

---

data/ecosystem/vendors.yaml

Per their documentation (https://promscale-legacy-docs.timescale.com/):
> Promscale has been discontinued. We strongly recommend that you do not use Promscale in a production environment. Learn more.
Also for reference: https://github.com/timescale/promscale/issues/1836

Remove promscale from vendors.yaml

---

content/en/docs/instrumentation/net/manual.md

This code is in a `{ ... }` block, so a `;` is needed to compile.

Tiny doc fix in the .NET manual instrumentation doc.

---

content/en/blog/2023/jaeger-exporter-collector-migration.md

This is to help users that upgrade to v0.85.0 of the OTel Collector.

add blogpost on migrating away from the Jaeger exporter

---

content/en/blog/2023/k8s-runtime-observability/index.md

Fix the command description to match the value specified in the image option of `k3d cluster create` command (`rancher/k3s:v1.27.1-k3s1`)

Fix typo in blog post K8s Runtime Observability

---

data/ecosystem/vendors.yaml
static/refcache.json

Hi! Adding [highlight.io](https://app.highlight.io) per the [vendor docs](https://opentelemetry.io/ecosystem/vendors/#add-your-organization).
* Link to the documentation that details how your offering consumes OpenTelemetry natively via [OTLP](http://localhost:1313/docs/specs/otlp/).
* Described in [detail on our docs](https://www.highlight.io/docs/general/company/open-source/contributing/adding-an-sdk).
* Link to your distribution, if applicable
* https://app.highlight.io/
* Link that proves that your offering is open source, if applicable. An open source distribution does not qualify your offering to be marked “open source”.
* [LICENSE](https://github.com/highlight/highlight/blob/3ecd5c367fe8830835cf6977788e8a5ac2b77257/LICENSE)
* GitHub handle or email address as a point of contact so …

add highlight.io to vendors

---

content/en/docs/collector/getting-started.md
content/en/docs/collector/scaling.md
content/en/docs/instrumentation/_index.md
content/en/docs/instrumentation/net/automatic/_index.md
content/en/docs/what-is-opentelemetry.md

This PR changes some links to the operator repository to the documentation on opentelemetry.io

Update operator links and texts

---

data/instrumentation.yaml

https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.11.0
> Logs are declared as stable in this release.
@open-telemetry/cpp-approvers please confirm

Update C++ logs to 'stable'

---

content/en/docs/instrumentation/js/examples.md

Aligns the JS example page with other languages. It points to the examples in the core repo which has a link to contrib. The other example currently listed has not been updated for 2 years, so I think we should not have it anymore.

Update JS examples page

---

content/en/docs/instrumentation/go/getting-started.md
static/refcache.json

Towards https://github.com/open-telemetry/opentelemetry.io/issues/2623
Towards https://github.com/open-telemetry/opentelemetry-go/issues/4531
Rewrite of: https://opentelemetry.io/docs/instrumentation/go/getting-started/
Preview: https://deploy-preview-3310--opentelemetry.netlify.app/docs/instrumentation/go/getting-started/
Based on https://github.com/open-telemetry/opentelemetry-go/pull/4539

Go: Roll the dice

---

content/en/docs/instrumentation/python/getting-started.md

Per @dashpole comments from https://github.com/open-telemetry/opentelemetry.io/pull/3310#pullrequestreview-1643131028 (expand for details).

Python Getting Started: Rename span and metric names

---

content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/python/getting-started.md
content/en/docs/instrumentation/ruby/getting-started.md

Fixes
1. JS is **not** an **automatic** instrumentation
2. JS getting started does **not** cover logs 
3. Python getting started does **not** cover logs 
4. Ruby is **not** an **automatic** instrumentation
2. Ruby getting started does **not** cover metrics, nor logs 

Fixes in getting started pages

---

data/instrumentation.yaml

Accordingly to release v1.19.0 of Open Telemetry Go, `metrics` SDK is now stable. Updating the docs to reflect that.
Reference
* https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.19.0
> This release contains the first stable release of the OpenTelemetry Go [metric SDK](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric).
---
Preview
https://deploy-preview-3330--opentelemetry.netlify.app/

update go metrics status to stable

---

content/en/docs/demo/architecture.md

Prometheus has support for an OTLP write receiver which the demo is taking advantage of [in this PR](https://github.com/open-telemetry/opentelemetry-demo/pull/1149)
This updates the architecture diagram to indicate that it is in use.

(demo): use prometheus - otlp write receiver

---

content/en/blog/2023/otel-go-metrics-sdk-stable.md

A simple notice announcing the stability of the Go Otel metric SDK.

Add post for Go OTel metric SDK reaching stable status

---

content/en/docs/instrumentation/js/benchmarks.md
static/refcache.json

The Javascript SDK now has microbenchmark tests that are automatically run on every push to main. The results are currently published at https://open-telemetry.github.io/opentelemetry-js/benchmarks/.
This PR adds a page here with the same results. This is similar to what has already been done for the Collector load tests.
https://opentelemetry.io/docs/collector/benchmarks/

Add page for JS benchmarks

---

content/en/docs/instrumentation/swift/getting-started.md
static/refcache.json

contributes to #2623
I have not a lot of experience with Swift, so I hope what I wrote makes sense to a proper swift developer. The purpose of this is not to be all neat & tidy, but quick and easy to follow, such that people can continue their journey from there.

Add basic getting started for swift

---

content/en/docs/collector/configuration.md

Adds subsections in the Service configuration section:
- Extensions
- Pipelines
- Telemetry
I've been finding myself wanting to get a link to e.g. the "telemetry" section, but without a subsection, it's not possible. I believe these subsections make sense.

Add subsections in service configuration

---

content/en/blog/2023/kubecon-na.md
static/refcache.json

Just came across this and noticed only one of my talks is listed on here - think they should both be there?
[This talk](https://sched.co/1R2oA) is on building observability [with OpenTelemetry] into the dev workflow

Add Jamie's other o11y talk to kubecon schedule

---

.github/workflows/auto-update-versions.yml

- Closes #3384
- Ensures that submodule clones are deep enough for the script to be able to find version tags of repos that have been updated.
- This is similar to the issue we hit with #3103

[CI] Spec vers: clone deep enough to find tag
