content/en/community/marketing-guidelines.md
hugo.yaml
static/refcache.json

- Contributes to #1269, not in the way I way hoping (which was to bring in the gRPC footer, but going for a quick solution here)
- I'll the issue once https://clomonitor.io/projects/cncf/open-telemetry says that it's happy for legal
- Add Trademark link to the footer
- Switched to using a canonical link for the LF TM

Link to LF trademark guidelines in footer

---

content/en/docs/specs/_index.md
content/en/docs/specs/status.md
content/en/ecosystem/registry/_index.md
layouts/index.redirects

- Fixes #3409 by adding catch all rules
- Contributes to #3392
- Adds a few path-specific rewrites. More will be added later. Eventually these will be moved into their respective spec pages.
- Fixes a link to events semconv in the status page
**Preview**: https://deploy-preview-3410--opentelemetry.netlify.app/docs/specs/
- https://deploy-preview-3410--opentelemetry.netlify.app/docs/specs/otel/logs/semantic_conventions/events
- https://deploy-preview-3410--opentelemetry.netlify.app/docs/specs/otel/trace/semantic_conventions/http
- https://deploy-preview-3410--opentelemetry.netlify.app/docs/specs/otel/logs/semantic_conventions
- https://deploy-preview-3410--opentelemetry.netlify.app/docs/specs/otel/metrics/semantic_conventions
- …

Add redirect rules for main spec 404s

---

content/en/blog/2023/gc-candidates.md

This PR fixes the information about the number of available seats for this GC election.
Source: https://github.com/open-telemetry/community/blob/main/elections/2023/governance-committee-election.md#vacancies
> Five people must be elected in this election, each with two-year terms

Fix the number of available seats for GC Elections

---

layouts/partials/banner.md

This sets a banner to announce the elections starting next week. We can get back to the KubeCon banner when voting is closed. 
Preview: https://deploy-preview-3421--opentelemetry.netlify.app/
cc @open-telemetry/otel-elections

GC election 2023 - banner update

---

content/en/docs/instrumentation/java/automatic/agent-config.md

After providing the possibility to override peer.service attribute by host, port and path in [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9061). This add documentation.

Add documentation for peer service mapping

---

data/ecosystem/integrations.yaml
static/refcache.json

Add [Traefik Hub](https://traefik.io/traefik-hub/) ([docs](https://doc.traefik.io/traefik-hub/operations/telemetry/overview/)) to the integrations page (related to https://github.com/open-telemetry/opentelemetry.io/issues/3221)

Add Traefik Hub to the integrations

---

content/en/docs/instrumentation/java/manual.md

There's a typo in the documentation regarding the Gradle dependency definition for auto-configuration.

Fix missing package name in Gradle dependencies for auto-configuration

---

content/en/docs/collector/deployment/_index.md
content/en/docs/collector/getting-started.md
content/en/docs/collector/installation.md

Follows up https://github.com/open-telemetry/opentelemetry.io/pull/3426 with a couple of improvements for Collector docs:
* Raises the "Installation" section above "Deployment"
* Adds a description to the Getting Started doc

Edits to Collector docs following the new Get Started

---

content/en/docs/instrumentation/go/exporters.md

It mentioned it was a trace exporter instead of a metrics exporter

Fix description of otlpmetricgrpc

---

.textlintrc.json
content/en/blog/2022/apisix/index.md
content/en/blog/2022/jaeger-native-otlp/index.md
content/en/blog/2022/opamp/index.md
content/en/blog/2023/jmx-metric-insight/index.md
content/en/blog/2023/opamp-status/index.md
content/en/blog/2023/otel-in-focus-01.md
content/en/blog/2023/otel-in-focus-06.md
content/en/blog/2023/otel-in-focus-09.md
content/en/docs/concepts/distributions.md
content/en/docs/demo/services/ad.md
content/en/docs/demo/services/fraud-detection.md
content/en/docs/demo/services/kafka.md
content/en/docs/faas/lambda-auto-instrument.md
content/en/docs/instrumentation/java/resources.md
content/en/docs/kubernetes/collector/components.md
content/en/docs/kubernetes/operator/automatic.md
data/registry/collector-receiver-datadog.yml

Codifies #1661, makes sure that "agent" is written lower case across the docs where applicable. Also adds a rule to detect OpAMP

Updates for text linting: Java agent, agent, OpAMP

---

content/en/blog/2023/opamp-status/index.md

- Followup to #3425
- Replace external links to OpAMP spec by local path to spec
- Replace external KubeCon NA links by local path to KubeCon NA blog post to offer more context for all things OTel at KubeCon NA.
- Ran Prettifier
**Preview**: https://deploy-preview-3460--opentelemetry.netlify.app/blog/2023/opamp-status/

OpAMP status blog copy edits and link adjustments

---

package.json

Fixes build warning. E.g., from https://app.netlify.com/sites/opentelemetry/deploys/653f2f0605f4400008b2daa5:
<pre>
12:20:54 AM: Attempting Node.js version "lts/*" from .nvmrc
12:20:54 AM: v20.9.0 is already installed.
12:20:54 AM: Now using node v20.9.0 (npm v10.1.0)
12:20:55 AM: Enabling Node.js Corepack
12:20:55 AM: Started restoring cached build plugins
12:20:55 AM: Finished restoring cached build plugins
12:20:55 AM: Started restoring cached corepack dependencies
12:20:55 AM: Finished restoring cached corepack dependencies
12:20:55 AM: No npm workspaces detected
12:20:55 AM: Started restoring cached node modules
12:20:55 AM: Finished restoring cached node modules
12:20:55 AM: Installing npm packages using npm version 10.1.0<strong>
12:20:57 AM: npm WARN EBADENGINE Unsupported engine …

[CI] Update package engines.node to 20.x to fix build warning

---

content/en/docs/kubernetes/operator/_index.md

- FYI, the top 404 in the past week was `/docs/k8s-operator/automatic/` (16 hits)
- `k8s-operator` pages were moved via #3027. While the index page was redirected, the section pages were not. This addresses the situation.
- Adds redirects for the moved section pages `automatic.md` and `target-allocator.md` using Netlify wildcard syntax
**Preview**: https://deploy-preview-3467--opentelemetry.netlify.app/
- https://deploy-preview-3467--opentelemetry.netlify.app/docs/k8s-operator/
- https://deploy-preview-3467--opentelemetry.netlify.app/docs/k8s-operator/automatic/
- https://deploy-preview-3467--opentelemetry.netlify.app/docs/k8s-operator/target-allocator/
- https://deploy-preview-3467--opentelemetry.netlify.app/docs/operator/automatic/

Fix K8s operator 404

---

layouts/index.redirects
layouts/partials/schema-file-list.html

- Fixes #3256
- (Was formerly a part of #3469)
**Redirect test**: https://deploy-preview-3475--opentelemetry.netlify.app/schemas/latest
```console
$ curl -sI https://deploy-preview-3475--opentelemetry.netlify.app/schemas/latest | grep -E 'HTTP|loc'
HTTP/2 301 
location: /schemas/1.22.0
```
**Note**: there's a simpler way to get the latest version, by using the semconv spec version. But to do that I'll need to rework some scripts. I'll do that in a followup PR.

Redirect `/schemas/latest` to latest schema

---

netlify.toml

- Fixes #3416
- (Was formerly a part of #3469)
- **Content-type** fix confirmed:
```console
$ curl -sI https://deploy-preview-3474--opentelemetry.netlify.app/schemas/1.20.0 | grep type
content-type: application/yaml
```
- **Download tests**: 
- https://deploy-preview-3474--opentelemetry.netlify.app/schemas/1.20.0

Schema content-type fix

---

.textlintrc.json

- Addresses the issue reported at https://github.com/open-telemetry/opentelemetry.io/pull/3470#issuecomment-1791673382
- Allows `.java`

[CI] Textlint: allow `.java`

---

package.json

Upgrades Hugo. There are changes to the generated site files, but only due to Java syntax-highlight fixes (cf. https://github.com/google/docsy/pull/1701):
```console
$ (cd public && git diff -bw --ignore-blank-lines -I "Hugo 0.1" -- . ':(exclude)*.xml') | grep ^diff | grep -v site/index
diff --git a/blog/2022/exponential-histograms/index.html b/blog/2022/exponential-histograms/index.html
diff --git a/blog/2022/instrument-kafka-clients/index.html b/blog/2022/instrument-kafka-clients/index.html
diff --git a/docs/concepts/instrumentation/libraries/index.html b/docs/concepts/instrumentation/libraries/index.html
diff --git a/docs/demo/services/ad/index.html b/docs/demo/services/ad/index.html
diff --git a/docs/instrumentation/java/automatic/annotations/index.html …
```

[infra] Update Hugo to 0.120.3 and netlify-cli

---

content/en/docs/instrumentation/php/exporters.md

The gRPC exporter example contains an import to outdated path for the Signals interface.

Fix wrong Signals interface path import

---

.textlintrc.json
content/en/blog/2022/debug-otel-with-otel/index.md
content/en/docs/instrumentation/java/manual.md

- Fixes #3498
- Contributes to #3458
- Followup and alternative (better) solution to #3492
- Adds a proper patter to `terminology` to recognize and fix "Java" mis-capitalizations. In particular, it avoids reporting false positives:
- File names: `file.java`
- Repo names: `opentelemetry-java`
- IDs: `java.util.List`, as they might appear, e.g., in markdown link-text 
- Drops `allow` pattern
- Drops "Java" word from terminology list
- Makes fixes to doc pages
- Switches to interpreting `.yml` files a markdown. This gives us better checking, with fewer false positives, especially for fields that contain markdown
- Improves on registry-`tags` allow pattern
**Preview**: e.g.,
- https://deploy-preview-3497--opentelemetry.netlify.app/docs/instrumentation/java/manual/

[CI] Textlint: properly check for Java capitalization & more

---

assets/scss/_styles_project.scss
content/en/blog/2023/integrations.md
content/en/ecosystem/integrations.md

- Rather than add a "note" at the top of integration post, I propose that we add a distinctive badge
- This PR adds a blog post that introduces the badge, which we'll be able to use in other posts such as #3466 and #3431
- Clicking the badge refers the reader back to this post.
- If you like the idea, I suggest we merge this. After I'll factor out the badge so that it can be reused in other posts via a shortcode.
**Preview**: https://deploy-preview-3485--opentelemetry.netlify.app/blog/2023/integrations/
Desktop:
> <img width="662" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/cd70ec85-cc54-4ea7-9ec4-3c539a9b1469">
Hovered state:
> <img width="648" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/2915d8c8-3a59-4e5f-8a08- …

Blog: OTel Integrations Welcome! + badge

---

assets/scss/_styles_project.scss
content/en/blog/2023/integrations.md
layouts/shortcodes/blog/integration-badge.html

- Followup to #3485
- Factors out the integration-badge into its own shortcode
- Moves hard-coded styling into `.ot-integration-badge*` classes
- Fixes the `<a>` element to use `role="button"` instead of `type` (that was a typo)
- Note: visually the badge is the same as it was in #3485 
**Preview**: https://deploy-preview-3505--opentelemetry.netlify.app/blog/2023/integrations/

Integration-badge factored out into its own shortcode

---

gulp-src/prune.js
static/refcache.json

- Drops entries from the refcache that have status 4XX. There shouldn't be any 4XX-status entries in the refcache.
- Reworks the `prune` Gulp task to:
- Fixes entry removal. 4XX entries and by-date entries are now handled separately
- Adds `list` flag, to list the date of the oldest entries

Drop entries from the refcache that have status 4XX

---

content/en/blog/2022/instrument-apache-httpd-server/index.md
content/en/docs/instrumentation/python/distro.md
scripts/normalize-cspell-front-matter.pl

- Fixes #3501
- Also strips out multiple occurrences of the separators (like multiple spaces), and replaces them by a single space

[CI] Strip commas from cSpell:ingore word lists

---

.github/workflows/auto-update-versions.yml
.github/workflows/scripts/auto-update-version.sh
content/en/docs/instrumentation/java/_index.md
content/en/docs/instrumentation/java/automatic/annotations.md
content/en/docs/instrumentation/java/exporters.md
content/en/docs/instrumentation/java/manual.md
content/en/docs/instrumentation/java/resources.md

- Preparation for #3377
- #3458
- Refactors the OTel-Java related front-matter version keys so that they are all in `docs/instrumentation/java/_index.md`. This enables all pages in that section to access the variables
- Renames the variables so that they are shorter, given the context. I.e., for pages under the Java section, `vers.semconv` means the version of Java semconv, etc.
- There are **no changes to the generated site files** (modulo timestamps etc):
```console
$ (cd public && git diff) | grep ^diff 
diff --git a/docs/instrumentation/java/automatic/annotations/index.html b/docs/instrumentation/java/automatic/annotations/index.html
diff --git a/docs/instrumentation/java/exporters/index.html b/docs/instrumentation/java/exporters/index.html
diff --git …
```

[CI] Refactor OTel-Java related front-matter version keys + autoupdate script changes

---

content/en/docs/instrumentation/net/getting-started.md
static/refcache.json

This reverts the docs to using the .NET coded instrumentation that is more intuitive for .NET developers. This was discussed in the OTel-dotnet SIG and agreed that this is the approach we want to push for as the initial getting started as it's what .NET engineers expect to see.
---
**Preview**: https://deploy-preview-3364--opentelemetry.netlify.app/docs/instrumentation/net/getting-started/

Changed getting started docs for .NET to coded instrumentation

---

content/en/docs/what-is-opentelemetry.md

Two changes for https://opentelemetry.io/docs/what-is-opentelemetry/:
* Move "Why OpenTelemetry" up to make it more prominent
* Add a link to mission, vision & values.

Move why OpenTelemetry up

---

assets/scss/_styles_project.scss
package.json

- Fixes #3157. For details and screenshots, see the issue comments
- Upgrades to Docsy 0.7.2
- Closes #3522 by superseding it -- since Docsy 0.7.2 requires Hugo 0.120.4
**Preview**: https://deploy-preview-3519--opentelemetry.netlify.app
```console
$ (cd public && git diff -bw --ignore-blank-lines -I "Create child page" -I "foldable-nav" -- . ':(exclude)*.xml') | grep ^diff | grep -v site/index
diff --git a/scss/main.css b/scss/main.css
diff --git a/scss/main.css.map b/scss/main.css.map
```

Upgrade Docsy to 0.7.2

---

content/en/docs/concepts/observability-primer.md

With HTTP semantic conventions stable I updated the observability primer with a set of example keys&values from there such that we don't have to make sure they are up-to-date anymore.
Also some OTel -> OpenTelemetry, because why not?

Update table in Observability primer

---

content/en/docs/instrumentation/python/exporters.md

Just a small typo in port number as 413* instead if 431*

Fix typo in port number for OTLP exporter

---

.github/workflows/auto-update-versions.yml
content/en/docs/collector/_index.md
content/en/docs/collector/custom-collector.md
content/en/docs/collector/getting-started.md
content/en/docs/collector/installation.md
content/en/docs/collector/trace-receiver.md

- This is the Collector counterpart to #3503
- Inside Collector doc pages, `vers` will refer to the Collector version, this
replaces `collectorVersion`
- There are no meaningful changes to the generated site pages

Rename collectorVersion param, following Java rework

---

assets/scss/_styles_project.scss
content/en/docs/instrumentation/erlang/exporters.md
content/en/docs/instrumentation/erlang/getting-started.md
content/en/docs/instrumentation/erlang/manual.md
content/en/docs/instrumentation/erlang/propagation.md
content/en/docs/instrumentation/erlang/resources.md
content/en/docs/instrumentation/erlang/sampling.md
content/en/docs/instrumentation/erlang/testing.md
content/en/docs/instrumentation/js/exporters.md
content/en/docs/instrumentation/js/getting-started/nodejs.md
content/en/docs/instrumentation/js/manual.md

- Contributes a fix and closes #3127
**Preview**: e.g., tabbed panes in https://deploy-preview-3560--opentelemetry.netlify.app/docs/collector/installation/#docker are still styled correctly.
```console
$ (cd public && git diff -bw --ignore-blank-lines) | grep ^diff                        
diff --git a/scss/main.css b/scss/main.css
diff --git a/scss/main.css.map b/scss/main.css.map
```

Drop custom SCSS now provided by Docsy 0.7.2

---

scripts/content-modules/adjust-pages.pl

Update semantic-conventions version to `1.23.1`.
See https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.23.1.
---
**Preview**:
- https://deploy-preview-3567--opentelemetry.netlify.app/docs/specs/semconv/
- https://deploy-preview-3567--opentelemetry.netlify.app/schemas/1.23.1
- https://deploy-preview-3567--opentelemetry.netlify.app/schemas/latest

Update semantic-conventions version to 1.23.1

---

content/en/docs/instrumentation/js/libraries.md

The doc in [configuration](https://opentelemetry.io/docs/instrumentation/js/libraries/) section the example:
* fix the `Span` and `ExpressRequestInfo` import
* the `span.setAttribute` has a type error, which the span type is defined as:
```ts
span.setAttribute(key: string, value: SpanAttributeValue): this
``` 
but the real code is:
```ts
span.setAttribute([SemanticAttributes.HTTP_METHOD], info.request.method);
span.setAttribute([SemanticAttributes.HTTP_URL], info.request.baseUrl);
```

Fix(doc): demo code bug for TS/JS

---

content/en/docs/instrumentation/cpp/manual.md

Quick fix for a sentence that is not accurate anymore, as a follow-up it would be great if the C++ manual instrumentation docs could get some love following https://github.com/open-telemetry/opentelemetry.io/issues/3229

Update missing log docs for C++

---

.github/workflows/pr-actions.yml

🙄 I missed a few things with #3590:
* the checkout of the repo needs to happen first
* to comment on PRs permissions are required
* to use `gh` the step needs `github.token`
* the variables set by `gh pr checkout` are different if the repo is upstream or a fork, I compared them and hopefully use the right ones now
Examples: https://github.com/svrnm/opentelemetry.io-pr-test/pulls

Fix pr actions, part 2

---

.github/CODEOWNERS

- Sets `docs-maintainers` as code owner for all Git submodules
- @svrnm - WDYT?
- Kinda related: #3598

CODEOWNERS: add docs-maintainers for content-modules

---

.github/CODEOWNERS
README.md

I would like to update the approvers & maintainers for our repository and at the same team structure the README similar to what other SIGs have on their repos (see https://github.com/open-telemetry/community/blob/main/community-members.md)
This should then also be reflected in changing @open-telemetry/docs-approvers , @open-telemetry/blog-approvers and @open-telemetry/docs-maintainers:
* Drop @open-telemetry/blog-approvers and replace it with docs-maintainers (i.e. a maintainer needs to approve a blog post, an approver is not enough)
* Update @open-telemetry/docs-maintainers to reflect the current state: keep @austinlparker, @chalin, @cartermp and me. Remove @mtwo, @flands & @jparsana except they want to stay on that group explicitly.
* Update @open-telemetry/docs-approvers, I'd like to …

Update community members in README

---

content/en/docs/kubernetes/helm/operator.md

[Update command to reflex new syntax.](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/UPGRADING.md#0423-to-0423)
Related to https://github.com/open-telemetry/opentelemetry-helm-charts/pull/936

[kubernetes] update autoGenerateCert syntax

---

.github/workflows/pr-actions.yml
data/registry/instrumentation-java-pekkoactor.yml
data/registry/instrumentation-java-pekkohttp.yml
layouts/shortcodes/docs/instrumentation/exporters-intro.md
templates/registry-entry.yml

Makes sure that cSpell is used consistently, add cSpell:ignore example to registry template

minor fixes for cspell

---

content/en/docs/instrumentation/ruby/exporters.md

`OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4318/v1/traces"` did not work as expected.
```
E, [2023-12-01T20:15:29.518443 #15315] ERROR -- : OpenTelemetry error: OTLP exporter received http.code=404 for uri: '/v1/v1/traces'
E, [2023-12-01T20:15:29.518806 #15315] ERROR -- : OpenTelemetry error: Unable to export 1 spans
```
It works correctly when removing "/v1/traces" from the endpoint.

doc: Remove `/v1/traces` from OTEL_EXPORTER_OTLP_ENDPOINT

---

content/en/docs/demo/services/checkout.md
content/en/docs/demo/services/product-catalog.md

I updated these docs to reflect the source code modifications.
See: https://github.com/open-telemetry/opentelemetry-demo/pull/1284

Update checkout.md & product-catalog.md

---

data/ecosystem/vendors.yaml

Hi! Adding VictoriaMetrics to OpenTelemetry vendor list, per the vendor docs instructions.
**Link to the documentation that details how your offering consumes OpenTelemetry natively via OTLP.**
VictoriaMetrics supports [metrics format for ingestion](https://docs.victoriametrics.com/#sending-data-via-opentelemetry).
**Link to your distribution, if applicable**
N/A
**Link that proves that your offering is open source, if applicable. An open source distribution does not qualify your offering to be marked “open source”.**
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/LICENSE
**GitHub handle or email address as a point of contact so that we can reach out in case we have questions**
@hagen1778

Update vendors.yaml to add VictoriaMetrics

---

scripts/cspell-ignore-scanner

@chalin update to you mentioning recently that we should add some terms (like ott) to our global ignore list. 
The script in this PR can help with that, it will collect all ignore lists and then print out the words with the most files having them in their ignore list, here are all with >5:
```
6 darwin
6 debugexporter
6 farfetch
6 loggingexporter
6 loglevel
6 millis
6 otlpreceiver
6 struct
7 autoconfigure
7 kubelet
7 myapp
8 sdktrace
11 distro
13 rolldice
```
Note, that I am not saying that we should add all of them, but the output of the script can help to identify those we should take into consideration.

Add script to scan cspell ignore lists

---

hugo.yaml

FontAwesome is a derived dependency, pulled in via Docsy. There should be no mention of FA versions in this repo. I think that the `font_awesome_version` is a vestige from long long ago.
Removing that like doesn't affect generated site files:
```console
$ (cd public && git diff -I 'var buildDate')
$
```

Drop obsolete hugo config param

---

content/en/docs/instrumentation/net/getting-started.md

- on the initial instructions, added a function for RollDice() that was referenced, but not included.
- when adding the Open Telemetry code, instructions to replace certain lines of code, including the required using statements.

improve dotnet getting started instructions

---

content/en/docs/cve.md
content/en/docs/security/_index.md
content/en/docs/security/cve.md
static/refcache.json

This is adding a page with a list of published security vulnerabilities across all repositories, similar to [Kubernetes docs](https://kubernetes.io/docs/reference/issues-security/official-cve-feed/).

Add CVE page

---

content/en/docs/demo/docker-deployment.md

Fixes a small typo and a missing parenthesis on the Docker deployment page.
---
https://deploy-preview-3664--opentelemetry.netlify.app/docs/demo/docker-deployment/#bring-your-own-backend

Fix missing parenthesis in docker-deployment.md

---

.github/CODEOWNERS

@open-telemetry/sig-security-maintainers  PTAL
This will make sure that changes to /docs/security will ask you for code review

Make sig-security-maintainers code owners for security docs

---

content/en/docs/collector/building/_index.md
content/en/docs/collector/building/authenticator-extension.md
content/en/docs/collector/building/connector.md
content/en/docs/collector/building/receiver.md
content/en/docs/collector/configuration.md
content/en/docs/collector/distributions.md

We discussed this a few times already that we should group some of the "Building..." and add a new section for them. Here it is. I thought about including [Building a custom collector](https://opentelemetry.io/docs/collector/custom-collector/) or not, and decided against inclusion: I think it is a very important topic that needs to be at a higher level, and it is  also different to the other as it is not something that requires you to write code. That's why this section is now called "Building custom components"
I also dropped/added some qualifiers:
* All mention of "custom" as this is now given by the top level
* Renamed "trace receiver" to only "receiver", as this is just an example but could be used for other components as well (I actually used it as an entry point to write a …

Add 'Building' section to collector docs

---

LICENSE-CODE
NOTICE

The LICENSE-CODE file has a copy&paste error, fixed by this. I checked with other projects and the meaning of the license and the `Copyright [yyyy] [name of copyright owner]` should **not** be replaced by a project name.
I also added a NOTICE file as suggested by the apache license, see [section 4.4](https://www.apache.org/licenses/LICENSE-2.0.html#redistribution) for details. Although our repo does not have a lot of content, I think it still helps to improve potential attributions.

Fix code license, add NOTICE

---

content/en/docs/concepts/context-propagation.md
content/en/docs/concepts/signals/traces.md

This PR moves the concept of context propagation out of traces into a dedicated page. I tried to fix some of the wording to make it clear that this concept is not exclusive to tracing/for all signals, but overall I tried to keep the text untouched as far as possible, as this may require a follow up PR to cleanup (so this is a "perfect is the enemy of good" PR)

Move context propagation into dedicated page

---

content/en/docs/instrumentation/php/automatic.md
content/en/docs/instrumentation/php/getting-started.md
content/en/docs/instrumentation/php/manual.md
content/en/docs/instrumentation/php/sdk.md

Globals was moved just prior to going GA, but the documentation was not updated accordingly.

php: fix namespace of Globals

---

content/en/docs/demo/docker-deployment.md

Fixes: #3473 
Add instructions on changing the port number when deploying the demo, as the machine may already have a conflict on the default port. This only affects docker deployments on local machines.

[demo] - document how to change demo port number for docker deploy

---

content/en/docs/instrumentation/php/manual.md

Adjust reference path for php library:
* OpenTelemetry\Contrib\Otlp\ConsoleMetricExporterFactory;
The following path was changed in opentelemetry-php PR https://github.com/open-telemetry/opentelemetry-php/pull/1055
https://github.com/open-telemetry/opentelemetry.io/blob/7fa1b1433b08bbb37e08a9cd22f94289e94111ab/content/en/docs/instrumentation/php/manual.md?plain=1#L451

docs: adjust reference path for php library

---

scripts/content-modules/adjust-pages.pl
static/refcache.json

Reverts open-telemetry/opentelemetry.io#3755, the legacy links are breaking the "Warnings in build logs" check:
https://github.com/open-telemetry/opentelemetry.io/actions/runs/7486415031/job/20376788178?pr=3731
Not sure why this was not caught by the cheks in #3755
for context: https://github.com/open-telemetry/opentelemetry-specification/pull/3794#discussion_r1427690941

Revert "Update opentelemetry-specification version to 1.29.0"

---

.cspell.yml
content/en/blog/2022/instrument-nginx/index.md
content/en/blog/2023/any-metric-receiver.md
content/en/blog/2023/logs-collection/index.md
content/en/docs/collector/building/receiver.md
content/en/docs/demo/architecture.md

- Fixes #3747
- For example, `content/en/docs/demo/architecture.md` no longer needs a local-page dictionary after we ignore some code blocks.
- I'll file a separate PR for the cleanup of the page-local dictionaries, if/once this gets merged.

[CI] Don't check spelling inside some code blocks

---

scripts/content-modules/adjust-pages.pl
static/refcache.json

Replacement for #3755 (see #3756 as well)

Update opentelemetry-specification version to 1.29.0

---

content/en/blog/2024/_index.md
content/en/blog/_index.md
layouts/blog/baseof.html
layouts/blog/list.html

- Fixes #3782
- Adds breadcrumbs to the blog section and post pages
- Adds last-modified info to the bottom of posts.
Related Docsy issues (FYI):
- https://github.com/google/docsy/issues/1789
- https://github.com/google/docsy/issues/1196
https://github.com/google/docsy/pull/1791
---
**Preview & Redirect test**: https://deploy-preview-3784--opentelemetry.netlify.app/blog/
> <img width="787" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/0360f8ed-1458-4e3d-8224-b38f0356801e">
> <img width="787" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/17073518-b1a0-46c0-bdc3-e98b3922f0d0">
> <img width="788" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/857cea9d-5eac-4756-8eae-3cf608b049db">

[Blog] Prepare for 2024 + blog navigation enhancements

---

content/en/blog/2019/_index.md
content/en/blog/2021/_index.md
content/en/blog/2022/_index.md
content/en/blog/2023/_index.md

I was overzealous when I reintroduced RSS feeds; this PR trims out feeds that won't ever change: we don't need RSS feeds for blog sections of previous years since there will never be any new publications in those sections.

[Blog] Keep RSS feed for root and current year only

---

.htmltest.yml
content/en/blog/2023/end-user-q-and-a-03.md
static/refcache.json

Refcache updates 2024-01-18

---

data/instrumentation.yaml

The [opentelemetry-ruby](https://github.com/open-telemetry/opentelemetry-ruby) repository receives active contributions implementing logs and metrics features. I think an appropriate status is "in development".

Update Ruby metrics and logs status to "in development"

---

.htmltest.yml
content/en/blog/2022/frontend-overhaul/index.md
content/en/blog/2022/otel-demo-app-nomad/index.md
static/refcache.json

Refcache updates 2024-01-19

---

content/en/docs/languages/net/libraries.md

Makes use of the newly introduced intro shortcode for the go page on instrumentation libraries.

Update .NET libraries page with new intro

---

content/en/docs/languages/go/getting-started.md

Follows https://github.com/open-telemetry/opentelemetry-go/pull/4849/
PTAL @open-telemetry/go-approvers

[Go] Getting started: Do not use semconv

---

data/registry/instrumentation-go-ibm-sarama.yml
static/refcache.json

Per https://github.com/IBM/sarama/issues/2510#issuecomment-1909758994
CC @dnwe

Add github.com/dnwe/otelsarama to registry

---

content/en/docs/demo/services/_index.md

- Fixes #3874
- Minor copy edit to Services page
- Recovers `service_table` alias
- Adds `service-table` alias since the page was dropped/merged via #3833
**Preview & redirect tests**:
- https://deploy-preview-3875--opentelemetry.netlify.app/docs/demo/services/
- https://deploy-preview-3875--opentelemetry.netlify.app/docs/demo/service_table/ --> `services/`
- https://deploy-preview-3875--opentelemetry.netlify.app/docs/demo/service-table/ --> `services/`

[demo] Add and recover aliases for service-table + copyedit

---

.textlintrc.yml
content/en/docs/concepts/signals/metrics.md

[CI/textlint] Enforce "backend" as one word

---

content/en/docs/languages/js/propagation.md
content/en/docs/languages/python/propagation.md

- Followup to:
- #3716
- #1951
- In each of the PRs listed above, a new `propagation.md` page is introduced. Generally for new pages we don't need an alias. This PR removes the superfluous aliases, and cleans up the page-local dictionary while we're there.
/cc @cartermp

Drop unnecessary `api/propagation` aliases and local dictionary

---

content/en/blog/2023/end-user-q-and-a-02.md
content/en/docs/languages/js/automatic/module-config.md
content/en/docs/languages/php/sdk.md
content/en/docs/languages/python/automatic/agent-config.md
content/en/docs/languages/sdk-configuration/_index.md
content/en/docs/languages/sdk-configuration/general.md
content/en/docs/languages/sdk-configuration/otlp-exporter.md

- It doesn't make sense IMHO for detailed SDK config pages to be under **Concepts**. This PR proposes a move of those detailed SDK config pages into the "Language APIs & SDKs" section, which feels like a better home.
Comments on this IA reorg are most welcome.
- ~The PR link checking will fail: I'll fix that if/once there is buy-in regarding the reorg.~
**Preview**: https://deploy-preview-3888--opentelemetry.netlify.app/docs/languages/sdk-configuration/
- https://deploy-preview-3888--opentelemetry.netlify.app/docs/concepts/sdk-configuration/
- https://deploy-preview-3888--opentelemetry.netlify.app/docs/concepts/sdk-configuration/general-sdk-configuration
- https://deploy-preview-3888--opentelemetry.netlify.app/docs/concepts/sdk-configuration/otlp-exporter-configuration …

[IA] Move detailed SDK config out of Concepts

---

.htmltest.yml
content/en/blog/2022/otel-demo-app-nomad/index.md
content/en/blog/2023/contributing-to-otel/index.md
content/en/blog/2023/humans-of-otel.md
content/en/docs/collector/building/connector.md
content/en/docs/kubernetes/helm/collector.md
data/ecosystem/integrations.yaml
scripts/normalize-cspell-front-matter.pl
static/refcache.json

- Contributes to #3804
- Fixes #3818
- Refreshes all refcache links so that all timestamps are in 2024! Hurrah, we're done with updates until 24Q3!
- Updates `normalize-cspell-front-matter.pl` to ensure that page-local dictionary words are unique
- Cleans up some page-local cSpell word lists using the updated script
/cc @avillela for the updates to your blog posts

Refcache entries refreshed up to 2024-01-01 & normalize-cspell-front-matter.pl: ensure words are unique

---

.github/workflows/auto-update-versions.yml
.gitmodules
scripts/auto-update/all-versions.sh
scripts/auto-update/version-in-file.sh
scripts/sync-submodules.pl

- Fixes #3910 
The failure was due to the rename of `instrumentation` to `languages`
- Fixes #3909
- Adds "pin" versions/commits to `.gitmodules`
- Contributes to #3149 by adding a "force" sync-submodules script using the specified version/commit "pin" in `.gitmodules`. The script isn't hooked up to anywhere yet.

[CI] Auto-update-versions: fix action + pin gitmodules

---

.cspell.yml
.textlintrc.yml
content/en/blog/2022/instrument-kafka-clients/index.md
content/en/blog/2023/otel-in-focus-06.md
content/en/blog/2023/otel-in-focus-09.md
content/en/docs/languages/java/automatic/spring-boot.md
content/en/docs/languages/java/exporters.md
content/en/docs/languages/java/getting-started.md
content/en/docs/languages/java/instrumentation.md
content/en/docs/languages/java/libraries.md

- Completes the fix for #3891
- Fixes the "Auto Config*" rewrite-rule so that it forces the "c" in "config*" to be in lowercase
- Scrubs some page-local dictionaries

[CI/textlint] "Auto Config*" rewrite-rule capitalization fix

---

README.md

- Fixes #3907
Replacing relative links (that won't render in GitHub) with absolute URLs. Open to suggestions for a better approach (I'd rather not send folks to the docs source if we've a rendered site).

Fix broken contribution links in README

---

.gitmodules
package.json

- Upgrades:
- Docsy to v0.8.0-17-g91efe35 -- e.g., brings in FontAwesome (minor/patch) upgrade
- Hugo to 0.122.0
- Contributes to #3149 by adding an NPM script named `sync` (I'm choosing to keep the name short since atm the only thing we're syncing are submodules).
- Closes #3872
Process followed for Docsy (/cc @svrnm):
- Updated `.gitmodules` with the new Docsy version pin
- Ran `npm run sync`

Upgrade docsy & hugo + add NPM sync script

---

layouts/partials/page-meta-links.html

- Patches the page-meta partial as part of a stepped process for #3922. This whitespace fix will make it easier to manage generated-site page diffs once we start upgrading `path_base_for_github_subdir` in submodules.

[docsy] Temp page-meta-links patch

---

data/registry/exporter-dotnet-oltp-hook.yml
data/registry/exporter-dotnet-otlp-hook.yml
static/refcache.json

I've created a standalone .NET CLR Startup Hook that uses the OLTP exporter to push spans to an OLTP Collector (via the OTel SDKs of course). This is useful for applications that are instrumented with System.Diagnostics.Activity, but for whatever reason can't take direct dependencies on the OTel SDK.

Add entry for baronfel/otel-startup-hook

---

.htmltest.yml
content/en/docs/collector/registry.md
content/en/docs/languages/cpp/registry.md
content/en/docs/languages/erlang/registry.md
content/en/docs/languages/go/registry.md
content/en/docs/languages/java/registry.md
content/en/docs/languages/js/registry.md
content/en/docs/languages/net/registry.md
content/en/docs/languages/php/registry.md
content/en/docs/languages/python/registry.md
content/en/docs/languages/ruby/registry.md
content/en/docs/languages/rust/registry.md
content/en/docs/languages/swift/registry.md

After revamping the registry, I was thinking about ways to make it easier to find for end-users. This PR suggests to add a link to each language & the collector which directly leads to the registry with the given language (or the collector) being preselected.
I picked Python, PHP, .NET and the collector as examples, but we can easily apply this to all languages. What do you all think?
Preview:
Go to https://deploy-preview-3932--opentelemetry.netlify.app/docs/languages/python/ and see the left-side menu. This also gives us a link like [opentelemetry.io/docs/languages/python/registry](https://deploy-preview-3932--opentelemetry.netlify.app/docs/languages/python/registry/) (real link leads to the preview)

Add redirects to collector/language-specific registry entries

---

.gitmodules
scripts/content-modules/adjust-pages.pl

- Contributes to #3922
- No change in generated site files
- Page-meta, such as View page source, still works for the mission page and roadmap
**Preview**: https://deploy-preview-3935--opentelemetry.netlify.app/community/

Update community submodule

---

content/en/docs/concepts/signals/metrics.md

There is an unnecessary 'd' there which is a typo.

Unnecessary word 'd' in metrics.md

---

content/en/docs/languages/java/instrumentation.md

Hi OpenTelemetry team 👋 
Following [a dependency management issue using Java Spring Boot app and Gradle build system](https://github.com/open-telemetry/opentelemetry.io/issues/3613), I updated the _Java Manual Instrumentation_ documentation page.
This PR proposes a fix to https://github.com/open-telemetry/opentelemetry.io/issues/3613 and the rationale for its content (using OTel BOM import rather than removing Spring dependency management pluging) is explained in my comment: https://github.com/open-telemetry/opentelemetry-java/issues/6018#issuecomment-1842561406.
It's my first contribution to this repository so feel free to provide guidance if I miss something. 
I have built the site locally and tested it using `npm run test`. It seemed fine 😇 
>[!NOTE]
> In addition, I updated the …

Fix Java manual instrumentation with Spring Boot app

---

content/en/docs/languages/rust/exporters.md
content/en/docs/languages/rust/getting-started.md
data/registry/otel-rust.yml
layouts/shortcodes/version-from-registry.md

My goal was to create version updating similar to Java for a few other languages. I wanted to start with rust, since this is a part of our docs that is still manageable. While doing so, I figured that our [current mechanism](https://github.com/open-telemetry/opentelemetry.io/blob/main/.github/workflows/auto-update-versions.yml) will not work:
* The versions for the OTLP and stdout exporter are not available from the repos
* The tagged SDK version ([v0.21.2](https://github.com/open-telemetry/opentelemetry-rust/releases/tag/v0.21.2)) is out of sync with the version on crates.io ([v0.21.0](https://crates.io/crates/opentelemetry))
By accident I stumbled upon the fact that those version are available (and auto-updated!) via the registry now! So with this PR I propose a short code that is able …

[IA] Auto-Update rust versions in docs from registry

---

CONTRIBUTING.md

Re-adding `[netlify]` that was removed by mistake in the previous round of changes (#3651):
> <img width="478" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/b513f59f-3efa-4cd5-ad1c-7efa985ca056">

Update CONTRIBUTING.md: add missing link definition

---

.cspell.yml
data/ecosystem/adopters.yaml
static/refcache.json

This change:
- Adds Skyscanner to the adopters list
- Sorts the list of adopters alphabetically. It seems it was sorted alphabetically and then at some point stopped being sorted alphabetically. Happy to revert that commit if it's not the intention of this list to be sorted alphabetically.

Add Skyscanner to adopters lists

---

.gitmodules
assets/scss/_external_link.scss
assets/scss/_styles_project.scss
hugo.yaml
layouts/_default/_markup/render-heading.html
static/refcache.json

- Upgrade docsy to a **pre-v.0.9.0 release**. For a list of breaking changes, see https://github.com/google/docsy/blob/main/CHANGELOG.md#090
- Note that the **copyright** notice now has a **date range**, and it has been streamlined:
> <img width="1199" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/5da1b22c-1be9-4d33-9ce4-af2ecb7fd01a">
- Other notable changes:
- Docsy now follows recommended accessibility practice: page-body **links are underlined**
- Heading self-link icon is now generated at build time, rather than client-side. The default icon is a hash character.
**Preview**: https://deploy-preview-3967--opentelemetry.netlify.app

Upgrade to docsy v0.8.0-49-g621fb34, prep for v0.9.0, streamline footer-center page + copyright date range

---

content/en/docs/languages/python/exporters.md
static/refcache.json

try to resolve: https://github.com/open-telemetry/opentelemetry.io/issues/3964

fix Python Exporters page links to python packages

---

content/en/docs/languages/go/resources.md

Follows https://github.com/open-telemetry/opentelemetry-go/pull/4887
@open-telemetry/go-approvers PTAL
Side note: @open-telemetry/docs-approvers, actually it may be better to simply add a reference to  https://pkg.go.dev/go.opentelemetry.io/otel/sdk/resource. But I would rather do it as a separate PR and also right now the example is not published on https://pkg.go.dev/go.opentelemetry.io/otel/sdk/resource.

Update Go resource example

---

layouts/shortcodes/docs/languages/exporters/intro.md

fixes https://github.com/open-telemetry/opentelemetry.io/issues/3951
---
**Preview**: **Preview**: https://deploy-preview-3963--opentelemetry.netlify.app/docs/languages/java/exporters/

Reword exporters intro to not imply the collector is a viz+analysis backend

---

content/en/docs/languages/java/_index.md
static/refcache.json

Seems those repositories exist but are not listed.

Added 2 repositories to java main MD

---

package.json

Trying to roll out all potential root causes for why the netlify build is not working, so I want to bump that version to latest. We may revert it if this is not helpful/making things worse, because builds are broken already.

Bump netlify version (17.16.1)

---

data/registry/tools-ruby-rspec-matcher.yml
static/refcache.json

This adds the rspec-otel gem to the registry.
https://rubygems.org/gems/rspec-otel

Add rspec-otel to registry

---

content/en/docs/languages/java/instrumentation.md

seem like example code had been changed without updating the hl_lines.

Document: fix instrumentation.md code highlight error

---

content/en/docs/demo/services/currency.md

The following PR adds logs to CurrencyService (c++):
https://github.com/open-telemetry/opentelemetry-demo/pull/1378
This PR updates the logs section of this service.
I also updated the metrics section which was outdated.

Add logs instructions to currencyservice

---

content/en/docs/kubernetes/operator/automatic.md

Updates the java examples to use the new http+protobuf default and port 4318.
A user pointed this out over in [#10614](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10614).

Update java default proto and port in automatic.md

---

data/ecosystem/vendors.yaml
static/refcache.json

We are introducing Application Observability as a new capability to OpenText Operations Bridge. Release announcement is at https://docs.microfocus.com/doc/OBS/SaaS/ReleaseNotes. Hence adding OpenText as one of the Vendors supporting OpenTelemetry.

adding opentext to vendor list

---

content/en/docs/kubernetes/operator/automatic.md
content/en/docs/languages/python/automatic/_index.md
content/en/docs/languages/python/automatic/example.md
content/en/docs/languages/python/getting-started.md

The evergreen problem that causes 50+ reply threads in slack persists. Herein I try to make it a little more clear what you need to do, until such a time that this resolves upstream.

Try to really clarify that you need flask and wekzeug < 3

---

content/en/ecosystem/adopters.md
data/ecosystem/adopters.yaml
static/refcache.json

I noticed that https://community.cncf.io/end-user-community/ no longer existed, and couldn't find a related page, so pointed to the root of the domain.
~~I also removed all adopters with no blog post as defined in the `grace-period-2024-01-01` footnote.~~

fix: adjust dead link

---

.gitmodules

- Followup to #3973
- Brings in the docsy patch release 0.9.1
- No changes to generated site files, other than the site timestamp.

Update docsy to 0.9.1

---

data/registry/exporter-rust-datadog.yml
data/registry/exporter-rust-stackdriver.yml
data/registry/exporter-rust-user-events-logs.yml
data/registry/exporter-rust-user-events-metrics.yml
data/registry/instrumentation-rust-trillium.yml
data/registry/tools-rust-aws.yml
data/registry/tools-rust-propagator-jaeger.yml
static/refcache.json

We recently cleaned up our README, and started referencing the Registry, but we want to make sure that the crates are still in the registry.
Relates https://github.com/open-telemetry/opentelemetry-rust/issues/1582

registry: Add Missing Rust Crates

---

content/en/blog/2024/kubecon-eu.md

- Followup to #3983
- Fixes:
> <img width="604" alt="Screen Shot 2024-02-28 at 13 01 34" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/4918290c-2731-4915-a117-6869f6928e9b">
- **Preview**: https://deploy-preview-4065--opentelemetry.netlify.app/blog/2024/kubecon-eu/#observability-day

Kubecon blog: fix markdown link def placement so it renders properly

---

data/registry/instrumentation-erlang-req.yml
data/registry/instrumentation-go-mongodb.yml
data/registry/instrumentation-php-psr14.yml
data/registry/tools-go-propagator-datadog.yml
data/registry/tools-php-propagator-b3.yml
data/registry/tools-python-propagator-gcp.yml
data/registry/tools-rust-propagator-jaeger.yml
hugo.yaml

- An upcoming semconv spec changes breaks the build because [Hugo is configured by default to linkify plain-text URLs](https://gohugo.io/getting-started/configuration-markup/#goldmark) -- there is a fictitious raw URL given as an example in prose that is treated as an external link and so link checking fails. That shouldn't happen.
**Use the markdown sytnax `<URL>` in prose to introduce the raw URL as a link.** /cc @theletterf et al.
- Turns off the Goldmark [linkify](https://github.github.com/gfm/#autolinks-extension-) extension.
- Fixes some affected links in registry YAML files
- Other minor copyedits in a few registry YAML files
- **Preview**, e.g.:
- https://deploy-preview-4067--opentelemetry.netlify.app/ecosystem/registry/?s=OpenTelemetry+Jaeger+context+propagation

[Hugo] Don't auto-linkify in prose & fix registry links

---

data/ecosystem/integrations.yaml
static/refcache.json

Traefik Hub's documentation has been remade with a new docs website; thus, the previous link moved.
cc @svx 
Original PR for reference: https://github.com/open-telemetry/opentelemetry.io/pull/3435

Fix Traefik Hub documentation link

---

content/en/blog/2024/kubecon-eu.md
content/en/blog/2024/otel-collector-anti-patterns/index.md

Now that we have the end user feedback sessions nailed for the OTel Observatory, I have added the session names.
Also updated employer name in my last blog post.

Update end user feedback sessions

---

content/en/docs/languages/sdk-configuration/general.md

and link to the matrix table outlining language support.
Addresses #4059.

point out that environmental variable support is optional

---

content/en/docs/contributing/_index.md

This PR fixes a few small typos and clarity issues on the [Contributing](https://opentelemetry.io/docs/contributing/) page.

Make copyedits to Contributing index.md

---

content/en/docs/kubernetes/operator/automatic.md

Java instrumentation now defaults to `http/protobuf` starting from 2.0.0. There was a typo when this readme file was recently updated.

docs: fixed a minor typo in k8s operator docs

---

data/instrumentation.yaml

These are now released as experimental: https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/sdk-logs
@open-telemetry/javascript-approvers would this make sense to change?

Update JS logs status to experimental

---

content/en/blog/2024/kubecon-eu.md
static/refcache.json

We had one more confirmation! for End User Feedback Session: Client-side. This PR adds it to the roster.

Add final End User Feedback Session

---

content/en/docs/collector/transforming-telemetry.md

This PR updates the filterprocessor example to use the preferred OTTL syntax instead of the deprecated include/exclude interface.
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18642.

[collector] Use ottl in filterprocessor example

---

data/ecosystem/vendors.yaml
layouts/shortcodes/ecosystem/vendor-table.md

Since we have a dedicated page for distributions now, I think it is best to remove this column, it also often creates confusion when new entries are generated.

Remove distribution column from vendors

---

content/en/docs/collector/quick-start.md

This PR proposes to add Docker as a prerequisite for the Collector quick start example. Althought Docker is ubitquitous for running applications, if it is not installed on the user's machine, it requires setup prior to running this example.

Add Docker as a prerequisite to Collector quick start example

---

content/en/ecosystem/adopters.md
content/en/ecosystem/distributions.md
content/en/ecosystem/integrations.md
content/en/ecosystem/vendors.md

This replaces all "must" with "should" in the requirements for being added to vendors, integrations, adopters
It removes the grace periode note, since we never enforced that.

Ecosystem policy updates

---

content/en/docs/concepts/observability-primer.md

This PR makes a tiny change to the reliability example on the [Observability Primer](https://opentelemetry.io/docs/concepts/observability-primer/) page. A pair of pants means something different in the UK. :)

Change wording to suit global audience

---

data/ecosystem/vendors.yaml
static/refcache.json

Read [LinkedIn post](https://www.linkedin.com/posts/jpkroehling_opentelemetry-graduation-by-austinlparker-activity-7172873030925332480-FvMW) from @jpkrohling and requested to include us in the vendors list,
as we have been leveraging, consuming OpenTelemetry traces in the Causely product.
Thanks!

Add Causely to vendors.yaml

---

content/en/docs/languages/java/automatic/spring-boot.md

Also 
- annotation dependency is included in starter now
- explain advanced config with the example of "exclude actuator endpoints from tracing"
- explain resource providers

spring starter can now use all sdk autoconfig properties

---

content/en/docs/demo/feature-flags.md

This PR updates the demo docs to reference the correct name of the feature flag for the recommendation service cache failure. It's not a significant change but brings the docs in line with the flag name in the `demo.flagd.json` file.

Demo Docs: Update the name of recommendation cache feature flag

---

content/en/docs/collector/architecture.md

This PR brings the Collector architecture docs page in line with the last version of its [predecessor file](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md).
Relates to [opentelemetry-collector/pull/9665](https://github.com/open-telemetry/opentelemetry-collector/pull/9665).
cc @mx-psi

Remove mention of spanmetrics processor

---

content/en/docs/languages/js/automatic/_index.md
static/refcache.json

Document that only traces are supported today. Fixes #4171

Update OTel JS Autoinstrumentation env var config

---

content/en/docs/concepts/signals/traces.md

fixes https://github.com/open-telemetry/opentelemetry.io/issues/4184

Clarify span events vs. attributes guidance

---

content/en/docs/languages/js/getting-started/nodejs.md

One common approach to register de API is to set the environment variable `NODE_OPTIONS` with `--require @opentelemetry/auto-instrumentations-node/register`, but if we follow the `Getting Started` for `Node.js`, the step to use `--require ./instrumentation.ts` on command line can cause a conflict, resulting on an error message similar to:
```
Error: @opentelemetry/api: Attempted duplicate registration of API: trace
at registerGlobal (/Users/maryliag/development/otel/opentelemetry-js/api/src/internal/global-utils.ts:47:17)
at TraceAPI.setGlobalTracerProvider (/Users/maryliag/development/otel/opentelemetry-js/api/src/api/trace.ts:67:35)
at NodeTracerProvider.register (/Users/maryliag/development/otel/opentelemetry-js/packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts:153:11) …
```

nodejs doc: add clarification to node.js getting started

---

content/en/docs/languages/java/instrumentation.md

Closes #4123 
I tried to mirror the [javascript docs](https://opentelemetry.io/docs/languages/js/instrumentation/#metrics) as closely as possible. Let me know if anything should be revisited or changed.

Update java metric instrumentation docs

---

content/en/docs/demo/feature-flags.md

This commit add the adServiceManualGc feature flag to the opentelemetry demo docs.
The feature flag triggers full manual garbage collections in the ad service.
Upstream PR can be found here: https://github.com/open-telemetry/opentelemetry-demo/pull/1463

[adservice] add new adservice ff to demo docs

---

data/registry/resource-detector-java-aws.yml
data/registry/resource-detector-java-gcp.yml

Add resource detectors available for Java in [opentelemetry-java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main) to OpenTelemetry Registry.
Fixes #4203

[Registry] Add resource detectors for Java

---

content/en/docs/languages/net/getting-started.md

OpenTelemetry.Instrumentation.AspNetCore has already stable versions

.NET - getting started avoid prereleases for OpenTelemetry.Instrumentation.AspNetCore

---

data/registry/instrumentation-dotnet-aws.yml
data/registry/instrumentation-java-aws-sdk.yml
data/registry/instrumentation-js-aws-sdk.yml
data/registry/instrumentation-ruby-aws-sdk.yml

This has come up several times at work (almost always when SQS is involved). This should make it more searchable.

Add some common tags to aws sdk instrumentation metadata

---

.gitmodules
package.json
static/refcache.json

- Contributes to #4064
- Closes #4126
Here's the diff in generated site files:
```console
$ (cd public && git diff -bw --ignore-blank-lines -I 'Hugo 0.12|navbar-dark|theme="dark"|code.jquery|sha512-|<img |var params =|class="text-') | grep ^diff | grep -vE '_print|\.xml$' | head
diff --git a/404.html b/404.html
diff --git a/js/main.js b/js/main.js
diff --git a/refcache.json b/refcache.json
diff --git a/scss/main.css b/scss/main.css
diff --git a/scss/main.css.map b/scss/main.css.map
```
Explanation of differences per file:
- 404 page - b/c of this fix https://github.com/google/docsy/issues/1872
- `main.{js,.css*}` - b/c BS was upgraded to 5.3
- refcache: due to jQuery version upgrade (yes, we want to [drop jQuery in the …

Upgrade Docsy, and Hugo to 0.123+

---

content/en/blog/2024/opentelemetry-announced-support-for-profiling.md
content/en/blog/2024/profiling.md

- Followup to #4183 etc
- Switches to using markdown syntax for footnotes -- which makes them clickable
- Promotes some plain text meant to be a heading to an actual heading
- Adjusts the linkTitle
- Renames the file to use a short name like other blog posts; and adds an appropriate alias
- Replaces "i.e." (which means "that is") by the intended (AFAICT) "for example)
/cc @cartermp @svrnm - who are on PTO, but might see this anyway :) 
**Preview**: https://deploy-preview-4211--opentelemetry.netlify.app/blog/2024/profiling/
**Redirect test**: https://deploy-preview-4211--opentelemetry.netlify.app/blog/2024/opentelemetry-announced-support-for-profiling

Copyedits to Profiling-announcement blog

---

data/ecosystem/vendors.yaml
static/refcache.json

Previous link was broken.
Adding the correct link to Datadog OTel doc page.

Update Datadog doc link

---

data/registry/resource-detector-java-contrib.yml
data/registry/resource-detector-java-spring-boot.yml

Adds the missing resource detectors for Java to OpenTelemetry Registry.

[Registry] Add missing resource detectors for Java

---

.cspell.yml
data/ecosystem/vendors.yaml

- The Vendors data file doesn't contain any descriptions. I see little value in running spell-check over it, so I've added the data file name to the sSpell ignore paths list.
- Normalizes the `vendors.yaml` entries -- dropping unnecessary quotes.
There is no change in generated site files (other than the site timestamp):
```console
$ (cd public && git diff -bw --ignore-blank-lines) | grep ^diff
```

Normalize vendors.yaml, and don't spell-check it

---

content/en/docs/languages/go/exporters.md

The mentioned exporters are stable: 
- https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp
- https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc

Go: OTLP metrics exporters are stable

---

content/en/docs/collector/deployment/gateway.md

Fixes #4223
Note that only metrics are in development now. I think a note is not required, though. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/README.md

Remove note regarding load-balancing exporter

---

data/ecosystem/vendors.yaml

Adds Embrace to the list of vendors who natively support OpenTelemetry.

Add Embrace to vendors list

---

content/en/docs/collector/building/receiver.md

This PR corrects type error for typeStr on Custom Receiver documentation, as well as removes ErrNilNextConsumer checks.
As of version 0.97.0 for dependencies when creating a custom receiver, using typeStr directly as a string was throwing an error of `cannot use typeStr (variable of type string) as component.Type value in argument to receiver.NewFactory ` which should now be done using `component.MustNewType("tailtracer")`, in a var declaration.
Also, as in [Issue 9322](https://github.com/open-telemetry/opentelemetry-collector/issues/9322) and later on accept as [PR 9779](https://github.com/open-telemetry/opentelemetry-collector/pull/9779) and [PR 31793](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31793),` component.ErrNilNextConsumer` is not a valid error type.

Removes deprecated ErrNilNextConsumer and solves type error for typeStr

---

data/ecosystem/distributions.yaml
static/refcache.json

This PR updates the distribution status for Grafana to point to grafana/alloy as well as include our .NET and Java SDK distributions.

Update Grafana distributions links

---

content/en/docs/languages/php/instrumentation.md

The Logger::info is deprecated.
Thus as suggested in the docblock I made the necessary change.
You can find details here: 
https://github.com/Seldaek/monolog/blob/main/src/Monolog/Logger.php#L51

Updated instrumentation.md to replace deprecated Logger::info with Level::info

---

content/en/docs/languages/net/automatic/_index.md
content/en/docs/languages/net/automatic/custom.md
content/en/docs/languages/net/automatic/nuget-packages.md
content/en/docs/languages/net/automatic/troubleshooting.md

Handles https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v1.5.0

OpenTelemetry .NET Automatic Instrumentation v1.5.0

---

content/en/docs/demo/feature-flags.md

This PR adds the adServiceHighCpu feature flag to the opentelemetry demo docs.
The feature flag triggers high cpu load in the ad service.
Upstream PR can be found here: https://github.com/open-telemetry/opentelemetry-demo/pull/1510

Add adServiceHighCpu featureflag to the demo docs

---

content/en/docs/kubernetes/operator/automatic.md
content/en/docs/languages/js/automatic/configuration.md

Current documentation states that it isn't possible to disable specific nodejs auto-instrumentation packages when using kubernetes-operator, but that isn't true after next kubernetes operator release, that allows enabling instrumentations based on `OTEL_NODE_ENABLED_INSTRUMENTATIONS` environment variable.
This documentation change is caused by feature enabled by merged [PR](https://github.com/open-telemetry/opentelemetry-operator/pull/2745)
**that currently isn't released (hence the DRAFT status of this PR),**
and another [PR](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1953) that built the foundation for it.

doc(k8s-operator): document customizing enabled auto-instrumentations for nodejs with kubernetes-operator

---

content/en/docs/collector/deployment/agent.md

In the [default deployment example](https://opentelemetry.io/docs/collector/deployment/agent/#example) the export configuration is expecting to use OTLP over HTTP on port 4318.
```
export OTEL_EXPORTER_OTLP_ENDPOINT=http://collector.example.com:4318
```
The collector examples though is then showing configuration for receivers on gRPC over 4317, instead of 4318.
I assume this was just an oversight when HTTP became the default.

Fix default collector deployment receiver endpoint

---

data/ecosystem/vendors.yaml
static/refcache.json

The [license](https://github.com/uptrace/uptrace/blob/master/LICENSE) is  AGPL-3.0.

chore: mark Uptrace as OSS

---

content/en/docs/contributing/_index.md

Reference: #4292 
The page under https://opentelemetry.io/docs/contributing/ talks about contributing to docs, although people might expect a page on how to contribute to the OpenTelemetry project in general. You have to read down a little bit to run into See also the general [OpenTelemetry Contributor Guide](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md), which provides details on the Contributor License Agreement and the Code of Conduct.
I think we should have this at the very top that this document is for contributing to docs and that the other document is where people find general guidelines.

Issue #4292 link to community guidelines at the top

---

content/en/docs/contributing/_index.md

Add note on drafts

---

content/en/docs/concepts/glossary.md

https://opentelemetry.io/docs/concepts/glossary/#processor talks about Instrumentation Library, but we should remove it, as it is a collector specific term.

Remove processor from glossary

---

content/en/docs/languages/java/automatic/spring-boot.md

Depends on https://github.com/open-telemetry/opentelemetry-java-examples/pull/394

howto configure exporter programmatically in spring starter

---

.github/workflows/pr-actions.yml

Make use of PAT in pr-actions.yml

---

content/en/docs/languages/go/exporters.md

The stdoutmetric package was released as a 1.x, the docs should reflect that

remove experimental label on stdout metrics export

---

content/en/docs/languages/go/exporters.md
static/refcache.json

This follows the examples for trace/metrics and marks log export support as experimental.
---
**Preview**: https://deploy-preview-4357--opentelemetry.netlify.app/docs/languages/go/exporters/#console

add console log export details for go

---

data/ecosystem/vendors.yaml
static/refcache.json

Hello - I am looking to update the the page linked to Embrace Mobile in the [vendors](https://opentelemetry.io/ecosystem/vendors/) list with a more-helpful page about this vendor.

update embrace link in vendors

---

content/en/docs/languages/go/exporters.md
static/refcache.json

Similar to examples for other signals, marked as experimental.

add example for exporting logs over otlp + http

---

.github/CODEOWNERS

follow up to https://github.com/open-telemetry/community/issues/2004

Update CODEOWNERS with new SIG End User group

---

content/en/docs/kubernetes/getting-started.md
content/en/docs/kubernetes/helm/collector.md
content/en/docs/kubernetes/helm/operator.md

The collector and operator helm charts have had a breaking change that needs addressed in our examples:
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1154
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1148
This PR updates the docs to set the image repository so that the chart can be installed.

[kubernetes] Update helm install commands

---

content/en/docs/languages/erlang/libraries.md
static/refcache.json

Part of https://github.com/open-telemetry/opentelemetry.io/issues/4319
@open-telemetry/erlang-contrib-maintainers Please have a look. Overall structure is based on other languages, though we might want to add further considerations on things like semver, stability, etc.

Add missing using instrumentation libraries pages: Erlang/Elixir

---

content/en/docs/languages/php/libraries.md

Part of https://github.com/open-telemetry/opentelemetry.io/issues/4319
@open-telemetry/php-maintainers Please have a look. Overall structure is based on other languages, though we might want to add further considerations on things like semver, stability, etc.

Add missing using instrumentation libraries pages: PHP

---

assets/scss/_registry.scss
content/en/ecosystem/registry/_index.md

- Fixes #4389
- Prepares for #4023
- **Preview**: https://deploy-preview-4390--opentelemetry.netlify.app/ecosystem/registry/?s=alert
/cc @svrnm 
There is not much of a difference between the before and after images (which is what we want).
Before:
> <img width="940" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/9856b26e-a49c-4cb6-9cd2-b742b3706ffe">
After:
> <img width="938" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/16d11924-03b8-4258-83fb-2440e83b6258">

Remove temp registry .highlight style override

---

.gitmodules

- Prep for #4023, without enabling the dark-mode menu

Docsy upgrade to v0.9.1-53-ga8e0a1a

---

content/en/docs/languages/python/libraries.md
static/refcache.json

Part of https://github.com/open-telemetry/opentelemetry.io/issues/4319

Add missing using instrumentation libraries pages: Python

---

content/en/docs/languages/js/automatic/configuration.md

Update Automatic Instrumentation Configuration for Node.js with recent changes to match README on its [repo](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node).

js docs: update doc on auto instrumentation

---

content/en/docs/languages/go/exporters.md

fixes https://github.com/open-telemetry/opentelemetry.io/issues/4412

Correct the http and grpc API calls for Go

---

layouts/shortcodes/ecosystem/vendor-table.md

We removed the distribution column, but we didn't remove it in the heading which breaks the table, this PR fixes that:
https://opentelemetry.io/ecosystem/vendors/

Fix vendors table (remove distros from table heading)

---

content/en/docs/languages/java/instrumentation.md

I noticed that the java example for propagating context across threads is more complicated that it needs to be. We have helper functions specifically for this situation. Updating to be more succinct.

Update java context propagation example to use Context.wrap

---

scripts/content-modules/adjust-pages.pl

- In prep for #4443
- Ensure that the SPEC processing of markdown-link definitions has non-empty URLs. The main change was from the subregex `[:\s]*` to `[:\s]+`.

[infra] Fix spec markdown link processing

---

.prettierignore

- Contributes to #4443
- I've double checked that `en` content _is_ being prettified

[infra] .prettierignore all languages other than en for now

---

content/en/docs/languages/java/instrumentation.md

A typo in the [Java instrumentation doc](https://opentelemetry.io/docs/languages/java/instrumentation/#acquiring-a-tracer) was [reported](https://cloud-native.slack.com/archives/C02UN96HZH6/p1715199466471439) by @austinlparker. 
> ...the line `this(min, max, OpenTelemetry.noop())` needs a semicolon after it
This PR adds the missing semicolon.

Fix typo in Java instrumentation doc

---

.gitmodules
package.json

- In support of debugging config issues of #4443
- No changes to the generated site files other than generator ID and site timestamp

Upgrade to Hugo 0.125.7, Docsy at HEAD

---

content/en/docs/kubernetes/helm/operator.md

This PR corrects an attribute in the Helm chart installation.
**Changes**:
The attribute `--set admissionWebhooks.certManager.autoGenerateCert.enabled=true` is updated to `--set admissionWebhooks.autoGenerateCert.enabled=true` for accurate configuration.
**Reason for Change**:
This change resolves the error: 
```shell
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-operator:
- admissionWebhooks.certManager: Additional property autoGenerateCert is not allowed
```

Fix opentelemetry-operator helm install command

---

hugo.yaml

- #4443
- #2402
- Introduces the proper config in support of `zh` pages, in particular the proper mount point
- This config change is in prep for introducing `zh` pages. No new content is generated yet because `zh` is `disabled`. I.e., there are no changes to the generated site files.

[i18n] Base config for zh

---

content/en/_index.md
hugo.yaml

- Contributes to #4443
- No change to generated site files (given that `zh` pages aren't in production yet)

[i18n] Don't generate _redirects for non-en languages

---

content/zh/_index.md

- Folks, I think that we're ready to launch the **homepage** 🚀 . It maybe look a bit strange given that we don't have any docs pages, but those should come soon :) ... and once they do, I'll implement a fallback to `en` pages (#4478)
- Fixes #2402
**Preview**: https://deploy-preview-4477--opentelemetry.netlify.app/zh/
/cc @open-telemetry/docs-cn-approvers @jiekun

[zh] Show Chinese homepage in production

---

package.json

- Uses `http://localhost` as default `--baseURL` when `$DEPLOY_PRIME_URL` is unset. This makes is easier to distinguish uses of `.` vs `.` in generated pages!
- Drops the `:pkg` qualifier from `update:*` script names; and other related script name tweaks
- NPM package updates
- Switches to the official `hugo-extended` NPM package, now that it's available
- Updates `netlify-cli`, since we might need it soon.
- This PR is in support of #4467

[CI] Use localhost URL prefix for DEPLOY_PRIME_URL & some pkg & script updates

---

layouts/partials/hooks/head-end.html

- Prep for #4487
- Ensures that every page has a canonical URL, as seems to be recommended by best practices

[CI] Ensure that every page has a canonical link

---

content/en/docs/languages/python/getting-started.md

A typo in getting-started.md of Python.
> The `parent_id` of `roll` is the same is the `span_id` for `/rolldice`
`is the same is` -> `is the same as`

Fix typo in Python getting-started.md

---

layouts/partials/hooks/head-end.html

- Contributes to #4487, well, it actually solves it, but I want to refactor the code. I'll do that later. I wanted to get this fix in before Google indexes the site :)
Look at the page source to ensure that the canonical link is appropriately set:
- **Preview**: https://deploy-preview-4494--opentelemetry.netlify.app/
```console
$ curl -s https://opentelemetry.io/zh/docs/getting-started/ | perl -nle 'print $1 if /(canonical"?\s+href=.*?)>/i'
canonical href=https://opentelemetry.io/zh/docs/getting-started/
```
```console
$ curl -s https://deploy-preview-4494--opentelemetry.netlify.app/zh/docs/getting-started/ | perl -nle 'print $1 if /(canonical"?\s+href=.*?)>/i'
canonical href=https://deploy-preview-4494--opentelemetry.netlify.app/docs/getting-started/
```

[zh] Ensure zh fallback pages specify en page as canonical source

---

.github/CODEOWNERS

Adds @open-telemetry/docs-zh-approvers as codeowners for docs/zh, since @open-telemetry/docs-zh-maintainers is a subteam they inherit that ownership and do not need to be mentioned

Add docs-zh-approvers to CODEOWNERS

---

content/en/blog/2024/otel-collector-container-log-parser/index.md
static/refcache.json

This PR adds a blog post about the new `filelogreceiver`'s  container parser which was introduced with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31959. 
/cc @djaglowski
Preview: https://deploy-preview-4489--opentelemetry.netlify.app/blog/2024/otel-collector-container-log-parser/

Add container parser blog post

---

content/en/docs/collector/configuration.md

Fixes #4484.
This PR adds an explanation for the use of double colons to refer to nested keys in YAML config paths.
---
**Preview**: https://deploy-preview-4524--opentelemetry.netlify.app/docs/collector/configuration/#location

Add explanation of double colons to Collector config page

---

.github/CODEOWNERS
content/en/blog/2023/end-user-discussions-03.md
content/en/docs/concepts/instrumentation/zero-code.md
content/en/docs/kubernetes/operator/automatic.md
content/en/docs/languages/js/instrumentation.md
content/en/docs/zero-code/js/_index.md
content/en/docs/zero-code/js/configuration.md

Contributes to #4427, such that Java is not the only language there for now. 
This PR also introduces updates for CODEOWNERS for both java and javascript

[IA] Relocate JavaScript Automatic pages to new Zero-code section + CODEOWNERS

---

content/en/docs/zero-code/net/_index.md

Follow up to #4532
Before changes

[dotnet-auto] Fix link title to .NET (menu)

---

.htmltest.yml
content/en/blog/2022/debug-otel-with-otel/index.md
content/en/blog/2023/spring-native/index.md
content/en/docs/faas/lambda-auto-instrument.md
content/en/docs/kubernetes/operator/automatic.md
content/en/docs/languages/java/getting-started.md
content/en/docs/languages/java/instrumentation.md
content/en/docs/languages/java/libraries.md
content/en/docs/languages/java/resources.md
content/en/docs/zero-code/java/agent/configuration.md
content/en/docs/zero-code/java/spring-boot-starter/sdk-configuration.md

- Contributes to #4428
- Drops temporary link-checker ignore rules
- Canonicalizes links to the Java agent pages
- Copyedits to cope with the switch from "automatic" to "zero-code"

[IA] Zero-code Java Agent: canonicalize links + copyedits

---

content/en/docs/zero-code/java/spring-boot-starter/_index.md
content/en/docs/zero-code/java/spring-boot-starter/additional-instrumentations.md
content/en/docs/zero-code/java/spring-boot-starter/annotations.md
content/en/docs/zero-code/java/spring-boot-starter/getting-started.md
content/en/docs/zero-code/java/spring-boot-starter/other-spring-autoconfig.md
content/en/docs/zero-code/java/spring-boot-starter/out-of-the-box-instrumentation.md

- Followup to #4554
- Adds missing alias
- Removes unnecessary aliases
- Includes some copyedits for #4554. I have more copyedits to make but decided to stop so that we can land the alias fixes ASAP
- Closes #4562 by superseding it
**Preview**: https://deploy-preview-4563--opentelemetry.netlify.app/docs/zero-code/java/spring-boot-starter/
- https://deploy-preview-4563--opentelemetry.netlify.app/docs/instrumentation/java/automatic/spring-boot/
This confirms the fix for the link failure reported in https://github.com/open-telemetry/opentelemetry-java-examples/actions/runs/9242715195/job/25527124585?pr=416. /cc @zeitlinger 
- https://deploy-preview-4563--opentelemetry.netlify.app/docs/languages/java/automatic/spring-boot/
- …

Spring Boot starter: Alias fixes and partial copyedits

---

.github/workflows/auto-update-versions.yml
content/en/docs/zero-code/java/_index.md
scripts/auto-update/all-versions.sh

- Contributes to #4428
- Ensures that all package `vers` entries get auto-updated for `content/en/docs/zero-code/java/_index.md`
- Cleans up `.github/workflows/auto-update-versions.yml`
- I tested this locally

[CI] [Java agent] Ensure pkg versions get updated under zero-code

---

content/en/docs/zero-code/java/agent/annotations.md
content/en/docs/zero-code/java/agent/extensions.md

- Contributes to #4428
- When the `languages/java/automatic` pages were moved, the page-relative aliases should have been made absolute. This PR addresses this need.
- Absolute paths used in this PR were recovered from:
- #1232
- https://github.com/open-telemetry/opentelemetry.io/commit/7f46ec2d7d04170d9aeaa8e2f5ec93408aee2ea5

[Java agent] Use absolute alias paths matching original

---

content/en/docs/zero-code/net/_index.md
content/en/docs/zero-code/net/configuration.md

- Contributes to #4427
- This PR is like #4568 but for .NET
- Adjusts .NET zero-code page title to use "zero-code" rather than "automatic"

[Zero-code .NET] Fix page-relative alias path following move to zero-code section

---

content/en/docs/zero-code/js/configuration.md

- Contributes to #4427
- Follow up to #4527
- Fixes typo in alias

Alias fix for zero-code JS

---

.github/CODEOWNERS

- Followup to changes made in #4527
- Sorts the `content` entries, in particular so as to not start mixing `en` and `zh` entries
- Fixes indentation
- No other changes

CODEOWNERS: sort entries

---

content/en/docs/collector/_index.md
content/en/docs/concepts/_index.md
content/en/docs/contributing/_index.md
content/en/docs/demo/_index.md
content/en/docs/faas/_index.md
content/en/docs/getting-started/_index.md
content/en/docs/kubernetes/_index.md
content/en/docs/languages/_index.md
content/en/docs/migration/_index.md
content/en/docs/security/_index.md
content/en/docs/specs/_index.md
content/en/docs/what-is-opentelemetry.md
content/en/docs/zero-code/_index.md
content/zh/docs/concepts/_index.md
content/zh/docs/what-is-opentelemetry.md

- Fixes the order of `zh` top-level sections
- Fixes #4572 -- see screenshots below
- Redistributes the weights of the top-level `docs` sections, without changing the order of `en` pages.
Here's proof that the order of pages under `en` hasn't changed:
```console
$ (cd public && git diff -bw --ignore-blank-lines) | grep ^diff | grep -v zh
diff --git a/_redirects b/_redirects
diff --git a/en/sitemap.xml b/en/sitemap.xml
```
**Preview**:
- https://deploy-preview-4573--opentelemetry.netlify.app/docs
- https://deploy-preview-4573--opentelemetry.netlify.app/zh/docs/
| Before | After |
|--------|--------|
| <img width="319" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/c92c308e-d946-44b6-894 …

[i18n] Docs section ordering fix

---

data/instrumentation.yaml

OTel Go Logs are already beta since https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.27.0

Update Go logs status to beta

---

content/zh/docs/concepts/semantic-conventions.md
content/zh/docs/demo/_index.md
content/zh/docs/kubernetes/_index.md

Follow through of:
- https://github.com/open-telemetry/opentelemetry.io/pull/4536#discussion_r1626069609
- #4582
For the record, here are the commands I used:
```bash
find content/zh -name '*.md' -exec perl -i -0777 -pe 's///gs' {} \;
find content/zh -name '*.md' -print0 | xargs -0 perl -i -0777 -pe 's/\n{2,}/\n\n/gs'
```

[zh] Strip away embedded HTML en fragments

---

content/ja/_index.md
content/zh/_index.md
content/zh/docs/_index.md
content/zh/docs/concepts/_index.md
content/zh/docs/concepts/components.md
content/zh/docs/concepts/context-propagation.md
content/zh/docs/concepts/semantic-conventions.md
content/zh/docs/demo/_index.md
content/zh/docs/kubernetes/_index.md
content/zh/docs/what-is-opentelemetry.md
scripts/i18n-check.sh

- Contributes to #4582
- For each i18n page:
- Adds the commit ref of the `en` page version from which the i18n page was translated from
- Updates `scripts/i18n-check.sh`:
- Add `-u` flag used to update or add the `default_lang_commit` field value to i18n pages
- Adds support for default target of `content`
Other than the script, all other files were updated by running the following command:
```console
$ ./scripts/i18n-check.sh -u                           
1       1       content/en/docs/demo/_index.md - content/zh/docs/demo/_index.md
30      30      content/en/docs/concepts/components.md - content/zh/docs/concepts/components.md
1       1       content/en/docs/kubernetes/_index.md - content/zh/docs/kubernetes/_index.md
13      1       content/en/_index.md - content/zh/_index.md
``` …

[i18n & CI] Add `default_lang_commit` to front matter of all non `en` pages

---

content/ja/docs/_index.md
content/ja/docs/what-is-opentelemetry.md

---
**Preview**: https://deploy-preview-4606--opentelemetry.netlify.app/ja/docs/

Add Japanese translation for "What is OpenTelemetry?"

---

.github/workflows/check-i18n.yml
.github/workflows/pr-actions.yml
.github/workflows/scripts/i18n-check-helper.sh
content/ja/docs/_index.md
content/ja/docs/what-is-opentelemetry.md
package.json

- Contributes to #4582
- Adds GH action (on PR) to run `i18n-check -u`
- Adds `fix:i18n` and `fix:text` to GH PR command action list

[CI & i18n] GH action to run i18n-check + new fix GH action

---

hugo.yaml

- Adds language codes specifying what the implicit specific localization is. This affects the `<html lang>` attribute.

[i18n] Add language codes

---

data/registry/instrumentation-js-azure-sdk.yml
static/refcache.json

**Preview**: https://deploy-preview-4626--opentelemetry.netlify.app/ecosystem/registry/?s=Azure+SDK+Instrumentation&component=&language=

Add npm package link for Azure SDK instrumentation

---

content/en/_index.md
content/ja/_index.md
content/ja/announcements/otel-community-day.md
content/ja/docs/_index.md
content/zh/_index.md
content/zh/announcements/otel-community-day.md
content/zh/docs/_index.md
content/zh/docs/demo/_index.md
content/zh/docs/kubernetes/_index.md

- Syncs some of the `ja` and `zh` pages and updates the hashes. The syncs mainly bring in link normalization. That is, the use of locale-relative links when possible.
- Updates page weights to match `en` pages

[ja & zh] Normalize links & update some hashes

---

content/zh/docs/faas/_index.md

- Followup to #4617
- Sets default_lang_commit to commit just before merge of #4617
https://github.com/open-telemetry/opentelemetry.io/commits/main/

[zh] faas/_index.md: fix invalid hash

---

.htmltest.yml
content/en/docs/concepts/instrumentation/libraries.md
layouts/partials/docs/get-signal-status.html
layouts/shortcodes/docs/languages/index-intro.md

- Followup to #4655
- Contributes to #4656
- API & SDK status section, under languages, will now display the following status, with links into the spec at http://localhost:1313/docs/specs/otel/versioning-and-stability/#signal-lifecycle:
- "In development" --> "Development"
- "Experimental" --> "Development"
- Links to https://github.com/open-telemetry/oteps/blob/main/text/0232-maturity-of-otel.md as a source of truth for statuses "alpha" and "beta"
- If/once the following is fixed, then we can link into the website-local [Versioning and stability](https://opentelemetry.io/docs/specs/otel/versioning-and-stability/#signal-lifecycle) page: 
https://github.com/open-telemetry/opentelemetry-specification/issues/4076
- Drops temporary `htmltest` ignore rule
- One link normalization
- For preview …

API & SDK signal status: update terminology and links

---

scripts/content-modules/adjust-pages.pl

- Drops one temporary patch
- Adds comments as to when the other patches can be dropped

[CI] Cleanup of adjust-pages.pl script

---

layouts/docs/baseof.html
layouts/partials/i18n/fallback-page.html
layouts/partials/i18n/lang.html
scripts/check-i18n.sh

- Fixes #4664
- Adds partial functions used to determine if a page is a fallback page, and what the true `lang` code is for such pages
- Adds a Docsy override of `layouts/docs/baseof.html`
- Non-functional tweaks to `scripts/check-i18n.sh`
```console
$ curl -s https://opentelemetry.io/ja/docs/getting-started/ | perl -nle 'print $1 if /html[^>]*(lang=\S+)/i' 
lang=ja
$ curl -s https://deploy-preview-4683--opentelemetry.netlify.app/ja/docs/getting-started/ | perl -nle 'print $1 if /html[^>]*(lang=\S+)/i' 
lang=en
```
- E.g., https://deploy-preview-4683--opentelemetry.netlify.app/ja/docs/getting-started/

[i18n] Ensure fallback pages have `en` lang

---

data/ecosystem/distributions.yaml

The Honeycomb distributions are being sunset. Removing them from the docs

update distributions to remove deprecated distros

---

content/en/docs/contributing/localization.md
content/zh/docs/what-is-opentelemetry.md
layouts/_default/_markup/render-link.html
layouts/shortcodes/sampling-support-list.md

- Fixes #4688
- Removes unnecessary `/zh/` path prefix from link paths in `zh` pages
**Preview**: https://deploy-preview-4689--opentelemetry.netlify.app/docs/contributing/localization/#translation-tips

[i18n] Make absolute paths locale-specific by default

---

data/registry/tools-browser-extension-autoinjection.yml
data/registry/tools-browser-extension-for-opentelemetry.yml

As discussed with @pichlermarc and @JamieDanielson the browser extension I contributed a few years back will be deprecated permanently and we will list extensions available outside the otel project as alternatives in the registry.

Deprecate OpenTelemetry Browser Extension Autoinjection in registry

---

layouts/shortcodes/docs/languages/exporters/intro.md

One of the disadvantages of using some "magic", this shortcode was broken for a while apparently, this should fix it

fix exporter intro shortcode for automatic to zero-code

---

.github/CODEOWNERS
.github/component-label-map.yml
content/en/docs/concepts/instrumentation/zero-code.md
content/en/docs/zero-code/go.md

Contributes to  #4427 but also makes people aware that this solution exists.

add a base page for go zero code instrumentation

---

.github/CODEOWNERS
content/en/blog/2022/debug-otel-with-otel/index.md
content/en/blog/2023/end-user-discussions-03.md
content/en/docs/concepts/instrumentation/zero-code.md
content/en/docs/kubernetes/operator/automatic.md
content/en/docs/languages/python/getting-started.md
content/en/docs/languages/python/libraries.md
content/en/docs/zero-code/python/_index.md
content/en/docs/zero-code/python/configuration.md
content/en/docs/zero-code/python/example.md
content/en/docs/zero-code/python/logs-example.md
content/en/docs/zero-code/python/operator.md

Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/4427

[IA] Move python automatic page to zero-code

---

content/en/docs/collector/troubleshooting.md

In the process of reworking the Collector repo docs to finish up [this issue](https://github.com/open-telemetry/opentelemetry-collector/issues/8886), I found that an addition had been made to the [Troubleshooting.md](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#null-maps-in-configuration) file after I copied over the content.
This PR adds the new content to the [Troubleshooting](https://opentelemetry.io/docs/collector/troubleshooting/) page, making it the single source of truth.
---
Preview: https://deploy-preview-4731--opentelemetry.netlify.app/docs/collector/troubleshooting/#collector-is-experiencing-configuration-issues

Add section on null maps to troubleshooting page

---

content/en/docs/collector/internal-telemetry.md

This PR fixes a tiny typo in the [Internal telemetry](https://opentelemetry.io/docs/collector/internal-telemetry/#data-flow) page of the Collector documentation.
Added: see [#10455](https://github.com/open-telemetry/opentelemetry-collector/pull/10455), which makes the same change in the Collector repo doc that'll soon be [replaced with a link to the website](https://github.com/open-telemetry/opentelemetry-collector/pull/10454).

Fix typo in monitoring section of Internal telemetry page

---

content/en/docs/zero-code/php.md

fix a minor bug in "manual setup" section, and improve explanation of example code.

improve php zero-code

---

hugo.yaml

- Contributes to #4769
- **Preview**: e.g., https://deploy-preview-4772--opentelemetry.netlify.app/docs/getting-started/
> <img width="617" alt="Screen Shot 2024-07-01 at 17 56 22" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/137cc2e1-9617-47a7-8f08-1872aab7af25">
> <img width="343" alt="Screen Shot 2024-07-01 at 17 56 35" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/cfd6e37d-fb0c-4f5b-b89d-78e8101f1bc0">

Enable page-feedback form for doc pages

---

content/en/blog/2024/hardening-the-collector-one.md

Adds new blog post in relation to open-telemetry/opentelemetry-collector/pull/10352 and open-telemetry/opentelemetry-collector-contrib/pull/33658.

Add blog post on hardening the Collector

---

content/en/docs/zero-code/java/agent/configuration.md

- Followup to #4804, which had GH action failures that were missed / masked by use of the slash`fix:*` triggers
- All PRs since #4804 will have GH action failures until this is merged

Fix links in Java agent config

---

.github/workflows/check-spelling.yml
package.json

- In support of #4794 
- Spell checks English pages only. We might want to do better later, but for now, this will allow us to make progress with our i18n support

[CI] Spell check `en` pages only

---

content/en/docs/languages/go/getting-started.md

This dependency is outdated and not used.

Remove the semconv dependency in Go getting started

---

content/en/docs/languages/go/getting-started.md
content/en/docs/languages/go/instrumentation.md

Set the Tracer and Meter names to uniquely identify the instrumentation scope[^1][^2] by using the unique Go import path of the package.
Closes https://github.com/open-telemetry/opentelemetry-go/issues/5412
[^1]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer
[^2]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter

Update Go example Tracer/Meter names

---

content/en/docs/languages/go/instrumentation.md

Use the latest version of [`semconv`](https://pkg.go.dev/go.opentelemetry.io/otel/semconv/v1.26.0).

Update Go instrumentation semconv examples

---

content/en/docs/collector/custom-collector.md

Link for "Building a Connector" on custom collector instruction page currently links to "Building a Trace Receiver." 
This commit fixes the link to redirect to the connector instructions.

Fix link to "Building a Connector" on custom-collector.md

---

content/pt/_index.md
hugo.yaml

> This is the new version of the PR #4615
- Create `/content/pt/_index.md`
- Add the language config to `hugo.yaml`
---
https://deploy-preview-4794--opentelemetry.netlify.app/pt/
Contributes to #4834

[pt-br] Localize index page to Portuguese (Brazil) 

---

content/en/blog/2024/otel-errors/index.md

Removing text from the blog post on OTel Errors to address #4823

Blog post clarification per #4823

---

content/zh/docs/contributing/style-guide.md

[zh] add contributing/style-guide.md

[zh] add contributing/style-guide.md

---

.github/workflows/component-owners.yml

Reverts open-telemetry/opentelemetry.io#4888
https://github.com/open-telemetry/opentelemetry.io/actions/runs/10100116486/job/27930816597 worked just fine, trying now with the OPENTELEMETRYBOT_GITHUB_TOKEN once again

Revert "Testing out a temporary token for component-owners"

---

content/pt/docs/_index.md

Add a translation of the index /docs to Portuguese. 
---
**Preview**: https://deploy-preview-4868--opentelemetry.netlify.app/pt/docs/

[pt-br] feat: add translation of index docs

---

content/en/docs/collector/internal-telemetry.md

The docs refer to the collector's queue as a retry queue, when it's actually a sending queue

Fix queue length documentation

---

.github/workflows/component-owners.yml

- In scope of the work for #3581
- Disables the PR trigger
- Enables workflow_dispatch trigger in the meantime simply because the `on` component can't be empty
/cc @svrnm

[CI] Component-owners workflow: remove PR trigger

---

.htmltest.yml
content/ja/docs/specs/_index.md
layouts/partials/redirects/sites.redirects

Improves the implementation of the redirect of spec pages from non-`en` locales, using `ja` as an example for now.
**Preview**: https://deploy-preview-4895--opentelemetry.netlify.app/ja/docs/
**Redirect tests**
- https://deploy-preview-4895--opentelemetry.netlify.app/ja/docs/specs
- https://deploy-preview-4895--opentelemetry.netlify.app/ja/docs/specs/status
- https://deploy-preview-4895--opentelemetry.netlify.app/ja/docs/specs/opamp

[i18n] Improve specs redirects

---

layouts/index.redirects
layouts/partials/func/trim-lines.html
layouts/partials/redirects/aliases.txt
layouts/partials/redirects/languages.txt
layouts/partials/redirects/localization.txt
layouts/partials/redirects/pages.txt
layouts/partials/redirects/redirect.txt
layouts/partials/redirects/schemas.txt
layouts/partials/redirects/social-media.txt

- Contributes to #4899
- In prep for:
- #4629
- #4898
The generated `_redirects` file is the same before and after this PR:
```console
$ npm run build                          
...
$ (cd public && git diff -bw) | grep ^diff
```
- https://deploy-preview-4900--opentelemetry.netlify.app/vendors
- https://deploy-preview-4900--opentelemetry.netlify.app/en/docs
- https://deploy-preview-4900--opentelemetry.netlify.app/ja/docs/specs/status

Refactor layouts/index.redirects

---

content/en/docs/languages/js/propagation.md

I was reviewing the [JS propagation page](https://opentelemetry.io/docs/languages/js/propagation/) and noticed this broken markdown link:

Fix JS propagation page link

---

content/en/docs/zero-code/python/_index.md

Although we have in all examples the command to install the `opentelemetry-distro` package, it may still not be so clear to users that they need a distro package to get auto-instrumentation working.
Follow-up for this https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2157

python: add note to zero-code docs highlighting the need for distro package

---

content/en/docs/collector/internal-telemetry.md

Update the names of the following internal telemetry metrics to reflect the actual metrics exposed by the collector:
`http_client_request_body_size` --> `http_client_request_size`
`http_client_request_duration` --> `http_client_duration`
`http_client_response_body_size` --> `http_client_response_size`
`http_server_request_body_size` --> `http_server_request_size`
`http_server_request_duration` --> `http_server_duration`
`http_server_response_body_size` --> `http_server_response_size`
Fixes #4905

Update internal telemetry metrics names

---

gulp-src/validate-registry.js
package.json

- Followup to #4805
- When running `check:registery` locally, only display warnings and notices when the `--debug` flag is provided. To do so run the script like this:
`npm run check:registry -- --debug`
/cc @svrnm

[CI] Only report registry format errors by default

---

scripts/content-modules/adjust-pages.pl

- Drops patches in `adjust-pages.pl`, now that spec PRs have landed in the Git submodules of this repo
- Semconv: when linking to `model` YAML files, links to the specific semconv version of the file rather than `blob/main`
/cc @open-telemetry/specs-semconv-approvers 
---
```console
$ git diff | grep ^diff
diff --git a/docs/specs/semconv/azure/events/index.html b/docs/specs/semconv/azure/events/index.html
```
Other than the `site/index.html` timestamp change, here's the only other change to the generated site files:
```console
$ git diff
```
```diff
diff --git a/docs/specs/semconv/azure/events/index.html b/docs/specs/semconv/azure/events/index.html
index 185e4e29ed..10eb31bda4 100644
--- a/docs/specs/semconv/azure/events/index.html
+++ …
```

[infra] Adjust-pages script cleanup and semconv vers tweak

---

content/en/docs/languages/sdk-configuration/otlp-exporter.md

These are suggested changes for the OTLP Exporter Configuration page:
- Introduced a new header `Protocol Configuration` to better organize environment variables related to OTLP protocol settings.
- Added documentation for the OTEL_EXPORTER_OTLP_LOGS_PROTOCOL environment variable, specifying its purpose and valid values.

otlp-exporter.md - Add Protocol Header & Fix OTEL_EXPORTER_OTLP_LOGS_PROTOCOL

---

content/en/blog/2024/otel-collector-container-log-parser/index.md

Tune example in alignment with docs: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d8085724ce153870078e21004f8e68d25175768e/pkg/stanza/docs/operators/container.md#parse-the-body-as-docker-container-log
Brought up at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31959#issuecomment-2265239004

Fix example of container parser

---

content/en/docs/languages/php/exporters.md
content/en/docs/languages/php/getting-started.md
content/en/docs/zero-code/php.md

Addresses some of the feedback raised in https://github.com/open-telemetry/opentelemetry.io/issues/4926
- move example code to page bottom, and note that it can be skipped
- break the page up more into discrete steps to follow
- some editorial improvements
- example of ini-based config

rework php zero-code page

---

content/en/docs/concepts/sampling/index.md

Most vendors tend to have more sophisticated solutions for sampling, and these are usually the right things to use. Adding some of that softer language here.

Add vendor blurb to sampling doc

---

content/en/docs/concepts/signals/logs.md

Refocused this page to be more end-user oriented. Also elaborated on the different log types.

Restructure the logs page

---

.github/workflows/check-spelling.yml

- Fixes #4963, I hope
- It won't take that much longer to check all files rather than let the plugin figure out which file list to check

[CI] GH action config tweak: spell-check all files

---

.cspell.yml
content/en/blog/2023/otel-in-focus-09.md
content/en/docs/concepts/signals/logs.md
content/en/docs/kubernetes/operator/automatic.md
content/en/docs/languages/js/getting-started/nodejs.md
content/en/docs/languages/js/libraries.md
content/en/docs/zero-code/net/nuget-packages.md

- Followup to #4956
- Moves "autoinstrumentation" into the main dictionary, since it's used quite often
- Other minor tweaks to the Logs page. /cc @cartermp

[cleanup] Add autoinstrumentation into the main dictionary

---

.github/workflows/check-spelling.yml

- This is take 2 of trying to solve #4963
- Fixes #4956, hopefully / maybe (via the change in config to `use_cspell_files`). Worth a try.

[CI] Try to get streetsidesoftware/cspell-action to play nice

---

.gitmodules

- Upgrades Docsy to v0.10.0-22-g2295188b
- There are no significant changes to the generated files, other than updates due to the new version of FontAwesome:
```console
$ (cd public && git diff -bw --ignore-blank-lines) | grep ^diff                 
diff --git a/scss/main.css b/scss/main.css
diff --git a/scss/main.css.map b/scss/main.css.map
```

[Docsy] Upgrade to v0.10.0-22-g2295188b

---

assets/js/registrySearch.js
layouts/ecosystem/registry.json.json
layouts/shortcodes/ecosystem/registry/search-form.html
static/refcache.json

Partially addresses #4987: this PR allows users to search for "native" and "first party" and find the registry entries.
This PR also includes an update of the used search engine (minisearch) + pinning the hash

make native and first party searchable in registry

---

.gitmodules
hugo.yaml

- Fixes #4967, offering a final solution as implemented in Docsy

Upgrade Docsy and undo temp config change

---

data/registry/application-integration-go-jaeger.yml
static/refcache.json

cc @jkowall 
https://deploy-preview-5004--opentelemetry.netlify.app/ecosystem/integrations/

Add jaeger to integrations

---

.github/workflows/check-spelling.yml
package.json

[CI] Install cspell/dict before running cspell action

---

content/es/_index.md

Add cSpell excepctions for ES index

---

.htmltest.yml
data/ecosystem/vendors.yaml
static/refcache.json

I was refreshing cache entries, but I think that my IP might have been flagged by Cloudflare. So for now, I'll just push back the refcache expiry date. I managed to detect and fix one link.

[CI] Push back htmltest refcache expiry date, and fix a link

---

.gitmodules

Had an issue with the java examples locally, that couldn't be fixed with `npm run sync`, I saw that it hadn't have a pin yet, so this provides that pin. cc @chalin

Add git sub module pin for java examples

---

layouts/shortcodes/docs/languages/exporters/prometheus-setup.md
static/refcache.json

Update link to PrometheusHttpServer in prometheus-setup.md

---

.gitmodules

the pinned version and the version in the repo are not the same leading to issues in some PRs.

fix java examples pin version

---

content/en/docs/security/security-response.md

This PR fixes https://github.com/open-telemetry/sig-security/issues/60 by better defining who's part of the fix team. This uses common roles from the regular incident response management playbook, applying the concepts to our use-case.
This also fixes https://github.com/open-telemetry/sig-security/issues/62 , by adding "other sigs" as part of "other stakeholders".
cc @mx-psi

Define who is part of the Fix Team

---

content/en/docs/languages/net/shim.md

should fix https://github.com/open-telemetry/opentelemetry.io/issues/5006

Update .NET tracing shim to correctly set span status

---

content/en/docs/languages/java/instrumentation.md

Came across this random "a" character:

Remove random 'a' character in java instrumentation

---

data/registry/exporter-js-sap-cloud-logging.yml
static/refcache.json

Adds the OpenTelemetry exporter for
SAP Cloud Logging for Node.js to the registry.
c.f.
https://www.npmjs.com/package/@sap/opentelemetry-exporter-for-sap-cloud-logging
https://discovery-center.cloud.sap/index.html#/serviceCatalog/cloud-logging?service_plan=overall-(large,-standard,-and-dev)&region=all&commercialModel=btpea

Add SAP Cloud Logging Exporter to registry

---

data/registry/exporter-js-sap-cloud-logging.yml

Fixes a spelling issue that's causing CI to fail on other PRs.

Add cspell:ignore to registry entry

---

content/ja/docs/contributing/_index.md

[ja] Fix the link to the contribution guide

---

content/zh/docs/languages/_index.md
content/zh/docs/languages/java/_index.md

tranlate content/en/docs/languages/java/_index.md to zh

[zh] tranlate java language index

---

content/ja/docs/collector/quick-start.md

Add Japanese translation of [Quick Start](https://opentelemetry.io/docs/collector/quick-start/) page

[ja] add Japanese translation of quick start of collector

---

.github/workflows/auto-update-versions.yml
.github/workflows/pr-actions.yml
package.json

- Uniformly sets `DEPTH` to 999 across scripts
- Closes #5084 and should resolve it for 99.9% of the time; to make it work 100% of the time we'd need to fetch the full submodule repos (by _not_ providing a `--depth` flag). But I don't think that it's worth imposing that for everyone who contributes to this repo.

[CI] Adjust submodule DEPTH uniformly across scripts

---

content/pt/docs/concepts/observability-primer.md

Add a localization to the observability-primer.md.
Issue: https://github.com/open-telemetry/opentelemetry.io/issues/4922

[pt] Add pt/content/docs/concepts/observability-primer.md

---

content/es/docs/getting-started/_index.md

Related to https://github.com/open-telemetry/opentelemetry.io/issues/4887

[es] feature: getting started - spanish translation

---

content/pt/announcements/_index.md
content/pt/announcements/otel-localized.md
content/pt/blog/2024/_index.md
content/pt/blog/2024/docs-localized.md
content/pt/blog/_index.md

Waiting for #4996 to be merged.
Add localization for annoucement page for OTel localization.
Issue: https://github.com/open-telemetry/opentelemetry.io/issues/4922 and https://github.com/open-telemetry/opentelemetry.io/issues/4863

[pt] Localize otel-localized announcement page to Portuguese (Brazil)

---

content/pt/docs/concepts/instrumentation/code-based.md

Add localization instrumentation code-based.
Issue: https://github.com/open-telemetry/opentelemetry.io/issues/4922

[pt] Add content/pt/docs/concepts/instrumentation/code-based.md

---

content/en/docs/languages/sdk-configuration/general.md

This PR simply corrects the name of the polling interval property used by the `jaeger_remote` and `parentbased_jaeger_remote` samplers.
Ref: https://github.com/open-telemetry/opentelemetry-java/blob/c90175f1ae7d15fef6bac8eb6c95492c981daa61/sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerProvider.java#L22

Fix name of jaeger_remote polling interval property

---

package.json

The main (only?) change in the generated files seems to be due to a fix in the encoding of `<meta description>` values. E.g.,
```console
$ (cd public && git diff -b -w --ignore-blank-lines -I "meta description")
```
```diff
diff --git a/blog/2022/apisix/index.html b/blog/2022/apisix/index.html
index b82feef160..14ac9df5ba 100644
--- a/blog/2022/apisix/index.html
+++ b/blog/2022/apisix/index.html
@@ -15,7 +15,7 @@
<meta name="theme-color" content="#4f62ad">
<title>Apache APISIX Integrates with OpenTelemetry to Collect Tracing Data | OpenTelemetry</title>
-<meta name="description" content="This article introduces the Apache APISIX&amp;rsquo;s opentelemetry plugin concept and how to enable and deploy the plugin.
+<meta name="description" content="This article introduces the Apache …
```

Update NPM packages, including Hugo to 0.133.0

---

content/en/docs/languages/go/exporters.md

Ensure readers copying the code know what "context" package is being referenced.

Add context import to examples that use "context"

---

content/en/docs/languages/sdk-configuration/general.md

Reverts open-telemetry/opentelemetry.io#5100
The Java SDK does not conform to the spec so we should fix that instead of updating the documentation.
https://github.com/open-telemetry/opentelemetry-specification/pull/4195#issuecomment-2310471702

Revert "Fix name of jaeger_remote polling interval property"

---

content/es/docs/contributing/_index.md

Related the issue: https://github.com/open-telemetry/opentelemetry.io/issues/4887

[es] feature: contributing - spanish translation

---

content/en/docs/collector/custom-collector.md
static/refcache.json

- Followup to / inspired by the link-checking failure of #5114 
- Clarifies the details of how to get an `ocb` binary (i.e., to look for releases having a tag that starts with `cmd/builder`), and links to the tags page instead of the specific version. This will make the link checking less brittle.
/cc @theletterf @svrnm

Custom collector page: link to tagged releases

---

.github/workflows/pr-actions.yml

- A step towards aleveating the pain of #4339
- Reports successful runs of `fix:*` commands, and instructs the user to run `fix:all` to ensure that all checks are passing. This isn't a perfect solution, but it will hopefully help avoid issues like https://github.com/open-telemetry/opentelemetry.io/pull/5119#issuecomment-2318012101.
/cc @cartermp @svrnm

[CI] After a `fix:*` command, tell user to rerun full checks

---

.github/workflows/pr-actions.yml

- Followup to #5122
- For an example of the success comment, see: https://github.com/open-telemetry/opentelemetry.io/pull/5116#issuecomment-2319052868
- Escapes special characters in `gh pr comment` comment string
- https://github.com/open-telemetry/opentelemetry.io/actions/runs/10622918753/job/29448244561 shows the need for escaping, given the error: `sh: line 1: /fix:all: No such file or directory`
/cc @tiffany76

[CI] PR-actions: escape PR comment special char

---

content/en/docs/languages/go/instrumentation.md

Sync gauge was not listed as supported, but the later section of the doc show that it is indeed supported.

Mention sync gauge in Otel Go metrics docs

---

.github/workflows/pr-actions.yml

- Followup to #5126
- Use `cat` trick to get a multiline (hopefully this will work :).

[CI] PR-actions: multiline comment fix

---

data/ecosystem/vendors.yaml
static/refcache.json

- Adding Last9 Levitate to the list of Vendors
- https://last9.io
- https://docs.last9.io/docs/levitate-integrations-opentelemetry

add last9 to otel vendors.yaml

---

layouts/shortcodes/ecosystem/integrations-table.md

- Reformats shortcode to make it easier to read
- Adds to checks for missing URLs, and reports an error (fails the build), when they are missing. (This should probably be a warning, but it matches the other checks that are done.
Note: I know that another partial does similar checks, but maybe not for Integration entries? Anyhow, these checks are now closer to their point of use.
/cc @svrnm 
The generated site files are the same (other than the site-build timestamp).
```console
$ (cd public && git diff)                                                                          
index 4555d76f20..6ed7ea752e 100644
--- a/site/index.html
+++ b/site/index.html
@@ -226,7 +226,7 @@ Attribute Value Netlify built false Deploy context local ">
<script> …
```

[CI] Report an error when URLs are missing from an integrations registry entry

---

content/en/docs/kubernetes/operator/troubleshooting/target-allocator.md
content/en/docs/languages/erlang/exporters.md

Removes old references to the logging exporter, which is being removed.
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/11037

[chore] Remove references to the logging exporter

---

assets/scss/_styles_project.scss
content/en/_index.md
content/en/ecosystem/integrations.md

Contributes to:
- #5155 
For **motivation**, see that issue's description. IMHO, there is more work to be done, but this is a low hanging fruit, which eliminates the Integrations CTA
This PR reworks the OTel-highlights "ribbon", in particular makes these changes for the three ribbon entries (for screenshots, see below):
- Telemetry ribbon entry (the first one): adds a "read more" link to the OTel primer
- Second ribbon entry changed to link to the Integrations page. Adds a link to the Instrumentation page
- Third entry: adds link to Adopters page
Before:
> <img width="1487" alt="image" src="https://github.com/user-attachments/assets/cb9d4dce-0126-4bda-bb77-19422073e293">
After:
> <img width="1238" alt="image" src="https://github.com/user-attachments/assets/0a8c680c-4c12-4e0d-ad00-ea2ba1360 …

[ux] Rework OTel-highlights ribbon, move Integrations to ribbon

---

content/en/docs/concepts/instrumentation/libraries.md

Updating the libraries page for style guide and language issues. Adding some comments where clarification might be required. This one really needed a cleanup.

Update libraries.md for style issues

---

content/en/docs/demo/architecture.md

Fixes https://github.com/open-telemetry/opentelemetry.io/issues/5168

Update architecture.md to remove incompatible link notation from diagram

---

content/en/community/members.md

Not sure why this was not breaking the PR before merging, it now affects other PRs, so here is a quick fix.

Fix internal link in community/members.md

---

content/en/docs/collector/quick-start.md

We regularly see the following problem with organizations adopting OTel in my workplace:
1. We tell them to install an OTel Collector, or they come with one, and it's basically just routing data ... no processing
2. They then need some kind of component in contrib. A receiver for some external data source, or a processor to redact info or transform telemetry, etc.
3. They then get an error because that component doesn't exist, so they're confused and frustrated and it's a _whole thing_ to get them to realize that they actually needed the contrib image or should have used OCB
4. We find out that they learned how to install the collector via Google --> landing on this page
And so, I'm proposing that we change this to be contrib, like the rest of our installation guides for the collector. …

Use collector contrib in quickstart

---

content/en/docs/demo/docker-deployment.md

Replaced the `make start-odd` and related Docker command in the "Enable API observability-driven testing" section with updated commands (`make run-tracetestings` and `docker compose -f docker-compose-tests.yml run traceBasedTests`) to reflect current available commands. The previous `make start-odd` command no longer exists.

Update observability-driven testing commands in documentation

---

content/en/docs/collector/installation.md

APK packages are no longer available (see https://github.com/open-telemetry/opentelemetry-collector-releases/pull/630)

Remove reference to APK packages

---

content/es/docs/getting-started/ops.md

Related the issue https://github.com/open-telemetry/opentelemetry.io/issues/5206

feat: [es]  opentelemetry.io/content/en/docs/getting-started/ops.md

---

.cspell/en-words.txt
content/en/api-docs.md
content/en/docs/languages/_index.md
content/en/status.md
static/refcache.json

Some minor updates to the status page and language api&sdk index page:
* Status page: Say "APIs & SDKs" instead of only "SDKs" like in the page navigation
* Language Index page: Rewording + mention /api-docs

Some updates to status page and language index page

---

data/registry/instrumentation-lua-apache-apisix.yml
data/registry/instrumentation-perl-mojolicious.yml
data/registry/instrumentation-perl-plack.yml
data/registry/instrumentation-rust-actix-web.yml
data/registry/instrumentation-rust-axum.yml
data/registry/instrumentation-rust-tide.yml
data/registry/instrumentation-rust-tracing.yml
data/registry/instrumentation-rust-trillium.yml
data/registry/instrumentation-swift-urlsession.yml
static/refcache.json

To address #4795, this is part of a series of PRs that add isFirstParty or isNative flags to instrumentation registries that lack them.
This batch touches Lua/Perl/Rust/Swift instrumentation registries.

firstParty flag for Lua/Perl/Rust/Swift

---

content/en/blog/2024/otel-operator-q-and-a/index.md
content/en/docs/languages/_index.md
content/en/docs/languages/java/configuration.md

Hi, 
while browsing the docs I found some links pointing to `localhost:1313`. These were likely inserted during local development.
This PR should fix that.
Cheers,
Markus

Fix various links that pointed to localhost:1313

---

content/en/docs/zero-code/_index.md

Not yet 100% done, but for end users good enough to not have the banner anymore (imho)

Remove zero-code under construction banner

---

content/en/blog/2023/otel-arrow/index.md
content/en/blog/2024/otel-arrow-production/index.md

- Followup to #5198
- Drive-by copyedits as I investigated the submodule issues of the above-mentioned PR
- **Preview**: https://deploy-preview-5268--opentelemetry.netlify.app/blog/2024/otel-arrow-production/
/cc @jmacd

OTel Arrow blog drive-by copyedits

---

README.md

Updating my affiliation, since I've signed my individual CLA and I'll no longer be a Splunk employee effective October 4. Feel free to merge it then, if you want!

Update README.md to remove Fabrizio's affiliation

---

content/en/docs/collector/internal-telemetry.md

This PR is a follow-up to #5092. It moves the [maturity level](https://opentelemetry.io/docs/collector/internal-telemetry/#telemetry-maturity-levels) section out of the [types of internal telemetry](https://opentelemetry.io/docs/collector/internal-telemetry/#types-of-internal-telemetry) section and into its own ##-level section.

Update the organization of internal telemetry page

---

content/en/docs/demo/architecture.md

The Otel collector image in demo architecture, had a duplicate of text: localhost 4318, I edited it and fixed it
Fixes #5238.

fixed the duplicated text: localhost 4318 on Otel collector image

---

content/en/docs/concepts/glossary.md
content/ja/docs/concepts/glossary.md

Fix link zpages content/en/docs/concepts/glossary.md

[en] fix link zpages content/en/docs/concepts/glossary.md

---

package.json

With this update, you can now run `npm run get:submodule -- --remote` to force fetch the latest available version of all submodules.

[CI] Update package.json: tweak script and minor pkg vers update

---

content/en/docs/concepts/signals/traces.md

The actual data shouldn't contain a leading `0x` hex prefix. Examples [here](https://github.com/open-telemetry/opentelemetry-proto/blob/main/examples/trace.json).

Remove leading 0x from json examples

---

content/es/docs/concepts/observability-primer.md

feat: [es] Create observability-primer.md
Related to https://github.com/open-telemetry/opentelemetry.io/issues/5206

"feat: [es] Create observability-primer.md "

---

content/es/docs/concepts/context-propagation.md

Create feat: [es] Create docs/languages/context-propagation
related to https://github.com/open-telemetry/opentelemetry.io/issues/5206

feat: [es] Create docs/languages/context-propagation

---

content/en/blog/2024/prom-and-otel/index.md
content/en/docs/languages/go/examples.md
content/en/docs/languages/go/exporters.md

Go examples has been moved to opentelemetry-go-contrib repository in https://github.com/open-telemetry/opentelemetry-go/issues/5801.
This PR updates docs to point to the new location of the go examples.

docs: update example links to opentelemetry-go-contrib repository

---

content/en/blog/2024/gc-candidates.md
static/refcache.json

Adds a new blogpost with information about the 2024 GC Election candidates.

New blogpost for GC 2024 candidates

---

content/pt/docs/languages/go/_index.md
content/pt/docs/languages/go/api.md
content/pt/docs/languages/go/examples.md
content/pt/docs/languages/go/getting-started.md
layouts/partials/pt/docs/latest-release.md
layouts/shortcodes/pt/docs/languages/index-intro.md

Add:
- content/pt/docs/languages/go/_index.md
- content/pt/docs/languages/go/api.md
- content/pt/docs/languages/go/examples.md
- content/pt/docs/languages/go/getting-started.md
- layouts/partials/pt/docs/latest-release.md
- layouts/shortcodes/pt/docs/languages/index-intro.md
Issue: https://github.com/open-telemetry/opentelemetry.io/issues/5344

[pt] Initialize translations for /pt/docs/languages/go

---

scripts/content-modules/adjust-pages.pl
scripts/content-modules/cp-pages.sh

- Fixes #5359
- My solution was to opt for relative paths inside of the `cp-pages.sh` script, and make the (very reasonable assuption) that the script is being run from the repo root. I can't recall why I opted for absolute path names. None of the directory names inside of the repo contain any spaces, so we're good.
- Closes #5377 by superseding it
- I've tested this from inside a folder whose name contains a space and the build still works. 
@FatumaA, can you confirm (once this lands)?

[CI] Ensure spec processing works even if path contains a space

---

.gitmodules

- In prep for Hugo upgrade to be done for #5153
- Brings in a fix to meta descriptions. For details see:
https://github.com/google/docsy/pull/2100

Update Docsy to v0.10.0-37-g7478e1a1

---

static/img/otel-diagram.svg

- Illustrates minimally intrusive solution to #5361
- Drops single `fill` attribute from `svg rect`, in support of dark mode:
- **Preview**: https://deploy-preview-5436--opentelemetry.netlify.app/docs/
Before:
> <img width="500" alt="image" src="https://github.com/user-attachments/assets/5b8815dd-74b2-4b48-8851-1c462dfd8b1f">
After:
> <img width="500" alt="image" src="https://github.com/user-attachments/assets/3f25b2a6-abfc-4f8d-8717-6ad36904975c">

OTel diagram: drop fill color in support of dark mode

---

.cspell.yml
.htmltest.yml
content/en/blog/_index.md
content/en/docs/contributing/localization.md
content/ja/docs/concepts/instrumentation/libraries.md
content/pt/docs/concepts/instrumentation/libraries.md
package.json
scripts/htmltest-config.pl
scripts/htmltest-config.sh

- Contributes to #3889
- Documents the process to follow by English-language contributors when non-English pages fail link checking
- Adds support for reading `htmltest` `IgnoreDirs` list entries from `content` pages' front matter
**Preview**: https://deploy-preview-5448--opentelemetry.netlify.app/docs/contributing/localization/#when-link-checking-fails-for-non-english-pages

[i18n, CI] How to deal with broken links in non-en pages when updating en pages

---

content/en/docs/zero-code/python/operator.md

Django applications require special treatment with operator based autoinstrumentation.

zero-code/python: add django applications notes in operator doc

---

data/registry/application-integration-python-mlflow.yml
static/refcache.json

Hi all! This is a follow-up to #5150. We've built an OTel exporter and have [instructions in the doc page](https://mlflow.org/docs/latest/llms/tracing/index.html#using-opentelemetry-collector-for-exporting-traces) on how to use it 😄. As for semantic conventions, due to historical reasons (some downstream applications are relying on the existing data format) it's a little difficult to migrate immediately, but we're keeping an eye on the spec and where it makes sense to integrate.

Add MLflow entry to the OpenTelemetry integrations registry

---

content/en/blog/2024/gc-election-results.md

Adds new blog post announcing the results of the 2024 OpenTelemetry Governance Committee Elections.
cc @open-telemetry/governance-committee

Add 2024 GC Election results blogpost

---

.cspell/en-words.txt
content/en/blog/2024/state-profiling.md
static/refcache.json

This adds the `State of Profiling` blog post the Profiling SIG has been working on.
For the record, the writing/review process happened in this Google Document:
https://docs.google.com/document/d/1RgsP_XJOhgB4e19RqXc_yN0gJ-1o9ZB_uqQRbjotVCU/edit
I've listed everyone who contributed to the Google Doc as coauthor of the post.
See issue: https://github.com/open-telemetry/opentelemetry.io/issues/5477
cc @mx-psi @felixge @christos68k @mtwo @florianl @rockdaboot

State of Profiling blog post

---

content/en/docs/languages/net/instrumentation.md

The removed text is already included by linking the span-status-preamble

Remove duplicate text

---

content/en/docs/languages/swift/instrumentation.md

Noticed this typo in the docs where the span is started

Fix span start typo

---

.htmltest.yml
scripts/htmltest-config.pl

- Sort the list of files processed while collecting `htmltest` config entries, so that the resulting config file is consistent across development environments (like Cloud IDEs).
- No changes to generated site files.

[CI] htmltest config: sort files before processing

---

content/en/docs/contributing/localization.md
static/refcache.json

- Fixes #4981
- Copyedits the "New localization" section
- Adds a note about spell checking

[i18n] Mention spell checker requirement for new localizations

---

data/registry/instrumentation-java-jdbi.yml
static/refcache.json

As of [release 3.46.0](https://github.com/jdbi/jdbi/releases/tag/v3.46.0), JDBI added native [OTel instrumentation](https://jdbi.org/#_opentelemetry_tracing).
This PR adds jdbi to the registry so that it will be listed on the Instrumentation ecosystem page under [Native Instrumentation](https://opentelemetry.io/docs/languages/java/instrumentation/#native-instrumentation)

Add jdbi to native java instrumentation registry

---

content/es/docs/concepts/components.md

[es] adding docs/concepts/components
related to: 
- https://github.com/open-telemetry/opentelemetry.io/issues/5206

[es] adding docs/concepts/components

---

.htmltest.yml
content/en/blog/_index.md
content/zh/blog/_index.md

[CI] Avoid dup htmltest config for blog pages

---

content/en/blog/_index.md

- Temporary workaround for #4440, until it is resolved in Docsy
- **Preview & redirect test**:
- https://deploy-preview-5520--opentelemetry.netlify.app/blog/
- https://deploy-preview-5520--opentelemetry.netlify.app/blog/index.xml
- https://deploy-preview-5520--opentelemetry.netlify.app/blog/2024/index.xml

Blog RSS workaround via redirect

---

content/en/announcements/kubecon-na-2024.md
content/en/blog/2024/kubecon-na.md
static/refcache.json

fixes #5278
@open-telemetry/sig-end-user-approvers please take a look for the section around the observatory. This years EU blog post had some more details on schedule, surveys, humans of OTel, so let me know which of these I can include

Blog post for KubeCon NA 2024

---

content/en/docs/collector/_index.md
content/en/docs/collector/configuration.md
content/en/docs/collector/deployment/_index.md

Now that #5209 is merged, this PR adds references to it from the Collector docs. The references are added to the following pages (links are previews):
- The [Collector landing page](https://deploy-preview-5524--opentelemetry.netlify.app/docs/collector/) links to both the security hosting and configuration pages
- The [Deployment landing page](https://deploy-preview-5524--opentelemetry.netlify.app/docs/collector/deployment/) links to the security hosting page.
- The [Configuration page](https://deploy-preview-5524--opentelemetry.netlify.app/docs/collector/configuration/) links to the security configuration page.
Tracking issue: #3479

Add cross references to Collector security docs

---

data/registry/instrumentation-java-jdbi.yml

follow up for #5512:
based on the documentation (https://jdbi.org/#_opentelemetry_tracing) the otel integration requires a plugin and is not a native integration:
> The OpenTelemetry project provides a SDK to implement distributed tracing. Installing the JdbiOpenTelemetryPlugin from the jdbi3-opentelemetry artifact will cause Jdbi statements to emit trace spans recording data similarly as JFR events above. Additionally, it will add the trace id to JFR events.
cc @jaydeluca

Java JDBI is first party not native

---

content/en/blog/2024/kubecon-na.md

I forgot to set the date for the kubecon blog post to today, so it's not at the top of the blog posts list

fix date for kubecon blog post

---

content/en/docs/languages/_index.md

- Contributes to #5531
- Thankfully, it seems to still pick the `en` redirect
- Redirect test: https://opentelemetry.io/docs/instrumentation/
- So I'll follow up later (rather than in this PR) with a change to the corresponding `pt` file (or @open-telemetry/docs-pt-approvers can do it)

Fix redirects (in pt) and add note to en page

---

content/en/docs/demo/kubernetes-deployment.md

As part of updating the Demo's Helm chart to version 1.12.0 of the Demo, we had to raise the Helm version prerequisite to `3.14+`.

[demo] update helm prerequisite

---

content/en/docs/demo/development.md

Fixes #5508 by adding a link to the github repo for the demo

[demo] add link to github repo

---

data/community/members.yaml
static/refcache.json

Updates members using `scripts/generate-community-data/generate.js`
My only required update was to update GC members after election, however running the script above seems to have reshuffled things and added more changes that have occurred since it was originally run. Let me know if I'm missing anything.

Update community members

---

package.json

- Avoids `postbuild` processing, which currently does link checking. We don't look anything for PRs since GH actions check links anyways. For more details, read below.
Context & discussion: I used to think that it was useful to have the links checked (esp. for production builds), so that we could track down issues by inspecting logs. And we're waiting other GH workflow checks in the case of PRs anyways. I've changed my mind. We can debug production build glitches locally, if ever they occur. And for PR builds, it'll be nice to get previews faster.

[CI] Don't check links on build

---

layouts/shortcodes/apidocs.md

- Contributes to fixing #5547
**Preview**:
- https://deploy-preview-5550--opentelemetry.netlify.app/docs/languages/
- https://deploy-preview-5550--opentelemetry.netlify.app/es/docs/languages/

Fix link paths in apidocs shortcode

---

.htmltest.yml
content/es/docs/_index.md
content/fr/docs/what-is-opentelemetry.md
content/ja/docs/_index.md
content/pt/docs/_index.md
content/zh/docs/_index.md
layouts/_default/_markup/render-link.html

- Fixes #5553
- Render-link hook: adds the language code prefix to absolute paths of links that appear in non-`en` pages
- As a consequence of this fix, link-check failures are now reported and will need to be fixed.
- Adds `IgnoreDir` regexs so that the offending non-`en` are temporarily excluded from link-checking

[i18n] Render-link fix: prepend lang code when page exists

---

layouts/shortcodes/spec_status.html

- Warns about spec-status access failures rather than reporting an error and aborting the build. 
- Allows the site build to proceed, now that we have a GH action that will fail when a warning is reported.
- Motivation was the build failure of #5552

Ensure that spec_status shortcode fails softly

---

.github/workflows/build-dev.yml
package.json
scripts/pin-submodules.pl

- Adds GH workflow that we can run manually to build the website from the HEAD of selected submodules. 
This is proposed as a solution to **mitigating OTel spec build failures** when a new version of the spec is released. The workflow could be **run by OTel spec maintainers** _before_ they publish a release.
- Cleans up and improves various other the NPM scripts, including `test-and-fix`

[CI] Add GH workflow to run dev build using submodules at head

---

.htmltest.yml
content/fr/docs/what-is-opentelemetry.md

Part of https://github.com/open-telemetry/opentelemetry.io/issues/5555

Add history heading ID to fr what-is-opentelemetry page

---

content/en/docs/collector/internal-telemetry.md
package.json

- Updates to Hugo [v0.138.0](https://github.com/gohugoio/hugo/releases/tag/v0.138.0)
- Illustrates use of the new Hugo [comment](https://gohugo.io/content-management/shortcodes/#comment) shortcode
- There are no changes to generated site files other than:
- The updated Hugo version as part of the generator ID header element
- The HTML comment removed from the page where this PR uses the `comment` shortcode instead.

[CI] Update pkgs, including Hugo to 0.138.0; use new `comment` shortcode

---

content/en/docs/languages/js/getting-started/nodejs.md
content/en/docs/languages/js/instrumentation.md

It's not a major issue, but it seems that the dice in our example code only rolls `1`, `2`, `3`, `4`, and `5`. Fixing this could make the game fairer. 🤣

Fix: fix dice number generator in JS examples

---

.htmltest.yml
data/registry/application-integration-cpp-envoy.yml
data/registry/instrumentation-java-okhttp.yml
layouts/partials/ecosystem/registry/entry.html
layouts/partials/ecosystem/registry/quickinstall/maven.md

This pull request fixes #5308 and adds quick installation for `okHTTP Instrumentation`

Add quick installation for maven to the registry 

---

scripts/content-modules/adjust-pages.pl

- Followup to #5552
- Report obsolete patch-code as INFO msgs so that it doesn't fail the build -- so that we can test new spec version builds using the `buid-dev` workflow. The patch code should be removed after the spec is updated so that we can confirm that the generated site files are the same.

[CI] adjust-pages: report obsolete patch-code as INFO msgs

---

content/es/docs/concepts/observability-primer.md

Restores the observability primer translation that got removed via https://github.com/open-telemetry/opentelemetry.io/pull/5328/files#r1836989309, oversight on my end, apologies.
cc @theletterf @chalin

[es] restore observability primer

---

.htmltest.yml
content/es/docs/_index.md
content/es/docs/concepts/components.md
content/es/docs/concepts/context-propagation.md
content/es/docs/what-is-opentelemetry.md

Add missing en anchors for ES translations

---

.htmltest.yml
content/pt/docs/_index.md
content/pt/docs/concepts/components.md
content/pt/docs/concepts/context-propagation.md
content/pt/docs/concepts/sampling/index.md
content/pt/docs/concepts/signals/traces.md
content/pt/docs/what-is-opentelemetry.md

Add missing en anchors for PT-BR translations

---

data/registry-schema.json

https://github.com/open-telemetry/opentelemetry.io/pull/5602#discussion_r1840247361 -- this way we can also allow URLs for author.url in registry entries

Update registry schema to allow any https URL for authors

---

.htmltest.yml
content/pt/docs/concepts/instrumentation/libraries.md
scripts/check-i18n.sh

[pt] Temporarily patch page to avoid link-check failure

---

content/en/blog/2024/community-awards-winners.md
static/refcache.json

Adding a blogpost to announce the 2024 OTel Community Awards winners, adding a link to slides presented during KubeCon at the OTel Observatory.

Blogpost to annoucing 2024 OTel Community Awards winners

---

.htmltest.yml
content/ja/docs/concepts/instrumentation/libraries.md

[ja] Temporarily patch page to avoid link-check failure

---

.github/workflows/check-links.yml

- Context: https://github.com/open-telemetry/opentelemetry.io/pull/5610#discussion_r1847023217
- Fails the "BUILD and CHECK LINKS" PR workflow if submodule versions changed as a result of restoring to pinned version
/cc @jack-berg @svrnm 
---
> ~The PR contains a seeded error (submodule update w/o a pin ID change) to test the detection of such a situation.~

[CI] Detect unpinned git submodules in GH PR checks

---

data/community/members.yaml
scripts/generate-community-data/generate.js
static/refcache.json

This adds a small fix to the script that updates the community membership pages. The results are sorted within each group before they are written to a file, that way we create some stability and future updates are easier to validate, since names are not jumping within the groups based on the updates and based on how the API returns results
cc @danielgblanco

Sort and update community members page

---

.gitmodules
content/en/docs/languages/java/sdk.md
static/refcache.json
tools/pubspec.yaml

Java documentation for cardinality limits

---

content/en/docs/languages/go/getting-started.md

- Fixes #5629
- No change to the generated site files, even after running `npm run code-excerpts`. (This will help make @jack-berg and the Java SIG's lives easier :)).

Disable code-excerpting from Go getting-started

---

data/registry/exporter-rust-stdout.yml

Fixes the title in the Rust stdout exporter from "OTLP Exporter" => "Stdout Exporter". Update version to latest published crate.

Fix title for Rust stdout exporter

---

content/en/docs/collector/internal-telemetry.md

I rewrote the "Values observable with internal metrics" section of the "Collector > Internal telemetry" page to accurately summarize existing telemetry instead of being partly wishful thinking. This should resolve #5483.
While doing that, I noticed that the table below was also inaccurate to the telemetry currently implemented in the Collector, so I updated it. (This involved replacing the `processor_accepted/dropped_*` metrics by `processor_incoming/outgoing_items`, and putting the `processor_batch` metrics under the correct level.)
I also added a note below the table which may be helpful in understanding it. It may be enough to resolve #5468. I will remove it if it is deemed unnecessary.

Updated summary and table of internal telemetry

---

content/en/blog/_index.md

- Followup to #5520
- Contributes to #5651
- Thanks to @jord1e for point that out. /cc @dmathieu. Can you confirm that it still works for you (it should).
Once I get a confirmation, I'll double check other 301s to see if they should be 302s.
**Redirect test**:
- https://deploy-preview-5652--opentelemetry.netlify.app/blog
- https://deploy-preview-5652--opentelemetry.netlify.app/blog/index.xml
```console
$ curl -I https://deploy-preview-5652--opentelemetry.netlify.app/blog/index.xml 
HTTP/2 302 
...
location: /blog/2024/index.xml
...
```

Blog RSS workaround via redirect using 302 status code

---

content/en/docs/zero-code/python/_index.md
static/refcache.json

When using https://docs.astral.sh/uv/ the default instructions fail because the shell syntax and method of running scripts is a bit different.
pip install also doesnt work like it would normally, and you wouldn't really want to use it anyways because uv is faster and uses its own venvs
This PR adds instructions to the troubleshooting section.

Add `uv` package manager instructions to Python zero-code docs

---

data/registry-schema.json
data/registry/collector-confmap-provider-envprovider.yml
data/registry/collector-confmap-provider-fileprovider.yml
data/registry/collector-confmap-provider-httpprovider.yml
data/registry/collector-confmap-provider-httpsprovider.yml
data/registry/collector-confmap-provider-yamlprovider.yml
static/refcache.json

As mentioned in #5387, there are more components that are compatible with the OpenTelemetry Collector.
These include `confmap.Converter` and `confmap.Provider` types. 
confmap.Converter: https://github.com/open-telemetry/opentelemetry-collector/issues/11582
confmap.Provider: https://github.com/open-telemetry/opentelemetry-collector/issues/4567
There are currently [five confmap.Providers that are maintained in the OpenTelemetry Collector core repository](https://github.com/open-telemetry/opentelemetry-collector/tree/main/confmap/provider) and while there is only one Converter there and it is deprecated, there are vendors that make use of converters and it is possible they would choose to publish them in the registry once this is available.
As I am not super familiar with the registry and …

add confmap provider to registry.json

---

assets/js/registrySearch.js
layouts/partials/ecosystem/registry/entry.html

In this update, when a flag is clicked, the filter is applied immediately to update the displayed records based on selected flag value. 
The flag value is not added to search input field and the search input field is cleared upon flag selection.

Implement clickable flag buttons to filter records without updating search term

---

content/en/docs/demo/architecture.md

This PR adds the missing `flagd` service to the diagram and realigns all services.
Also, we have removed redis from the demo some time ago and replaced with ValKey.

[Demo] Update diagram

---

content/en/docs/kubernetes/collector/components.md

This filelog receiver example was out-of-date now that the container operator exists.  This brings the example in line with the default value we use in the helm chart.

fix: Update filelog receiver operators in kubernetes docs

---

data/registry-schema.json
data/registry/collector-confmap-provider-envprovider.yml
data/registry/collector-confmap-provider-fileprovider.yml
data/registry/collector-confmap-provider-httpprovider.yml
data/registry/collector-confmap-provider-httpsprovider.yml
data/registry/collector-confmap-provider-yamlprovider.yml

This changes the name for Collector Confmap Providers in the registry from "confmap provider" to "provider".
The way the registry shows how to add a component, `confmap provider`, is not the correct way to include a provider with your collector build. While the name is more descriptive, without knowing a way to have a different display name in the drop-down, it seems better to name it `provider` instead to ensure a correct code snippet.

fix confmap provider name

---

content/zh/docs/concepts/signals/_index.md

content/zh/docs/concepts/signals/_index.md

[zh] Add concepts/signals/_index.md

---

data/instrumentation.yaml

Update status from alpha to beta reflecting the repo: https://github.com/open-telemetry/opentelemetry-rust?tab=readme-ov-file#project-status

Update Rust logs,metrics status to beta

---

content/en/blog/2024/scaling-collectors.md

The ansible role is named opentelemetry_collector without the extra r
I found this spelling error while searching for an example of setting up the collector with ansible.

Fix ansible role name misspelling

---

.github/workflows/scripts/update-registry-versions.sh
data/registry/instrumentation-php-cakephp.yml
data/registry/instrumentation-php-curl.yml
data/registry/instrumentation-php-extrdkafka.yml
data/registry/instrumentation-php-psr6.yml
static/refcache.json

The workflow to update versions in the registry was broken due to some errors introduced by PHP packages missing the `open-telemetry` prefix. I fixed those files, but also introduced 2 additional changes:
* A way to catch errors if getting the latest version for a package fails, so a situation like this will not break the workflow again 
* A way to check if any versions have been updated and only if a new PR will be created, otherwise the script will always terminate with error

Fix registry version updater

---

content/pt/docs/concepts/components.md
content/pt/docs/languages/go/exporters.md
layouts/shortcodes/pt/docs/languages/exporters/intro.md
layouts/shortcodes/pt/docs/languages/exporters/jaeger.md
layouts/shortcodes/pt/docs/languages/exporters/outro.md
layouts/shortcodes/pt/docs/languages/exporters/prometheus-setup.md
layouts/shortcodes/pt/docs/languages/exporters/zipkin-setup.md

* Add new translations:
- layouts/shortcodes/pt/docs/languages/exporters/intro.md
- layouts/shortcodes/pt/docs/languages/exporters/jaeger.md
- layouts/shortcodes/pt/docs/languages/exporters/outro.md
- layouts/shortcodes/pt/docs/languages/exporters/prometheus-setup.md
- layouts/shortcodes/pt/docs/languages/exporters/zipkin-setup.md
* Fixes translations for snippets on:
- content/pt/docs/concepts/components.md (https://opentelemetry.io/pt/docs/concepts/components/#exporters)
- content/pt/docs/languages/go/exporters.md (https://opentelemetry.io/pt/docs/languages/go/exporters/)
Fixes #5592

[pt] Translate shortcode snippets /languages/exporters

---

content/en/docs/collector/internal-telemetry.md

The following PR removes the suggestion in the documentation to send the Collector's internal telemetry through the Collector's pipelines. As the warning suggests, doing this is risky and we likely don't want to recommend users do this.

remove suggestion to process internal telemetry through collector

---

package.json

Updates Hugo to [0.139.4](https://github.com/gohugoio/hugo/releases/tag/v0.139.4). The main change that has an impact is:
> - tpl/tplimpl: Escape Markdown attributes in render hooks and shortcodes https://github.com/gohugoio/hugo/commit/54398f8d572c689f9785d59e907fd910a23401b0 `@jmooring`
The generated site-file diff:
```console
$ (cd public && git diff -bw -I 'img src|img alt|iframe|Hugo 0' -- . ':(exclude)*.xml') | grep ^diff
diff --git a/blog/2023/euwg-future-of-observability-panel/index.html b/blog/2023/euwg-future-of-observability-panel/index.html
diff --git a/blog/2023/humans-of-otel/index.html b/blog/2023/humans-of-otel/index.html
diff --git a/blog/2024/humans-of-otel-eu-2024/index.html b/blog/2024/humans-of-otel-eu-2024/index.html
``` …

[CI] Update Hugo to 0.139.4

---

content/en/docs/concepts/signals/metrics.md

Description of Gauge was misleading due to a typo between asynchronous and synchronous.
Fix #5774

Update metrics.md - fix typo on Gauge (a-synchronous)

---

.github/workflows/check-format.yml
package.json

- Pins version of Prettier in `packages.json`
- Ensures that the `check-format` workflow runs the version of Prettier specified in the `package.json` file

[CI] Ensure specified version of Prettier is run in workflow

---

.github/workflows/auto-update-community-members.yml

fixes an issue where the author is the merge queue bot(?) in https://github.com/open-telemetry/opentelemetry.io/pull/5757

Set author in auto-update-community-members.yml

---

content/en/blog/2024/prometheus-compatibility-survey/index.md

Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main. This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.

update links to openmetrics to reference the v1.0.0 release

---

content/en/blog/2024/year-in-review.md

- Followup to #5775
- Fix OTel capitalization in title. I'm not even sure if this is what we want, but it seems off to not have the mixed case
/cc @svrnm @tiffany76

[blog] Year-in-review copyedits

---

content/en/blog/2024/profiling.md
content/en/docs/contributing/development.md
gulp-src/prune.js
static/refcache.json

- Fixes #5801
- Improves the usability of the `prune.js` task when it comes to listing prune candidates. Use `--list` to list all prune candidate entries, with `-n <num>` to list only _num_ entries.
- Refreshes the oldest 40+ entries of the refcache, so that the next oldest are Jan 18 UTC. That'll give us until then to work on #2554

[CI] refcache refresh & cleanup + script update

---

content/en/blog/2024/humans-of-otel-na-2024.md
static/refcache.json

Create blog post for Humans of OTel NA 2024. Reference issue: #5812

Add Humans of OTel blog post.

---

content/en/docs/collector/internal-telemetry.md

Because of a somewhat outdated dependency, the Collector does not yet have support for exporting internal logs through OTLP/gRPC, only through OTLP/HTTP. Because of this, the example config added to the "Internal telemetry" docs page in PR #5702 does not actually work, and will result in an "unsupported protocol" error. There is [work underway](https://github.com/open-telemetry/opentelemetry-collector/pull/11611) to fix this, but according to @codeboten, it is blocked by other work, and may take some time to be merged.
For this reason, in the meantime, this PR updates the example config to use OTLP/HTTP instead of OTLP/gRPC, to avoid confusing users who try to use the example as-is.

Change internal logs config example to use OTLP/HTTP

---

content/en/docs/languages/php/sdk.md

Update PHP configuration documentation to mention that boolean values need to be protected by double-quotes
if provided via `php.ini`.
Closes: https://github.com/open-telemetry/opentelemetry-php/issues/1442

Document required quoting of booleans in php.ini

---

data/ecosystem/vendors.yaml
static/refcache.json

This pull request includes updates to the `data/ecosystem/vendors.yaml` and `static/refcache.json` files to add a new vendor [Odigos](https://github.com/odigos-io), to the ecosystem and update the status of its documentation URL.
Odigos is an open-source distributed tracing solution, that implements OTLP automatically on k8s applications, and spins up a collectors pipeline to process and transfer the telemetry data to various vendors/destinations.

feat(): Add Odigos vendor information and update refcache for its documentation

---

content/en/blog/2024/fuzzing-audit-results.md
content/en/docs/zero-code/java/agent/annotations.md
content/en/docs/zero-code/java/agent/configuration.md
content/en/docs/zero-code/java/agent/disable.md
content/en/docs/zero-code/java/agent/instrumentation/http.md

* Some small changes to the wording of some sections so they flow a little better
* Added emphasis on the note around the complexity of disabling instrumentation, as discussed in a recent SIG meeting
* Moved some gradle/maven code into a tab pane
One other thing I tried to fix was the [rendering of this section](https://opentelemetry.io/docs/zero-code/java/agent/instrumentation/#peer-service-name), particularly [this line](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/zero-code/java/agent/instrumentation/_index.md?plain=1#L22) which doesn't seem to be rendering properly:
I wasn't able to figure out a fix, in case anyone has any tips on how I can address that

Small updates to the java agent zero code docs

---

content/en/blog/2023/otel-arrow/index.md
content/en/blog/2024/otel-arrow-production/index.md
content/en/blog/2024/profiling.md
content/en/docs/concepts/instrumentation/libraries.md
content/en/docs/concepts/signals/_index.md
content/ja/docs/concepts/instrumentation/libraries.md
content/ja/docs/concepts/signals/_index.md
content/pt/docs/concepts/instrumentation/libraries.md
content/pt/docs/concepts/signals/_index.md
content/zh/docs/concepts/signals/_index.md
layouts/partials/docs/get-signal-status.html

This PR replaces references from the "oteps" repo with ones from the "opentelemetry-specification" repo as the former has been archived.

Replace "oteps" repo references with "opentelemetry-specification" repo

---

data/registry/tools-dotnet-aspire-dashboard.yml
static/refcache.json

Fix typo in registry

---

.gitmodules

- Upgrades Docsy to v0.11.0-22-g2f361b2b in prep for further changes
- Contributes to #4781 for `ja` via https://github.com/google/docsy/pull/2149. Thank you @rinsuki! For example:
> <img width="300" alt="image" src="https://github.com/user-attachments/assets/613d09dd-41e4-4a5e-b27a-f1c64a291321" />
/cc @open-telemetry/docs-ja-approvers

Upgrade Docsy to v0.11.0-22-g2f361b2b

---

content/ja/docs/demo/_index.md
content/ja/docs/demo/architecture.md

I translated demo page (_index and architecture).

[ja] translate demo/_index and demo/architecture page into ja

---

.htmltest.yml
content/en/blog/2025/_index.md
content/en/blog/_index.md

- #5017
- #5873
- Introduces "2025" blog section, including an RSS feed
- Adds link-checker ignore rules for blog sections older than a year
- I'm delaying updating the redirect rules to point to the 2025 section until we have our first 2025 blog post. Otherwise it just looks like the blog section is broken, because no posts are shown.
**Preview and redirect tests**:
- https://deploy-preview-5874--opentelemetry.netlify.app/blog/ --> ~redirect to 2025 section~ still redirects to 2024
- https://deploy-preview-5874--opentelemetry.netlify.app/blog/index.xml --> ~redirect to 2025 RSS feed~ still redirects to 2024 RSS feed

Blog section for 2025

---

content/en/blog/2024/fuzzing-audit-results.md
static/refcache.json

- Followup to https://github.com/open-telemetry/opentelemetry.io/pull/5827/files#r1899680772
- Contributes (and maybe closes) #5798
- Adds link to CNCF blog post describing the overall effort and validating the CNCF sponsorship. /cc @AdamKorcz 
- **Preview**: https://deploy-preview-5875--opentelemetry.netlify.app/blog/2024/fuzzing-audit-results/

[Blog] Fuzzing blog post - add link to CNCF blog

---

layouts/blog/content.html

- Contributes to, and is a first proposal to resolve #3493
- Overrides the blog `content.html` layout to add a `pageinfo` div `{{ if .Date.Before (now.AddDate -1 0 0) -}}`, that is, if the post if more than a year old. The warning text is added just before the content starts, and below the breadcrumbs, title, and author. I find that it looks better this way (as compared to have a warning before the breadcrumbs).
**Preview**:
- Not outdated (as of today): https://deploy-preview-5883--opentelemetry.netlify.app/blog/2024/year-in-review/
- Outdated:
- https://deploy-preview-5883--opentelemetry.netlify.app/blog/2023/humans-of-otel/
- https://deploy-preview-5883--opentelemetry.netlify.app/blog/2023/otel-in-focus-break/
> <img width="777" alt="image" …

Warn when blog posts are outdated

---

content/en/blog/2025/_index.md
layouts/blog/list.html

- Followup to #5874
- Ensures that the blog/2025 section isn't empty. Wishes reader a happy new year and invites them back soon. Note that the message can stay a bit even after our first 2025 post (IMHO).
**Preview**: https://deploy-preview-5885--opentelemetry.netlify.app/blog/2025
> <img width="777" alt="image" src="https://github.com/user-attachments/assets/6cef7b24-1d14-4ccf-9a40-9ff941e3e0c6" />

Blog 2025 section: offer wishes and hope of articles to come

---

package.json

Ensures that `update:submodule` also fetches tags. This command caters to two use cases where developers have submodules with:
- Only one remote (most likely named `origin`). This is likely the case for most devs.
- Two remotes, named `origin` and `upstream` (if you're a dev who also sometimes submit PRs to the submodule). In this case, the given `foreach` command will fetch tags from `upstream`. (The command is a bit brittle, but I don't foresee any likely cases for which this might cause an issue -- and if it does we can adjust at that time.)

[CI] When updating submodules, also fetch tags

---

content/ja/docs/collector/installation.md

Translate this page into Japanese: https://opentelemetry.io/docs/collector/installation/.
This is the same request as https://github.com/open-telemetry/opentelemetry.io/pull/5109 but changed author email so that I can re-sign CLA under the new employer's name.

[ja] add Japanese translation of "install the Collector"

---

.github/workflows/build-dev.yml
.github/workflows/survey-on-merged-pr.yml

This contributes to https://github.com/open-telemetry/sig-contributor-experience/issues/28
@open-telemetry/sig-contributor-experience-approvers want to try out if we can encourage new contributors to fill out a survey post merge to share with us some of their experience. The issue above provides more details

Add a post-merge workflow to ask contributors for filling out a survey

---

.github/workflows/survey-on-merged-pr.yml

fixes the action for commenting with a survey link below PRs.

Add missing GH token to survey-on-merged-pr.yml

---

content/en/docs/demo/architecture.md

Fixing broken link to collector config file.

Fixing broken link in architecture.md

---

content/en/docs/collector/internal-telemetry.md

Remove references to the metrics representing the number of dropped items in the monitoring guide that were deprecated in [v0.110.0](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.110.0)

docs: Remove references to processor metrics that are no longer available

---

content/en/docs/collector/custom-collector.md

Contributing my first commit to OpenTelemetry with a first `good-to-have` issue
Closes #5656

Add otelcol_version

---

content/en/docs/collector/configuration.md

Add example of configuring receivers for TLS

---

content/en/docs/languages/js/instrumentation.md

Resolves #5805 
I tested in the Typescript playground that this fixes the type checking issue.
I have not checked that this fully functionally works (is there an existing otel-js playground for that? If not I can probably find an online editor playground to setup in. Just lmk)

Fix TS example for recording exceptions

---

content/en/docs/collector/transforming-telemetry.md

fix: transform should be array item, not map

Fix data type in yaml

---

content/en/docs/languages/java/api.md
content/en/docs/zero-code/java/agent/annotations.md
content/en/docs/zero-code/java/agent/api.md
content/en/docs/zero-code/java/spring-boot-starter/annotations.md
content/en/docs/zero-code/java/spring-boot-starter/api.md

Fixes https://github.com/open-telemetry/opentelemetry.io/issues/5713

Extending with custom manual instrumentation

---

.github/workflows/survey-on-merged-pr.yml

The workflow is still not working, there is an authentication issue, but I am not sure what the root cause for this is. This introduces 2 changes:
* Change from `pull_request` to `pull_request_target`
* Add checkout action, because I suspect that `git`/`gh` is not setup properly. https://github.com/open-telemetry/opentelemetry.io/blob/main/.github/workflows/pr-actions.yml does it before sending the first comment, so maybe the checkout action does something that's missing.

Another fix for survey-on-merged-pr.yml

---

gulp-src/prune.js
static/refcache.json

- Contributes to #5017
- Adjusts `prune` Gulp task to better handle defaults
- Refreshes a few hundred refcache entries
- ~I'm going to also test the fix `refcache:refresh` PR action here, so marking this as draft in the meantime.~

[CI] refcache refresh and adjust prune Gulp task

---

content/en/docs/languages/java/configuration.md

Fix the mismatch of the property name in the document vs. actual code.
See the system property name in the code -  - https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java#L41
```
static final String DISABLED_ATTRIBUTE_KEYS = "otel.resource.disabled.keys";
```

[Java] correct the resource property name

---

content/en/ecosystem/adopters.md
content/en/ecosystem/vendors.md
data/ecosystem/vendors.yaml
static/refcache.json

- Contributes to #5017
- Refreshes some refcache entries
- Resolves 404 entries, in particular:
- Replaces https://community.cncf.io/end-user-community with path to our local page `/community/end-user/`
- Updates Observe Inc's link to OTel (I've emailed their support team to inquire about the current link's 404 -- cc'd @svrnm).
- Fixes #5939
/cc @open-telemetry/sig-end-user-approvers

[CI] Refcache refresh + update to ecosystem pages and list entries

---

content/en/ecosystem/adopters.md
content/en/ecosystem/distributions.md
content/en/ecosystem/integrations.md
content/en/ecosystem/registry/updating.md
content/en/ecosystem/vendors.md
layouts/shortcodes/ecosystem/keep-up-to-date.md

- A proposed solution for #5938, but I'm open to alternatives (let's discuss alternatives in the issue).
- Adds a mention that registry-entry authors are responsible for keeping their data up-to-date
- Failing that, we reserve the right to update and/or remove entries. We'll contact entry authors on a best effort basis
- Adds a page on "Keeping registry information current"
**Preview**:
- https://deploy-preview-5937--opentelemetry.netlify.app/ecosystem/
- E.g., https://deploy-preview-5937--opentelemetry.netlify.app/ecosystem/adopters/
- https://deploy-preview-5937--opentelemetry.netlify.app/ecosystem/registry/updating/

[ecosystem] Document registry curation policy and responsibilities

---

.cspell.yml
.htmltest.yml
static/refcache.json

- This lays a foundation for, and contributes to #5951
- Updates refcache with many links into `github.com`
- Ignores URLs to `github.com` orgs and users that result in 400 statuses

[CI] Check links into github.com, excluding 4XXs for now

---

.htmltest.yml
content/en/blog/2024/otel-operator-q-and-a/index.md
static/refcache.json

- Drops unnecessary IgnoreURL regex alternatives (htmltest must have gotten confused or overwhelmed when it hit too many 429 statuses).
- Fixes some prometheus-operator links

[CI] Fix some external links into GitHub, and clean up IgnoreURL rules

---

.htmltest.yml
content/zh/docs/contributing/_index.md
data/ecosystem/vendors.yaml
data/registry/instrumentation-java-micrometer-tracing.yml
scripts/content-modules/adjust-pages.pl
static/refcache.json

- Notes:
- @svrnm added the Micrometer link via https://github.com/open-telemetry/opentelemetry.io/pull/2201. This PR adjusts the link
- f5 exporter is gone since https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31186, and so is dropped in this PR

[CI] Fix some github.com links into OTel org

---

scripts/content-modules/adjust-pages.pl

- Improves adjust-pages processing of links to `README.md` pages
- This is in preparation for fixing of `opentelemetry-collector-contrib` links of #5951.
These are the site-generated files affected by this PR's script adjustment:
```console
$ npm run cd:public -- git diff | grep ^diff
diff --git a/docs/specs/otlp/index.html b/docs/specs/otlp/index.html
diff --git a/docs/specs/semconv/attributes-registry/artifact/index.html b/docs/specs/semconv/attributes-registry/artifact/index.html
diff --git a/docs/specs/semconv/non-normative/db-migration/index.html b/docs/specs/semconv/non-normative/db-migration/index.html
diff --git a/docs/specs/semconv/non-normative/http-migration/index.html b/docs/specs/semconv/non-normative/http-migration/index.html
diff --git …
```

[CI] Improve spec adjust-pages to handle README.md paths to spec-external resources

---

.htmltest.yml
content/en/blog/2024/otel-collector-anti-patterns/index.md
content/en/blog/2024/otel-collector-survey/index.md
content/es/docs/kubernetes/collector/components.md
static/refcache.json

- Fixes external links into the `opentelemetry-collector-contrib` and `opentelemetry-collector` repos
- In a blog post, pins the URLs to v0.117.0 for most links to keep them valid over time

[CI] Fix external links into opentelemetry-collector-contrib

---

.htmltest.yml
content/en/blog/2024/otel-generative-ai/index.md
content/en/docs/zero-code/net/_index.md
data/registry/instrumentation-java-struts.yml
static/refcache.json

[CI] Fixes github.com links for opentelemetry-dotnet-instrumentation and more

---

.htmltest.yml
static/refcache.json

- We don't actually need to wait for the semconv update because the in-toto link issue was fixed via #5969

[CI] Address semconv link to in-toto

---

content/en/docs/specs/status.md

Due to
* https://github.com/open-telemetry/opentelemetry-specification/pull/4352
* https://github.com/open-telemetry/opentelemetry-specification/issues/4357
and to fix the broken Event API status once the next spec release comes out,
my recommendation for now is to remove information here about the Event API, and we can revisit once we introduce language into the specification about the Logs API being user-facing and/or introduce an ergonomic Event API.

Remove Event API status

---

content/en/docs/kubernetes/operator/automatic.md

Fix link in Deno instructions for operator

---

.gitmodules
content/en/blog/2024/otel-operator-q-and-a/index.md
package.json

- Upgrades Docsy
- Upgrades to Hugo v0.141.0
- We'll address https://github.com/gohugoio/hugo/issues/13286 if/when it gets fixed.
- Copyedit to author name of a 2024 blog that had an excess comma at the end
- For an example of how generated HTML for code-blocks have changes, see the opening comment of https://github.com/google/docsy/pull/2177

Upgrade to Docsy v0.11.0-34-gef59ee75, and more

---

content/en/_index.md
content/en/blog/2024/_index.md
content/en/blog/2025/_index.md
content/en/blog/_index.md
content/es/_index.md
content/fr/_index.md
content/ja/blog/2024/_index.md
content/ja/blog/_index.md
content/pt/blog/2024/_index.md
content/pt/blog/_index.md
content/zh/blog/2024/_index.md
content/zh/blog/_index.md
hugo.yaml
layouts/_default/rss.xml

- Contributes to #5902
- Fixes #5873. (Re)fixes:
- #3740
- #4440
- Supports RSS feeds for the homepage of each locale, and the blog landing page. Each RSS feed is for the entire site or section, as appropriate.
- Limits the number of entries to 20, which seems typical.
- Fixes the config for all locales
- Eliminates the need for blog redirects, which needed to be updated each year. Replaces the redirect hack by a JS solution that will open the 2025 and 2024 blog subsections in the left nav. I'll adjust the code later so that we don't have to update this each year.
**Preview**:
- https://deploy-preview-6002--opentelemetry.netlify.app
- https://deploy-preview-6002--opentelemetry.netlify.app/blog
- https://deploy-preview-6002--opentelemetry.netlify.app/blog/2024
RSS feeds:
- …

[infra] Better support for RSS and blog pages

---

content/en/docs/collector/architecture.md

- **Best reviewed by ignoring whitespace diffs**
- Fixes #5999
- Eliminates color overrides for most Mermaid diagrams, falling back to defaults that are dark-mode compatible
- Drops named anchors in "Running as ..." headings, since those prevented the corresponding TOC entries from working
- Closes #6001, as an alternative solution, which also fixes _all_ diagrams, and the TOC heading links
- https://deploy-preview-6013--opentelemetry.netlify.app/docs/collector/architecture/#pipelines
- https://deploy-preview-6013--opentelemetry.netlify.app/docs/collector/architecture/#running-as-an-agent
| Before | After |
|--------|--------|
| <img width="444" alt="image" src="https://github.com/user-attachments/assets/e0796213-1229-473f-a3d2-29a810f6c5ee" /> | <img width="444" alt="image" …

Make collector mermaid diagrams darkmode compatible

---

content/en/docs/demo/services/load-generator.md
static/refcache.json

It appears the folder name for the load generator changed, or there was a typo in this link.

Fix load generator source link

---

.github/workflows/component-owners.yml

chore(ci): Only run component owners for open-telemetry

---

scripts/content-modules/adjust-pages.pl

- Followup to #6022
- Ensures that path patch gets applied to path in  front matter too. Currently we get a 404:
```console
$ curl -sIL https://opentelemetry.io/docs/specs/otel/common/attribute-naming/ | grep -E 'HTTP|^date|loc'
HTTP/2 301 
date: Wed, 22 Jan 2025 13:51:50 GMT
location: /docs/specs/semconv/general/naming/
HTTP/2 404 
date: Wed, 22 Jan 2025 13:51:50 GMT
```
This PR also patches the redirect path:
```console
$ curl -sIL https://deploy-preview-6027--opentelemetry.netlify.app/docs/specs/otel/common/attribute-naming/ | grep -E 'HTTP|^date|loc' 
HTTP/2 301 
date: Wed, 22 Jan 2025 13:53:43 GMT
location: /docs/specs/semconv/general/attribute-naming/
HTTP/2 200 
date: Wed, 22 Jan 2025 13:53:43 GMT
```
**Preview**: https://deploy-preview-6027--opentelemetry.netlify.app/docs/specs/ote …

Ensure that spec front matter redirect path gets patched too

---

.github/workflows/auto-update-community-members.yml
.github/workflows/auto-update-registry.yml
content/en/blog/2023/histograms-vs-summaries/index.md
content/en/blog/2024/prometheus-compatibility-survey/index.md
content/en/docs/concepts/resources/index.md
content/en/docs/contributing/blog.md
content/en/docs/demo/services/payment.md
content/en/docs/languages/java/sdk.md
content/en/docs/languages/js/resources.md
data/registry-schema.json

Per https://github.com/open-telemetry/opentelemetry.io/pull/6009#issuecomment-2605506429

[chore] Spelling `a`...`container.id`

---

content/en/docs/specs/status.md
layouts/_default/_markup/render-link.html
scripts/content-modules/adjust-pages.pl

- Fixes #6025
- Adds code to the render-link hook to resolve intra-spec references in a manner that was previously done using `relref`. The `relref` function is no longer used / emitted.
- Greatly simplifies `scripts/content-modules/adjust-pages.pl` by removing link-transformation code that was previously used to insert `relref` function calls, and rename `README.md`. We might eventually be able to move more of the `adjust-pages.pl` functionality into the render-link hook.
The only change to the generated site files is the addition of trailing `/` at the end of `/docs/specs/otel/document-status` links in semconv pages:
```console
$ (cd public && git diff -bw --ignore-blank-lines -I '/docs/specs/otel/document-status' -I 'modified_time|Last modified|dateModified' -- . ':(exclude)*.xml') | …
```

Use render-link hook to resolve references in specs

---

content/pt/docs/languages/python/_index.md

This pull request adds a comprehensive documentation page for Python in the OpenTelemetry project. The most important changes include the addition of installation instructions, version support details, and links to related repositories and packages.
Documentation updates:
* [`content/pt/docs/languages/python/_index.md`](diffhunk://#diff-2e8373a87d316f754b709f81fb25da44d6cbad49324e57689a7ea9ec45785fa3R1-R72): Added a new documentation page for Python, including sections on version support, installation instructions, extensions, and links to related repositories and packages.
*Issue*: #5963

[pt] feat: add languages python index localization

---

.github/workflows/build-semconv-daily.yml
.github/workflows/reusable-workflow-notification.yml

[Secrets are not automatically passed to reusable workflows](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow)
cc @open-telemetry/specs-semconv-maintainers

Fix daily semconv build workflow

---

content/en/blog/2024/otel-operator-q-and-a/index.md
content/en/blog/2024/prom-and-otel/index.md
content/en/docs/concepts/components.md
content/en/docs/faas/_index.md
content/en/docs/languages/js/exporters.md
scripts/registry-scanner/index.mjs

Per https://github.com/open-telemetry/opentelemetry.io/pull/6009#issuecomment-2605506429
This items had interdependencies with other items in the PR series.

[chore] Spelling: the..typescript

---

.textlintrc.yml
content/en/blog/2023/end-user-discussions-01.md
content/en/docs/collector/building/connector/index.md

- Inspired by #6021
- Adds textlint rewrite rules for `walk-through` and `work-around`, to encode use without the hyphen.
- Runs textlint over pages to fix words
- Manually adjusts one more spelling
- ~Closes #6021 by superseding it~
/cc @jsoref @reyang

[infra] Add textlint rules for work-around and walk-through

---

scripts/content-modules/adjust-pages.pl

- Improved support for build-dev and related workflows
- Skips applying patches to spec pages when a spec repo submodule is being used at HEAD or any version other than the patch-target version.
- Context: https://github.com/open-telemetry/semantic-conventions/issues/1791#issuecomment-2608761283
/cc @trask

[CI] Don't apply spec patch if submodule is at HEAD

---

content/en/docs/languages/php/context.md
content/en/docs/languages/php/instrumentation.md
content/en/docs/languages/php/sdk.md
content/en/docs/zero-code/php.md

- fix class in zero-code example
- minor typo fixes
- fix link to go to PHP's resources page
- remove duplicated warning about php.ini and booleans
Closes: #6016

PHP docs minor fixes

---

content/en/blog/2025/go-goals.md

The result of running `npm run fix:dict`. We should be catching this during build checks. (**Edit**: see #6040)

Fix go-goals front matter

---

.textlintrc.yml

- https://github.com/open-telemetry/opentelemetry.io/pull/6054 has a failure that isn't particularly reasonable... It shouldn't be a problem to link to `open-telemetry/<repo name>` nor to describe such a link by that name.
https://github.com/open-telemetry/opentelemetry.io/actions/runs/12932842042/job/36070036852

chore(ci): Make linter tolerate org/repo references

---

content/en/docs/collector/_index.md
layouts/partials/redirects/aliases.txt
scripts/content-modules/adjust-pages.pl

- Fixes #6057
- Adjusts `layouts/partials/redirects/aliases.txt`:
- Drops patch code for `semconv/general`; the patch code is now in `adjust-pages.pl` and uses our new patch-coding conventions (so that the patch is conditional on the spec version, etc)
- Supports page-relative alias paths when they start with `./`. Otherwise, a non-absolute alias path is assumed to be relative to the given page's parent.
- Adjusts collector alias to use `./`
- Adds patches for the problems solved at their source by:
- https://github.com/open-telemetry/semantic-conventions/pull/1805
- https://github.com/open-telemetry/opentelemetry-specification/pull/4385
- https://deploy-preview-6059--opentelemetry.netlify.app/
- https://deploy-preview-6059--opentelemetry.netlify.app/docs/specs/otel/logs/event-api/
- …

[CI] Fix 404 due to redirects, and more

---

.github/workflows/build-dev.yml
.github/workflows/build-semconv-daily.yml

From @chalin's https://github.com/open-telemetry/opentelemetry.io/pull/6034#pullrequestreview-2568562436
> we might want to see how we can tweak this so that it doesn't fail if the refcache is updated, only if there are broken links.

Skip refcache check for daily semconv build

---

content/en/blog/2025/go-compile-time-instrumentation.md
static/refcache.json

Add blogpost after https://github.com/open-telemetry/community/pull/2490 was merged and the SIG has been created, announcing donations proposals and creation of new SIG.
cc @open-telemetry/governance-committee @open-telemetry/go-compile-instrumentation-approvers 
---
**Preview**: https://deploy-preview-5956--opentelemetry.netlify.app/blog/2025/go-compile-time-instrumentation/

Add blog post on Go Compile-Time Instrumentation SIG

---

content/en/docs/collector/management.md
content/en/docs/concepts/glossary.md
content/en/docs/contributing/style-guide.md
content/en/docs/what-is-opentelemetry.md
content/ja/docs/concepts/glossary.md
content/pt/docs/concepts/glossary.md
static/refcache.json

- Related / in prep for #6068
- Consolidates the "terms" in the style guide, by moving them into the glossary, and referring to the glossary. Moves spelling & capitalization recommendations along with them.
- Copyedits and style (markdown) cleanup of the glossary and a few pages it refers to
For example, see:
- https://deploy-preview-6074--opentelemetry.netlify.app/docs/concepts/glossary/#opentelemetry
- https://deploy-preview-6074--opentelemetry.netlify.app/docs/contributing/style-guide/#opentelemetryio-word-list

Glossary: add terms from style guide, and some rework

---

content/en/docs/zero-code/php.md

- install otlp exporter
- use http/protobuf by default
- minor editorialization
Related: https://github.com/open-telemetry/opentelemetry-php/issues/1437

update PHP zero-code docs

---

.github/workflows/survey-on-merged-pr.yml

if `pull_request_target` is used it seems that the `gh comment` is looking for the PR in the fork that's why this is breaking

Reset survey-on-merged-pr `on` to `pull_request`

---

.gitmodules
layouts/docs/baseof.html

- Upgrades to Docsy v0.11.0-37-ga854cb31
- Sync's (minimizes differences) between Docsy's and our `layouts/docs/baseof.html`, in prep of further changes.

Upgrade Docsy and sync layout

---

.gitmodules
.htmltest.yml
assets/scss/_styles_project.scss
layouts/docs/baseof.html
layouts/partials/translate-scripts.html

- Adds a Google-translate button to the top of English fallback pages (and only fallback pages). After choosing your own locale language, GT will automatically translate all fallback pages when you visit them. The feature allows you to toggle between viewing the original and toggling translation.
- The goal here is **not** to replace manual translations, but to offer an improved user experience for those navigating the site in a particular locale. Google translate isn't perfect, but it can be "good enough". Also it can be a point of comparison for translator.
**Preview**: https://deploy-preview-6117--opentelemetry.netlify.app/fr/docs/
Here's an example of the `/fr/docs` English fallback page translated by Google:
> <img width="1069" alt="image" …

[i18n] Google translate button in fallback pages for all locales

---

scripts/content-modules/adjust-pages.pl

- Followup to #6103
- #6101
- https://github.com/open-telemetry/semantic-conventions/issues/1821
- Patches semconv `README.md` file front matter by removing the `path_base_for_github_subdir` YAML entry. This patch is needed until https://github.com/open-telemetry/semantic-conventions/pull/1846 last in a semconv version
Test the "View page source" links of the following, they are valid (non-404) now:
- https://deploy-preview-6107--opentelemetry.netlify.app/docs/specs/semconv/
- https://deploy-preview-6107--opentelemetry.netlify.app/docs/specs/semconv/attributes-registry/

[CI] Semconv: apply patch to remove path_base

---

.htmltest.yml
content/en/blog/2023/testing-otel-demo/index.md
content/en/docs/demo/_index.md
content/en/docs/demo/docker-deployment.md
content/en/docs/demo/services/cart/index.md
content/en/docs/demo/services/image-provider.md
content/es/docs/demo/_index.md
content/ja/docs/demo/_index.md
content/ja/docs/demo/architecture.md
content/zh/docs/demo/_index.md
static/refcache.json

- Contributes to #5017
- Removes temporary rule that had some external links into the demo repo igored
- Updates links to services etc that were recently renamed.
- Updates the refcache
- I decided to fix the broken links in non-`en` pages, and to tag the links with a `?i18n-patch` query parameter as an indicator for humans and tools that this is a link patch, but otherwise the rest of the page still matches it's `default_lang_commit`

Demo repo links: fix & check them all, update refcache

---

layouts/_default/_markup/render-link.html

- Improves the detection of the use of `https://opentelemetry.io` as part of a markdown link.
- Context: https://github.com/open-telemetry/opentelemetry.io/pull/6072?new_mergebox=false#discussion_r1935521715

Improve detection of site-local path written as external URL

---

content/en/blog/2025/otel-mainframe-priorities-survey.md
static/refcache.json

Fixes #6045
Adds a blog post to promote the OpenTelemetry on Mainframe Priorities Survey created by the Mainframe SIG. The blog has been previously published by the Open Mainframe Project [here](https://openmainframeproject.org/blog/opentelemetry-on-mainframe-priorities-survey/).

Add blog post about the mainframe priorities survey

---

package.json

- Context: #5016
- Reenabling preview of future pages until I can think of a better solution to #5016. Side-effect is that we'll see all announcements, not just the currently relevant ones 🤷🏼‍♂️

[CI] Include future posts in preview

---

.github/workflows/check-links.yml

- Fixes #6127
/cc @trask @tiffany76

[CI] Push changes on link-check refcache diff

---

content/en/blog/2025/go-auto-instrumentation-beta.md
content/en/blog/2025/otel-collector-k8s-discovery.md
content/ja/docs/collector/installation.md
content/ja/docs/concepts/instrumentation/code-based.md
content/ja/docs/concepts/observability-primer.md
content/ja/docs/concepts/signals/traces.md
content/ja/docs/demo/_index.md
content/ja/docs/demo/development.md
content/pt/docs/languages/js/getting-started/nodejs.md
content/pt/docs/languages/sdk-configuration/general.md
content/zh/docs/concepts/observability-primer.md
content/zh/docs/contributing/style-guide.md
content/zh/docs/demo/_index.md
package.json

- Fixes #6142
- For some reason the shell used by NPM was a barebones one, not `bash`. Anyhow, fixed this by avoiding path expansion using the `{...}` syntax.
- Runs `fix:dict` on all locales now
- Includes the results of running `fix:dict`

[CI] Fix fix:dict and run it

---

.github/workflows/survey-on-merged-pr.yml

Update the server url to have the pre-selected value for repo.
The prior form didn't have a repo field, now with the new field, we want to have the value already pre-selected to help the user.

Update survey URL

---

content/en/docs/collector/building/connector/index.md
content/en/docs/collector/custom-collector.md

The parameter was deprecated in previous versions and has been completely removed in version >=0.113.0.
- Updated documentation to reflect the change
Users with versions >= 0.113.0 will need to update their configurations to remove this parameter. For older versions, the parameter will continue to work as expected.
https://github.com/open-telemetry/opentelemetry.io/issues/6114
- https://github.com/open-telemetry/opentelemetry-collector/issues/11405
- https://github.com/open-telemetry/opentelemetry-collector/issues/9366
- https://github.com/open-telemetry/opentelemetry-collector/pull/11588

docs(builder): remove 'otelcol_version' configuration parameter

---

content/pt/docs/languages/go/examples.md
content/pt/docs/languages/go/exporters.md
content/pt/docs/languages/go/getting-started.md
content/pt/docs/languages/go/instrumentation.md

Updates the Portuguese localized content for the following files:
- content/pt/docs/languages/go/getting-started.md
- content/pt/docs/languages/go/instrumentation.md
- content/pt/docs/languages/go/exporters.md
- content/pt/docs/languages/go/examples.md

[pt] Update localized content under content/pt/docs/languages/go

---

content/pt/docs/languages/js/getting-started/browser.md

Updates the `default_lang_commit` tag for the following files:
- content/pt/docs/languages/js/getting-started/browser.md

[pt] Update localized content on content/pt/docs/languages/js/getting-started/browser.md

---

.github/workflows/check-links.yml
content/en/docs/kubernetes/operator/troubleshooting/target-allocator.md
data/ecosystem/vendors.yaml
scripts/double-check-refcache-400s.mjs
scripts/get-url-status.mjs
static/refcache.json

- Refreshes a bunch of external link last-seen timestamps
- Updates old links that were now 404s
- Oldest link in cache was last visited 2024-08-06:
```console
$ npm run _refcache:prune -- --list -n 1
> _refcache:prune
> npx gulp prune --list -n 1
[07:26:51] Using gulpfile ~/git/lf/open-telemetry/opentelemetry.io/gulpfile.js [07:26:51] Starting 'prune'...
INFO: 1 entries with 4XX status. Pruning them.
INFO: 4805 entries as prune candidates for before-date 9999-12-30. Number of date-based entries to delete: 1.
2024-08-06 09:13 for https://avatars.githubusercontent.com/u/1781907
[07:26:51] Finished 'prune' after 147 ms
```

[chore] Refcache refresh, oldest link is now 2024-08-06

---

content/ja/docs/concepts/components.md
layouts/shortcodes/ja/docs/languages/exporters/intro.md

#5982 
I have addressed the translation omissions in the [exporter section](https://opentelemetry.io/ja/docs/concepts/components/#exporters).
There are still some English parts within the shortcode, but I plan to handle those during the translation of other sections that use the shortcode.
Executed `npm run fix:all` in my local env and confirmed that there are no issues.

[ja]Addressed the translation omissions

---

content/zh/docs/faas/lambda-manual-instrument.md

Add content/zh/docs/faas/lambda-manual-instrument.md

[zh] Add lambda-manual-instrument.md

---

content/en/docs/demo/tests.md

- fix grammatical error in demo/tests page.
- fixes #6171

fix: missing `to` in demo/tests page

---

.textlintrc.yml
content/en/blog/2019/opentelemetry-governance-committee-explained/index.md
content/en/blog/2022/demo-announcement/index.md
content/en/blog/2022/instrument-kafka-clients/index.md
content/en/blog/2022/why-and-how-ebay-pivoted-to-opentelemetry/index.md
content/en/blog/2023/end-user-q-and-a-03.md
content/en/blog/2023/kubecon-eu.md
content/en/blog/2023/kubecon-na.md
content/en/blog/2023/otel-in-focus-04.md
content/en/blog/2024/kubecon-eu.md
content/en/blog/2024/kubecon-na.md
content/en/blog/2024/new-otel-features-envoy-istio/index.md
content/en/docs/demo/requirements/architecture.md
content/en/docs/faas/_index.md
static/refcache.json

- Adds a 'textlint' rule for "cloud native", without a hyphen, per:
- CNCF usage, see https://cncf.io and https://glossary.cncf.io
- https://developers.google.com/style/hyphens
- Fixes occurrences in doc pages
- Adds link to "cloud native apps" glossary entry from the FaaS page

[spelling] Write "cloud native" without a hyphen

---

.htmltest.yml
data/registry/instrumentation-rust-trillium.yml
scripts/double-check-refcache-400s.mjs
scripts/get-url-status.mjs
static/refcache.json

- Fixes #6175
- Contributes to #5017
- Enables the checking of links to crates.io, despite https://github.com/rust-lang/crates.io/issues/788
- Fixes package name
/cc @open-telemetry/rust-approvers

[CI] Check links to crates.io, and link fix

---

content/pt/docs/concepts/signals/_index.md
content/pt/docs/concepts/signals/baggage.md
content/pt/docs/concepts/signals/logs.md
content/pt/docs/concepts/signals/metrics.md
content/pt/docs/concepts/signals/traces.md

Updates the Portuguese localized content for the following files:
- content/pt/docs/concepts/signals/_index.md
- content/pt/docs/concepts/signals/baggage.md
- content/pt/docs/concepts/signals/logs.md
- content/pt/docs/concepts/signals/metrics.md
- content/pt/docs/concepts/signals/traces.md

[pt] Update localized content under content/pt/docs/concepts/signals

---

.gitmodules
content/en/docs/collector/internal-telemetry.md
package.json

- Upgrades to Hugo 0.143.0
- Upgrades Docsy, bringing with it the `comment` shortcode that Hugo has deprecated

[CI] Upgrade Docsy, and Hugo to 0.143.0

---

content/en/docs/zero-code/java/spring-boot-starter/other-spring-autoconfig.md

The folder/package `opentelemetry-spring-boot-autoconfigure` doesn't seem to exist anymore. Also, the following link has an invalid hash, but in any case it points back to this website, so we should just refer directly to this website. WDYT @trask @open-telemetry/java-instrumentation-approvers?
```markdown
[opentelemetry-spring-boot-autoconfigure](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md#features?FIXME)
```
This work is in support of:
- #6196
Related:
- #6205

Link fix of Spring Boot Starter other-spring-autoconfig.md

---

content/en/docs/languages/java/sdk.md

- Fixes #6173
- **Redirect test**: https://deploy-preview-6209--opentelemetry.netlify.app/docs/languages/java/exporters

Add alias for java/exporters

---

content/en/docs/contributing/issues.md

I fixed the outdated the word of Create Issue button in contributing/issues page.
issue: https://github.com/open-telemetry/opentelemetry.io/issues/6198

fix: update an outdated word of Create Issue in contributing/issues page

---

content/en/docs/platforms/faas/_index.md
content/en/docs/platforms/kubernetes/_index.md

- Followup to #6232
- Reverts the inadvertent redirects path change
- https://deploy-preview-6233--opentelemetry.netlify.app/docs/faas/
- https://deploy-preview-6233--opentelemetry.netlify.app/docs/kubernetes/

[IA] Revert inadvertent redirects path change

---

content/pt/docs/languages/java/instrumentation.md

Updates the default commit for localized content (Portuguese) for the following files:
- content/pt/docs/languages/java/instrumentation.md

[pt] Update localized content on content/pt/docs/languages/java/instrumentation.md

---

content/en/docs/languages/java/instrumentation.md

Fixes #6093 
Update to the correct description for `Log instrumentation`.

fix description of log instrumentation

---

.github/workflows/update-semconv-integration-branch.yml

It's failing on subsequent runs, this seems to fix it when I test on my fork...

Fix semconv integration branch workflow

---

content/en/docs/contributing/style-guide.md

I found the a duplicated words in contributing/style-guide page.
I fixed it because  I think that it is a mistake.

fix: removing deplulicated words of `file file`

---

content/ja/docs/contributing/prerequisites.md

translated contributing/prerequisites into ja.

[ja] translate contributing/prerequisites into ja

---

hugo.yaml

Per https://github.com/open-telemetry/community/issues/2444, this updates the footer to remove the link to Twitter.

Update Footer with Bluesky Link

---

scripts/auto-update/version-in-file.sh

- Fixes #6271
- Makes `scripts/auto-update/version-in-file.sh` a little more resilient when it comes to processing the `latest` version ID. It now ignores any prefix, extracting the semver from the end of the ID.
- Looks for existing PRs by matching on branch names, this avoids `semantic-conventions` potentially being skipped because there was a PR over `semantic-conventions-java`
- Tested locally. Let's see if it works in GH.
/cc @jack-berg @TylerHelmuth

[CI] Make version-if-file.sh more robust

---

.htmltest.yml
content/en/blog/2024/otel-operator-q-and-a/index.md
content/en/blog/2024/prometheus-compatibility-survey/index.md
content/en/docs/collector/building/authenticator-extension.md
content/en/docs/contributing/development.md
content/en/docs/languages/rust/_index.md
layouts/shortcodes/docs/languages/exporters/intro.md
layouts/shortcodes/docs/languages/exporters/prometheus-setup.md
layouts/shortcodes/ja/docs/languages/exporters/intro.md
layouts/shortcodes/pt/docs/languages/exporters/intro.md
layouts/shortcodes/pt/docs/languages/exporters/prometheus-setup.md
scripts/get-url-status.mjs
static/refcache.json

Fix invalid links to Prometheus, API pages, and more

---

content/ja/docs/demo/docker-deployment.md
hugo.yaml

translated demo/docker-deployment page.

[ja] translate demo/docker-deployment into ja

---

content/ja/docs/getting-started/ops.md

The diff happened by `npm run check:i18n -- content/ja`, so I updated `default_lang_commit`. I think that there are no other outdated words.
I also guessed that this diff is caused due to a bellow PR but it forgot to update `default_lang_commit` in ja page.
- https://github.com/open-telemetry/opentelemetry.io/pull/6232
- https://github.com/open-telemetry/opentelemetry.io/pull/6232/files#diff-140c308473d8cad8d40d0982bc9510e96f383b39811dc992f3f959ebb154eaf9

[ja] update default_lang_commit in content/ja/docs/getting-started page

---

layouts/docs/td-content-after-header.html

- Adds a banner at the top of fallback pages, informing readers of the obvious (that the page is in English), explaining why (page hasn't been translated), and asks for help.
- E.g., see https://deploy-preview-6287--opentelemetry.netlify.app/fr/docs/
> <img width="780" alt="image" src="https://github.com/user-attachments/assets/03d44f59-8464-49ef-8183-73a7792e509e" />

[i18n] Add page-not-yet-translated banner, ask for help

---

content/en/docs/contributing/pr-checks.md
content/en/docs/contributing/pull-requests.md
content/es/docs/contributing/pull-requests.md
content/ja/docs/contributing/pull-requests.md
static/refcache.json

Changes to contributing PR page:
- Adds a section covering the `/fix:*` commands
- Moves CLA-requirement alert to the top of the page
- Copyedits
**Preview**: https://deploy-preview-6286--opentelemetry.netlify.app/docs/contributing/pull-requests/#fixing-prs-in-github

Add fix cmd desc to contrib docs, and other edits

---

.github/workflows/auto-update-community-members.yml
.github/workflows/auto-update-registry.yml
.github/workflows/auto-update-versions.yml

- ... rather than `ubuntu-2x.xx`
- Closes #5715, by doing the opposite 🤷🏼‍♂️ 😄 
/cc @trask @svrnm

[CI/chore] Update workflows to run on ubuntu-latest

---

data/ecosystem/distributions.yaml
static/refcache.json

Add ADOT instrumentations to distribution list

---

.htmltest.yml
assets/scss/_page_no_left_sidebar.scss
assets/scss/_styles_project.scss
content/en/status.md
content/en/training/_index.md

- Contributes to #3463
- Displays the Status and Training page layout by displaying:
- Proper title and description, in the same manner as (most) other pages
- Table of contents with repo links (view page source, etc)
- Essentially, these are not displayed like docs pages, but without a left sidebar/nav
- Copyedits to the Training page
- **Preview**:
- https://deploy-preview-6296--opentelemetry.netlify.app/status/
- https://deploy-preview-6296--opentelemetry.netlify.app/training/
Status page shown. Similar changes were made to the Training page.
Before:
> <img width="1184" alt="image" src="https://github.com/user-attachments/assets/d1fd7490-c6ec-48e2-823c-75dc2c49a719" />
After:
> <img width="1186" alt="image" src="https://github.com/user-attachments/assets/41f37d72-2b22-44e0-9a40-54ca73bc …

Improve Status and Training page layout, some copyedits

---

content/en/docs/collector/configuration.md

Document usage of multiple collector config files

---

content/en/docs/contributing/issues.md

- Fixes the styling of lists and of the "first-timer" alert in [Contributing > Issues](https://opentelemetry.io/docs/contributing/issues/) page
- Eliminates the `prettier-ignore` directives because we want as much markdown prettified as possible, esp. across locales
- Inlines markdown link definitions (to make it a wee bit easier for other locales). 
- Btw, the next alert style adjustments work well in dark mode too.
**Preview**: https://deploy-preview-6302--opentelemetry.netlify.app/docs/contributing/issues/#fixing-an-existing-issue
| [Before](https://opentelemetry.io/docs/contributing/issues/#fixing-an-existing-issue) | [After](https://deploy-preview-6302--opentelemetry.netlify.app/docs/contributing/issues/#fixing-an-existing-issue) |
|--------|--------|
| <img width="682" alt="image" …

[style] Fix contrib/issues list and alert styling

---

content/ja/docs/concepts/signals/_index.md

I updated content/ja/docs/signals/_index.md page to latest.
It is related to https://github.com/open-telemetry/opentelemetry.io/issues/6172.

[ja] update content/ja/docs/signals/_index.md page

---

content/ja/docs/contributing/style-guide.md

translated contributing/style-guide page into ja

[ja] translate contributing/style-guide into ja

---

content/en/blog/2023/http-conventions-declared-stable.md

- Cleans up in-page styles of a 2023 blog. While we don't generally update old blog posts, they sometimes end up being used as templates or examples.
- Removes unused table-specific styling. For some reason the styles were inactive, maybe because an early run of Prettier put a space between the table and the markdown class attributes (which renders the attributes inactive).
**Preview**, e.g.: https://deploy-preview-6303--opentelemetry.netlify.app/blog/2023/http-conventions-declared-stable/#summary-of-changes

Cleanup 2023 blog post's in-page CSS

---

content/ja/docs/concepts/signals/traces.md

I updated content/ja/docs/concepts/traces page.
It is related to https://github.com/open-telemetry/opentelemetry.io/issues/6172.

[ja] update content/ja/docs/concepts/traces page

---

.github/workflows/pr-actions.yml

- For context see https://github.com/open-telemetry/opentelemetry.io/actions/runs/13314886857/job/37186341674. We want the workflow to be able to successfully report an error, so the checkout step has to happen before any step that can fail.
- Reorders steps so that checkout happens earlier.

[CI] PR-actions workflow: ensure error in cmd name can be reported

---

.cspell.yml
.github/workflows/check-text.yml
content/es/docs/contributing/issues.md

- Enables mdl2 checks, which seem to be catching more issues
- Fixes the issues in es issues page
- Copyedits that were forgotten during reivew, see https://github.com/open-telemetry/opentelemetry.io/pull/6088#discussion_r1952837501

[CI] Enable markdownlint2 checks, and fix issues

---

content/en/docs/concepts/instrumentation/libraries.md

I fixed a tidy mistake in content/en/docs/concepts/instrumentation/libraries page.

fix: remove duplucated `)`in content/en/docs/concepts/instrumentation/libraries page

---

content/en/docs/languages/go/exporters.md

Fixes https://github.com/open-telemetry/opentelemetry.io/issues/5847
Better code example showing how to use an exporter are help in package documentation. E.g. https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp#example-package
I also fixed the location of the OTLP logs exporters (there were under Prometheus :sweat_smile: )
---
**Preview**: https://deploy-preview-6319--opentelemetry.netlify.app/docs/languages/go/exporters/

[Go] Remove redunant snippets from exporters docs

---

content/en/ecosystem/registry/_index.md
hugo.yaml
layouts/partials/ecosystem/registry/entry.html
layouts/shortcodes/ecosystem/registry/search-form.html

- Enables `ecosystem` fallback pages for `pt`, in support of #6263
- Ensures that non-en registry links stay within their site locale
**Preview**: https://deploy-preview-6320--opentelemetry.netlify.app/ecosystem/registry/

Registry support for i18n

---

assets/scss/_styles_project.scss
content/en/training/index.md

- Contributes to #3463
- Centers certificate badge and course card only for narrow displays (phone and pad). Just set a left padding on desktop
- Adds FREE badge to course
**Preview**: https://deploy-preview-6321--opentelemetry.netlify.app/training/
Mobile / narrow displays:
> <img width="222" alt="image" src="https://github.com/user-attachments/assets/663345de-536f-4420-8486-12dc8227f029" />
Desktop:
> <img width="888" alt="image" src="https://github.com/user-attachments/assets/ee80d2cd-a482-438e-a0ec-92ed7ab8807f" />

[training] Improve page design for desktop and mobile

---

content/pt/ecosystem/registry/_index.md
content/pt/ecosystem/registry/adding.md
content/pt/ecosystem/registry/updating.md

Tracked on #6242
- content/pt/ecosystem/registry/_index.md
- content/pt/ecosystem/registry/adding.md
- content/pt/ecosystem/registry/updating.md

[pt] Localize content/pt/ecosystem/registry

---

content/pt/ecosystem/adopters.md

Tracked on #6243
- content/pt/ecosystem/adopters.md

[pt] Localize content/pt/ecosystem/adopters.md

---

content/pt/ecosystem/_index.md

Tracked on #6240
- content/pt/ecosystem/_index.md

[pt] Localize content/pt/ecosystem/_index.md

---

content/en/blog/2024/otel-generative-ai/index.md
content/en/blog/2024/prom-and-otel/index.md
content/en/blog/2024/year-in-review.md
static/refcache.json

- ... this make is easier to keep track of which articles have been cross posted. /cc @svrnm 
- Contributes to #6329

[chore] Add links into CNCF blog of crossposted articles

---

content/en/docs/demo/development.md

.NET6 is no longer supported. What is more, demo was already updated to .NET8.

Demo - update required .NET version to .NET8

---

content/en/ecosystem/registry/_index.md
layouts/shortcodes/ecosystem/registry/search-form.html

- Moves the alert from the registry search-form shortcode into the page where it is used. This will make it possible for the alert text to be localized more easily.
- There is no change to the generated site files.
/cc @vitorvasc

[i18n] Move registry search-form alert into registry page

---

content/en/blog/2022/go-web-app-instrumentation/index.md
content/en/docs/concepts/resources/index.md
content/en/docs/languages/go/getting-started.md
content/en/docs/languages/go/instrumentation.md
content/en/docs/languages/net/instrumentation.md
content/en/docs/languages/python/exporters.md
content/en/docs/languages/swift/libraries.md

Related to https://github.com/open-telemetry/opentelemetry-go-contrib/issues/6802
I guess for Swift it might have even been a bug: https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-swift+registerTracerProvider&type=code

Fix typo traceProvider -> tracerProvider

---

scripts/content-modules/adjust-pages.pl

- In preparation for https://github.com/open-telemetry/opentelemetry-specification/pull/4410
- Ensures that path-relative links to OTEPS are translated into external links (into the spec repo)
- Other cleanup and rule consolidation
- There is no change to the generated site files, but it fixes https://github.com/open-telemetry/opentelemetry.io/actions/runs/13394526898/job/37410079743
/cc @carlosalberto

[CI] Support relative links to oteps from OTel spec

---

content/pt/ecosystem/registry/_index.md

Removes the Fixes the redirects, aliases and outputs properties so it doesn't duplicate the redirect rules, as mentioned on https://github.com/open-telemetry/opentelemetry.io/issues/6330.
Also, updates the header definition to match the original content.

[pt] Update content/pt/ecosystem/registry/_index.md - Fix duplicate redirect

---

content/ja/blog/2024/docs-localized.md

I updated content/ja/blog/2024/docs-localized page.
ref: #6172.
When I checked the diff, I noticed that all contents was not recognized.
I confirm the ja localization is true. So then, I updated `default_lang_commit`.
```bash
> npm run check:i18n -- -d content/ja/blog/2024/docs-localized.md
> check:i18n
> scripts/check-i18n.sh -d content/ja/blog/2024/docs-localized.md
Processing paths: content/ja/blog/2024/docs-localized.md
diff --git a/content/en/blog/2024/docs-localized.md b/content/en/blog/2024/docs-localized.md
new file mode 100644
index 00000000..030b5252
--- /dev/null
+++ b/content/en/blog/2024/docs-localized.md
@@ -0,0 +1,36 @@
+---
+title: OpenTelemetry website goes multilingual!
+linkTitle: Multilingual website
+date: 2024-08-20
+author: >-
+  [Severin …
```

[ja] update content/ja/blog/2024/docs-localized

---

content/en/blog/2025/ottl-contexts-just-got-easier.md
static/refcache.json

Blog post about the upcoming OTTL context inference feature (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29017), which will be released on version `0.120.0` (**2025-02-17**).
---
Closes: https://github.com/open-telemetry/opentelemetry.io/issues/6289
Preview: https://deploy-preview-6290--opentelemetry.netlify.app/

Add blog post about the OTTL context inference feature

---

content/en/docs/languages/php/instrumentation.md
content/en/docs/languages/php/resources.md

`ResourceAttributes::DEPLOYMENT_ENVIRONMENT` is no longer supported.
https://github.com/open-telemetry/opentelemetry-php/commit/d2b15077df5e3e13b5c62c87effb99abf70d7e9d#diff-e9c5d40b11db32802d0ca95fbd8b82016f75d1f7a1ac8e5952e3fbcc0c9c13dbL1057

[PHP] Replace deprecated constants `DEPLOYMENT_ENVIRONMENT` to `DEPLOYMENT_ENVIRONMENT_NAME`

---

content/en/docs/languages/java/configuration.md

The current wording around 2 config settings in the Java BatchSpanProcessor leaves room for misinterpretation. The use of "size" could suggest bytes or some other data unit, but the actual implementation is in "number of spans"...so this change clarifies that. 
Hopefully this makes things clearer for readers.

Change wording of "size" to "number of spans".

---

content/en/docs/collector/internal-telemetry.md

Fix http port on internal telemetry page

---

.markdownlint.json
content/en/_includes/_index.md
content/en/_includes/page-not-translated-msg.md
content/en/docs/languages/_includes/_index.md
content/en/docs/languages/_includes/instrumentation-intro.md
content/en/docs/languages/js/_includes/browser-instrumentation-warning.md
content/en/docs/languages/js/_index.md
content/en/docs/languages/js/getting-started/browser.md
content/en/docs/languages/js/instrumentation.md
content/en/ecosystem/_includes/_index.md
content/en/ecosystem/_includes/keep-up-to-date.md
content/pt/_includes/_index.md
content/pt/_includes/page-not-translated-msg.md
content/pt/docs/languages/_includes/_index.md
content/pt/docs/languages/_includes/instrumentation-intro.md
content/pt/docs/languages/js/_includes/browser-instrumentation-warning.md
content/pt/docs/languages/js/getting-started/browser.md
hugo.yaml

- Drops markdownlint check for a title so that we don't need to include one in included files. I doubt we've every had someone include a regular doc page without a title. (In any case, I'll look into creating a custom rule later if ever this becomes an issue).
- Greatly streamlines the "includes" features by making use of targeted cascades across (multilingual) sites
- Deletes all `**/_includes/_index.md` files since we no longer need them
- Drops bogus titles from all includes files
- Moves `content/en/docs/languages/js/_browser-instrumentation-warning.md` back into an includes folder since this will be required moving forward.
- Because of recent past changes to the includes, the `pt` aviso for JS pages wasn't being picked up, instead the English version was …

[CI/i18n] Streamline includes and fix pt Aviso

---

content/en/docs/collector/internal-telemetry.md

This follows the project's recommendation of using http/protobuf instead of grpc.

update protocol to http for internal collector metrics config

---

content/en/blog/2023/end-user-discussions-01.md
content/en/blog/2023/end-user-discussions-02.md
content/en/blog/2023/end-user-discussions-03.md
content/en/blog/2023/end-user-discussions-04.md
content/en/blog/2023/end-user-q-and-a-02.md
content/en/blog/2023/otel-arrow/index.md
content/en/blog/2024/cve-2024-36129.md
content/en/docs/languages/python/mypy.md
layouts/_default/_markup/render-link.html
static/refcache.json

- Contributes to #6409
- Adds a check to the render-link hook, ensuring that non-localhost URLs use `https` rather than `http` (since doing so if often a typo)
- Fixes various `http` links

[CI] Report `http` scheme in URL unless localhost, fix links

---

content/pt/docs/languages/python/_index.md
content/pt/docs/languages/python/getting-started.md

Tracked on https://github.com/open-telemetry/opentelemetry.io/issues/6291
content/pt/docs/languages/python/getting-started.md
#6291

[pt] Localize content/pt/docs/languages/python/getting-started.md

---

content/en/ecosystem/_includes/keep-up-to-date.md

- Fixes the heading ID inside the `keep-up-to-date.md` include file so that it is the same across locales
**Preview**:
- https://deploy-preview-6419--opentelemetry.netlify.app/ecosystem/adopters/#keeping-up-to-date
- https://deploy-preview-6419--opentelemetry.netlify.app/pt/ecosystem/adopters/#keeping-up-to-date
Related:
- #6415, might be waiting on this PR

[ecosystem] Fix heading ID for included section

---

content/ja/_index.md

I updated content/ja/_index page.
ref: #6172.

[ja] update content/ja/_index

---

assets/js/tracing.js

This PR is a side-quest to #6396 and updates the `tracing.js` to discontinue use the `spanProcessors` option over the now-deprecated `NodeTracerProvider#addSpanProcessor()`.
Also uses replaces the use of the deprecated `SemanticResourceAttributes.SERVICE_NAME` with `ATTR_SERVICE_NAME`, which should have the side-effect of improving bundle size.

refactor(tracing): discontinue use of deprecated APIs

---

content/en/docs/demo/services/frontend.md
content/en/docs/languages/js/exporters.md
content/en/docs/languages/js/instrumentation.md
content/en/docs/languages/js/serverless.md

Hi all - this PR contains updates to documentation discontinuing the use of deprecated APIs. As discussed in #6396 this is in preparation of the upcoming SDK `2.0.0` release, but uses only features that are available in the currently latest release `1.30.1`/`0.57.2` for now.
I will follow up with 2 other PRs for
- `assets/js/tracing.js` (edit: #6418) 
- actually lifting all JS docs to 2.0 
**Notable changes:**
- `BasicTracerProvider#register()` will be removed to allow for better tree-shaking
- this was replaced in the docs by manually registering the propagator that would've been registered by `BasicTracerProvider#register()`
- `NodeTracerProvider#register()` is still available in 2.0, therefore docs using it remain unchanged
- `WebTracerProvider#register()` is still available in 2.0, …

[javascript] discontinue use of deprecated APIs

---

content/en/docs/demo/services/frontend.md

Updates frontend service browser code to reflect was is in the Demo. Changes were made to remove deprecated API calls. Requires [PR 2092](https://github.com/open-telemetry/opentelemetry-demo/pull/2092) in the demo repo to be merged first.

[demo] update frontend browser sdk code

---

content/en/docs/collector/configuration.md

based on information provided: 
* https://docs.google.com/document/d/1NeheFG7DmcUYo_h2vLtNRlia9x5wOJMlV4QKEK05FhQ/edit?tab=t.0#heading=h.g6rvvz3l271i
* https://github.com/open-o11y/opentelemetry-collector-testing/blob/master/docs/design.md#receivers

[docs] Improve pipeline section docs

---

content/ja/docs/concepts/resources/index.md

I updated content/ja/docs/concepts/resources/index.md page.

[ja] update content/ja/docs/concepts/resources/index page

---

content/ja/docs/languages/_index.md

Translate docs/languages/_index page into ja

[ja] Translate docs/languages/_index page

---

content/ja/docs/collector/_index.md
content/ja/docs/demo/architecture.md
content/ja/docs/demo/feature-flags.md
layouts/docs/td-content-after-header.html
layouts/partials/i18n/fallback-page.html
scripts/check-i18n.sh

- Contributes to #6443
- Adds support for a "this page is outdated" banner for pages that have `drifted_from_default` set to a value other than false.
- I've not yet setup the banner so that it can be easily localized. That will come later.
- https://deploy-preview-6475--opentelemetry.netlify.app/fr/docs/what-is-opentelemetry/ - page outdated because the English page has changed
- https://deploy-preview-6475--opentelemetry.netlify.app/es/docs/kubernetes/ - page outdated because the English page has moved
> [!NOTE]
> The banner illustrated next has a [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element, which is show in its **expanded** form.
> <img width="600" alt="image" src="https://github.com/user-attachments/assets/ebe396ea-c774-4882-b452-35506eb6c18 …

[i18n] Display page-outdated banner for non-en pages that have drifted

---

content/en/docs/collector/_index.md
content/en/docs/collector/distributions.md

- Reworks the Collector index page:
- Splits "Status and releases" into separate sections
- For releases, uses the title "Distributions and releases" and adds a link to the Distributions page
- Contributes to #6460 indirectly by eliminating the use of the shortcode in the Collector pages
**Preview**:
- https://deploy-preview-6476--opentelemetry.netlify.app/docs/collector/#status
- https://deploy-preview-6476--opentelemetry.netlify.app/docs/collector/distributions/

[Collector] Slight rewording of distributions and release info

---

content/en/docs/contributing/localization.md
static/refcache.json

- Reworks translation guidance summary to make it more visually captivating and intuitive
- Adds explicit guidance relative to respecting the original content and style "as is"
https://deploy-preview-6483--opentelemetry.netlify.app/docs/contributing/localization/#summary
> <img width="699" alt="image" src="https://github.com/user-attachments/assets/e3b87b0f-54e0-4d5c-8c8e-01369a18a8f1" />

[i18n] Update Do's and Don'ts of Localization guidance

---

data/ecosystem/vendors.yaml

Because AWS now supports native OTLP at AWS X-Ray and Amazon CloudWatch Logs, [the vendor list table](https://opentelemetry.io/ecosystem/vendors/) is not up-to-date. This PR updates the status of AWS.
ref: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-OTLPEndpoint.html

Change the status of AWS' native OTLP support

---

content/en/docs/concepts/instrumentation/_index.md
content/en/docs/what-is-opentelemetry.md

- Contributes to #6486
- In preparation for #6474
- Reworks the start of "What is OTel"
- Normalizes links
**Preview**:
- https://deploy-preview-6487--opentelemetry.netlify.app/docs/what-is-opentelemetry/
- https://deploy-preview-6487--opentelemetry.netlify.app/docs/concepts/instrumentation/

Rework of What-is-OTel and Instrumentation pages

---

content/en/docs/languages/_includes/index-intro.md
layouts/partials/include.md
layouts/shortcodes/docs/languages/index-intro2.md
layouts/shortcodes/include.html

- Refactoring in prep for #6460 and other work
- Why this change: we can't call shortcodes from other shortcodes or partials (without resorting to `.RenderString` magic, which doesn't work when we're trying to keep things all in markdown).
- Factors out the core functionality of the `includes.html` shortcode and makes it available as a partial of the same name
- In prep for 6460, this refactors the `docs/languages/index-intro.md` shortcode for better **separate concerns**: have the natural language part in an include file, while keeping the code in a shortcode
- An include-file version of the `docs/languages/index-intro.md` shortcode
- A new version of the shortcode (suffixed with "2"), which isn't currently used
The only change in the generated site files are for pages with includes. Any …

[infra] Factor out include partial from shortcode

---

scripts/content-modules/adjust-pages.pl

- Adjusts the `adjust-pages.pl` script to emit a warning when a spec page doesn't have a level-1 heading, as was the case for https://github.com/open-telemetry/semantic-conventions/issues/1971

[CI] Warn about spec pages without level 1 headings

---

content/ja/docs/contributing/localization.md

ref: #6490 
---
**Preview**: https://deploy-preview-6492--opentelemetry.netlify.app/ja/docs/contributing/localization/

[ja] fix drift of content/ja/docs/contributing/localization

---

content/ja/docs/concepts/instrumentation/_index.md

ref: #6490
---
preview https://deploy-preview-6508--opentelemetry.netlify.app/ja/docs/concepts/instrumentation/

[ja] fix drift of content/ja/docs/concepts/instrumentation/_index

---

content/ja/docs/contributing/issues.md

ref: #6490
---
preview https://deploy-preview-6510--opentelemetry.netlify.app/ja/docs/contributing/issues/

[ja] fix drift of content/ja/docs/contributing/issues

---

content/ja/docs/demo/feature-flags.md

ref: #6490
---
preview https://deploy-preview-6505--opentelemetry.netlify.app/ja/docs/demo/feature-flags/

[ja] fix drift of content/ja/docs/demo/feautre-flags

---

content/ja/docs/collector/distributions.md

ref: #6490
---
preview https://deploy-preview-6506--opentelemetry.netlify.app/ja/docs/collector/distributions/

[ja] fix drift of content/ja/docs/collector/distributions

---

content/ja/docs/contributing/pull-requests.md

ref: #6490
---
preview https://deploy-preview-6509--opentelemetry.netlify.app/ja/docs/contributing/pull-requests/

[ja] fix drift of content/ja/docs/contributing/pull-requests

---

content/ja/docs/collector/_index.md

- ref: #6490
---
**Preview**: https://deploy-preview-6507--opentelemetry.netlify.app/ja/docs/collector/

[ja] fix drift of content/ja/docs/collector/_index

---

content/en/docs/contributing/pr-checks.md

I did below changes
- I fixed a unnecessary character in docs/contributing/pr-checks.
- I fixed an invalid npm run command

fix: some of invalid character and command in docs/contributing/pr-checks

---

data/registry/tools-dotnet-purview-telemetry-sourcegenerator.yml
static/refcache.json

Updated the description for Purview.Telemetry.SourceGenerator based on a recent major change.
Also updated:
- The tags, to match the ones in NuGet
- The links, to include a link to the wiki providing consumers detailed documentation.
-

Updated description/ details for Purview.Telemetry.SourceGenerator in Registry

---

content/en/docs/zero-code/java/agent/annotations.md
content/ja/blog/2025/ai-agent-observability/index.md
content/ja/docs/collector/deployment/agent.md
content/ja/docs/collector/deployment/gateway/index.md
content/ja/docs/what-is-opentelemetry.md
content/pt/docs/concepts/instrumentation/_index.md
static/refcache.json

The documentation for Java's `@WithSpan` annotation currently omits the `kind` (SpanKind control) parameter. With the upcoming 2.14.0 release, we're also gaining another parameter (`inheritContext`)...so this seemed like a good opportunity to document them both.

Add docs for @WithSpan params.

---

.cspell.yml

With these config updates, we should see no more spelling issues reported in VS Code.

[CI] cSpell config tweak

---

content/en/docs/what-is-opentelemetry.md
static/refcache.json

- Contributes to #6486
- Fixes #6474. /cc @LisaHJung 
**Preview**: https://deploy-preview-6550--opentelemetry.netlify.app/docs/what-is-opentelemetry/

Add video link to what-is-opentelemetry page

---

content/en/blog/2025/kubecon-eu.md
static/refcache.json

Add link to Google Calendar containing events at the OTel Observatory. Although there are still some slots available, I think we have enough there already to share more widely.
**Preview**: https://deploy-preview-6542--opentelemetry.netlify.app/blog/2025/kubecon-eu/

Add OTel Observatory calendar link to KubeCon EU 25 blog post

---

content/en/docs/concepts/instrumentation/_index.md

Fixing links for `logs` and `metrics` to point at their respective pages as they currently point at traces documentation.
Current link for logs and metrics: https://opentelemetry.io/docs/concepts/signals/traces/
New logs link: https://opentelemetry.io/docs/concepts/signals/logs/
New metrics link: https://opentelemetry.io/docs/concepts/signals/metrics/

docs: Update links for metrics and logs in _index.md

---

content/en/docs/languages/python/exporters.md

This pull request includes a minor correction to the `content/en/docs/languages/python/exporters.md` file. The change removes an extra comma in the sentence describing how to send trace data to Zipkin.
Documentation improvement:
* [`content/en/docs/languages/python/exporters.md`](diffhunk://#diff-332118e78b0825892438757cd0b61990b37fcde4bca77fbd0b1327baf59cc3d4L240-R240): Removed an unnecessary comma in the sentence explaining the protocols for sending trace data to Zipkin.
Issue: #6564

fix: content/en/docs/languages/python/exporters.md

---

content/pt/docs/languages/python/libraries.md

This pull request adds a new documentation file in Portuguese for using instrumentation libraries with Python. The new file provides guidance on installing, configuring, and using various instrumentation libraries, including an example with HTTPX.
Key changes include:
* **New Documentation File**:
* Added a new file `content/pt/docs/languages/python/libraries.md` with detailed instructions on using instrumentation libraries in Python.
* **Content Details**:
* The file includes sections on using instrumentation libraries, setup instructions, an example with HTTPX, how to turn off instrumentations, available instrumentation libraries, and next steps for further instrumentation and exporting telemetry data.
* **Issue**: https://github.com/open-telemetry/opentelemetry.io/issues/6553

[pt] Add localization content/pt/docs/languages/python/libaries.md

---

content/pt/docs/languages/python/exporters.md

This pull request includes comprehensive documentation updates for the `exporters.md` file in the Portuguese language. 
Documentation updates:
* Added an introduction and detailed sections for dependencies and usage of different telemetry data exporters, including OTLP, Jaeger, Prometheus, and Zipkin.
* Included code examples for installing and configuring exporters using both HTTP/protobuf and gRPC protocols.
* Provided instructions for setting up console exporters for local development and debugging purposes.
* Added a note on configuring temporalities for metrics using the `OTEL_EXPORTER_METRICS_TEMPORALITY_PREFERENCE` environment variable.
* Included references to additional documentation for Jaeger, Prometheus, and Zipkin exporters.
Issue: #6562

[pt] Add localization content/pt/docs/languages/python/exporter.md

---

content/en/docs/languages/go/instrumentation.md

We cannot directly compile the content at https://opentelemetry.io/docs/languages/go/instrumentation/#using-gauges, the issue is that the speedGauge is not declared before using

[en]chore: refine Metric Gauges usage in Go SDK

---

content/ja/docs/contributing/announcements.md

I translated contributing/announcements into ja.
orginal https://opentelemetry.io/docs/contributing/announcements/
preview https://deploy-preview-6530--opentelemetry.netlify.app/ja/docs/contributing/announcements/

[ja] translated contributing/announcements into ja

---

content/en/docs/contributing/localization.md
content/en/docs/contributing/pr-checks.md

- Introduces a new convention to help localization teams figure out which text not to translate
- Updates localization guide: adds convention that text marked `notranslate` should not be translated
- Uses this in the `pr-actions` page, where there are workflow step names to be preserved in English
- Copyedits (while we're in there :)
**Preview**:
- https://deploy-preview-6595--opentelemetry.netlify.app/docs/contributing/localization/
- https://deploy-preview-6595--opentelemetry.netlify.app/docs/contributing/pr-checks/

[i18n] Introduce `notranslate` convention and guidance

---

.gitignore
.gitmodules

- Upgrades Docsy to bring in new heading-render-hook functionality, in support of #6595 and use of `lang="en"` attributes
- Spell-check fixes

Docsy upgrade to bring in new heading render hook

---

.htmltest.yml
content/en/docs/contributing/pr-checks.md

- Fixes #6600
- Documents the `?no-link-check` convention
- Adds a section explaining how to handle invalid links to the PR-checks page
**Preview**: https://deploy-preview-6602--opentelemetry.netlify.app/docs/contributing/pr-checks/#build-and-check-links
/cc @tiffany76

Explain how to handle external links when checker reports failure

---

content/en/blog/2025/otel-js-sdk-2-0.md
static/refcache.json

OpenTelemetry JavaScript recently released SDK 2.0. There have been many improvements and breaking changes and we want to make this easily findable.
---
**Preview**: https://deploy-preview-6574--opentelemetry.netlify.app/blog/2025/otel-js-sdk-2-0/

[blog] Announce JS SDK 2.0

---

content/en/docs/collector/_index.md

Removed a technically incorrect statement about "instrumentation libraries" exporting telemetry.  It is OTLP Exporter that exports telemetry. I did not replace the statement with OTLP Exporter, because just few lines below (line 50) such a statement already exists.

Nit fix to collector doc

---

data/ecosystem/distributions.yaml
static/refcache.json

This PR adds the [Dynatrace OpenTelemetry Collector](https://github.com/Dynatrace/dynatrace-otel-collector) distribution to the distribution list

Add Dynatrace OTel collector to distribution list

---

content/ja/docs/what-is-opentelemetry.md

ref: #6490
---
original https://opentelemetry.io/docs/what-is-opentelemetry/
preview https://deploy-preview-6511--opentelemetry.netlify.app/ja/docs/what-is-opentelemetry/

[ja] fix drift of content/ja/docs/what-is-opentelemetry

---

content/ja/docs/contributing/sig-practices.md

I translated contributing/sig-practices into ja.
original https://opentelemetry.io/docs/contributing/sig-practices/
preview https://deploy-preview-6538--opentelemetry.netlify.app/ja/docs/contributing/sig-practices/

[ja] translated contributing/sig-practices into ja

---

assets/js/tracing.js

- Fixes #6632.
- We should probably be more careful when there are major version upgrades of OTel packages. /cc @cartermp 
- Local production build shows traces exported to the browser console ✅ 
**Preview**: https://deploy-preview-6633--opentelemetry.netlify.app/

[CI] Upgrade tracing code by following JS SDK migration guide

---

content/en/docs/languages/js/serverless.md

add missing provider.register() in serverless example with aws lambda

add missing provider.register() in serverless

---

content/en/docs/zero-code/java/agent/performance.md

Changing the format of this note to use an alert component instead of a quotation block for consistency with the way we handle these types of notes elsewhere.

Use alert component for java performance note

---

content/en/docs/zero-code/java/agent/configuration.md

This page is meta-level information about how to supply configuration options, but users might land here searching for what the options actually are.
I've added an alert at the top of the page pointing users to this information if they want it.
Fixes #6622.

Point to Configure the SDK

---

content/en/docs/languages/dotnet/instrumentation.md

The sentence being removed already exists in the layouts/shortcodes/docs/languages/span-status-preamble.md file, so it appears as duplicate in the output docs: https://opentelemetry.io/docs/languages/dotnet/instrumentation/#set-activity-status

Remove text duplication in dotnet instrumentation

---

content/en/docs/getting-started/dev.md

Goal is to align the two Getting Started guides : 
https://opentelemetry.io/docs/getting-started/dev/
https://opentelemetry.io/docs/getting-started/ops/
The Getting Started Ops page have a link to the Otel demo but the Dev page doesn't have one. This should fix it. 
Also, I saw that the link goes to this page : 
https://opentelemetry.io/ecosystem/demo/
Which is not the demo page is this supposed to be this way ? 
Here is the direct demo page : 
https://opentelemetry.io/docs/demo/

Add Otel demo link to Getting Started Dev

---

data/ecosystem/adopters.yaml

Tranzzo adopted OpenTelemetry ~ 1 year ago and actively uses it to collect traces and metrics.
OpenTelemetry Collector is a core component where all signals are sent, then data is processed by Prometheus (or VictoriaMetrics for other environment) and Jaeger.
We have 2 main stacks for our backend: Java + Spring and Scala + Play.
For Java + Spring services, we use Micrometer as a Vendor-neutral application observability facade with OTLP exporter.
Scala + Play services instrumented using Java OpenTelemetry SDK.
The metrics and traces gathered through OpenTelemetry play a crucial role in Tranzzo's release processes, ongoing monitoring efforts, and performance optimization initiatives.
We are happy with OpenTelemetry, which allows us to switch between observability backends easily.
For now we …

Add Tranzzo to OpenTelemetry adopters

---

content/en/docs/platforms/kubernetes/operator/automatic.md

I wanted to get started using open telemetry auto instrumentation. Following the docs on this site and applying the demo manifest I received a deprecation warning.
This PR replaces the demo manifest updating the apiVersion from `v1alpha1`  to `v1beta1`.
Note: I added `config.exporters.debug.verbosity: basic` because simply `config.exporters.debug` results in `invalid configuration: no exporter configuration specified in config`

Updated OpenTelemetryCollector demo manifest

---

content/pt/docs/concepts/glossary.md

Updates the drifted content for `content/pt/docs/concepts/glossary.md`.
```diff
❯ npm run check:i18n -- -d content/pt/docs/concepts/glossary.md
> check:i18n
> scripts/check-i18n.sh -d content/pt/docs/concepts/glossary.md
Processing paths: content/pt/docs/concepts/glossary.md
diff --git a/content/en/docs/concepts/glossary.md b/content/en/docs/concepts/glossary.md
index e393a25e..89b2b68c 100644
--- a/content/en/docs/concepts/glossary.md
+++ b/content/en/docs/concepts/glossary.md
@@ -116,8 +116,9 @@ some customizations. See [more][distribution].
-Something that happened where representation depends on the
-[Data source](#data-source). For example, [Spans](#span).
+An Event is a [Log Record](#log-record) with an event name and a well-known
+structure. For example, browser …
```

[pt] Update localized content on content/pt/docs/concepts/glossary.md

---

content/pt/docs/concepts/instrumentation/_index.md

Updates the drifted content for `content/pt/docs/concepts/instrumentation/_index.md`.
```diff
❯ npm run check:i18n -- -d content/pt/docs/concepts/instrumentation/_index.md
> check:i18n
> scripts/check-i18n.sh -d content/pt/docs/concepts/instrumentation/_index.md
Processing paths: content/pt/docs/concepts/instrumentation/_index.md
diff --git a/content/en/docs/concepts/instrumentation/_index.md b/content/en/docs/concepts/instrumentation/_index.md
index 39ae1d73..665b3a81 100644
--- a/content/en/docs/concepts/instrumentation/_index.md
+++ b/content/en/docs/concepts/instrumentation/_index.md
@@ -5,16 +5,15 @@ aliases: [instrumenting]
weight: 15
---
-In order to make a system observable, it must be **instrumented**: That is, code
-from the system's components must emit …
```

[pt] Update localized content on content/pt/docs/concepts/instrumentation/_index.md

---

content/pt/_includes/page-not-translated-msg.md
content/pt/docs/concepts/components.md
content/pt/docs/concepts/instrumentation/libraries.md
content/pt/docs/concepts/instrumentation/zero-code/index.md
content/pt/docs/concepts/resources/index.md
content/pt/docs/getting-started/ops.md
content/pt/docs/languages/_includes/instrumentation-intro.md
content/pt/docs/languages/_index.md
content/pt/docs/languages/js/_includes/browser-instrumentation-warning.md
content/pt/docs/languages/js/getting-started/browser.md
content/pt/ecosystem/adopters.md
content/pt/ecosystem/distributions.md
content/pt/ecosystem/integrations.md
content/pt/ecosystem/vendors.md

The following pages are marked as drifted, however, their content remains the same since the last commit. Ths PR only updates the `default_lang_commit` value for them. 
- [content/pt/ecosystem/distributions.md](https://github.com/open-telemetry/opentelemetry.io/compare/8a15d0d668c516ccb255cd0a92e0bcd442e83b4d...b6ddba1118d07bc3c8d1d07b293f227686d0290e#diff-9c846049966b6c82c5895b32af85022d16ac9299d3eccf93bd4ba858461f0177)
- [content/pt/ecosystem/integrations.md](https://github.com/open-telemetry/opentelemetry.io/compare/8a15d0d668c516ccb255cd0a92e0bcd442e83b4d...HEAD#diff-d3131193abe43d44e1b8a1614a6cb79da9eb8a33267267c0f9be8fafb52d1f12)
- [content/pt/ecosystem/vendors.md](https://github.com/open-telemetry/opentelemetry.io/compare/8a15d0d668c516ccb255cd0a92e0bcd442e83b4d... …

[pt] Update default_lang_commit for drifted pages

---

content/pt/status.md

Updates the drifted content for `content/pt/status.md`.
```diff
❯ npm run check:i18n -- -d content/pt/status.md
> check:i18n
> scripts/check-i18n.sh -d content/pt/status.md
Processing paths: content/pt/status.md
diff --git a/content/en/status.md b/content/en/status.md
index 513cc8ea..a741c3d2 100644
--- a/content/en/status.md
+++ b/content/en/status.md
@@ -3,12 +3,10 @@ title: Status
menu: { main: { weight: 30 } }
aliases: [/project-status, /releases]
description: Maturity-level of the main OpenTelemetry components
+type: docs
+body_class: td-no-left-sidebar
---
-{{% blocks/section color="white" %}}
-
-## {{% param title %}}
-
OpenTelemetry is made up of [several components](/docs/concepts/components/),
some language-specific and others language-agnostic. When looking …
```

[pt] Updated localized content on content/pt/status.md

---

content/pt/docs/getting-started/dev.md

Updates the drifted content for `content/pt/docs/getting-started/dev.md`.
```diff
❯ npm run check:i18n -- -d content/pt/docs/getting-started/dev.md
> check:i18n
> scripts/check-i18n.sh -d content/pt/docs/getting-started/dev.md
Processing paths: content/pt/docs/getting-started/dev.md
diff --git a/content/en/docs/getting-started/dev.md b/content/en/docs/getting-started/dev.md
index 73c8175a..82f4a63f 100644
--- a/content/en/docs/getting-started/dev.md
+++ b/content/en/docs/getting-started/dev.md
@@ -22,11 +22,14 @@ natively:
- [How can I add native instrumentation to my library?](../../concepts/instrumentation/libraries/)
+If you are looking for a set of applications to try things out, you will find
+our official [OpenTelemetry demo](/ecosystem/demo/) useful.
+
Next, you …
```

[pt] Update localized content on content/pt/docs/getting-started/dev.md

---

.gitmodules
layouts/_default/_markup/render-heading.html

- In prep for Hugo upgrade.
- Followup to #6743
- Upgrades Docsy to use new render-heading hook partial
- No change to generated site files other than CSS file updates due to Bootstrap upgrade

Docsy upgrade to use new render-heading partial

---

data/registry/instrumentation-java-elasticsearch-client.yml
data/registry/instrumentation-java-micrometer-tracing.yml
static/refcache.json

Addresses issues discussed briefly in https://github.com/open-telemetry/opentelemetry.io/issues/6741
In particular:
- Updates the link for the Elasticsearch Java client
- Adjusts the entry fro Micrometer Tracing by 1) correcting the entry (change value of `isNative` to false, since it's not actually a native instrumentation, but rather a bridging component); 2) correcting and updating the URLs (previously the documentation link lead to the Micrometer->OTLP documentation)

Fix Java native instrumentation entries

---

content/pt/docs/languages/_includes/index-intro.md
content/pt/docs/languages/_includes/instrumentation-intro.md
content/pt/docs/languages/go/_index.md
content/pt/docs/languages/python/_index.md
layouts/partials/pt/docs/latest-release.md

- Contributes to #6460 for `pt` pages
- Continues work started in #6750
- Moves the content of `shortcodes/pt/docs/languages/index-intro.md` into the drift-trackable `content/pt/docs/languages/_includes/index-intro.md` file
- Drop the two partials under `layouts/partials/pt/docs/` that are no longer necessary under this new scheme.
- https://deploy-preview-6751--opentelemetry.netlify.app/pt/docs/languages/python/ - is the [same as before](https://opentelemetry.io/pt/docs/languages/python/)
- https://deploy-preview-6751--opentelemetry.netlify.app/pt/docs/languages/cpp/ now pickup the `pt` include even if the rest of the page is still in `en` :)
/cc @open-telemetry/docs-pt-approvers

[pt] Create index-intro.md include and drop shortcodes

---

content/en/docs/what-is-opentelemetry.md

- Contributes to #4876
- Resolves issues raised in https://github.com/open-telemetry/opentelemetry.io/pull/6698#issuecomment-2802590264
- I'll later document that it is a requirement that links to spec pages (from outside the specs section), need to be absolute so that the render-link hook can ensure that the references point to the English spec section.

[i18n] Update what-is-opentelemetry.md to use absolute path to spec pages

---

content/es/docs/concepts/distributions.md
content/es/docs/getting-started/dev.md
content/ja/docs/concepts/distributions.md
content/ja/docs/concepts/instrumentation/zero-code/index.md
content/ja/docs/contributing/localization.md
content/ja/docs/contributing/pr-checks.md
content/ja/docs/getting-started/dev.md
content/ja/docs/languages/_index.md
content/pt/_includes/page-not-translated-msg.md
content/pt/docs/concepts/components.md
content/pt/docs/concepts/distributions.md
content/pt/docs/concepts/glossary.md
content/pt/docs/concepts/instrumentation/_index.md
content/pt/docs/concepts/instrumentation/libraries.md
content/pt/docs/concepts/resources/index.md
content/pt/docs/getting-started/ops.md
content/pt/docs/languages/_index.md
content/pt/docs/languages/js/_includes/browser-instrumentation-warning.md
content/pt/docs/languages/js/getting-started/browser.md
content/pt/ecosystem/adopters.md
content/pt/ecosystem/distributions.md
content/pt/ecosystem/integrations.md
content/pt/ecosystem/vendors.md
content/pt/status.md
content/zh/docs/getting-started/dev.md

Changes from running:
```console
$ npm run check:i18n -- -D                                    
> check:i18n
> scripts/check-i18n.sh -D
Processing paths: content
> Drifted file: content/ja/docs/contributing/localization.md
...
```

[i18n] Update drift status of non-English pages

---

content/en/docs/languages/go/exporters.md

As mentioned on https://github.com/open-telemetry/opentelemetry.io/issues/6781, I assume that this section has an extra paragraph that should've been removed on https://github.com/open-telemetry/opentelemetry.io/pull/6319.

[Go] fix: remove extra text on content/en/docs/languages/go/exporters.md

---

.github/workflows/survey-on-merged-pr.yml

While sending the same message on the JS sdk repo, we got the feedback that we should add the username to the message, so they get properly pinged, otherwise people can miss it.
Adding the same change here after being tested on the other repo for awhile.

Add username to survey message

---

data/registry/collector-receiver-tracesimulation.yml
static/refcache.json

This PR adds a new receiver entry for the [Trace Simulation Receiver](https://github.com/k4ji/tracesimulationreceiver) to the OpenTelemetry Collector registry.
The Trace Simulation Receiver is a custom OpenTelemetry receiver that generates synthetic traces based on a declarative blueprint. It's designed for testing telemetry pipelines, validating backend behavior, and demonstrating observability features.
Please let me know if any additional changes are needed, Thank you!

Add registry entry for tracesimulationreceiver

---

package.json

- Fixes #6748
The only changes to generated site files are the Hugo version, build timestamp, and `iframe` allow-fullscreen encoding:
```console
$ (cd public && git diff -I "Hugo 0.14" -I "(allow|; )fullscreen" -- ':(exclude)*.xml') | grep ^diff | head 
```

Update NPM pkgs, Hugo to 0.147.0

---

hugo.yaml

- Contributes to #6658
- Followup to #6769
- Changes Hugo's config so that i18n key entries fall back to `en` values when they are missing from other locales. This seems better atm while we're in the trial period for the Ask AI feature. That is, it's way more usable than the screenshot below. Of course it means we might miss other missing translations, but we could use `--printI18nWarnings` on the build if/when that becomes an issue.
Before:
> <img width="777" alt="image" src="https://github.com/user-attachments/assets/b587b664-a243-4b8b-8fdc-38c6767ea062" />
After:
> <img width="795" alt="image" src="https://github.com/user-attachments/assets/c42812dd-fa3a-4572-a89f-a9af82c12e71" />

Don't require locales to have Ask-AI i18n entries yet, fall back to en

---

content/pt/docs/what-is-opentelemetry.md

Updates the drifted content for `content/pt/docs/what-is-opentelemetry.md`.
```diff
❯ npm run check:i18n -- -d content/pt/docs/what-is-opentelemetry.md
> check:i18n
> scripts/check-i18n.sh -d content/pt/docs/what-is-opentelemetry.md
Processing paths: content/pt/docs/what-is-opentelemetry.md
diff --git a/content/en/docs/what-is-opentelemetry.md b/content/en/docs/what-is-opentelemetry.md
index bcb28175..12d3c14c 100644
--- a/content/en/docs/what-is-opentelemetry.md
+++ b/content/en/docs/what-is-opentelemetry.md
@@ -1,50 +1,56 @@
---
title: What is OpenTelemetry?
-description: A short explanation of what OpenTelemetry is and isn't.
+description: A brief explanation of what OpenTelemetry is and isn't.
aliases: [/about, /docs/concepts/what-is-opentelemetry, /otel]
weight: 150 …
```

[pt] Updated localized content on content/pt/docs/what-is-opentelemetry.md

---

.gitmodules
.prettierignore

- Fixes #6561
- Updates the community submodule and it's pinned commit hash
- Drops requiring that the community submodule mission and roadmap files be formatted

Update community repo

---

content/en/docs/_includes/resources-intro.md
content/en/docs/_index.md
layouts/shortcodes/docs/languages/resources-intro.md

- Contributes to #6460
- Moves prose out of `layouts/shortcodes/docs/languages/resources-intro.md` into an include file of the same name.
- There a bit of extra complexity because I chose to preserve the default-resource parameter "a process", which needs to be defined in the `content` not the shortcode. I can always simplify this by inlining the "a process". Reviewers can let me know what you think.
**Preview**:
- https://deploy-preview-6816--opentelemetry.netlify.app/docs/concepts/resources/
- And any one of the languages, such as https://deploy-preview-6816--opentelemetry.netlify.app/docs/languages/go/resources/

[i18n] Make resources-intro an include for `en`

---

content/en/docs/languages/other/_index.md
static/refcache.json

- Drops external link with invalid has
- Uses site-local path instead

Fix invalid hash in languages/other external link - use path instead

---

content/pt/docs/languages/go/exporters.md
content/pt/docs/what-is-opentelemetry.md

- Retrogrades commit hash of go/exporters to reflect #6812
/cc @vitorvasc

[pt] Set drifted status + mention error in translation

---

layouts/partials/docs/native-libraries.md
layouts/shortcodes/docs/languages/index-adopters.md
layouts/shortcodes/docs/languages/index-intro.md
layouts/shortcodes/docs/languages/libraries-intro.md
layouts/shortcodes/docs/languages/resources-intro.md
layouts/shortcodes/ja/docs/languages/resources-intro.md
layouts/shortcodes/pt/docs/languages/resources-intro.md

- This is cleanup in support of #6460
- Drops Prettier directives from layouts, because we don't prettify them anymore.
- No visual changes to generated site files (for the pages I sampled).
For example:
- https://deploy-preview-6821--opentelemetry.netlify.app/docs/languages/dotnet/libraries/#use-natively-instrumented-libraries

Drop Prettier directives from layouts

---

.prettierignore
content/en/docs/_includes/exporters/intro.md

- This is cleanup in support of #6460
- Drops temporary Prettier ignore rule.
- No visual changes to generated site files (for the pages I sampled).
For example:
- https://deploy-preview-6822--opentelemetry.netlify.app/docs/languages/dotnet/exporters/#otlp-dependencies

Drop temporary Prettier ignore rule

---

content/en/docs/_includes/resources-intro.md
content/en/docs/_index.md
content/en/docs/concepts/resources/index.md
layouts/partials/include.html
layouts/shortcodes/docs/languages/resources-intro.md

- Contributes to  #6460
- Follow up to #6816
- Refactors resource-intro files so that the default resource string is fetched from the include file front matter
- (This PR has two solutions in two different commits. The latter commit is the final solution we're opting for. Committing both solutions, for the record. :)
There are no changes to generated site files:
```console
$ (cd public && g diff -bw --ignore-blank-lines -I 'modified_time|dateModified|proofer-ignore') | grep ^diff | grep -v \.xml
diff --git a/zh/docs/index.html b/zh/docs/index.html
```
(The zh page diff is because of Git commit hashes in the page drifted banner.)

Refactor resource-intro: get default resource from include file

---

content/en/docs/demo/kubernetes-deployment.md

Updates the `kubectl port-forward` command in the demo documentation to reflect the current Helm chart behavior, where the service name is now simply `frontend-proxy`.
The Helm chart previously generated service names with the release name as a prefix (e.g., `my-otel-demo-frontend-proxy`). This changed in [PR #1520](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1520), which simplified component naming. However, the demo documentation was not updated accordingly and still refers to the old naming convention, which can lead to confusion or non-working commands for new users.
- Replaced the incorrect service name with `frontend-proxy`
- Updated to reflect the namespace (`--namespace default`) as indicated in the Helm install summary
```
$ helm install my-otel-demo …
```

Fix: port-forward example to clarify service name usage and namespace

---

content/en/docs/contributing/localization.md
static/refcache.json

- Context:
- As endorsed by @svrnm, @tiffany76, and @theletterf in https://cloud-native.slack.com/archives/C06EDFPQ5EH/p1745946122339229
- https://github.com/open-telemetry/opentelemetry.io/pull/6775#discussion_r2066973571
- Adds guidance that locales should NOT translate markdown link definition labels
**Preview**: https://deploy-preview-6838--opentelemetry.netlify.app/docs/contributing/localization/#do-not

Localization: add guidance about not translating link def labels

---

content/en/docs/contributing/localization.md
content/en/docs/contributing/pull-requests.md

- Fixes #6710
- Updates guidance:
- Adds recommendation that doc PRs should not span locales
- Updates guidance on what to do if English-doc changes break links (paths) in non-English pages
**Preview**:
- https://deploy-preview-6842--opentelemetry.netlify.app/docs/contributing/pull-requests/#merge-requirements
- https://deploy-preview-6842--opentelemetry.netlify.app/docs/contributing/localization/#prs-should-not-span-locales
/cc @tiffany76

Document that doc changes should not span locales

---

content/en/docs/zero-code/python/example.md

This change adds a `--logs_exporter none` flag in two places in the zero-code python example. I tested this manually against the latest OTel Python auto instrumentation package.
Addresses issue #6825.

Add logs_exporter flag to otel instrument examples

---

content/pt/docs/languages/_includes/exporters/jaeger.md
content/pt/docs/languages/_includes/exporters/outro.md
content/pt/docs/languages/_includes/exporters/prometheus-setup.md
content/pt/docs/languages/_includes/exporters/zipkin-setup.md

Closes #6848
Fixes the Portuguese shortcodes for the pages that were rendering the original content in English.
- [pt/docs/languages/python/exporters.md](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/pt/docs/languages/python/exporters.md) ([see the docs](https://opentelemetry.io/pt/docs/languages/python/exporters))

[pt] Add shortcodes for pt/docs/languages/_includes/exporters

---

.cspell/en-words.txt
.textlintrc.yml
content/en/blog/2024/kubecon-china.md

- Inspired by https://github.com/open-telemetry/opentelemetry.io/pull/6655/files#r2092834799
- I don't know why cSpell is allowing "protable", other than because it is a product name. The simplest fix (implemented here) seems to be to use textlint to enforce the correct spelling of portable.

[CI] Enforce Istio and mTLS capitalization, and spelling of portable

---

content/en/docs/demo/kubernetes-deployment.md

✍️ Description
This change addresses the error encountered during deployment of the opentelemetry-demo.yaml manifest:
```bash
The ConfigMap "grafana-dashboards" is invalid: metadata.annotations: Too long: may not be more than 262144 bytes
```
The issue stems from an annotation (likely added by tooling such as kubectl apply --server-side or kubectl.kubernetes.io/last-applied-configuration) exceeding the Kubernetes annotation size limit of 256 KiB.
Please provide a meaningful description of what your changes will do. Bonus points for including links to related issues, other PRs, or technical references.
🔗 Related Issue
Fixes: [#2139](https://github.com/open-telemetry/opentelemetry-demo/issues/2139)
A detailed description helps reviewers understand the context of your change and reduces
the …

fix: 🐛  oversized grafana-dashboards ConfigMap annotations exceeding Kubernetes limit

---

content/pt/docs/concepts/distributions.md
content/pt/docs/concepts/instrumentation/libraries.md
content/pt/docs/concepts/signals/_index.md
content/pt/docs/concepts/signals/baggage.md
content/pt/docs/concepts/signals/logs.md

Tracked on #6878
Updates and fixes the link definition labels for pages under `content/pt/docs/concepts`:
- content/pt/docs/concepts/instrumentation/libraries.md
- content/pt/docs/concepts/signals/_index.md
- content/pt/docs/concepts/signals/baggage.md
- content/pt/docs/concepts/signals/logs.md
- content/pt/docs/concepts/distributions.md
The only drifted file was `content/pt/docs/concepts/distributions.md`, but there wasn't a significant change for the localization. See 55f9c9d07ba35c241048ffc0d756d67843d68805.

[pt] Fix link definition labels for pages under content/pt/docs/concepts

---

content/en/docs/platforms/kubernetes/operator/_index.md

Updates the OpenTelemetry Operator [Getting started](https://opentelemetry.io/docs/platforms/kubernetes/operator/#getting-started) guide with a link the to `cert-manager` installation docs, so that users more easily know what software they need to install.
The same can be found in the open-telemetry/opentelemetry-operator [README](https://github.com/open-telemetry/opentelemetry-operator/blob/2bae42922d067e8978ec534e959a808a1a87acbd/README.md?plain=1#L24).

[k8s operator] Provide link to cert-manager installation

---

content/en/docs/platforms/kubernetes/operator/_index.md

Updates the OpenTelemetry Operator for Kubernetes [example](https://opentelemetry.io/docs/platforms/kubernetes/operator/#getting-started) to address the warnings about migrating to v1beta1 and using empty objects. It also adds processors, which was previously empty. Now the example reflects that in the open-telemetry/opentelemetry-operator [README](https://github.com/open-telemetry/opentelemetry-operator?tab=readme-ov-file#getting-started).
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/6926.

[k8s operator] Update OpenTelemetry Operator example

---

content/en/docs/languages/go/instrumentation.md

Per https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.36.0
CC @open-telemetry/go-approvers

[Go] Bump semconv to v1.32.0

---

.github/workflows/pr-actions.yml

Reverts #6663 with an improved workflow to run fix commands via GitHub comment:
- add hardened runners by StepSecurity
- split the creation of the changes & the application of them into two separate steps to disable the possibility to inject something malicious into the workflow run
@open-telemetry/docs-approvers @trask PTAL!
@theletterf I remember you had some code that would also check for the handle if the person is allowed to trigger the workflow (e.g. only org members, maintainers, etc.), we could add this as well.
NOTE: As always this github action has not been yet tested in full details, so unfortunately we will need to merge it at some point and then iterate on it until it works as expected.

Bring back pr actions

---

content/ja/docs/demo/feature-flags/_index.md

I moved content/ja/docs/demo/feature-flags.md to content/ja/docs/demo/feature-flags/_index.md due to https://github.com/open-telemetry/opentelemetry.io/pull/6798.
The current target page is not shown now.
preview
https://deploy-preview-6906--opentelemetry.netlify.app/ja/docs/demo/

[ja] docs(i18n): fix removed file of content/ja/docs/demo/feature-flags.md

---

data/registry/instrumentation-js-oracledb.yml
static/refcache.json

"Added a Registry entry for the recently released Oracle Database instrumentation package, available [here](https://www.npmjs.com/package/@opentelemetry/instrumentation-oracledb)."

- Add  Oracle Database opentelemetry integration in registry

---

package.json

No change to generated site files other than Hugo version ID.

Update NPM packages, Hugo to 0.147.6

---

.github/workflows/pr-actions.yml

- Contributes to 
- Context: example of us having to delete the file manually, https://github.com/open-telemetry/opentelemetry.io/pull/6948/commits/feaf2dea5d2fba98ba5072b885e7de233fe791ee
- Ensure that `pr-fix.patch` is deleted after the patch is applied so that the file isn't committed.
/cc @svrnm

[CI] Update pr-actions.yml: delete pr-fix.patch file after it is applied

---

content/en/docs/concepts/resources/index.md

I believe the former is deprecated.

Update `deployment.environment` to `deployment.environment.name`

---

content/en/announcements/kubecon-china.md
content/en/announcements/kubecon-japan.md
content/en/blog/2025/kubecon-china.md
content/en/blog/2025/kubecon-japan.md

- Links KubeCon China and Japan announcements to their respective blog posts
- Adds UTM query attributes to the registration links in the blog posts
/cc @tiffany76 @katzchang

Link KubeCon announcements to blog posts

---

content/en/blog/2025/otel-arrow-phase-2.md
content/en/docs/contributing/localization.md
content/ja/docs/contributing/localization.md

This pull request includes corrections to link definitions and updates to improve clarity in documentation across multiple files. The most important changes involve fixing a typo in the URL for the OpenTelemetry website and ensuring consistency in localized documentation.
* [`content/en/docs/contributing/localization.md`](diffhunk://#diff-95e7906a1be8699bb50d991938c4cc6fd2d3e3288bf9a09fe5acc8d9b86938bfL106-R106): Corrected the URL for the OpenTelemetry website in both English and French examples to ensure accuracy. [[1]](diffhunk://#diff-95e7906a1be8699bb50d991938c4cc6fd2d3e3288bf9a09fe5acc8d9b86938bfL106-R106) [[2]](diffhunk://#diff-95e7906a1be8699bb50d991938c4cc6fd2d3e3288bf9a09fe5acc8d9b86938bfL115-R115)
* [`content/ja/docs/contributing/localization.md`](diffhunk://#diff-c11fc7894a039cb …

CHORE - fix: correction opentelemetry word

---

content/pt/docs/contributing/style-guide.md

This pull request adds a new style guide for documentation in Portuguese (`content/pt/docs/contributing/style-guide.md`). The guide provides guidelines for terminology, formatting, and tools to ensure consistency and quality in the OpenTelemetry documentation.
- https://github.com/open-telemetry/opentelemetry.io/issues/6854

[pt] Add localize content/pt/docs/contributing/style-guide.md

---

content/en/announcements/kubecon-china.md
content/en/announcements/kubecon-japan.md
scripts/list-expired.pl

- Fixes #6946
- Adds support for the following: to ensure that announcements (or any other expired markdown file) isn't deleted by `fix:expired`, add `keep` as a comment after the expiry date. The post will still be removed on the expiry date, but the file won't be deleted even if `fix:expired` is run.
/cc @tiffany76 - this is in contrast to what we had discussed during the Comms meeting. I've implemented support for `keep` after all.

[CI] Support `keep` directive for announcements and other md pages that expire

---

.github/component-label-map.yml

add lang:bn to component label map

---

content/ja/announcements/kubecon-japan.md

I updated an announcement of kubecon japan.
Preview
- https://deploy-preview-7053--opentelemetry.netlify.app/announcements/kubecon-japan/

docs(i18n): fix drift of content/ja/announcements/kubecon-japan.md

---

content/en/announcements/open-observability-summit-na.md
content/en/blog/2025/otel-day.md

- Followup to #7085
- Links to OTel day blog post from the announcement
- Follows through with the suggested cSpell changes made over #7085 but not committed

OTel day banner: link to blog, and adjust local word list

---

content/en/docs/languages/js/propagation.md

In the "Automatic context propogation" section for JS SDK, there are two links, one that states "@opentelemetry/instrumentation-http" and one that states "@opentelemetry/instrumentation-express". 
However both these links point to the instrumentation-http package. 
This fixes the express link to point to express npm package.

Fix propogation link to express instrumentation

---

content/en/blog/2025/slack-workspace-changes.md
static/refcache.json

This PR creates a short call-to-action blog post for OTel community members to save their data in Slack before Friday.
Fixes #7135.

[blog] Create call-to-action post for CNCF Slack changes

---

content/ja/docs/_includes/exporters/intro.md
content/ja/docs/languages/_index.md
content/ja/docs/languages/sdk-configuration/general.md

Current English files.
- https://deploy-preview-7096--opentelemetry.netlify.app/docs/languages/
- https://deploy-preview-7096--opentelemetry.netlify.app/docs/languages/sdk-configuration/general/
Preview.
- https://deploy-preview-7096--opentelemetry.netlify.app/ja/docs/languages/
- https://deploy-preview-7096--opentelemetry.netlify.app/ja/docs/languages/sdk-configuration/general/

[ja] docs(i18n): fix drift of content/ja/docs/languages/*.md files

---

content/ja/blog/2025/kubecon-japan.md

Original English page.
- https://deploy-preview-7143--opentelemetry.netlify.app/blog/2025/kubecon-japan/
Preview
- https://deploy-preview-7143--opentelemetry.netlify.app/ja/blog/2025/kubecon-japan/

[ja] docs(i18n): fix drift of content/ja/blog/2025/kubecon-japan.md

---

data/ecosystem/distributions.yaml
static/refcache.json

Adds New Relic Distribution of the OpenTelemetry Collector (NRDOT) to the list of distributions on the website.

Add New Relic Distribution (NRDOT)

---

data/registry/collector-exporter-faro.yml
data/registry/collector-receiver-faro.yml
static/refcache.json

Faro receiver and faro exporter components were added to the opentelemetry collector contrib distribution:
https://github.com/open-telemetry/opentelemetry-collector-releases/pull/955
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40822
Adding them to the registry

Added faro receiver, faro exporter to registry

---

content/en/docs/languages/python/getting-started.md

The code under the [Metrics section of Python getting-started.md](https://github.com/open-telemetry/opentelemetry.io/blob/748555c22f43476291ae0c7974ca4a2577da0472/content/en/docs/languages/python/getting-started.md#metrics) fails with the following traceback when the "player" query parameter is specified and not empty:
```
Traceback (most recent call last):
File \"/Users/jl-martins/Projects/otel-python-getting-started/.venv/lib/python3.13/site-packages/flask/app.py\", line 1511, in wsgi_app
response = self.full_dispatch_request()
File \"/Users/jl-martins/Projects/otel-python-getting-started/.venv/lib/python3.13/site-packages/flask/app.py\", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
File \"/Users/jl-martins/Projects/otel-python-getting-started/.venv/lib/python3.1 …
```

Fix TypeError in Python getting-started.md

---

content/en/docs/languages/go/instrumentation.md

Per https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.37.0

[Go] Bump semconv to v1.34.0

---

.github/workflows/check-spelling.yml

Currently when a check spell CI test fails, it shows the message `Add comment '/fix:fix:format'` instead of the correct `Add comment '/fix:format'`

Fix error message on failed check spell

---

README.md

Noticed this while running validation between README files and GitHub team memberships

Add missing approver

---

.github/workflows/check-links.yml
assets/js/registrySearch.js
layouts/_shortcodes/ecosystem/registry/search-form.html
package.json

Re: #7100 #7223 
Not exactly sure what the problem is, but it seems there is a caching issue with the minisearch from the CDN. 
This PR works around that by adding minisearch as a dependency to package.json and importing it into the registrySearch.js directly.

Add minisearch as dependency, remove CDN link

---

data/ecosystem/vendors.yaml
static/refcache.json

- Link to the documentation that details how your offering consumes OpenTelemetry natively via OTLP: https://langfuse.com/docs/opentelemetry/get-started
- Link to your distribution: https://langfuse.com/
- Link that proves that your offering is open source, if applicable. An open source distribution does not qualify your offering to be marked “open source”: https://langfuse.com/open-source
- GitHub handle or email address as a point of contact so that we can reach out in case we have questions: https://github.com/jannikmaierhoefer

docs: add Langfuse to vendors.yaml

---

data/ecosystem/adopters.yaml
static/refcache.json

Starting last year, UiPath started internal project to migrate observability stack to OpenTelemetry. Thus creating PR for adding company name into the adopter list

Add UiPath to OpenTelemetry adopter list

---

.htmltest.yml

this adds additional URLs that give a 403 to the htmltest.yml
https://github.com/open-telemetry/opentelemetry.io/actions/runs/16274549848/job/45950704599
cc @jsuereth

add additional ignore rules to htmltest.yml

---

content/pt/docs/contributing/acknowledgements.md

This pull request introduces a new acknowledgements page to the Portuguese documentation, crediting various sources for their contributions to the site's content.
- Closes #6861 
* Added a new file, `content/pt/docs/contributing/acknowledgements.md`, which includes a list of sources that have contributed to the site's content. The page provides links to articles, authors, and organizations, along with specific references to sections of the documentation that were influenced by these sources.

[pt] - add localization content/pt/docs/contributing/acknowledgements.md

---

content/pt/docs/contributing/development.md

This pull request adds a new Portuguese-language documentation file, `development.md`, which provides detailed instructions for setting up a development environment for the site. It covers supported environments, local and cloud-based setups, build and serve commands, content management, and submodule handling.
Issue: [#6859](https://github.com/open-telemetry/opentelemetry.io/issues/6859)
* **Comprehensive Guide**: Introduced `content/pt/docs/contributing/development.md` to guide contributors on setting up a development environment, including local setups, cloud-based tools like Gitpod and Codespaces, and DevContainer support.
* **Build and Serve Instructions**: Added sections on how to build (`npm run build`) and serve (`npm run serve`) the site locally, with troubleshooting tips for …

[pt] feat: add localization development content/en/docs/contributing/development.md

---

content/en/docs/collector/internal-telemetry.md

This removes the broken hash to #lifecycle-status making the spec build work again:
https://github.com/open-telemetry/opentelemetry.io/issues/7324
We can update the link afterwards to point to the new #maturity-levels but since the document almost only has that chapter we might even leave it like that for now.

remove hash lifecycle status from link in internal telemetry

---

content/en/docs/contributing/localization.md

After [discussion](https://cloud-native.slack.com/archives/C06EDFPQ5EH/p1753967403228399?thread_ts=1752658839.398279&cid=C06EDFPQ5EH), update localization guidance w.r.t. markdown link labels, allowing locale (sub)SIGs to choose.
Context:
- #6878, which should be closed if this PR is approved.
/cc @vitorvasc

Markdown link labels can be translated

---

content/en/docs/languages/_includes/native-lib-alert.md
content/en/docs/languages/java/instrumentation.md
content/ja/docs/languages/java/instrumentation.md
content/pt/docs/languages/java/instrumentation.md
layouts/_partials/docs/native-libraries.md
layouts/_partials/func/get-lang.html

- Contributes to #6460
- Factors out the prose part of the `native-libraries` partial, putting it into an include file
- Replaces the inline alert-shortcode HTML by a call to the alert shortcode
- Adds a `func` partial used to determine the language that a page is a part of when under `docs/languages`
- There was not change to the generated site code as a result of the refactoring. Changes were introduced by using the alert shortcode instead of hard-coded (obsolete) HTML.
- https://deploy-preview-7452--opentelemetry.netlify.app/docs/languages/cpp/library/#use-natively-instrumented-libraries - shows "Help wanted" alert
- https://deploy-preview-7452--opentelemetry.netlify.app/docs/languages/java/instrumentation/#native-instrumentation - shows an info alert

[i18n] Move alert prose from `native-libraries` partial into an include file

---

content/en/docs/concepts/context-propagation.md

This PR improves the readability of the second paragraph in the Context section on the [Context Propagation documentation page](https://opentelemetry.io/docs/concepts/context-propagation/).
The revised paragraph reduces ambiguity around how parent-child relationships between spans are established.
Fixes #6674 as suggested by @brennanc01

Rewording second paragraph in "Context" section of context propagation docs - Issue #6674

---

content/en/blog/2025/otip-alibaba.md
static/refcache.json

Adds a blog post (and link to recording) for the latest OTel in Practice session with Alibaba.
Closes https://github.com/open-telemetry/community/issues/2871

Add blog for OTiP: Alibaba

---

content/es/docs/_includes/resources-intro.md

Translate [concept/resource](https://opentelemetry.io/es/docs/concepts/resources/) page to spanish, the **include section**, related to the issue: https://github.com/open-telemetry/opentelemetry.io/issues/5206

add: docs/_includes resource-intro to spanish

---

content/en/docs/zero-code/obi/setup/kubernetes-helm.md

Follow up to #7566 and #7567, this PR changes the front matter to remove the Helm chart page from the website build. This will be reversed once the Helm chart work is complete.

Update front matter to better hide OBI Helm chart page

---

data/ecosystem/vendors.yaml
static/refcache.json

No code changes, added [Apache Doris](https://github.com/apache/doris) and [VeloDB](https://www.velodb.io) as OpenTelemetry vendors.
Apache Doris is an open source OLAP database for real-time analytics.One of its major use cases is logging and observability. It's already in the eco-system of [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/dorisexporter) as a storage backend. And the [doris-opentelemetry-demo](https://github.com/apache/doris-opentelemetry-demo) project is created to for Doris backend based on the latest offical opentelemetry-demo.
VeloDB is a commercial product based on Apache Doris. One of its major solutions is [logging and observability](https://www.velodb.io/solutions/use-cases/observability).
Here's the docs on OTel …

Add Apache Doris and VeloDB to OpenTelemetry vendors

---

.github/workflows/auto-update-community-members.yml
data/registry/instrumentation-ruby-all.yml

Closes #6966.
Adds the `fix:refcache` command to the execution of the `auto-update-community-members.yml` workflow, since we often need to manually trigger refcache update before merging the PRs.
FYI @open-telemetry/docs-maintainers

[Infra] Add fix:refcache to auto-update-community-members.yml workflow

---

.github/workflows/check-links.yml

In this PR I hit a "Links / REFCACHE updates?" check failure in CI:
https://github.com/open-telemetry/opentelemetry.io/pull/7606#issuecomment-3208176252
The error message in the GitHub Actions log was:
```
> _diff:check
> git diff --name-only --exit-code
static/refcache.json
ERROR: the files above have changed. Locally rerun `npm run test-and-fix` and commit changes
```
which is misleading, because (I'm told) the correct action to fix is `npm run fix:refcache`.  This attempts to improve that error message.

ci: improve the error message when the 'REFCACHE updates?' check fails

---

content/ja/docs/languages/sdk-configuration/general.md

Closes #7562.
There is no difference between English and Japanese.
I just update `default_lang_commit`.
A preview page.
- https://deploy-preview-7617--opentelemetry.netlify.app/ja/docs/languages/sdk-configuration/general/
An original page.
- https://deploy-preview-7617--opentelemetry.netlify.app/docs/languages/sdk-configuration/general/

[ja] docs(i18n): fix drift of content/ja/languages/sdk-configuration/general.md

---

content/en/docs/languages/js/getting-started/nodejs.md
static/refcache.json

- This switches from ts-node to tsx to do the on-the-fly transpilation.
'npx tsx-node app.ts' fails with the default "tsconfig.json" created
via 'tsc --init' now. tsx is better maintained and simplifies this
example somewhat.
- Switch from using `--require ...` to `--import ...` for pre-loading
the OpenTelemetry bootstrap code. `--import` is supported now in all
supported Node.js versions and it helps avoid some breakage and
confusion with Node.js 22 and 24 that implement type-stripping
of .ts files. With type-stripping the .ts file (using `import ...`
ESM syntax) is run directly. `--require` doesn't support loading
ESM, but `--import` supports loading ESM (and CJS as a fallback).
Fixes: https://github.com/open-telemetry/opentelemetry.io/issues/7547

Fix JS/TS "getting started" code to work

---

content/es/blog/2025/how-to-name-your-span-attributes.md

It adds the Spanish translation for the blog post 'How to Name your Span Attributes': #7602
/cc @open-telemetry/docs-es-approvers

[es] Translate 'How to Name Your Span Attributes' blog post

---

.github/CODEOWNERS

Keep this PR as a reminder that we want to revisit the docs localization maintainership by end of september
cc @open-telemetry/docs-maintainers @open-telemetry/docs-ja-maintainers @open-telemetry/docs-pt-maintainers

Revert "[experimental] enable pt/ja maintainers to merge PRs"

---

content/en/docs/languages/rust/libraries.md

- Fixes #7663 by changing the crate link for the documentation.

docs: fix link to deprecated crate

---

content/en/docs/languages/go/instrumentation.md

Release v1.38.0 included semantic conventions for v1.37.0. Use these in the examples documented.

Bump Go semconv package

---

content/en/docs/languages/go/getting-started.md

This upgrades the Go getting started code samples, as named return variables are not a recommended practice, and our linter prevents their use.
See https://github.com/open-telemetry/opentelemetry-go-contrib/pull/7852

Update go getting-started examples in english

---

content/en/docs/languages/php/instrumentation.md

since 1.36.0 PHP semantic conventions have been reorganised. The previous classes still exist but are deprecated.
Fixes: #7704

update php SemConv usage

---

content/pt/blog/2025/how-to-name-your-metrics.md

It adds the Portuguese translation for the blog post 'How to Name Your Metrics': https://github.com/open-telemetry/opentelemetry.io/pull/7659
/cc @jpkrohling

[pt] Translate 'How to Name Your Metrics' blog post

---

content/pt/blog/2025/contribute-to-otel.md

Add portuguese localization to blog post "How to Contribute to OpenTelemetry"
It will need to wait for #7757 to geet merged, specially so the `default_lang_commit` can get updated in this PR

[pt] Localization of blog post "How to Contribute to OpenTelemetry"

---

.cspell/es-palabras.txt
content/es/blog/2025/how-to-name-your-metrics.md

It adds the Spanish translation for the blog post 'How to Name Your Metrics': https://github.com/open-telemetry/opentelemetry.io/pull/7659

[es] Translate 'How to Name Your Metrics' blog post

---

data/ecosystem/vendors.yaml
static/refcache.json

Request to add Oodle AI to the list of vendors
Here's our docs page for Otel integration - https://docs.oodle.ai/integrations/metrics/otel/
Our company website - https://oodle.ai
Incase of any questions, please reach-out to the same github handle(prameelaks) or support@oodle.ai

Adding Oodle AI to the OTel vendors list

---

content/en/docs/getting-started/reference-application-specification.md

Contributes to the effort to rework our getting started guides

[Getting Started] Add reference app specification

---

content/en/docs/contributing/blog.md
static/refcache.json

As discussed during one of the last Comms Meetings I add a note about "Call For Contributors" blog posts to the submission guidelines.

Add CfC note to blog submission guidelines

---

content/en/blog/2025/go-opentelemetry-io-expired-certificate.md
static/refcache.json

This adds the retrospective blog post for yesterday's expired certificate incident on go.opentelemetry.io.
Added by @mx-psi: Issue tracking this #7887

Retrospective for September 25th incident on go.opentelemetry.io

---

content/en/blog/2025/kotlin-multiplatform-opentelemetry.md
static/refcache.json

Adds a blog post introducing a Kotlin Multiplatform implementation of OpenTelemetry as suggested in #7809.

Add blog post entry for kotlin multiplatform

---

.github/workflows/update-semconv-integration-branch.yml
.github/workflows/update-spec-integration-branch.yml

- Fixes #7845
- Updates workflow code to ignore link-check failures so that the refcache can still be updated and the workflow run be successful
- Added `env` var so that the code becomes more generic. In a followup PR, we can update the `semconv` integration similarly, and then possibly factor out an action to be shared by both workflows

[CI] Spec integration workflow fix: ignore link-check failures when updating refcache

---

.github/workflows/refcache-refresh.yml

- Followup to #7954
- Updates `refcache-refresh.yml` workflow so that it prunes separately from updating the refcache. This way, subsequent passes can update refcache entries that might have been throttled (gotten temporary 403 or 429 statuses).

[CI] Update refcache-refresh.yml workflow to prune separately from update

---

content/en/announcements/kubecon-na.md
content/en/blog/2025/kubecon-na.md
static/refcache.json

This PR creates the blog post for KubeCon North America 2025. The banner is already published, so this PR updates it to point to the blog post.
To be done:
- Looks okay to me: https://deploy-preview-7968--opentelemetry.netlify.app/blog/2025/kubecon-na/
- So far, the answer is no. 
Fixes #7574

Create KubeCon NA 2025 blog post

---

.github/workflows/refcache-refresh.yml

- Adds `rebase` workflow arg, to force a rebase from `main` instead of a merge
- Adds `GH_TOKEN` to `Checkout or create branch` as requested by GH in https://github.com/open-telemetry/opentelemetry.io/actions/runs/18218693656/job/51873573828

[CI] refcache-refresh.yml fixes: add GH token, and rebase arg

---

.github/workflows/refcache-refresh.yml
package.json

- Ensures that scheduled runs use the same default refresh_count as for dispatched runs. (Without this, we get an error -- see https://github.com/open-telemetry/opentelemetry.io/actions/runs/18242645281/job/51946564996.)
- As of #7982, the refcache can contain 404 entries. This PR updates `fix:refcache` so that it prunes 404 entries first.

[CI] workflows/refcache-refresh fix: use default count for scheduled runs too

---

.gitmodules
assets/scss/_styles_project.scss
assets/scss/_variables_project.scss
content/en/docs/contributing/localization.md
layouts/baseof.html
layouts/docs/baseof.html

This Docsy update
- Fixes #7436
> <img width="444" height="714" alt="image" src="https://github.com/user-attachments/assets/81bd7a96-b2af-4c69-aa2c-de8e2a029338" />
- Prepares us for #5646
- Adds dynamic TOC entry highlighting as a reader scrolls through a page. Implemented via Bootstrap's ScrollSpy (see https://github.com/google/docsy/pull/2287).
- Improves colors for alerts (see https://github.com/google/docsy/pull/2285)
- There's a bug with the scrolling (for details see https://github.com/google/docsy/issues/2329), but it doesn't happen for many pages, so I'll tackle it later.
- https://deploy-preview-7104--opentelemetry.netlify.app/docs/platforms/kubernetes/getting-started/#filelog-receiver - deep linking example
- https://deploy-preview-7104--opentelemetry.netlify.app/community/
- …

Update docsy to v0.12.0-25-g82d492bb for TOC highlighting, etc
